// kanakku-v1.9.9/vuejs-files/template/src/views/pages/uiinterface/baseui/popover.vue
<template>
  <!-- Main Wrapper -->
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>

    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <componentheader :title="title" />
        <div class="row">
          <!-- Popover -->
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h5 class="card-title">Basic Popover</h5>
              </div>
              <div class="card-body">
                <div class="popover-list">
                  <a-popover title="Popover title" trigger="click" placement="right">
                    <template #content>
                      <span
                        >And here's some amazing content. It's very engaging. Right?</span
                      >
                    </template>
                    <b-button variant="primary me-1">Click to toggle popover</b-button>
                  </a-popover>
                  <a-popover title="Popover title" trigger="click" placement="right">
                    <template #content>
                      <span
                        >And here's some amazing content. It's very engaging. Right?</span
                      >
                    </template>
                    <b-button variant="primary me-1">Dismissible popover</b-button>
                  </a-popover>
                  <a-popover title="Popover title" trigger="hover" placement="top">
                    <template #content>
                      <span
                        >Vivamus sagittis lacus vel augue laoreet rutrum faucibus.</span
                      >
                    </template>
                    <b-button variant="primary me-1">On Hover Tooltip</b-button>
                  </a-popover>
                </div>
              </div>
            </div>
          </div>
          <!-- /Popover -->

          <!-- Popover -->
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                <h5 class="card-title">Direction Popover</h5>
              </div>
              <div class="card-body">
                <div class="popover-list">
                  <a-popover title="Popover title" trigger="click" placement="top">
                    <template #content>
                      <span
                        >Vivamus sagittis lacus vel augue laoreet rutrum faucibus.</span
                      >
                    </template>
                    <b-button variant="primary me-1">Popover on top</b-button>
                  </a-popover>
                  <a-popover trigger="click" placement="right">
                    <template #content>
                      <span
                        >Vivamus sagittis lacus vel augue laoreet rutrum faucibus.</span
                      >
                    </template>
                    <b-button variant="primary me-1">Popover on right</b-button>
                  </a-popover>
                  <a-popover trigger="click" placement="bottom">
                    <template #content>
                      <span
                        >Vivamus sagittis lacus vel augue laoreet rutrum faucibus.</span
                      >
                    </template>
                    <b-button variant="primary me-1">Popover on bottom</b-button>
                  </a-popover>
                  <a-popover trigger="click" placement="left">
                    <template #content>
                      <span
                        >Vivamus sagittis lacus vel augue laoreet rutrum faucibus.</span
                      >
                    </template>
                    <b-button variant="primary me-1">Popover on left</b-button>
                  </a-popover>
                </div>
              </div>
            </div>
          </div>
          <!-- /Popover -->
        </div>
      </div>
    </div>
    <!-- /Page Wrapper -->
  </div>
  <!-- /Main Wrapper -->
</template>
<script>
export default {
  data() {
    return {
      title: "Popover",
    };
  },
};
</script>

// kanakku-v1.9.9/angular-files/template-rtl/src/app/feature-module/ui-interface/base-ui/popover/popover.component.ts
import { Component} from '@angular/core';

@Component({
  selector: 'app-popover',
  templateUrl: './popover.component.html',
  styleUrls: ['./popover.component.scss'],
})
export class PopoverComponent {
  popoverOne = false;
  content =
    "And here's some amazing content. It's very engaging. Right?";

}

<!-- Page Header -->
<div class="page-header">
  <div class="content-page-header">
    <h5>Popover</h5>
  </div>	
</div>
<!-- /Page Header -->	

<div class="row">

  <!-- Popover -->
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Basic Popover</h5>
      </div>
      <div class="card-body card-buttons">
        <div class="popover-list">
          <button
            class="btn btn-primary"
            type="button"
            [popover]="content"
            popoverTitle="Popover title"
            placement="auto"
            triggers="click"
          >
            Click to toggle popover
          </button>
        
          <a
            class="example-popover btn btn-primary"
            tabindex="0"
            role="button"
            [popover]="content"
            popoverTitle="Popover title"
            placement="auto"
            triggers="focus"
            >Dismissible popover</a
          >
        
          <button
            class="example-popover btn btn-primary"
            type="button"
            [popover]="content"
            placement="bottom"
            triggers="mouseenter"
          >
            On Hover Tooltip
          </button>
        </div>
      </div>
    </div>
  </div>
  <!-- /Popover -->

  <!-- Popover -->
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Direction Popover</h5>
      </div>
      <div class="card-body card-buttons">
        <div class="popover-list">
          <button
            class="example-popover btn btn-primary"
            type="button"
            [popover]="
              'Vivamus sagittis lacus vel augue laoreet rutrum faucibus.'
            "
            [popoverTitle]="'Popover title'"
            placement="top"
          >
            Popover on top
          </button>
          <button
            class="example-popover btn btn-primary"
            type="button"
            [popover]="
              'Vivamus sagittis lacus vel augue laoreet rutrum faucibus.'
            "
            placement="left"
          >
            Popover on right
          </button>
          <button
            class="example-popover btn btn-primary"
            type="button"
            [popover]="
              'Vivamus sagittis lacus vel augue laoreet rutrum faucibus.'
            "
            placement="bottom"
          >
            Popover on bottom
          </button>
          <button
            class="example-popover btn btn-primary"
            type="button"
            [popover]="
              'Vivamus sagittis lacus vel augue laoreet rutrum faucibus.'
            "
            placement="right"
          >
            Popover on left
          </button>
        </div>
      </div>
    </div>
  </div>
  <!-- /Popover -->
