// kanakku-v1.9.9/vuejs-files/template-rtl/src/views/pages/auth/login.vue
<template>
  <!-- Main Wrapper -->
  <div class="main-wrapper login-body">
    <div class="login-wrapper">
      <div class="container">
        <img class="img-fluid logo-dark mb-2" src="@/assets/img/logo2.png" alt="Logo" />
        <div class="loginbox">
          <div class="login-right">
            <div class="login-right-wrap">
              <h1>Login</h1>
              <p class="account-subtitle">Access to our dashboard</p>

              <Form
                class="login"
                @submit="onSubmit"
                :validation-schema="schema"
                v-slot="{ errors }"
              >
                <div class="form-group">
                  <label class="form-control-label">Email Address</label>
                  <Field
                    name="email"
                    type="text"
                    value="admin@dreamguys.in"
                    class="form-control mt-2"
                    :class="{ 'is-invalid': errors.email }"
                  />
                  <div class="invalid-feedback">{{ errors.email }}</div>
                  <div class="emailshow text-danger" id="email"></div>
                </div>
                <div class="form-group">
                  <label class="form-control-label">Password</label>
                  <div class="pass-group">
                    <Field
                      v-if="showPassword"
                      name="password"
                      type="text"
                      value="123456"
                      class="form-control pass-input mt-2"
                      :class="{ 'is-invalid': errors.password }"
                    />
                    <Field
                      v-else
                      name="password"
                      type="password"
                      value="123456"
                      class="form-control pass-input mt-2"
                      :class="{ 'is-invalid': errors.password }"
                    />
                    <span
                      @click="toggleShow"
                      class="fas toggle-password"
                      :class="{
                        'fa-eye': showPassword,
                        'fa-eye-slash': !showPassword,
                      }"
                    ></span>
                    <div class="invalid-feedback">{{ errors.password }}</div>
                    <div class="emailshow text-danger" id="password"></div>
                  </div>
                </div>
                <div class="form-group">
                  <div class="row">
                    <div class="col-6">
                      <div class="custom-control custom-checkbox">
                        <input
                          type="checkbox"
                          class="custom-control-input me-1"
                          id="cb1"
                        />
                        <label class="custom-control-label" for="cb1">Remember me</label>
                      </div>
                    </div>
                    <div class="col-6 text-end">
                      <router-link class="forgot-link" to="/forgot-password"
                        >Forgot Password ?</router-link
                      >
                    </div>
                  </div>
                </div>
                <button
                  class="btn btn-lg btn-block btn-primary w-100"
                  type="submit"
                  value="Login"
                >
                  Login
                </button>
                <div class="login-or">
                  <span class="or-line"></span>
                  <span class="span-or">or</span>
                </div>
                <!-- Social Login -->
                <div class="social-login mb-3">
                  <span>Login with</span>
                  <a href="javascript:void(0)" class="facebook"
                    ><i class="fab fa-facebook-f"></i></a
                  ><a href="javascript:void(0)" class="google"
                    ><i class="fab fa-google"></i
                  ></a>
                </div>
                <!-- /Social Login -->
                <div class="text-center dont-have">
                  Don't have an account yet?
                  <router-link to="/register">Register</router-link>
                </div>
              </Form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /Main Wrapper -->
</template>
<script>
import { ref } from "vue";
import { router } from "@/router";
import VueRouter from "vue-router";
import { useStore } from "vuex";
import { Form, Field } from "vee-validate";
import * as Yup from "yup";
export default {
  components: {
    Form,
    Field,
  },
  data() {
    return {
      showPassword: false,
      password: null,
    };
  },
  computed: {
    buttonLabel() {
      return this.showPassword ? "Hide" : "Show";
    },
  },
  methods: {
    toggleShow() {
      this.showPassword = !this.showPassword;
    },
  },
  setup() {
    let users = localStorage.getItem("storedData");
    if (users === null) {
      let password = [
        {
          email: "admin@dreamguys.in",
          password: "123456",
        },
      ];
      const jsonData = JSON.stringify(password);
      localStorage.setItem("storedData", jsonData);
    }
    const schema = Yup.object().shape({
      email: Yup.string().required("Email is required").email("Email is invalid"),
      password: Yup.string()
        .min(6, "Password must be at least 6 characters")
        .required("Password is required"),
    });
    const onSubmit = (values) => {
      document.getElementById("email").innerHTML = "";
      document.getElementById("password").innerHTML = "";
      let data = localStorage.getItem("storedData");
      var Pdata = JSON.parse(data);
      const Eresult = Pdata.find(({ email }) => email === values.email);
      if (Eresult) {
        if (Eresult.password === values.password) {
          router.push("/index");
        } else {
          document.getElementById("password").innerHTML = "Incorrect password";
        }
      } else {
        document.getElementById("email").innerHTML = "Email is not valid";
      }
    };
    return {
      schema,
      onSubmit,
    };
  },
};
</script>
<style></style>

// kanakku-v1.9.9/reactjs-files/template/src/authentication/Login.jsx
import React, {useEffect, useState} from 'react';
import { Link } from 'react-router-dom'
import {InvoiceLogo1, Logo} from "../_components/imagepath"
import { useForm, Controller } from 'react-hook-form'
import { yupResolver } from '@hookform/resolvers/yup'
import * as yup from 'yup';
import  { alphaNumericPattern, emailrgx } from '../assets/constant'

const schema = yup
  .object({
  
    email: yup
      .string()
      .matches(emailrgx, 'Email is required')
      .required('Email is required')
      .trim(),
	  password: yup.string() .min(6)
    .max(6) .required ('Password is required')
    .trim(),
  })
  
const Login = (props) => {

	const[eye,seteye]=useState(true);
    const [emailerror,setEmailError] = useState("");
	const [nameerror,setNameError] = useState("");
    const [passworderror,setPasswordError] = useState("");
    const [formgroup,setFormGroup] = useState("");
    const [inputValues,setInputValues] = useState({
    email:"admin@dreamguys.co.in",
    password:"123456",
    });

	const {
		handleSubmit,
		control,
    setError,
    clearErrors,
		formState: { errors },
	  } = useForm({
		resolver: yupResolver(schema),
    defaultValues : inputValues,
	  })
    
  const  onSubmit = (data) => {
	  console.log("data", data)
	 
    if(data.password != "123456") {
      setError('password', {
        message: 'password is mismatch',
      })
  } else {
    clearErrors('password')
    props.history.push('index') 
    
  }
  }

const onEyeClick = () =>{
	seteye(!eye)
}
        
        
return (
   <>
         
  <div className="main-wrapper login-body">
    <div className="login-wrapper">
      <div className="container">
        <img
          className="img-fluid logo-dark mb-2"
          src={InvoiceLogo1}
          alt="Logo"
        />
        <div className="loginbox">
          <div className="login-right">
            <div className="login-right-wrap">
              <h1>Login</h1>
              <p className="account-subtitle">Access to our dashboard</p>
              <div>
              <form onSubmit={handleSubmit(onSubmit)}>
                             
              <div className="form-group input_text">
                  <label className="form-control-label">Email Address</label>
                  <Controller
                      name="email"
                      control={control}
                      render={({ field: { value, onChange } }) => (
                        <input   className={`form-control  ${errors?.email ? "error-input" : "" }`} type="text" value={value} onChange={onChange} autoComplete="false"  />

                      )}
										/>
											
									<small>{errors?.email?.message}</small>
                </div>
                <div className="form-group input_text login-eye">
                  <label className="form-control-label">Password</label>
                  <Controller
                      name="password"
                      control={control}
                      render={({ field: { value, onChange } }) => (
                        <div className="pass-group">
                          <input  type={eye ? "password" : "text"}  className={`form-control  ${errors?.password? "error-input" : "" }`}  value={value} onChange={onChange} autoComplete="false"  />
                          <span onClick={onEyeClick} className={`fa toggle-password" ${eye ? "fa-eye-slash" : "fa-eye" }`}/>
                        </div>
                      )}
                    />
											
									<small>{errors?.password?.message}</small>
                </div>                
                <div className="form-group">
                  <div className="row">
                    <div className="col-6">
                      <div className="custom-control custom-checkbox">
                        <input
                          type="checkbox"
                          className="form-check-input"
                          id="cb1"
                        />
                        <label className="custom-control-label ms-1" htmlFor="cb1">
                          Remember me
                        </label>
                      </div>
                    </div>
                    <div className="col-6 text-end">
                    <Link className="forgot-link" to="/forgot-password"> Forgot Password ? </Link>
                    </div>
                  </div>
                </div>             
                <button
                  className="btn btn-lg btn-block w-100 btn-primary w-100"
                  type="submit" 
                >
                  Login
                </button>
                </form>
                <div className="login-or">
                  <span className="or-line" />
                  <span className="span-or">or</span>
                </div>
                {/* Social Login */}
                <div className="social-login mb-3">
                  <span>Login with</span>
                  <Link  to="#" className="facebook">
                    <i className="fab fa-facebook-f" />
                  </Link>
                  <Link  to="#" className="google">
                    <i className="fab fa-google" />
                  </Link>
                </div>
                {/* /Social Login */}
                <div className="text-center dont-have">
                  Don't have an account yet?{" "}
                  <Link to="/register">Register</Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

            </>
        );
    
}
export default Login;
