// kanakku-v1.9.9/vuejs-files/template/src/views/pages/auth/register.vue
<template>
  <!-- Main Wrapper -->
  <div class="main-wrapper login-body">
    <div class="login-wrapper">
      <div class="container">
        <img class="img-fluid logo-dark mb-2" src="@/assets/img/logo2.png" alt="Logo" />

        <div class="loginbox">
          <div class="login-right">
            <div class="login-right-wrap">
              <h1>Register</h1>
              <p class="account-subtitle">Access to our dashboard</p>

              <!-- Form -->
              <Form
                class="register"
                @submit="onSubmit"
                :validation-schema="schema"
                v-slot="{ errors }"
              >
                <div class="form-group">
                  <label class="form-control-label">Name</label>
                  <input class="form-control mt-2" type="text" />
                </div>
                <div class="form-group">
                  <label class="form-control-label">Email Address</label>
                  <span class="text-danger">*</span>
                  <Field
                    name="email"
                    type="text"
                    class="form-control mt-2"
                    :class="{ 'is-invalid': errors.email }"
                  />
                  <div class="invalid-feedback">{{ errors.email }}</div>
                  <div class="emailshow text-danger" id="email"></div>
                </div>
                <div class="form-group">
                  <label class="form-control-label">Password</label>
                  <span class="text-danger">*</span>
                  <Field
                    name="password"
                    type="password"
                    class="form-control pass-input mt-2"
                    :class="{ 'is-invalid': errors.password }"
                  />
                  <div class="invalid-feedback">{{ errors.password }}</div>
                  <div class="emailshow text-danger" id="password"></div>
                </div>
                <div class="form-group">
                  <label class="form-control-label">Confirm Password</label>
                  <span class="text-danger">*</span>
                  <Field
                    name="confirmpassword"
                    type="password"
                    class="form-control pass-input mt-2"
                    :class="{ 'is-invalid': errors.confirmpassword }"
                  />
                  <div class="invalid-feedback">{{ errors.confirmpassword }}</div>
                  <div class="emailshow text-danger" id="confirmpassword"></div>
                </div>
                <div class="form-group mb-0">
                  <button class="btn btn-lg btn-block btn-primary w-100" type="submit">
                    Register
                  </button>
                </div>
              </Form>
              <!-- /Form -->

              <div class="login-or">
                <span class="or-line"></span>
                <span class="span-or">or</span>
              </div>
              <!-- Social Login -->
              <div class="social-login">
                <span>Register with</span>
                <a href="javascript:void(0)" class="facebook"
                  ><i class="fab fa-facebook-f"></i></a
                ><a href="javascript:void(0)" class="google"
                  ><i class="fab fa-google"></i
                ></a>
              </div>
              <!-- /Social Login -->
              <div class="text-center dont-have">
                Already have an account? <router-link to="/">Login</router-link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /Main Wrapper -->
</template>
<script>
import { ref } from "vue";
import { useStore } from "vuex";
import { Form, Field } from "vee-validate";
import { router } from "@/router";
import VueRouter from "vue-router";
import * as Yup from "yup";
export default {
  components: {
    Form,
    Field,
  },
  setup() {
    const schema = Yup.object().shape({
      email: Yup.string().required("Email is required").email("Email is invalid"),
      password: Yup.string()
        .min(6, "Password must be at least 6 characters")
        .required("Password is required"),
      confirmpassword: Yup.string()
        .min(6, "Password must be at least 6 characters")
        .required("Confirm password is required"),
    });
    const onSubmit = (values) => {
      if (values.password === values.confirmpassword) {
        let Rawdata = localStorage.getItem("storedData");
        let Pdata = [];
        Pdata = JSON.parse(Rawdata);
        const Eresult = Pdata.find(({ email }) => email == values.email);
        if (Eresult) {
          document.getElementById("email").innerHTML = "This email are already exist";
        } else {
          Pdata.push(values);
          const jsonData = JSON.stringify(Pdata);
          router.push("/index");
          localStorage.setItem("storedData", jsonData);
        }
      } else {
        document.getElementById("confirmpassword").innerHTML = "Password not matching";
      }
    };
    return {
      schema,
      onSubmit,
    };
  },
};
</script>
<style></style>

// kanakku-v1.9.9/reactjs-files/template/src/authentication/Register.jsx
import React, {useEffect, useState} from 'react';
import { Link } from 'react-router-dom'
import {InvoiceLogo1, Logo} from "../_components/imagepath"
import { useForm, Controller } from 'react-hook-form'
import { yupResolver } from '@hookform/resolvers/yup'
import * as yup from 'yup';
import  { alphaNumericPattern, emailrgx } from '../assets/constant'

const schema = yup
  .object({
    name: yup.string().matches(alphaNumericPattern, 'please enther valid name')
      .required('Please enter your name'),
    email: yup
      .string()
      .matches(emailrgx, 'Email is required')
      .required('Email is required')
      .trim(),
	  password: yup.string() .min(6)
	  .max(6) .required ('Password is required')
	  .trim(),

	  confirmPassword:  yup.string() .min(6) .max(6).required('ConfirmPassword is required').trim(),
  })
  .required()

const Register = (props) => {

	const[eye,seteye]=useState(true);
    const [emailerror,setEmailError] = useState("");
	const [nameerror,setNameError] = useState("");
    const [passworderror,setPasswordError] = useState("");
    const [formgroup,setFormGroup] = useState("");
    const [inputValues,setInputValues] = useState({
    email:"admin@dreamguys.co.in",
    password:"123456",
    });

	const {
		handleSubmit,
		control,
		setError,
    clearErrors,
		formState: { errors },
	  } = useForm({
		resolver: yupResolver(schema),
	  })
    
  const  onSubmit = (data) => {
	console.log("data", data)
   
  if(data.password != "123456") {
	setError('password', {
	  message: 'password is mismatch',
	})
} else {
  clearErrors('password')
  props.history.push('login') 
  
}
}

 
    
  
        return (
		<div className="main-wrapper  login-body">
		
			<div className="login-wrapper">
				<div className="container">
					<img className="img-fluid logo-dark mb-2" src={InvoiceLogo1} alt="Logo" />
					
					<div className="loginbox">
						<div className="login-right">
							<div className="login-right-wrap">
								<h1>Register</h1>
								<p className="account-subtitle">Access to our dashboard</p>
								
								{/* Form */}
								<form onSubmit={handleSubmit(onSubmit)}>
								<div className="form-group">
										<label className="form-control-label">Name</label>
										<input className="form-control" type="text"/>
									</div>
									<div className="form-group">
										<label className="form-control-label">Email Address</label>
										<input className="form-control" type="text"/>
									</div>
									<div className="form-group">
										<label className="form-control-label">Password</label>
										<input className="form-control" type="text"/>
									</div>
									<div className="form-group">
										<label className="form-control-label">Confirm Password</label>
										<input className="form-control" type="text"/>
									</div>
									<div className="form-group mb-0">
										<button className="btn btn-lg btn-block btn-primary w-100" type="submit">Register</button>
									</div>								
								</form>
								{/* /Form */}
								
								<div className="login-or">
									<span className="or-line"></span>
									<span className="span-or">or</span>
								</div>
								{/* Social Login */}
								<div className="social-login">
									<span>Register with</span>
									<Link to="#" className="facebook"><i className="fab fa-facebook-f"></i></Link><Link to="#" className="google"><i className="fab fa-google"></i></Link>
								</div>
								{/* /Social Login */}
								<div className="text-center dont-have">Already have an account? <Link to="/login">Login</Link></div>
							</div>
						</div>
					</div>
				</div>
			</div>
			
		</div>

        );
    
}
export default Register;
