// kanakku-v1.9.9/angular-files/template-rtl/src/app/feature-module/ui-interface/charts/apexcharts/apexcharts.component.ts
import { Component, ViewChild } from '@angular/core';
/* eslint-disable @typescript-eslint/no-explicit-any */
import {
  ChartComponent,
  ApexAxisChartSeries,
  ApexChart,
  ApexXAxis,
  ApexDataLabels,
  ApexTitleSubtitle,
  ApexStroke,
  ApexGrid,
  ApexPlotOptions,
  ApexYAxis,
  ApexLegend,
  ApexTooltip,
  ApexResponsive,
  ApexFill,
} from 'ng-apexcharts';

export type ChartOptions = {
  series: ApexAxisChartSeries | any;
  chart: ApexChart | any;
  xaxis: ApexXAxis | any;
  dataLabels: ApexDataLabels | any;
  grid: ApexGrid | any;
  stroke: ApexStroke | any;
  title: ApexTitleSubtitle | any;
  plotOptions: ApexPlotOptions | any;
  yaxis: ApexYAxis | any;
  legend: ApexLegend | any;
  tooltip: ApexTooltip | any;
  responsive: ApexResponsive[] | any;
  fill: ApexFill | any;
  labels: string[] | any;
};

@Component({
  selector: 'app-apexcharts',
  templateUrl: './apexcharts.component.html',
  styleUrls: ['./apexcharts.component.scss'],
})
export class ApexchartsComponent {
  @ViewChild('chart') chart!: ChartComponent;
  public chartOptionsOne: Partial<ChartOptions>;
  public chartOptionsTwo: Partial<ChartOptions>;
  public chartOptionsThree: Partial<ChartOptions>;
  public chartOptionsFour: Partial<ChartOptions>;
  public chartOptionsFive: Partial<ChartOptions>;
  public chartOptionsSix: Partial<ChartOptions>;
  public chartOptionsSeven: Partial<ChartOptions>;
  public chartOptionsEight: Partial<ChartOptions>;

  constructor() {
    this.chartOptionsOne = {
      series: [
        {
          name: 'Desktops',
          data: [10, 41, 35, 51, 49, 62, 69, 91, 148],
        },
      ],
      chart: {
        height: 350,
        type: 'line',
        zoom: {
          enabled: false,
        },
      },
      dataLabels: {
        enabled: false,
      },
      stroke: {
        curve: 'straight',
      },
      title: {
        text: 'Product Trends by Month',
        align: 'left',
      },
      grid: {
        row: {
          colors: ['#f3f3f3', 'transparent'],
          opacity: 0.5,
        },
      },
      xaxis: {
        categories: [
          'Jan',
          'Feb',
          'Mar',
          'Apr',
          'May',
          'Jun',
          'Jul',
          'Aug',
          'Sep',
        ],
      },
    };
    this.chartOptionsTwo = {
      series: [
        {
          name: 'series1',
          data: [31, 40, 28, 51, 42, 109, 100],
        },
        {
          name: 'series2',
          data: [11, 32, 45, 32, 34, 52, 41],
        },
      ],
      chart: {
        height: 350,
        type: 'area',
      },
      dataLabels: {
        enabled: false,
      },
      stroke: {
        curve: 'smooth',
      },
      xaxis: {
        type: 'datetime',
        categories: [
          '2018-09-19T00:00:00.000Z',
          '2018-09-19T01:30:00.000Z',
          '2018-09-19T02:30:00.000Z',
          '2018-09-19T03:30:00.000Z',
          '2018-09-19T04:30:00.000Z',
          '2018-09-19T05:30:00.000Z',
          '2018-09-19T06:30:00.000Z',
        ],
      },
      tooltip: {
        x: {
          format: 'dd/MM/yy HH:mm',
        },
      },
    };
    this.chartOptionsThree = {
      series: [
        {
          name: 'Net Profit',
          data: [44, 55, 57, 56, 61, 58, 63, 60, 66],
        },
        {
          name: 'Revenue',
          data: [76, 85, 101, 98, 87, 105, 91, 114, 94],
        },
      ],
      chart: {
        type: 'bar',
        height: 350,
      },
      plotOptions: {
        bar: {
          horizontal: false,
          columnWidth: '55%',
        },
      },
      dataLabels: {
        enabled: false,
      },
      stroke: {
        show: true,
        width: 2,
        colors: ['transparent'],
      },
      xaxis: {
        categories: [
          'Feb',
          'Mar',
          'Apr',
          'May',
          'Jun',
          'Jul',
          'Aug',
          'Sep',
          'Oct',
        ],
      },
      yaxis: {
        title: {
          text: '$ (thousands)',
        },
      },
      fill: {
        opacity: 1,
      },
      tooltip: {
        y: {
          formatter: function (val: any) {
            return '$ ' + val + ' thousands';
          },
        },
      },
    };
    this.chartOptionsFour = {
      series: [
        {
          name: 'PRODUCT A',
          data: [44, 55, 41, 67, 22, 43],
        },
        {
          name: 'PRODUCT B',
          data: [13, 23, 20, 8, 13, 27],
        },
        {
          name: 'PRODUCT C',
          data: [11, 17, 15, 15, 21, 14],
        },
        {
          name: 'PRODUCT D',
          data: [21, 7, 25, 13, 22, 8],
        },
      ],
      chart: {
        type: 'bar',
        height: 350,
        stacked: true,
        toolbar: {
          show: true,
        },
        zoom: {
          enabled: true,
        },
      },
      responsive: [
        {
          breakpoint: 480,
          options: {
            legend: {
              position: 'bottom',
              offsetX: -10,
              offsetY: 0,
            },
          },
        },
      ],
      plotOptions: {
        bar: {
          horizontal: false,
        },
      },
      xaxis: {
        type: 'category',
        categories: [
          '01/2011',
          '02/2011',
          '03/2011',
          '04/2011',
          '05/2011',
          '06/2011',
        ],
      },
      legend: {
        position: 'right',
        offsetY: 40,
      },
      fill: {
        opacity: 1,
      },
    };
    this.chartOptionsFive = {
      series: [
        {
          name: "basic",
          data: [400, 430, 448, 470, 540, 580, 690, 1100, 1200, 1380]
        }
      ],
      chart: {
        type: "bar",
        height: 350
      },
      plotOptions: {
        bar: {
          horizontal: true
        }
      },
      dataLabels: {
        enabled: false
      },
      xaxis: {
        categories: [
          "South Korea",
          "Canada",
          "United Kingdom",
          "Netherlands",
          "Italy",
          "France",
          "Japan",
          "United States",
          "China",
          "Germany"
        ]
      }
    };
    this.chartOptionsSix = {
      series: [
        {
          name: 'Website Blog',
          type: 'column',
          data: [440, 505, 414, 671, 227, 413, 201, 352, 752, 320, 257, 160],
        },
        {
          name: 'Social Media',
          type: 'line',
          data: [23, 42, 35, 27, 43, 22, 17, 31, 22, 22, 12, 16],
        },
      ],
      chart: {
        height: 350,
        type: 'line',
      },
      stroke: {
        width: [0, 4],
      },
      title: {
        text: 'Traffic Sources',
      },
      dataLabels: {
        enabled: true,
        enabledOnSeries: [1],
      },
      labels: [
        '01 Jan 2001',
        '02 Jan 2001',
        '03 Jan 2001',
        '04 Jan 2001',
        '05 Jan 2001',
        '06 Jan 2001',
        '07 Jan 2001',
        '08 Jan 2001',
        '09 Jan 2001',
        '10 Jan 2001',
        '11 Jan 2001',
        '12 Jan 2001',
      ],
      xaxis: {
        type: 'datetime',
      },
      yaxis: [
        {
          title: {
            text: 'Website Blog',
          },
        },
        {
          opposite: true,
          title: {
            text: 'Social Media',
          },
        },
      ],
    };
    this.chartOptionsSeven = {
      series: [44, 55, 13, 43, 22],
      chart: {
        type: 'donut',
      },
      labels: ['Team A', 'Team B', 'Team C', 'Team D', 'Team E'],
      responsive: [
        {
          breakpoint: 480,
          options: {
            chart: {
              width: 200,
              height: 350,
            },
            legend: {
              position: 'bottom',
            },
          },
        },
      ],
    };
    this.chartOptionsEight = {
      series: [44, 55, 67, 83],
      chart: {
        height: 350,
        type: 'radialBar',
      },
      plotOptions: {
        radialBar: {
          dataLabels: {
            name: {
              fontSize: '22px',
            },
            value: {
              fontSize: '16px',
            },
            total: {
              show: true,
              label: 'Total',
              formatter: function () {
                return '249';
              },
            },
          },
        },
      },
      labels: ['Apples', 'Oranges', 'Bananas', 'Berries'],
    };
  }
}

<div class="row">
  <!-- Chart -->
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Apex Simple</h5>
      </div>
      <div class="card-body">
        <div class="chart">
          <apx-chart
            [series]="chartOptionsOne.series"
            [chart]="chartOptionsOne.chart"
            [xaxis]="chartOptionsOne.xaxis"
            [dataLabels]="chartOptionsOne.dataLabels"
            [grid]="chartOptionsOne.grid"
            [stroke]="chartOptionsOne.stroke"
            [title]="chartOptionsOne.title"
          ></apx-chart>
        </div>
      </div>
    </div>
  </div>
  <!-- /Chart -->

  <!-- Chart -->
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Area Chart</h5>
      </div>
      <div class="card-body">
        <div class="chart">
          <apx-chart
            [series]="chartOptionsTwo.series"
            [chart]="chartOptionsTwo.chart"
            [xaxis]="chartOptionsTwo.xaxis"
            [stroke]="chartOptionsTwo.stroke"
            [tooltip]="chartOptionsTwo.tooltip"
            [dataLabels]="chartOptionsTwo.dataLabels"
          ></apx-chart>
        </div>
      </div>
    </div>
  </div>
  <!-- /Chart -->

  <!-- Chart -->
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Column Chart</h5>
      </div>
      <div class="card-body">
        <div class="chart">
          <apx-chart
            [series]="chartOptionsThree.series"
            [chart]="chartOptionsThree.chart"
            [dataLabels]="chartOptionsThree.dataLabels"
            [plotOptions]="chartOptionsThree.plotOptions"
            [yaxis]="chartOptionsThree.yaxis"
            [legend]="chartOptionsThree.legend"
            [fill]="chartOptionsThree.fill"
            [stroke]="chartOptionsThree.stroke"
            [tooltip]="chartOptionsThree.tooltip"
            [xaxis]="chartOptionsThree.xaxis"
          ></apx-chart>
        </div>
      </div>
    </div>
  </div>
  <!-- /Chart -->

  <!-- Chart -->
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Column Stacked Chart</h5>
      </div>
      <div class="card-body">
        <div class="chart">
          <apx-chart
            [series]="chartOptionsFour.series"
            [chart]="chartOptionsFour.chart"
            [dataLabels]="chartOptionsFour.dataLabels"
            [plotOptions]="chartOptionsFour.plotOptions"
            [responsive]="chartOptionsFour.responsive"
            [xaxis]="chartOptionsFour.xaxis"
            [legend]="chartOptionsFour.legend"
            [fill]="chartOptionsFour.fill"
          ></apx-chart>
        </div>
      </div>
    </div>
  </div>
  <!-- /Chart -->

  <!-- Chart -->
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Bar Chart</h5>
      </div>
      <div class="card-body">
        <div class="chart">
          <apx-chart
            [series]="chartOptionsFive.series"
            [chart]="chartOptionsFive.chart"
            [dataLabels]="chartOptionsFive.dataLabels"
            [plotOptions]="chartOptionsFive.plotOptions"
            [xaxis]="chartOptionsFive.xaxis"
          ></apx-chart>
        </div>
      </div>
    </div>
  </div>
  <!-- /Chart -->

  <!-- Chart -->
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Mixed Chart</h5>
      </div>
      <div class="card-body">
        <div class="chart">
          <apx-chart
            [series]="chartOptionsSix.series"
            [chart]="chartOptionsSix.chart"
            [yaxis]="chartOptionsSix.yaxis"
            [xaxis]="chartOptionsSix.xaxis"
            [labels]="chartOptionsSix.labels"
            [stroke]="chartOptionsSix.stroke"
            [title]="chartOptionsSix.title"
            [dataLabels]="chartOptionsSix.dataLabels"
            [fill]="chartOptionsSix.fill"
            [tooltip]="chartOptionsSix.tooltip"
          ></apx-chart>
        </div>
      </div>
    </div>
  </div>
  <!-- /Chart -->

  <!-- Chart -->
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Donut Chart</h5>
      </div>
      <div class="card-body">
        <div  class="chart">
          <apx-chart
            [series]="chartOptionsSeven.series"
            [chart]="chartOptionsSeven.chart"
            [labels]="chartOptionsSeven.labels"
            [responsive]="chartOptionsSeven.responsive"
          ></apx-chart>
        </div>
      </div>
    </div>
  </div>
  <!-- /Chart -->

  <!-- Chart -->
  <div class="col-md-6 d-flex">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Radial Chart</h5>
      </div>
      <div class="card-body">
        <div class="chart">
          <apx-chart
            [series]="chartOptionsEight.series"
            [chart]="chartOptionsEight.chart"
            [plotOptions]="chartOptionsEight.plotOptions"
            [labels]="chartOptionsEight.labels"
          ></apx-chart>
        </div>
      </div>
    </div>
  </div>
  <!-- /Chart -->
</div>

// kanakku-v1.9.9/reactjs-files/template-rtl/src/charts/apexcharts/index.jsx
import React, { Component } from "react";
import { Link } from "react-router-dom";
import { Helmet } from "react-helmet";
import Chart from "react-apexcharts";
import Header from "../../layouts/Header";
import Sidebar from "../../layouts/Sidebar";

class apexCharts extends Component {
  constructor(props) {
    super(props);

    this.state1 = {
      series: [
        {
          name: "Desktops",
          data: [10, 41, 35, 51, 49, 62, 69, 91, 148],
        },
      ],
      options: {
        chart: {
          height: 350,
          type: "line",
          zoom: {
            enabled: false,
          },
        },
        dataLabels: {
          enabled: false,
        },
        stroke: {
          curve: "straight",
        },
        title: {
          text: "Product Trends by Month",
          align: "left",
        },
        grid: {
          row: {
            colors: ["#f3f3f3", "transparent"], // takes an array which will be repeated on columns
            opacity: 0.5,
          },
        },
        xaxis: {
          categories: [
            "Jan",
            "Feb",
            "Mar",
            "Apr",
            "May",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
          ],
        },
      },
    };
    this.state2 = {
      series: [
        {
          name: "series1",
          data: [31, 40, 28, 51, 42, 109, 100],
        },
        {
          name: "series2",
          data: [11, 32, 45, 32, 34, 52, 41],
        },
      ],
      options: {
        chart: {
          height: 350,
          type: "area",
        },
        dataLabels: {
          enabled: false,
        },
        stroke: {
          curve: "smooth",
        },
        xaxis: {
          type: "datetime",
          categories: [
            "2018-09-19T00:00:00.000Z",
            "2018-09-19T01:30:00.000Z",
            "2018-09-19T02:30:00.000Z",
            "2018-09-19T03:30:00.000Z",
            "2018-09-19T04:30:00.000Z",
            "2018-09-19T05:30:00.000Z",
            "2018-09-19T06:30:00.000Z",
          ],
        },
        tooltip: {
          x: {
            format: "dd/MM/yy HH:mm",
          },
        },
      },
    };
    this.state3 = {
      series: [
        {
          name: "Net Profit",
          data: [44, 55, 57, 56, 61, 58, 63, 60, 66],
        },
        {
          name: "Revenue",
          data: [76, 85, 101, 98, 87, 105, 91, 114, 94],
        },
      ],
      options: {
        chart: {
          type: "bar",
          height: 350,
        },
        plotOptions: {
          bar: {
            horizontal: false,
            columnWidth: "55%",
            endingShape: "rounded",
          },
        },
        dataLabels: {
          enabled: false,
        },
        stroke: {
          show: true,
          width: 2,
          colors: ["transparent"],
        },
        xaxis: {
          categories: [
            "Feb",
            "Mar",
            "Apr",
            "May",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
            "Oct",
          ],
        },
        yaxis: {
          title: {
            text: "$ (thousands)",
          },
        },
        fill: {
          opacity: 1,
        },
        tooltip: {
          y: {
            formatter: function (val) {
              return "$ " + val + " thousands";
            },
          },
        },
      },
    };
    this.state4 = {
      series: [
        {
          name: "PRODUCT A",
          data: [44, 55, 41, 67, 22, 43],
        },
        {
          name: "PRODUCT B",
          data: [13, 23, 20, 8, 13, 27],
        },
        {
          name: "PRODUCT C",
          data: [11, 17, 15, 15, 21, 14],
        },
        {
          name: "PRODUCT D",
          data: [21, 7, 25, 13, 22, 8],
        },
      ],
      options: {
        chart: {
          type: "bar",
          height: 350,
          stacked: true,
          toolbar: {
            show: true,
          },
          zoom: {
            enabled: true,
          },
        },
        responsive: [
          {
            breakpoint: 480,
            options: {
              legend: {
                position: "bottom",
                offsetX: -10,
                offsetY: 0,
              },
            },
          },
        ],
        plotOptions: {
          bar: {
            horizontal: false,
            borderRadius: 10,
          },
        },
        xaxis: {
          type: "datetime",
          categories: [
            "01/01/2011 GMT",
            "01/02/2011 GMT",
            "01/03/2011 GMT",
            "01/04/2011 GMT",
            "01/05/2011 GMT",
            "01/06/2011 GMT",
          ],
        },
        legend: {
          position: "right",
          offsetY: 40,
        },
        fill: {
          opacity: 1,
        },
      },
    };
    this.state5 = {
      series: [
        {
          data: [400, 430, 448, 470, 540, 580, 690, 1100, 1200, 1380],
        },
      ],
      options: {
        chart: {
          type: "bar",
          height: 350,
        },
        plotOptions: {
          bar: {
            borderRadius: 4,
            horizontal: true,
          },
        },
        dataLabels: {
          enabled: false,
        },
        xaxis: {
          categories: [
            "South Korea",
            "Canada",
            "United Kingdom",
            "Netherlands",
            "Italy",
            "France",
            "Japan",
            "United States",
            "China",
            "Germany",
          ],
        },
      },
    };
    this.state6 = {
      series: [
        {
          name: "Website Blog",
          type: "column",
          data: [440, 505, 414, 671, 227, 413, 201, 352, 752, 320, 257, 160],
        },
        {
          name: "Social Media",
          type: "line",
          data: [23, 42, 35, 27, 43, 22, 17, 31, 22, 22, 12, 16],
        },
      ],
      options: {
        chart: {
          height: 350,
          type: "line",
        },
        stroke: {
          width: [0, 4],
        },
        title: {
          text: "Traffic Sources",
        },
        dataLabels: {
          enabled: true,
          enabledOnSeries: [1],
        },
        labels: [
          "01 Jan 2001",
          "02 Jan 2001",
          "03 Jan 2001",
          "04 Jan 2001",
          "05 Jan 2001",
          "06 Jan 2001",
          "07 Jan 2001",
          "08 Jan 2001",
          "09 Jan 2001",
          "10 Jan 2001",
          "11 Jan 2001",
          "12 Jan 2001",
        ],
        xaxis: {
          type: "datetime",
        },
        yaxis: [
          {
            title: {
              text: "Website Blog",
            },
          },
          {
            opposite: true,
            title: {
              text: "Social Media",
            },
          },
        ],
      },
    };
    this.state7 = {
      series: [44, 55, 41, 17, 15],
      options: {
        chart: {
          type: "donut",
        },
        responsive: [
          {
            breakpoint: 480,
            options: {
              chart: {
                width: 200,
              },
              legend: {
                position: "bottom",
              },
            },
          },
        ],
      },
    };
    this.state8 = {
      series: [44, 55, 67, 83],
      options: {
        chart: {
          height: 350,
          type: "radialBar",
        },
        plotOptions: {
          radialBar: {
            dataLabels: {
              name: {
                fontSize: "22px",
              },
              value: {
                fontSize: "16px",
              },
              total: {
                show: true,
                label: "Total",
                formatter: function (w) {
                  // By default this function returns the average of all series. The below is just an example to show the use of custom formatter function
                  return 249;
                },
              },
            },
          },
        },
        labels: ["Apples", "Oranges", "Bananas", "Berries"],
      },
    };
  }

  render() {
    return (
      <div className="main-wrapper">
        <Header/>
        <Sidebar />
        <div className="page-wrapper">
          <div className="content container-fluid">
            {/* Page Header */}
            
              <div class="page-header">
                <div class="content-page-header">
                  <h5>Charts</h5>
                </div>
              </div>

            {/* /Page Header */}
            <div className="row">
              {/* Chart */}
              <div className="col-md-6">
                <div className="card">
                  <div className="card-header">
                    <h5 className="card-title">Apex Simple</h5>
                  </div>
                  <div className="card-body">
                    <Chart
                      options={this.state1.options}
                      series={this.state1.series}
                      type="line"
                      width={500}
                      height={320}
                    />
                  </div>
                </div>
              </div>
              {/* /Chart */}
              {/* Chart */}
              <div className="col-md-6">
                <div className="card">
                  <div className="card-header">
                    <h5 className="card-title">Area Chart</h5>
                  </div>
                  <div className="card-body">
                    <div id="s-line-area" />
                    <Chart
                      options={this.state2.options}
                      series={this.state2.series}
                      type="area"
                      height={350}
                    />
                  </div>
                </div>
              </div>
              {/* /Chart */}
              {/* Chart */}
              <div className="col-md-6">
                <div className="card">
                  <div className="card-header">
                    <h5 className="card-title">Column Chart</h5>
                  </div>
                  <div className="card-body">
                    <div id="s-col" />
                    <Chart
                      options={this.state3.options}
                      series={this.state3.series}
                      type="bar"
                      height={350}
                    />
                  </div>
                </div>
              </div>
              {/* /Chart */}
              {/* Chart */}
              <div className="col-md-6">
                <div className="card">
                  <div className="card-header">
                    <h5 className="card-title">Column Stacked Chart</h5>
                  </div>
                  <div className="card-body">
                    <div id="s-col-stacked" />
                    <Chart
                      options={this.state4.options}
                      series={this.state4.series}
                      type="bar"
                      height={350}
                    />
                  </div>
                </div>
              </div>
              {/* /Chart */}
              {/* Chart */}
              <div className="col-md-6">
                <div className="card">
                  <div className="card-header">
                    <h5 className="card-title">Bar Chart</h5>
                  </div>
                  <div className="card-body">
                    <div id="s-bar" />
                    <Chart
                      options={this.state5.options}
                      series={this.state5.series}
                      type="bar"
                      height={350}
                    />
                  </div>
                </div>
              </div>
              {/* /Chart */}
              {/* Chart */}
              <div className="col-md-6">
                <div className="card">
                  <div className="card-header">
                    <h5 className="card-title">Mixed Chart</h5>
                  </div>
                  <div className="card-body">
                    <div id="mixed-chart" />
                    <Chart
                      options={this.state6.options}
                      series={this.state6.series}
                      type="line"
                      height={350}
                    />
                  </div>
                </div>
              </div>
              {/* /Chart */}
              {/* Chart */}
              <div className="col-md-6">
                <div className="card">
                  <div className="card-header">
                    <h5 className="card-title">Donut Chart</h5>
                  </div>
                  <div className="card-body">
                    <div id="donut-chart" />
                    <Chart
                      options={this.state7.options}
                      series={this.state7.series}
                      type="donut"
                    />
                  </div>
                </div>
              </div>
              {/* /Chart */}
              {/* Chart */}
              <div className="col-md-6">
                <div className="card">
                  <div className="card-header">
                    <h5 className="card-title">Radial Chart</h5>
                  </div>
                  <div className="card-body">
                    <div id="radial-chart" />
                    <Chart
                      options={this.state8.options}
                      series={this.state8.series}
                      type="radialBar"
                      height={350}
                    />
                  </div>
                </div>
              </div>
              {/* /Chart */}
            </div>
          </div>
        </div>
      </div>
    );
  }
}
export default apexCharts;
