// kanakku-v1.9.9/angular-files/template/src/app/feature-module/products-service/category/category.component.ts
import { Component, OnInit } from '@angular/core';
import { Sort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { DataService, routes } from 'src/app/core/core.index';
import { apiResultFormat, category, pageSelection } from 'src/app/core/models/models';


@Component({
  selector: 'app-category',
  templateUrl: './category.component.html',
  styleUrls: ['./category.component.scss']
})
export class CategoryComponent implements OnInit {
  public routes = routes;
  public category: Array<category> = [];
  isCollapsed = false;
  parent = 'none';
  parent2 = 'none';
 
  public Toggledata  = false;
  dataSource!: MatTableDataSource<category>;
  public searchDataValue = '';
  // pagination variables
  public lastIndex = 0;
  public pageSize = 10;
  public totalData = 0;
  public skip = 0;
  public limit: number = this.pageSize;
  public pageIndex = 0;
  public serialNumberArray: Array<number> = [];
  public currentPage = 1;
  public pageNumberArray: Array<number> = [];
  public pageSelection: Array<pageSelection> = [];
  public totalPages = 0;
  //** / pagination variables
  

  constructor(private data: DataService) {}

  ngOnInit(): void {
    this.getTableData();
  }
  private getTableData(): void {
    this.category = [];
    this.serialNumberArray = [];

    this.data.getCategory().subscribe((data: apiResultFormat) => {
      this.totalData = data.totalData;
      data.data.map((res: category, index: number) => {
        const serialNumber = index + 1;
        if (index >= this.skip && serialNumber <= this.limit) {
          res.id = serialNumber;
          this.category.push(res);
          this.serialNumberArray.push(serialNumber);
        }
      });
      this.dataSource = new MatTableDataSource<category>(this.category);
      this.calculateTotalPages(this.totalData, this.pageSize);
    });
  }
  public sortData(sort: Sort) {
    const data = this.category.slice();
    if (!sort.active || sort.direction === '') {
      this.category = data;
    } else {
      this.category = data.sort((a, b) => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const aValue = (a as any)[sort.active];
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const bValue = (b as any)[sort.active];
        return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
      });
    }
  }
  public getMoreData(event: string): void {
    if (event == 'next') {
      this.currentPage++;
      this.pageIndex = this.currentPage - 1;
      this.limit += this.pageSize;
      this.skip = this.pageSize * this.pageIndex;
      this.getTableData();
    } else if (event == 'previous') {
      this.currentPage--;
      this.pageIndex = this.currentPage - 1;
      this.limit -= this.pageSize;
      this.skip = this.pageSize * this.pageIndex;
      this.getTableData();
    }
  }
  public moveToPage(pageNumber: number): void {
    this.currentPage = pageNumber;
    this.skip = this.pageSelection[pageNumber - 1].skip;
    this.limit = this.pageSelection[pageNumber - 1].limit;
    if (pageNumber > this.currentPage) {
      this.pageIndex = pageNumber - 1;
    } else if (pageNumber < this.currentPage) {
      this.pageIndex = pageNumber + 1;
    }
    this.getTableData();
  }
  public PageSize(): void {
    this.pageSelection = [];
    this.limit = this.pageSize;
    this.skip = 0;
    this.currentPage = 1;
    this.getTableData();
  }
  private calculateTotalPages(totalData: number, pageSize: number): void {
    this.pageNumberArray = [];
    this.totalPages = totalData / pageSize;
    if (this.totalPages % 1 != 0) {
      this.totalPages = Math.trunc(this.totalPages + 1);
    }
    for (let i = 1; i <= this.totalPages; i++) {
      const limit = pageSize * i;
      const skip = limit - pageSize;
      this.pageNumberArray.push(i);
      this.pageSelection.push({ skip: skip, limit: limit });
    }
  }
  open() {
    this.Toggledata = !this.Toggledata;
   
  }
  users = [
    { name: 'Barbara Moore', checked: false },
    { name: 'Hendry Evan', checked: false },
    { name: 'Richard Miles', checked: false }
  ];
  
  toggleCollapse() {
    this.isCollapsed = !this.isCollapsed;
  }
  user = [
    { name: 'Stationary', checked: false },
    { name: 'Medical', checked: false },
    { name: 'Designing', checked: false }
  ];
  useres = [
    { name: 'P125393', checked: false },
    { name: 'P125394', checked: false },
    { name: 'P125395', checked: false }
  ];
  files: File[] = [];
  onSelect(event: { addedFiles: File[] }) {
    this.files.push(...event.addedFiles);
  }
  onRemove(event:File) {
   this.files.splice(this.files.indexOf(event), 1);
  }

}


<!-- Page Header -->
<div class="page-header">
	<div class="content-page-header ">
		<h5>Category </h5>
		<div class="list-btn">
			<ul class="filter-list">
				<li>
				  <a
					(click)="open()"
					matTooltip="Filter"
					href="javascript:void(0);"
					class="btn btn-filters w-auto popup-toggle"
				  >
					<span class="me-2"
					  ><img src="assets/img/icons/filter-icon.svg" alt="filter" /></span
					>Filter
				  </a>
				</li>
				<li>
				  <a class="btn-filters" matTooltip="Grid-View" href="javascript:void(0);"
					><span><i class="feather icon-grid"></i></span>
				  </a>
				</li>
				<li>
				  <a class="active btn-filters" matTooltip="List-View" href="javascript:void(0);"
					><span><i class="feather icon-list"></i></span>
				  </a>
				</li>
				<li class="">
				  <div class="dropdown dropdown-action">
					<a
					  href="#"
					  class="btn-filters"
					  data-bs-toggle="dropdown"
					  aria-expanded="false"
					  matTooltip="download"
					  ><span><i class="feather icon-download"></i></span
					></a>
					<div class="dropdown-menu dropdown-menu-end">
					  <ul class="d-block">
						<li>
						  <a
							class="d-flex align-items-center download-item"
							href="javascript:void(0);"
							download
							><i class="far fa-file-pdf me-2"></i>PDF</a
						  >
						</li>
						<li>
						  <a
							class="d-flex align-items-center download-item"
							href="javascript:void(0);"
							download
							><i class="far fa-file-text me-2"></i>CVS</a
						  >
						</li>
					  </ul>
					</div>
				  </div>
				</li>
				<li>
				  <a class="btn-filters"  matTooltip="print" href="javascript:void(0);"
					><span><i class="feather icon-printer"></i></span>
				  </a>
				</li>
				<li>
				  <a class="btn btn-import" href="javascript:void(0);"
					><span
					  ><i class="feather icon-check-square me-2"></i> Import</span
					></a
				  >
				</li>
				<li>
				  <a
					class="btn btn-primary"
					href="javascript:void(0);"
					data-bs-toggle="modal"
					data-bs-target="#add_category"
					><i class="fa fa-plus-circle me-2" aria-hidden="true"></i>Add
					Category</a
				  >
				</li>
			  </ul>
		</div>
	</div>
</div>
<!-- /Page Header -->
	
<!-- Search Filter -->
<div id="filter_inputs" class="card filter-card">
	<div class="card-body pb-0">
		<div class="row">
			<div class="col-sm-6 col-md-3">
				<div class="form-group">
					<label htmlFor="label">Name</label>
					<input id="label" type="text" class="form-control">
				</div>
			</div>
			<div class="col-sm-6 col-md-3">
				<div class="form-group">
					<label htmlFor="label">Email</label>
					<input id="label" type="text" class="form-control">
				</div>
			</div>
			<div class="col-sm-6 col-md-3">
				<div class="form-group">
					<label htmlFor="label">Phone</label>
					<input id="label" type="text" class="form-control">
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /Search Filter -->

<!-- All Invoice -->
<div class="card invoices-tabs-card">
	<div class="invoices-main-tabs">
		<div class="row align-items-center">
			<div class="col-lg-12">
				<div class="invoices-tabs">
					<ul>
						<li><a [routerLink]="routes.productlist">Product</a></li>
						<li><a [routerLink]="routes.category" class="active">Category</a></li>	
						<li><a [routerLink]="routes.units">Units</a></li>	
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /All Invoice -->

<!-- Table -->
<div class="row">
	<div class="col-sm-12">
		<div class=" card-table">
			<div class="card-body">
				<div class="table-responsive">
					<table matSort
					(matSortChange)="sortData($event)"
					 class="table table-center table-hover datatable">
						<thead class="thead-light">
							<tr>
								<th  mat-sort-header="id">#</th>
								<th mat-sort-header="category">Category Name</th>
								<th mat-sort-header="img">Category Image</th>
								<th mat-sort-header="total">Total Products</th>
								<th mat-sort-header="action">Action</th>
							</tr>
						</thead>
						<tbody>
							<tr *ngFor="let data of category; let i = index">
								<td>{{data.id}}</td>
								<td>{{data.category}}</td>
								<td>
									<h2 class="table-avatar">
										<img class="avatar-img rounded" width="30" height="30" [src]="data.img" alt="User Image">
									</h2>
								</td>
								<td>{{data.total}}</td>
								<td class="d-flex align-items-center">
									<a class=" btn-action-icon me-2"  href="javascript:void(0);" data-bs-toggle="modal" data-bs-target="#edit_category"><i class="feather icon-edit"></i></a>
									<a class=" btn-action-icon" href="javascript:void(0);" data-bs-toggle="modal" data-bs-target="#delete_modal"><i class="feather icon-trash-2"></i></a>
								</td>
							</tr>
							
						</tbody>
					</table>
					<div class="table_header">
						<div class="row">
						  <div class="col-sm-12 col-md-6">
							<div class="dataTables_length">
							  <label>
								Show
								<select
								  [(ngModel)]="pageSize"
								  (ngModelChange)="PageSize()"
								  class="form-control form-control-sm"
								>
								  <option value="10">10</option>
								  <option value="25">25</option>
								  <option value="50">50</option>
								  <option value="100">100</option>
								</select>
								Entries
							  </label>
							</div>
						  </div>
						</div>
						<div class="col-sm-12 col-md-3">
						  <div class="pagination_section">
							<ul class="pagination">
							  <li
								class="page-item "
								[ngClass]="{
								  disabled: currentPage === 1
								}"
							  >
								<a
								  (click)="getMoreData('previous')"
								  class="page-link"
								  href="javascript:void(0);"
								  tabindex="-1"
								  ><i class="fa fa-angle-double-left me-2"></i>Previous</a
								>
							  </li>
			
							  <ng-container
								*ngFor="let item of pageNumberArray; let i = index"
							  >
								<li
								  class="page-item"
								  [class.active]="item === currentPage"
								  [ngClass]="
									(pageNumberArray[currentPage - 2] > item &&
									  item !== 1 &&
									  pageNumberArray.length > 6) ||
									(pageNumberArray[currentPage] < item &&
									  item !== 1 &&
									  pageNumberArray.length > 6 &&
									  pageNumberArray.length !== item)
									  ? 'hide-sub-menu'
									  : 'show-sub-menu'
								  "
								>
								  <a
									(click)="moveToPage(item)"
									class="page-link"
									href="javascript:void(0);"
								  >
									{{ item }}
									<span *ngIf="item === currentPage" class="visually-hidden"
									  >(current)</span
									>
								  </a>
								</li>
								<li
								  class="page-item"
								  *ngIf="
									i === 0 && pageNumberArray.length > 6 && currentPage > 2
								  "
								  [hidden]="currentPage === 1"
								  
								>
								  <a class="page-link" (click)="moveToPage(currentPage - 2)" tabindex="0" href="javascript:void(0);"> ... </a>
								</li>
								<li
								  *ngIf="
									i === pageNumberArray.length - 2 &&
									pageNumberArray.length > 6
								  "
								  [hidden]="
									currentPage >=
									  pageNumberArray[pageNumberArray.length - 2] ||
									totalData <
									  serialNumberArray[serialNumberArray.length - 1]
								  "
								  class="page-item"
								 
								>
								  <a class="page-link"  (click)="moveToPage(currentPage + 2)" tabindex="0" href="javascript:void(0);"> ... </a>
								</li>
							  </ng-container>
			
							  <li
								class="page-item"
								[ngClass]="{
								  disabled:
									currentPage ===
									  pageNumberArray[pageNumberArray.length - 1] ||
									  category.length === 0
								}"
							  >
								<a
								  (click)="getMoreData('next')"
								  class="page-link"
								  href="javascript:void(0);"
								  >Next<i class="fa fa-angle-double-right ms-2"></i>
								</a>
							  </li>
							</ul>
						  </div>
						</div>
					  </div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /Table -->

<!-- Add Asset -->
<div   [ngClass]="{'open-filter' : Toggledata === true}"class="toggle-sidebar">
	<div class="sidebar-layout-filter">
	  <div class="sidebar-header">
		<h5>Filter</h5>
		<a  (click)="open()" href="javascript:void(0);" class="sidebar-closes"><i class="fa-regular fa-circle-xmark"></i></a>
	  </div>
	  <div class="sidebar-body">						
		<form action="#" autocomplete="off">
		  <!-- Product -->
		  <div class="accordion" id="accordionMain1">
			<div class="card-header-new" id="headingOne">
			  <h6 class="filter-title">
			  <a href="javascript:void(0);" class="w-100" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
				Product Name
				<span class="float-end"><i class="fa-solid fa-chevron-down"></i></span>
			  </a> 
			  </h6>
			</div>
		  
			<div id="collapseOne" class="collapse show" aria-labelledby="headingOne"  data-bs-parent="#accordionExample1">
			  <div class="card-body-chat">
				<div class="row">
				  <div class="col-md-12">
					<div id="checkBoxes1">
					  <div class="form-custom">														
						<input type="text" class="form-control" id="member_search1" placeholder="Search Product">
						<span><img src="assets/img/icons/search.svg" alt="img"></span>
					  </div>
					  <div class="selectBox-cont">
						<label class="custom_check w-100">
						  <input type="checkbox" name="username">
						  <span class="checkmark"></span>  Lorem ipsum dolor sit 
						</label>
						<label class="custom_check w-100">
						  <input type="checkbox" name="username">
						  <span class="checkmark"></span> Lorem ipsum dolor sit 
						</label>
						<label class="custom_check w-100">
						  <input type="checkbox" name="username">
						  <span class="checkmark"></span> Lorem ipsum dolor sit 
						</label>
						<label class="custom_check w-100">
						  <input type="checkbox" name="username">
						  <span class="checkmark"></span> Lorem ipsum dolor sit 
						</label>
						<!-- View All -->
						<div class="view-content">
						  <div
							class="viewall-One"
							*ngFor="let user of users"
							[ngClass]="{
							  closed: !isCollapsed,
							  open: isCollapsed
							}"
						  >
							<label class="custom_check w-100">
							  <input
								type="checkbox"
								name="username"
								[(ngModel)]="user.checked"
							  />
							  <span class="checkmark"></span> {{ user.name }}
							</label>
						  </div>
						  <div class="view-all">
							<a
							  href="javascript:void(0);"
							  class="viewall-button-One"
							  (click)="toggleCollapse()"
							  ><span class="me-2">{{
								isCollapsed ? "Close" : "View All"
							  }}</span
							  ><span
								><i class="fa fa-circle-chevron-down"></i></span
							></a>
						  </div>
						</div>
						<!-- /View All -->
					  </div>
					</div>
				  </div>
				</div>
			  </div>
			</div>
		  </div>
		  <!-- /Product -->							
  
		  <!-- Product Code -->
		  <div class="accordion" id="accordionMain2">
			<div class="card-header-new" id="headingTwo">
			  <h6 class="filter-title">
			  <a href="javascript:void(0);" class="w-100 collapsed"  data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
				Product Code
				<span class="float-end"><i class="fa-solid fa-chevron-down"></i></span>
			  </a> 
			  </h6>
			</div>
		  
			<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo"  data-bs-parent="#accordionExample2">
			  <div class="card-body-chat">
				<div id="checkBoxes3">
				  <div class="selectBox-cont">
					<div class="form-custom">														
					  <input type="text" class="form-control" id="member_search2" placeholder="Search Invoice">
					  <span><img src="assets/img/icons/search.svg" alt="img"></span>
					</div>
					<label class="custom_check w-100">
					  <input type="checkbox" name="category">
					  <span class="checkmark"></span> P125389
					</label>
					<label class="custom_check w-100">
					  <input type="checkbox" name="category">
					  <span class="checkmark"></span> P125390
					</label>
					<label class="custom_check w-100">
					  <input type="checkbox" name="category">
					  <span class="checkmark"></span>  P125391
					</label>
					<label class="custom_check w-100">
					  <input type="checkbox" name="category">
					  <span class="checkmark"></span> P125392
					</label>
					 <!-- View All -->
					 <div class="view-content">
					  <div
						class="viewall-One"
						*ngFor="let useres of users"
						[ngClass]="{
						  open: !isCollapsed,
						  closed: isCollapsed
						}"
					  >
						<label class="custom_check w-100">
						  <input
							type="checkbox"
							name="useresname"
							[(ngModel)]="useres.checked"
						  />
						  <span class="checkmark"></span> {{useres.name }}
						</label>
					  </div>
					  <div class="view-all">
						<a
						  href="javascript:void(0);"
						  class="viewall-button-One"
						  (click)="toggleCollapse()"
						  ><span class="me-2">{{
							isCollapsed ? "View All" : "Close"
						  }}</span
						  ><span
							><i class="fa fa-circle-chevron-down"></i></span
						></a>
					  </div>
					</div>
					<!-- /View All -->
				  </div>
				</div>	
			  </div>
			</div>
		  </div>
		  <!-- /Product Code -->
  
		  <!-- Unts -->
		  <div class="accordion" id="accordionMain3">
			<div class="card-header-new" id="headingThree">
			  <h6 class="filter-title">
			  <a href="javascript:void(0);" class="w-100 collapsed"  data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
				Units
				<span class="float-end"><i class="fa-solid fa-chevron-down"></i></span>
			  </a> 
			  </h6>
			</div>
		  
			<div id="collapseThree" class="collapse" aria-labelledby="headingThree"  data-bs-parent="#accordionExample3">
			  <div class="card-body-chat">
				<div id="checkBoxes2">										
				  <div class="selectBox-cont">
					<label class="custom_check w-100">
					  <input type="checkbox" name="bystatus">
					  <span class="checkmark"></span> Inches
					</label>
					<label class="custom_check w-100">
					  <input type="checkbox" name="bystatus">
					  <span class="checkmark"></span>  Pieces
					</label>
					<label class="custom_check w-100">
					  <input type="checkbox" name="bystatus">
					  <span class="checkmark"></span> Hours
					</label>
					<label class="custom_check w-100">
					  <input type="checkbox" name="bystatus">
					  <span class="checkmark"></span> Box
					</label>
					<label class="custom_check w-100">
					  <input type="checkbox" name="bystatus">
					  <span class="checkmark"></span> Kilograms
					</label>
					<label class="custom_check w-100">
					  <input type="checkbox" name="bystatus">
					  <span class="checkmark"></span> Meter
					</label>
				  </div>
				</div>	
			  </div>
			</div>
		  </div>
		  <!-- /Units -->
  
		   <!-- Category -->
		   <div class="accordion accordion-last" id="accordionMain4">
			<div class="card-header-new" id="headingFour">
			  <h6 class="filter-title">
				<a
				  href="javascript:void(0);"
				  class="w-100 collapsed"
				  data-bs-toggle="collapse"
				  data-bs-target="#collapseFour"
				  aria-expanded="true"
				  aria-controls="collapseFour"
				>
				  Category
				  <span class="float-end"
					><i class="fa-solid fa-chevron-down"></i
				  ></span>
				</a>
			  </h6>
			</div>
  
			<div
			  id="collapseFour"
			  class="collapse"
			  aria-labelledby="headingFour"
			  data-bs-parent="#accordionExample4"
			>
			  <div class="card-body-chat">
				<div id="checkBoxes3">
				  <div class="selectBox-cont">
					<label class="custom_check w-100">
					  <input type="checkbox" name="category" />
					  <span class="checkmark"></span> Advertising
					</label>
					<label class="custom_check w-100">
					  <input type="checkbox" name="category" />
					  <span class="checkmark"></span> Food
					</label>
					<label class="custom_check w-100">
					  <input type="checkbox" name="category" />
					  <span class="checkmark"></span> Repairs
					</label>
					<label class="custom_check w-100">
					  <input type="checkbox" name="category" />
					  <span class="checkmark"></span> Software
					</label>
					<!--view all-->
					<div class="view-content">
					  <div
						class="viewall-One"
						*ngFor="let users of user"
						[ngClass]="{
						  open: !isCollapsed,
						  closed: isCollapsed
						}"
					  >
						<label class="custom_check w-100">
						  <input
							type="checkbox"
							name="username"
							[(ngModel)]="users.checked"
						  />
						  <span class="checkmark"></span> {{ users.name }}
						</label>
					  </div>
					  <div class="view-all">
						<a
						  href="javascript:void(0);"
						  class="viewall-button-One"
						  (click)="toggleCollapse()"
						  ><span class="me-2">{{
							isCollapsed ? "View All" : "Close"
						  }}</span
						  ><span><i class="fa fa-circle-chevron-down"></i></span
						></a>
					  </div>
					</div>
					<!-- /View All -->
				  </div>
				</div>
			  </div>
			</div>
		  </div>
		  <!-- /Category -->
  
		  <div class="filter-buttons">
			<button type="submit" class="d-inline-flex align-items-center justify-content-center btn w-100 btn-primary">
			  Apply
			</button>
			<button type="submit" class="d-inline-flex align-items-center justify-content-center btn w-100 btn-secondary">
			  Reset
			</button>
		  </div>
		</form>
		
	  </div>
	</div>
  </div>
<!-- /Add Asset -->	
<!-- Add Category Modal -->
<div class="modal custom-modal fade" id="add_category" role="dialog">
	<div class="modal-dialog modal-dialog-centered modal-md">
		<div class="modal-content">
			<div class="modal-header border-0 pb-0">
				<div class="form-header modal-header-title text-start mb-0">
					<h4 class="mb-0">Add Category</h4>
				</div>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
					
				</button>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-12">
						<div class="card-body">
							<div class="form-group-item border-0 pb-0 mb-0">
								<div class="row">
									<div class="col-lg-12 col-sm-12">
										<div class="input-block mb-3">
											<label>Name <span class="text-danger">*</span></label>
											<input type="text"  class="form-control" placeholder="Enter Title">
										</div>											
									</div>
									<div class="col-lg-12 col-sm-12">
										<div class="input-block mb-3">
											<label>Slug</label>
											<input type="text" class="form-control" placeholder="Enter Slug">
										</div>
									</div>
									<div class="col-lg-12 col-sm-12">
										<div class="input-block mb-3">
											<label>Parent Category</label>
											<mat-select [(ngModel)]="parent" [ngModelOptions]="{standalone: true}" class="select mat-cust-select form-control">
												<mat-option value="none">None</mat-option>
												<mat-option value="customer1">Coupon</mat-option>
												<mat-option value="customer2">News</mat-option>
												<mat-option value="customer3">Plugins</mat-option>
												<mat-option value="customer3">Theme</mat-option>
												<mat-option value="customer3">Tutorial</mat-option>
											</mat-select>
										</div>
									</div>
									<div class="col-lg-12 col-sm-12">
										<div class="input-block mb-0 pb-0">
											<label>Image</label>
											<ngx-dropzone (change)="onSelect($event)" class="service-upload">
												<ngx-dropzone-label class="drop-browse align-center">
												  <span
													><img src="assets/img/icons/drop-icon.svg" alt="upload"
												  /></span>
												  <div class="d-flex">
													Drop your files here or<span class="text-primary ms-1"
													>browse</span
												  >
												  </div>
												   
												  <span class="text-muted">Maximum size: 50MB</span>
												</ngx-dropzone-label>
												<ngx-dropzone-image-preview
												  ngProjectAs="ngx-dropzone-preview"
												  *ngFor="let f of files"
												  [file]="f"
												  [removable]="true"
												  (removed)="onRemove(f)"
												>
												</ngx-dropzone-image-preview>
											</ngx-dropzone>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<a href="#" data-bs-dismiss="modal" class="btn btn-back cancel-btn me-2">Cancel</a>
				<a href="#" data-bs-dismiss="modal" class="btn btn-primary paid-continue-btn">Add Category</a>
			</div>
		</div>
	</div>
</div>
<!-- /Add Category Modal -->

<!-- Add Category Modal -->
<div class="modal custom-modal fade" id="edit_category" role="dialog">
	<div class="modal-dialog modal-dialog-centered modal-md">
		<div class="modal-content">
			<div class="modal-header border-0 pb-0">
				<div class="form-header modal-header-title text-start mb-0">
					<h4 class="mb-0">Edit Category</h4>
				</div>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
					
				</button>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-12">
						<div class="card-body">
							<div class="form-group-item border-0 pb-0 mb-0">
								<div class="row">
									<div class="col-lg-12 col-sm-12">
										<div class="input-block mb-3">
											<label>Name <span class="text-danger">*</span></label>
											<input type="text"  class="form-control" value="Advertising" placeholder="Enter Title">
										</div>											
									</div>
									<div class="col-lg-12 col-sm-12">
										<div class="input-block mb-3">
											<label>Slug</label>
											<input type="text" class="form-control" value="advertising" placeholder="Enter Slug">
										</div>
									</div>
									<div class="col-lg-12 col-sm-12">
										<div class="input-block mb-3">
											<label>Parent Category</label>
											<mat-select [(ngModel)]="parent2" [ngModelOptions]="{standalone: true}" class="select mat-cust-select form-control">
												<mat-option value="none">None</mat-option>
												<mat-option value="customer1">Coupon</mat-option>
												<mat-option value="customer2">News</mat-option>
												<mat-option value="customer3">Plugins</mat-option>
												<mat-option value="customer3">Theme</mat-option>
												<mat-option value="customer3">Tutorial</mat-option>
											</mat-select>
										</div>
									</div>
									<div class="col-lg-12 col-sm-12">
										<div class="input-block mb-0 pb-0">
											<label>Image</label>
											<ngx-dropzone (change)="onSelect($event)" class="service-upload">
												<ngx-dropzone-label class="drop-browse align-center">
												  <span
													><img src="assets/img/icons/drop-icon.svg" alt="upload"
												  /></span>
												  <div class="d-flex">
													Drop your files here or<span class="text-primary ms-1"
													>browse</span
												  >
												  </div>
												   
												  <span class="text-muted">Maximum size: 50MB</span>
												</ngx-dropzone-label>
												<ngx-dropzone-image-preview
												  ngProjectAs="ngx-dropzone-preview"
												  *ngFor="let f of files"
												  [file]="f"
												  [removable]="true"
												  (removed)="onRemove(f)"
												>
												</ngx-dropzone-image-preview>
											</ngx-dropzone>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<a href="#" data-bs-dismiss="modal" class="btn btn-back cancel-btn me-2">Cancel</a>
				<a href="#" data-bs-dismiss="modal" class="btn btn-primary paid-continue-btn">Update</a>
			</div>
		</div>
	</div>
</div>
<!-- /Add Vendor Modal -->

<!-- Delete Items Modal -->
<div class="modal custom-modal fade" id="delete_modal" role="dialog">
	<div class="modal-dialog modal-dialog-centered modal-md">
		<div class="modal-content">
			<div class="modal-body">
				<div class="form-header">
					<h3>Delete Category</h3>
					<p>Are you sure want to delete?</p>
				</div>
				<div class="modal-btn delete-action">
					<div class="row">
						<div class="col-6">
							<button type="reset" data-bs-dismiss="modal" class="w-100 btn btn-primary paid-continue-btn">Delete</button>
						</div>
						<div class="col-6">
							<button type="submit" data-bs-dismiss="modal" class="w-100 btn btn-primary paid-cancel-btn">Cancel</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- /Delete Items Modal -->

// kanakku-v1.9.9/reactjs-files/template-rtl/src/products/category.jsx
import React, { useState } from "react";
import { Link } from "react-router-dom";
import Header from "../layouts/Header";
import Sidebar from "../layouts/Sidebar";
import FeatherIcon from "feather-icons-react";
import Data from "../assets/jsons/category";
import "../_components/antd.css";
import { Table } from "antd";
import {
  onShowSizeChange,
  itemRender,
} from "../_components/paginationfunction";
import AddVendor from "../vendors/addVendor";
import Select2 from "react-select2-wrapper";
import { DropIcon } from "../_components/imagepath";

const Category = () => {

  const [menu, setMenu] = useState(false);
  const [show, setShow] = useState(false);

  const toggleMobileMenu = () => {
    setMenu(!menu);
  };

  const [category, setCategory] = useState([
    { id: 1, text: "None" },
    { id: 2, text: "Coupons" },
    { id: 3, text: "News" },
    { id: 4, text: "Plugins" },
    { id: 4, text: "Themes" },
    { id: 4, text: "Tutorial" },
  ]);

  const datasource = Data?.Data;
  console.log(datasource);

  const columns = [
    {
      title: "#",
      dataIndex: "Id",
      sorter: (a, b) => a.Id.length - b.Id.length,
    },
    {
      title: "Category Name",
      dataIndex: "Category",
      sorter: (a, b) => a.Category.length - b.Category.length,
    },
    {
      title: "Category Image",
      dataIndex: "Img",
      render: (text, record) => (
        <h2 className="table-avatar">
          <img
            className="avatar-img rounded"
            width={30}
            height={30}
            src={record.Img}
            alt="User Image"
          />
        </h2>
      ),
      sorter: (a, b) => a.Img.length - b.Img.length,
    },
    {
      title: "Total Products",
      dataIndex: "Total",
      sorter: (a, b) => a.Total.length - b.Total.length,
    },
    {
      title: "Action",
      dataIndex: "Action",
      render: (text, record) => (
        <div className="d-flex align-items-center">
          <Link
            className=" btn-action-icon ms-2"
            to="#"
            data-bs-toggle="modal"
            data-bs-target="#edit_category"
          >
            <i className="fe fe-edit">
              <FeatherIcon icon="edit" />
            </i>
          </Link>
          <Link
            className=" btn-action-icon"
            to="#"
            data-bs-toggle="modal"
            data-bs-target="#delete_modal"
          >
            <i className="fe fe-trash-2">
              <FeatherIcon icon="trash-2" />
            </i>
          </Link>
        </div>
      ),
      sorter: (a, b) => a.Action.length - b.Action.length,
    },
  ];

  return (
    <>
      <div className={`main-wrapper ${menu ? "slide-nav" : ""}`}>
        <Header onMenuClick={(value) => toggleMobileMenu()} />
        <Sidebar />

        <div className="page-wrapper">
          <div className="content container-fluid">
            {/* Page Header */}
            <div className="page-header">
              <div className="content-page-header ">
                <h5>Category </h5>
                <div className="list-btn">
                  <ul className="filter-list">
                    <li>
                      <Link className="btn btn-filters w-auto popup-toggle"
                      onClick={() => setShow(!show)}
                      >
                        <span className="ms-2">
                          {/* <i className="fe fe-filter" /> */}
                          <FeatherIcon icon="filter"/>
                        </span>
                        Filter{" "}
                      </Link>
                    </li>
                    <li>
                      <Link className="btn-filters" to="#">
                        <span>
                          {/* <i className="fe fe-grid" /> */}
                          <FeatherIcon icon="grid"/>
                        </span>
                      </Link>
                    </li>
                    <li>
                      <Link className="active btn-filters ms-2" to="#">
                        <span>
                          {/* <i className="fe fe-list" /> */}
                          <FeatherIcon icon="list"/>
                        </span>{" "}
                      </Link>
                    </li>
                    <li className="">
                      <div className="dropdown dropdown-action">
                        <Link
                          to="#"
                          className="btn-filters ms-2"
                          data-bs-toggle="dropdown"
                          aria-expanded="false"
                        >
                          <span>
                            {/* <i className="fe fe-download" /> */}
                            <FeatherIcon icon="download"/>
                          </span>
                        </Link>
                        <div className="dropdown-menu dropdown-menu-right">
                          <ul className="d-block">
                            <li>
                              <Link
                                className="d-flex align-items-center download-item"
                                to="#"
                                download=""
                              >
                                <i className="far fa-file-pdf ms-2" />
                                PDF
                              </Link>
                            </li>
                            <li>
                              <Link
                                className="d-flex align-items-center download-item"
                                to="#"
                                download=""
                              >
                                <i className="far fa-file-text ms-2" />
                                CVS
                              </Link>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </li>
                    <li>
                      <Link className="btn-filters ms-2" to="#">
                        <span>
                          {/* <i className="fe fe-printer" /> */}
                          <FeatherIcon icon="printer"/>
                        </span>
                      </Link>
                    </li>
                    <li>
                      <Link
                        className="btn btn-primary"
                        to="#"
                        data-bs-toggle="modal"
                        data-bs-target="#add_category"
                      >
                        <i
                          className="fa fa-plus-circle ms-2"
                          aria-hidden="true"
                        />
                        Add Category
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            {/* /Page Header */}
            {/* Search Filter */}
            <div id="filter_inputs" className="card filter-card">
              <div className="card-body pb-0">
                <div className="row">
                  <div className="col-sm-6 col-md-3">
                    <div className="form-group">
                      <label>Name</label>
                      <input type="text" className="form-control" />
                    </div>
                  </div>
                  <div className="col-sm-6 col-md-3">
                    <div className="form-group">
                      <label>Email</label>
                      <input type="text" className="form-control" />
                    </div>
                  </div>
                  <div className="col-sm-6 col-md-3">
                    <div className="form-group">
                      <label>Phone</label>
                      <input type="text" className="form-control" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* /Search Filter */}
            {/* All Invoice */}
            <div className="card invoices-tabs-card">
              <div className="invoices-main-tabs">
                <div className="row align-items-center">
                  <div className="col-lg-12">
                    <div className="invoices-tabs">
                      <ul>
                        <li>
                          <Link to="/product-list">Product</Link>
                        </li>
                        <li>
                          <Link to="/category" className="active">
                            Category
                          </Link>
                        </li>
                        <li>
                          <Link to="/units">Units</Link>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* /All Invoice */}
            {/* Table */}
            <div className="row">
              <div className="col-sm-12">
                <div className=" card-table">
                  <div className="card-body category">
                    <div className="table-responsive table-hover">
                      <Table
                        pagination={{
                          total: datasource.length,
                          showTotal: (total, range) =>
                            `Showing ${range[0]} to ${range[1]} of ${total} entries`,
                          showSizeChanger: true,
                          onShowSizeChange: onShowSizeChange,
                          itemRender: itemRender,
                        }}
                        columns={columns}
                        dataSource={datasource}
                        rowKey={(record) => record.id}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* /Table */}
          </div>
        </div>

        <AddVendor 
          setShow={setShow}
          show={show}
        />

        <div
          className="modal custom-modal fade"
          id="add_category"
          role="dialog"
        >
          <div className="modal-dialog modal-dialog-centered modal-md">
            <div className="modal-content">
              <div className="modal-header border-0 pb-0">
                <div className="form-header modal-header-title text-start mb-0">
                  <h4 className="mb-0">Add Category</h4>
                </div>
                <button
                  type="button"
                  className="close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <span className="align-center" aria-hidden="true">
                    ×
                  </span>
                </button>
              </div>
              <div className="modal-body">
                <div className="row">
                  <div className="col-md-12">
                    <div className="card-body">
                      <div className="form-group-item border-0 pb-0 mb-0">
                        <div className="row">
                          <div className="col-lg-12 col-sm-12">
                            <div className="form-group">
                              <label>
                                Name <span className="text-danger">*</span>
                              </label>
                              <input
                                type="text"
                                className="form-control"
                                placeholder="Enter Title"
                              />
                            </div>
                          </div>
                          <div className="col-lg-12 col-sm-12">
                            <div className="form-group">
                              <label>Slug</label>
                              <input
                                type="text"
                                className="form-control"
                                placeholder="Enter Slug"
                              />
                            </div>
                          </div>
                          <div className="col-lg-12 col-sm-12">
                            <div className="form-group">
                              <label>Parent Category</label>
                              <Select2
                                // className="w-100"
                                data={category}
                                options={{
                                  placeholder: "None",
                                }}
                              />
                            </div>
                          </div>
                          <div className="col-lg-12 col-sm-12">
                            <div className="form-group mb-0 pb-0">
                              <label>Image</label>
                              <div className="form-group service-upload mb-0">
                                <span>
                                  <img src={DropIcon} alt="upload" />
                                </span>
                                <h6 className="drop-browse align-center">
                                  Drop your files here or
                                  <span className="text-primary ms-1">
                                    browse
                                  </span>
                                </h6>
                                <p className="text-muted">Maximum size: 50MB</p>
                                <input
                                  type="file"
                                  multiple=""
                                  id="image_sign"
                                />
                                <div id="frames" />
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="modal-footer">
                <Link
                  to="#"
                  data-bs-dismiss="modal"
                  className="btn btn-primary paid-cancel-btn ms-2"
                >
                  Cancel
                </Link>
                <Link
                  to="#"
                  data-bs-dismiss="modal"
                  className="btn btn-primary paid-continue-btn"
                >
                  Add Category
                </Link>
              </div>
            </div>
          </div>
        </div>

        <div
          className="modal custom-modal fade"
          id="edit_category"
          role="dialog"
        >
          <div className="modal-dialog modal-dialog-centered modal-md">
            <div className="modal-content">
              <div className="modal-header border-0 pb-0">
                <div className="form-header modal-header-title text-start mb-0">
                  <h4 className="mb-0">Edit Category</h4>
                </div>
                <button
                  type="button"
                  className="close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <span className="align-center" aria-hidden="true">
                    ×
                  </span>
                </button>
              </div>
              <div className="modal-body">
                <div className="row">
                  <div className="col-md-12">
                    <div className="card-body">
                      <div className="form-group-item border-0 pb-0 mb-0">
                        <div className="row">
                          <div className="col-lg-12 col-sm-12">
                            <div className="form-group">
                              <label>
                                Name <span className="text-danger">*</span>
                              </label>
                              <input
                                type="text"
                                className="form-control"
                                defaultValue="Advertising"
                                placeholder="Enter Title"
                              />
                            </div>
                          </div>
                          <div className="col-lg-12 col-sm-12">
                            <div className="form-group">
                              <label>Slug</label>
                              <input
                                type="text"
                                className="form-control"
                                defaultValue="advertising"
                                placeholder="Enter Slug"
                              />
                            </div>
                          </div>
                          <div className="col-lg-12 col-sm-12">
                            <div className="form-group">
                              <label>Parent Category</label>
                              <Select2
                                // className="w-100"
                                data={category}
                                options={{
                                  placeholder: "None",
                                }}
                              />
                            </div>
                          </div>
                          <div className="col-lg-12 col-sm-12">
                            <div className="form-group mb-0 pb-0">
                              <label>Image</label>
                              <div className="form-group service-upload mb-0">
                                <span>
                                  <img
                                    src={DropIcon}
                                    alt="upload"
                                  />
                                </span>
                                <h6 className="drop-browse align-center">
                                  Drop your files here or
                                  <span className="text-primary ms-1">
                                    browse
                                  </span>
                                </h6>
                                <p className="text-muted">Maximum size: 50MB</p>
                                <input
                                  type="file"
                                  multiple=""
                                  id="image_sign"
                                />
                                <div id="frames" />
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="modal-footer">
                <a
                  href="#"
                  data-bs-dismiss="modal"
                  className="btn btn-primary paid-cancel-btn ms-2"
                >
                  Cancel
                </a>
                <a
                  href="#"
                  data-bs-dismiss="modal"
                  className="btn btn-primary paid-continue-btn"
                >
                  Update
                </a>
              </div>
            </div>
          </div>
        </div>

        <div
          className="modal custom-modal fade"
          id="delete_modal"
          role="dialog"
        >
          <div className="modal-dialog modal-dialog-centered modal-md">
            <div className="modal-content">
              <div className="modal-body">
                <div className="form-header">
                  <h3>Delete Category</h3>
                  <p>Are you sure want to delete?</p>
                </div>
                <div className="modal-btn delete-action">
                  <div className="row">
                    <div className="col-6">
                      <button
                        type="reset"
                        data-bs-dismiss="modal"
                        className="w-100 btn btn-primary paid-continue-btn"
                      >
                        Delete
                      </button>
                    </div>
                    <div className="col-6">
                      <button
                        type="submit"
                        data-bs-dismiss="modal"
                        className="w-100 btn btn-primary paid-cancel-btn"
                      >
                        Cancel
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Category;
