// kanakku-v1.9.9/reactjs-files/template-rtl/src/blog/addCategories.jsx
import React, { useState } from "react";
import { Link } from "react-router-dom";
import Header from "../layouts/Header";
import Sidebar from "../layouts/Sidebar";
import ReactTagsInput from "./tagInput";
import InputTag from "./inputTag";

const AddCategories = () => {
  const [menu, setMenu] = useState(false);

  const toggleMobileMenu = () => {
    setMenu(!menu);
  };

  return (
    <>
      <div className={`main-wrapper ${menu ? "slide-nav" : ""}`}>
        <Header onMenuClick={(value) => toggleMobileMenu()} />
        <Sidebar />

        <div className="page-wrapper">
          <div className="content container-fluid">
            <div className="content-page-header">
              <h5>Add Category</h5>
            </div>
            <div className="row">
              <div className="col-md-12">
                <div className="card-body">
                  <div className="form-group-item border-0 pb-0">
                    <div className="row">
                      <div className="col-lg-4 col-md-6 col-sm-12">
                        <div className="form-group">
                          <label>
                            Category Name <span className="text-danger">*</span>
                          </label>
                          <input
                            type="text"
                            className="form-control"
                            placeholder="Enter Title"
                          />
                        </div>
                      </div>
                      <div className="col-lg-4 col-md-6 col-sm-12">
                        <div className="form-group">
                          <label>
                            Slug <span className="text-danger">*</span>
                          </label>
                          <input
                            type="text"
                            className="form-control mb-2"
                            placeholder="Enter Title"
                          />
                          <span className="optional">
                            (If you leave it empty, it will be generated
                            automatically.)
                          </span>
                        </div>
                      </div>
                      <div className="col-lg-4 col-md-6 col-sm-12">
                        <div className="form-group">
                          <label>
                            Description (Meta Tag){" "}
                            <span className="star-red">*</span>
                          </label>
                          {/* <input
                            type="text"
                            data-role="tagsinput"
                            className="input-tags form-control"
                            placeholder=""
                            name="services"
                            defaultValue="Description Tag"
                            id="services"
                          /> */}
                          <ReactTagsInput/>
                        </div>
                      </div>
                      <div className="col-lg-4 col-md-6 col-sm-12">
                        <div className="form-group">
                          <label>
                            Keywords (Meta Tag){" "}
                            <span className="star-red">*</span>
                          </label>
                          {/* <input
                            type="text"
                            data-role="tagsinput"
                            className="input-tags form-control"
                            placeholder=""
                            name="services"
                            defaultValue="Keywords Tag"
                            id="services2"
                          /> */}
                          <InputTag/>
                        </div>
                      </div>
                      <div className="col-lg-4 col-md-6 col-sm-12">
                        <div className="form-group">
                          <label>
                            Order <span className="text-danger">*</span>
                          </label>
                          <input
                            type="text"
                            className="form-control"
                            placeholder="Enter Title"
                          />
                        </div>
                      </div>
                      <div className="col-lg-4 col-md-6 col-sm-12">
                        <div className="form-group mb-0 mt-5">
                          <div className="check-mark-status d-flex justify-content-between">
                            <h6 className="label-text">Status</h6>
                            <div className="status-toggle">
                              <input
                                id="rating_1"
                                className="check"
                                type="checkbox"
                                defaultChecked="true"
                              />
                              <label
                                htmlFor="rating_1"
                                className="checktoggle checkbox-bg"
                              >
                                checkbox
                              </label>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="text-end">
                    <button
                      type="submit"
                      className="btn btn-primary cancel ms-2"
                    >
                      Cancel
                    </button>
                    <button type="submit" className="btn btn-primary">
                      Add Category
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default AddCategories;

// kanakku-v1.9.9/vuejs-files/template-rtl/src/views/pages/content/blog/add-categories.vue
<template>
  <!-- Main Wrapper -->
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>
    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <div class="content-page-header">
          <h5>Add Category</h5>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="card-body">
              <div class="form-group-item border-0 pb-0">
                <div class="row">
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Category Name <span class="text-danger">*</span></label>
                      <input type="text" class="form-control" placeholder="Enter Title" />
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Slug <span class="text-danger">*</span></label>
                      <input
                        type="text"
                        class="form-control mb-2"
                        placeholder="Enter Title"
                      />
                      <span class="optional"
                        >(If you leave it empty, it will be generated
                        automatically.)</span
                      >
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label
                        >Description (Meta Tag) <span class="star-red">*</span></label
                      >
                      <vue3-tags-input :tags="tags" class="input-tags form-control" />
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Keywords (Meta Tag) <span class="star-red">*</span></label>
                      <vue3-tags-input :tags="tag" class="input-tags form-control" />
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Order <span class="text-danger">*</span></label>
                      <input type="text" class="form-control" placeholder="Enter Title" />
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group mb-0 mt-5">
                      <div class="check-mark-status d-flex justify-content-between">
                        <h6 class="label-text">Status</h6>
                        <div class="status-toggle">
                          <input id="rating_1" class="check" type="checkbox" checked="" />
                          <label for="rating_1" class="checktoggle checkbox-bg"
                            >checkbox</label
                          >
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="text-end">
                  <button type="submit" class="btn btn-primary cancel me-2">
                    Cancel
                  </button>
                  <b-button type="submit" variant="primary">Add Category</b-button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /Page Wrapper -->
    </div>
  </div>
  <!-- /Main Wrapper -->
</template>
<script>
import Vue3TagsInput from "vue3-tags-input";
export default {
  components: {
    Vue3TagsInput,
  },
  data() {
    return { tags: ["Description Tag"], tag: ["Keywords Tag"] };
  },
};
</script>
