// kanakku-v1.9.9/reactjs-files/template-rtl/src/blog/categories.jsx
import React, { useState } from "react";
import { Link } from "react-router-dom";
import Header from "../layouts/Header";
import Sidebar from "../layouts/Sidebar";
import "../_components/antd.css";
import { Pagination, Table } from "antd";
import Data from "../assets/jsons/categories";
import FeatherIcon from "feather-icons-react";
import {
  onShowSizeChange,
  itemRender,
} from "../_components/paginationfunction";
import AddVendor from "../vendors/addVendor";

const Categories = () => {
  const [menu, setMenu] = useState(false);
  const [show, setShow] = useState(false);

  const toggleMobileMenu = () => {
    setMenu(!menu);
  };

  const datasource = Data?.Data;
  console.log(datasource);

  const columns = [
    {
      title: "#",
      dataIndex: "Id",
      sorter: (a, b) => a.Id.length - b.Id.length,
    },
    {
      title: "Category Name",
      dataIndex: "Name",
      render: (text, record) => (
        <>
          <div>
            <h2>
              <img
                className="avatar-img rounded ms-2"
                width={30}
                height={30}
                src={record.CategoryImg}
                alt="User Image"
              />
            </h2>
            {record.Name}
          </div>
        </>
      ),
      sorter: (a, b) => a.Name.length - b.Name.length,
    },
    {
      title: "Date",
      dataIndex: "date",
      sorter: (a, b) => a.date.length - b.date.length,
    },
    {
      title: "Added By",
      dataIndex: "Added",
      render: (text, record) => (
        <>
          <h2 className="table-avatar">
            <Link to="profile" className="avatar avatar-sm ms-2">
              <img
                className="avatar-img rounded-circle"
                src={record.img}
                alt="User Image"
              />
            </Link>
            <Link to="profile">{record.Added}</Link>
          </h2>
        </>
      ),
      sorter: (a, b) => a.Added.length - b.Added.length,
    },
    {
      title: "Status",
      dataIndex: "Status",
      render: (text, record) => (
        <>
          <div className="status-toggle mt-4">
            <input
              id="rating_1"
              className="check"
              type="checkbox"
              defaultChecked="true"
            />
            <label htmlFor="rating_1" className="checktoggle checkbox-bg">
              checkbox
            </label>
          </div>
        </>
      ),
      sorter: (a, b) => a.Status.length - b.Status.length,
    },
    {
      title: "Action",
      dataIndex: "Action",
      render: (text, record) => (
        <>
          <div className="d-flex align-items-center">
            <Link
              className=" btn-action-icon ms-2"
              to="#"
              download=""
            >
              {/* <i className="fe fe-edit" /> */}
              <FeatherIcon icon="edit"/>
            </Link>
            <Link
              className=" btn-action-icon"
              to="#"
              download=""
            >
              {/* <i className="fe fe-trash-2" /> */}
              <FeatherIcon icon="trash-2"/>
            </Link>
          </div>
        </>
      ),
      sorter: (a, b) => a.Action.length - b.Action.length,
    },
  ];

  return (
    <>
      <div className={`main-wrapper ${menu ? "slide-nav" : ""}`}>
        <Header onMenuClick={(value) => toggleMobileMenu()} />
        <Sidebar />

        <div className="page-wrapper">
          <div className="content container-fluid">
            {/* Page Header */}
            <div className="page-header">
              <div className="content-page-header ">
                <h5>Categories</h5>
                <div className="list-btn">
                  <ul className="filter-list">
                    <li>
                      <Link className="btn btn-filters w-auto popup-toggle"
                        onClick={() => setShow(!show)}
                      >
                        <span className="ms-2">
                          {/* <i className="fe fe-filter" /> */}
                          <FeatherIcon icon="filter"/>
                        </span>
                        Filter{" "}
                      </Link>
                    </li>
                    <li>
                      <Link className="btn-filters" to="#">
                        <span>
                          {/* <i className="fe fe-settings" /> */}
                          <FeatherIcon icon="settings"/>
                        </span>{" "}
                      </Link>
                    </li>
                    <li>
                      <Link className="btn-filters" to="#">
                        <span>
                          {/* <i className="fe fe-grid" /> */}
                          <FeatherIcon icon="grid"/>
                        </span>{" "}
                      </Link>
                    </li>
                    <li>
                      <Link
                        className="active btn-filters"
                        to="#"
                      >
                        <span>
                          {/* <i className="fe fe-list" /> */}
                          <FeatherIcon icon="list"/>
                        </span>{" "}
                      </Link>
                    </li>
                    <li>
                      <Link className="btn btn-primary" to="/add-categories">
                        <i
                          className="fa fa-plus-circle ms-2"
                          aria-hidden="true"
                        />
                        Add Categories
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            {/* /Page Header */}
            {/* Search Filter */}
            <div id="filter_inputs" className="card filter-card">
              <div className="card-body pb-0">
                <div className="row">
                  <div className="col-sm-6 col-md-3">
                    <div className="form-group">
                      <label>Name</label>
                      <input type="text" className="form-control" />
                    </div>
                  </div>
                  <div className="col-sm-6 col-md-3">
                    <div className="form-group">
                      <label>Email</label>
                      <input type="text" className="form-control" />
                    </div>
                  </div>
                  <div className="col-sm-6 col-md-3">
                    <div className="form-group">
                      <label>Phone</label>
                      <input type="text" className="form-control" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* /Search Filter */}
            {/* Table */}
            <div className="row">
              <div className="col-sm-12">
                <div className=" card-table">
                  <div className="card-body Categories">
                    <div className="table-responsive table-hover">
                      <Table
                        pagination={{
                          total: datasource.length,
                          showTotal: (total, range) =>
                            `Showing ${range[0]} to ${range[1]} of ${total} entries`,
                          showSizeChanger: true,
                          onShowSizeChange: onShowSizeChange,
                          itemRender: itemRender,
                        }}
                        columns={columns}
                        dataSource={datasource}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* /Table */}
          </div>
        </div>

        <AddVendor 
          setShow={setShow}
          show={show}
        />
        
      </div>
    </>
  );
};

export default Categories;

// kanakku-v1.9.9/vuejs-files/template-rtl/src/views/pages/content/blog/categories.vue
<template>
  <!-- Main Wrapper -->
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>
    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <blogheader :title="title" :path="path" :text="text" />

        <!-- Search Filter -->
        <div id="filter_inputs" class="card filter-card">
          <div class="card-body pb-0">
            <div class="row">
              <div class="col-sm-6 col-md-3">
                <div class="form-group">
                  <label>Name</label>
                  <input type="text" class="form-control" />
                </div>
              </div>
              <div class="col-sm-6 col-md-3">
                <div class="form-group">
                  <label>Email</label>
                  <input type="text" class="form-control" />
                </div>
              </div>
              <div class="col-sm-6 col-md-3">
                <div class="form-group">
                  <label>Phone</label>
                  <input type="text" class="form-control" />
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /Search Filter -->

        <!-- Table -->
        <div class="row">
          <div class="col-sm-12">
            <div class="card-table">
              <div class="card-body">
                <div class="table-responsive">
                  <a-table
                    class="stripped table-hover"
                    :columns="columns"
                    :data-source="data"
                    @change="onChange"
                  >
                    <template #bodyCell="{ column, record }">
                      <template v-if="column.key === 'id'">
                        <h2 class="d-flex text-center">
                          <img
                            class="avatar-img rounded me-2"
                            width="30"
                            height="30"
                            :src="require(`@/assets/img/category/${record.img}`)"
                            alt="User Image"
                          /><span class="mt-2">{{ record.CategoryName }}</span>
                        </h2>
                      </template>
                      <template v-else-if="column.key === 'AddedBy'">
                        <h2 class="table-avatar">
                          <router-link to="profile" class="avatar avatar-sm me-2"
                            ><img
                              class="avatar-img rounded-circle"
                              :src="require(`@/assets/img/profiles/${record.img1}`)"
                              alt="User Image"
                          /></router-link>
                          <router-link to="profile">{{ record.AddedBy }}</router-link>
                        </h2>
                      </template>
                      <template v-else-if="column.key === 'Status'">
                        <div class="status-toggle">
                          <input
                            :id="record.Id"
                            class="check"
                            type="checkbox"
                            checked=""
                          />
                          <label :for="record.For" class="checktoggle checkbox-bg">{{
                            record.Status
                          }}</label>
                        </div>
                      </template>
                      <template v-else-if="column.key === 'action'">
                        <a
                          class="btn-action-icon me-2"
                          href="javascript:void(0);"
                          download=""
                          ><i class="feather feather-edit"></i
                        ></a>
                        <a class="btn-action-icon" href="javascript:void(0);" download=""
                          ><i class="feather feather-trash-2"></i
                        ></a>
                      </template>
                    </template>
                  </a-table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /Table -->
      </div>
    </div>
    <!-- /Page Wrapper -->
  </div>
  <!-- /Main Wrapper -->
</template>
<script>
const columns = [
  {
    title: "#",
    dataIndex: "NUM",
    sorter: {
      compare: (a, b) => {
        a = a.NUM.toLowerCase();
        b = b.NUM.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Category Name",
    dataIndex: "CategoryName",
    key: "id",
    sorter: (a, b) => a.CategoryName.localeCompare(b.CategoryName),
  },
  {
    title: "Date",
    dataIndex: "Date",
    sorter: (a, b) => a.Date.localeCompare(b.Date),
  },
  {
    title: "Added By",
    dataIndex: "AddedBy",
    key: "AddedBy",
    sorter: {
      compare: (a, b) => {
        a = a.AddedBy.toLowerCase();
        b = b.AddedBy.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Status",
    dataIndex: "Status",
    key: "Status",
    sorter: {
      compare: (a, b) => {
        a = a.Status.toLowerCase();
        b = b.Status.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },

  {
    title: "Action",
    key: "action",
    sorter: true,
  },
];
const data = [
  {
    NUM: "1",
    CategoryName: "Advertising",
    Date: "25 Fb 2022, 06:12 PM",
    AddedBy: "Admin",
    Status: "checkbox",
    Id: "rating_1",
    For: "rating_1",
    img: "category-01.jpg",
    img1: "avatar-01.jpg",
  },
  {
    NUM: "2",
    CategoryName: "Food",
    Date: "19 Dec 2022, 06:12 PM",
    AddedBy: "Admin",
    Status: "checkbox",
    Id: "rating_2",
    For: "rating_2",
    img: "category-02.jpg",
    img1: "avatar-01.jpg",
  },
  {
    NUM: "3",
    CategoryName: "Marketing",
    Date: "21 Dec 2022, 06:12 PM",
    AddedBy: "Admin",
    Status: "checkbox",
    Id: "rating_3",
    For: "rating_3",
    img: "category-03.jpg",
    img1: "avatar-01.jpg",
  },
  {
    NUM: "4",
    CategoryName: "Repairs",
    Date: "30 Jan 2022, 06:12 PM",
    AddedBy: "Admin",
    Status: "checkbox",
    Id: "rating_4",
    For: "rating_4",
    img: "category-04.jpg",
    img1: "avatar-01.jpg",
  },
  {
    NUM: "5",
    CategoryName: "Software",
    Date: "19 Mar 2022, 06:12 PM",
    AddedBy: "Admin",
    Status: "checkbox",
    Id: "rating_5",
    For: "rating_5",
    img: "category-05.jpg",
    img1: "avatar-01.jpg",
  },
  {
    NUM: "6",
    CategoryName: "Stationary",
    Date: "19 Jan 2022, 06:12 PM",
    AddedBy: "Admin",
    Status: "checkbox",
    Id: "rating_6",
    For: "rating_6",
    img: "category-06.jpg",
    img1: "avatar-01.jpg",
  },
  {
    NUM: "7",
    CategoryName: "Food",
    Date: "19 Dec 2022, 06:12 PM",
    AddedBy: "Admin",
    Status: "checkbox",
    Id: "rating_7",
    For: "rating_7",
    img: "category-02.jpg",
    img1: "avatar-01.jpg",
  },
  {
    NUM: "8",
    CategoryName: "Marketing",
    Date: "21 Dec 2022, 06:12 PM",
    AddedBy: "Admin",
    Status: "checkbox",
    Id: "rating_8",
    For: "rating_8",
    img: "category-03.jpg",
    img1: "avatar-01.jpg",
  },
];
export default {
  data() {
    return {
      title: "Countries",
      path: "",
      text: "Add Countries",
      data,
      columns,
    };
  },
};
</script>
