// kanakku-v1.9.9/angular-files/template/src/app/feature-module/customerdetailspage/customer-details-paid/customer-details-paid.component.ts
import { Component, OnInit } from '@angular/core';
import { Sort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { DataService, routes } from 'src/app/core/core.index';
import { apiResultFormat, pageSelection, recurringinvoice } from 'src/app/core/models/models';

@Component({
  selector: 'app-customer-details-paid',
  templateUrl: './customer-details-paid.component.html',
  styleUrls: ['./customer-details-paid.component.scss']
})
export class CustomerDetailsPaidComponent implements OnInit {
  public recurringinvoice: Array<recurringinvoice> = [];
  public routes = routes
  public Toggledata  = false;
  dataSource!: MatTableDataSource<recurringinvoice>;
  public searchDataValue = '';
  // pagination variables
  public lastIndex = 0;
  public pageSize = 10;
  public totalData = 0;
  public skip = 0;
  public limit: number = this.pageSize;
  public pageIndex = 0;
  public serialNumberArray: Array<number> = [];
  public currentPage = 1;
  public pageNumberArray: Array<number> = [];
  public pageSelection: Array<pageSelection> = [];
  public totalPages = 0;
  //** / pagination variables
  

  constructor(private data: DataService) {}

  ngOnInit(): void {
    this.getTableData();
  }
  private getTableData(): void {
    this.recurringinvoice = [];
    this.serialNumberArray = [];

    this.data.recurringinvoice().subscribe((data: apiResultFormat) => {
      this.totalData = data.totalData;
      data.data.map((res: recurringinvoice, index: number) => {
        const serialNumber = index + 1;
        if (index >= this.skip && serialNumber <= this.limit) {
          res.invoiceId = serialNumber;
          this.recurringinvoice.push(res);
          this.serialNumberArray.push(serialNumber);
        }
      });
      this.dataSource = new MatTableDataSource<recurringinvoice>(this.recurringinvoice);
      this.calculateTotalPages(this.totalData, this.pageSize);
    });
  }
 
  
  
  public sortData(sort: Sort) {
    const data = this.recurringinvoice.slice();

    if (!sort.active || sort.direction === '') {
      this.recurringinvoice = data;
    } else {
      this.recurringinvoice = data.sort((a, b) => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const aValue = (a as any)[sort.active];
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const bValue = (b as any)[sort.active];
        return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
      });
    }
  }
  public getMoreData(event: string): void {
    if (event == 'next') {
      this.currentPage++;
      this.pageIndex = this.currentPage - 1;
      this.limit += this.pageSize;
      this.skip = this.pageSize * this.pageIndex;
      this.getTableData();
    } else if (event == 'previous') {
      this.currentPage--;
      this.pageIndex = this.currentPage - 1;
      this.limit -= this.pageSize;
      this.skip = this.pageSize * this.pageIndex;
      this.getTableData();
    }
  }
  public moveToPage(pageNumber: number): void {
    this.currentPage = pageNumber;
    this.skip = this.pageSelection[pageNumber - 1].skip;
    this.limit = this.pageSelection[pageNumber - 1].limit;
    if (pageNumber > this.currentPage) {
      this.pageIndex = pageNumber - 1;
    } else if (pageNumber < this.currentPage) {
      this.pageIndex = pageNumber + 1;
    }
    this.getTableData();
  }
  public PageSize(): void {
    this.pageSelection = [];
    this.limit = this.pageSize;
    this.skip = 0;
    this.currentPage = 1;
    this.getTableData();
  }
  private calculateTotalPages(totalData: number, pageSize: number): void {
    this.pageNumberArray = [];
    this.totalPages = totalData / pageSize;
    if (this.totalPages % 1 != 0) {
      this.totalPages = Math.trunc(this.totalPages + 1);
    }
    for (let i = 1; i <= this.totalPages; i++) {
      const limit = pageSize * i;
      const skip = limit - pageSize;
      this.pageNumberArray.push(i);
      this.pageSelection.push({ skip: skip, limit: limit });
    }
  }
  open() {
    this.Toggledata = !this.Toggledata;
   
  }

}


<!-- Page Header -->
<div class="page-header">
    <div class="content-page-header">
        <h5>Customer Details Active</h5>
    </div>
</div>
<!-- /Page Header -->

<!-- Table -->
<div class="row">
<div class="col-sm-12">
<div class="card-table"> 
    <div class="card-body">
        <div class="table-responsive">
            
            <table 
            matSort
            (matSortChange)="sortData($event)"
            class="table table-stripped table-hover datatable">
                <thead class="thead-light">
                    <tr>
                        <th mat-sort-header="invoiceId">
                            <label class="custom_check">
                                <input type="checkbox" name="invoice">
                                <span class="checkmark"></span> 
                            </label>Invoice ID
                        </th>
                        <th mat-sort-header="category">Category</th>
                        <th mat-sort-header="createdOn">Created On</th>
                        <th mat-sort-header="invoicePerson">Invoice To</th>
                        <th mat-sort-header="tOtalAmount">Total Amount</th>												   
                        <th mat-sort-header="paidAmount">Paid Amount</th>
                        <th mat-sort-header="paymentMode">Payment Mode</th>
                        <th mat-sort-header="balanace">Balance</th>
                        <th mat-sort-header="dueDate">Due Date</th>
                        <th mat-sort-header="status">Status</th>
                        <th mat-sort-header="action" class="text-end">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr *ngFor="let data of recurringinvoice; let i = index">
                        <td>
                            <label class="custom_check">
                                <input type="checkbox" name="invoice">
                                <span class="checkmark"></span> 
                            </label>
                            <a [routerLink]="routes.viewInvoice" class="invoice-link">{{data.invoiceId}}</a>
                        </td>
                        <td>{{data.category}}</td>
                        <td>{{data.createdOn}}</td>
                        <td>
                            <h2 class="table-avatar">
                                <a [routerLink]="routes.profile" class="avatar avatar-sm me-2"><img class="avatar-img rounded-circle" [src]="data.img" alt="User Image"></a>
                                <a [routerLink]="routes.profile">{{data.invoicePerson}} <span>{{data.mailId}}</span></a>
                            </h2>
                        </td>
                        <td>{{data.totalAmount}}</td>
                        <td>{{data.paidAmount}}</td>													
                        <td>{{data.paymentmode}}</td>
                        <td>{{data.balance}}</td>
                        <td>{{data.dueDate}}</td>
                        <td><span class="badge bg-success-light">{{data.status}}</span></td>
                        <td>
                            <div class="dropdown dropdown-action">
                                <a href="#" class=" btn-action-icon " data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-ellipsis-v"></i></a>
                                <div class="dropdown-menu dropdown-menu-end">
                                    <ul>
                                        <li>
                                            <a class="dropdown-item" href="javascript:void(0);" data-bs-toggle="modal" data-bs-target="#delete_modal"><i class="far fa-trash-alt me-2"></i>Delete</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" [routerLink]="routes.customerdetailspaid"><i class="far fa-bell me-2"></i>Active</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" [routerLink]="routes.customerdetailscancel"><i class="far fa-bell-slash me-2"></i>In Active</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </td>
                    </tr>
                                                        
                </tbody>
            </table>
            <div class="table_header">
                <div class="row">
                  <div class="col-sm-12 col-md-6">
                    <div class="dataTables_length">
                      <label>
                        Show
                        <select
                          [(ngModel)]="pageSize"
                          (ngModelChange)="PageSize()"
                          class="form-control form-control-sm"
                        >
                          <option value="10">10</option>
                          <option value="25">25</option>
                          <option value="50">50</option>
                          <option value="100">100</option>
                        </select>
                        Entries
                      </label>
                    </div>
                  </div>
                </div>
                <div class="col-sm-12 col-md-3">
                  <div class="pagination_section">
                    <ul class="pagination">
                      <li
                        class="page-item "
                        [ngClass]="{
                          disabled: currentPage === 1
                        }"
                      >
                        <a
                          (click)="getMoreData('previous')"
                          class="page-link"
                          href="javascript:void(0);"
                          tabindex="-1"
                          ><i class="fa fa-angle-double-left me-2"></i>Previous</a
                        >
                      </li>
    
                      <ng-container
                        *ngFor="let item of pageNumberArray; let i = index"
                      >
                        <li
                          class="page-item"
                          [class.active]="item === currentPage"
                          [ngClass]="
                            (pageNumberArray[currentPage - 2] > item &&
                              item !== 1 &&
                              pageNumberArray.length > 6) ||
                            (pageNumberArray[currentPage] < item &&
                              item !== 1 &&
                              pageNumberArray.length > 6 &&
                              pageNumberArray.length !== item)
                              ? 'hide-sub-menu'
                              : 'show-sub-menu'
                          "
                        >
                          <a
                            (click)="moveToPage(item)"
                            class="page-link"
                            href="javascript:void(0);"
                          >
                            {{ item }}
                            <span *ngIf="item === currentPage" class="visually-hidden"
                              >(current)</span
                            >
                          </a>
                        </li>
                        <li
                          class="page-item"
                          *ngIf="
                            i === 0 && pageNumberArray.length > 6 && currentPage > 2
                          "
                          [hidden]="currentPage === 1"
                       
                        >
                          <a class="page-link"    (click)="moveToPage(currentPage - 2)" href="javascript:void(0);"> ... </a>
                        </li>
                        <li
                          *ngIf="
                            i === pageNumberArray.length - 2 &&
                            pageNumberArray.length > 6
                          "
                          [hidden]="
                            currentPage >=
                              pageNumberArray[pageNumberArray.length - 2] ||
                            totalData <
                              serialNumberArray[serialNumberArray.length - 1]
                          "
                          class="page-item"
                         
                        >
                          <a class="page-link"  (click)="moveToPage(currentPage + 2)" href="javascript:void(0);"> ... </a>
                        </li>
                      </ng-container>
    
                      <li
                        class="page-item"
                        [ngClass]="{
                          disabled:
                            currentPage ===
                              pageNumberArray[pageNumberArray.length - 1] ||
                              recurringinvoice.length === 0
                        }"
                      >
                        <a
                          (click)="getMoreData('next')"
                          class="page-link"
                          href="javascript:void(0);"
                          >Next<i class="fa fa-angle-double-right ms-2"></i>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            
        </div>
    </div>
</div>
</div>
</div>
<!-- /Table -->

<!-- Delete Items Modal -->
<div class="modal custom-modal fade" id="delete_modal" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-md">
        <div class="modal-content">
            <div class="modal-body">
                <div class="form-header">
                    <h3>Delete Customer Details</h3>
                    <p>Are you sure want to delete?</p>
                </div>
                <div class="modal-btn delete-action">
                    <div class="row">
                        <div class="col-6">
                            <a href="#" data-bs-dismiss="modal" class="btn btn-primary paid-continue-btn">Delete</a>
                        </div>
                        <div class="col-6">
                            <a href="#" data-bs-dismiss="modal" class="btn btn-primary paid-cancel-btn">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Delete Items Modal -->

// kanakku-v1.9.9/vuejs-files/template/src/views/pages/customers/customer-details-paid.vue
<template>
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>

    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <componentheader :title="title" />

        <!-- Table -->
        <div class="row">
          <div class="col-sm-12">
            <div class="card-table">
              <div class="card-body">
                <div class="table-responsive">
                  <a-table
                    class="stripped table-hover"
                    :columns="columns"
                    :data-source="data"
                    @change="onChange"
                  >
                    <template #bodyCell="{ column, record }">
                      <template v-if="column.key === 'InvoiceID'">
                        <label class="custom_check">
                          <input type="checkbox" name="invoice" />
                          <span class="checkmark"></span>
                        </label>
                        <router-link to="/invoice-details" class="invoice-link">{{
                          record.InvoiceID
                        }}</router-link>
                      </template>
                      <template v-else-if="column.key === 'InvoiceTo'">
                        <h2 class="table-avatar">
                          <router-link to="/profile" class="avatar avatar-sm me-2"
                            ><img
                              class="avatar-img rounded-circle"
                              :src="require(`@/assets/img/profiles/${record.Image}`)"
                              alt="User Image"
                          /></router-link>
                          <router-link to="profile"
                            >{{ record.Name
                            }}<span>{{ record.Number }}</span></router-link
                          >
                        </h2>
                      </template>
                      <template v-else-if="column.key === 'Status'">
                        <span class="badge bg-success-light">{{ record.Status }}</span>
                      </template>
                      <template v-else-if="column.key === 'Action'">
                        <div class="dropdown dropdown-action">
                          <a
                            href="javascript:;"
                            class="btn-action-icon"
                            data-bs-toggle="dropdown"
                            aria-expanded="false"
                            ><i class="fas fa-ellipsis-v"></i
                          ></a>
                          <div class="dropdown-menu dropdown-menu-end">
                            <ul>
                              <li>
                                <a
                                  class="dropdown-item"
                                  href="javascript:void(0);"
                                  data-bs-toggle="modal"
                                  data-bs-target="#delete_modal"
                                  ><i class="far fa-trash-alt me-2"></i>Delete</a
                                >
                              </li>
                              <li>
                                <router-link class="dropdown-item" to="/active-customers"
                                  ><i class="far fa-bell me-2"></i>Active</router-link
                                >
                              </li>
                              <li>
                                <router-link
                                  class="dropdown-item"
                                  to="/deactive-customers"
                                  ><i class="far fa-bell-slash me-2"></i>In
                                  Active</router-link
                                >
                              </li>
                            </ul>
                          </div>
                        </div>
                      </template>
                    </template>
                  </a-table>
                </div>
              </div>
            </div>
          </div>
          <!-- /Table -->

          <!-- Delete Items Modal -->
          <div class="modal custom-modal fade" id="delete_modal" role="dialog">
            <div class="modal-dialog modal-dialog-centered modal-md">
              <div class="modal-content">
                <div class="modal-body">
                  <div class="form-header">
                    <h3>Delete Customer Details</h3>
                    <p>Are you sure want to delete?</p>
                  </div>
                  <div class="modal-btn delete-action">
                    <div class="row">
                      <div class="col-6">
                        <a
                          href="javascript:;"
                          data-bs-dismiss="modal"
                          class="btn btn-primary paid-continue-btn"
                          >Delete</a
                        >
                      </div>
                      <div class="col-6">
                        <a
                          href="javascript:;"
                          data-bs-dismiss="modal"
                          class="btn btn-primary paid-cancel-btn"
                          >Cancel</a
                        >
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- /Delete Items Modal -->
        </div>
      </div>
      <!-- /Page Wrapper -->
    </div>
  </div>
</template>

<script>
const columns = [
  {
    title: "Invoice ID",
    dataIndex: "InvoiceID",
    key: "InvoiceID",
    sorter: {
      compare: (a, b) => {
        a = a.InvoiceID.toLowerCase();
        b = b.InvoiceID.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Category",
    dataIndex: "Category",
    sorter: {
      compare: (a, b) => {
        a = a.Category.toLowerCase();
        b = b.Category.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Created On",
    dataIndex: "CreatedOn",
    sorter: {
      compare: (a, b) => {
        a = a.CreatedOn.toLowerCase();
        b = b.CreatedOn.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Invoice To",
    dataIndex: "InvoiceTo",
    key: "InvoiceTo",
    sorter: {
      compare: (a, b) => {
        a = a.InvoiceTo.toLowerCase();
        b = b.InvoiceTo.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "TotalAmount",
    dataIndex: "TotalAmount",
    sorter: {
      compare: (a, b) => {
        a = a.TotalAmount.toLowerCase();
        b = b.TotalAmount.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Paid Amount",
    dataIndex: "PaidAmount",
    sorter: {
      compare: (a, b) => {
        a = a.PaidAmount.toLowerCase();
        b = b.PaidAmount.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Payment Mode",
    dataIndex: "PaymentMode",
    sorter: {
      compare: (a, b) => {
        a = a.PaymentMode.toLowerCase();
        b = b.PaymentMode.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Balance",
    dataIndex: "Balance",
    sorter: {
      compare: (a, b) => {
        a = a.Balance.toLowerCase();
        b = b.Balance.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "DueDate",
    dataIndex: "DueDate",
    sorter: {
      compare: (a, b) => {
        a = a.DueDate.toLowerCase();
        b = b.DueDate.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Status",
    dataIndex: "Status",
    key: "Status",
    sorter: {
      compare: (a, b) => {
        a = a.Status.toLowerCase();
        b = b.Status.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Action",
    key: "Action",
    sorter: true,
  },
];
const data = [
  {
    InvoiceID: "#4987",
    Category: "Food",
    CreatedOn: "23 Mar 2023",
    Image: "avatar-02.jpg",
    InvoiceTo: "JohnSmith",
    Number: "+1 843-443-3282",
    TotalAmount: "$1,54,220",
    PaidAmount: "$1,50,000",
    PaymentMode: "Cash",
    Balance: "$2,54,00",
    DueDate: "25 Mar 2023",
    Status: "Paid",
  },
  {
    InvoiceID: "#4988",
    Category: "Advertising",
    CreatedOn: "16 Mar 2022",
    Image: "avatar-01.jpg",
    InvoiceTo: "Johnny",
    Number: "+1 917-409-0861",
    TotalAmount: "$3,54,220",
    PaidAmount: "$2,50,000",
    PaymentMode: "Cheque",
    Balance: "$4,220",
    DueDate: "16 Jan 2023",
    Status: "Paid",
  },
  {
    InvoiceID: "#4989",
    Category: "Marketing",
    CreatedOn: "25 Feb 2023",
    Image: "avatar-08.jpg",
    InvoiceTo: "Robert",
    Number: "+1 956-623-2880",
    TotalAmount: "$1,54,220",
    PaidAmount: "$1,50,000",
    PaymentMode: "Cash",
    Balance: "$4,220",
    DueDate: "16 Jan 2023",
    Status: "Paid",
  },
  {
    InvoiceID: "#4990",
    Category: "Repairs",
    CreatedOn: "25 Mar 2022",
    Image: "avatar-04.jpg",
    InvoiceTo: "Sharonda",
    Number: "+1 707-439-1732",
    TotalAmount: "$1,54,220",
    PaidAmount: "$1,50,000",
    PaymentMode: "Cash",
    Balance: "$4,220",
    DueDate: "12 May 2023",
    Status: "Paid",
  },
  {
    InvoiceID: "#4991",
    Category: "Software",
    CreatedOn: "12 May 2022",
    Image: "avatar-06.jpg",
    InvoiceTo: "Pricilla",
    Number: "+1 559-741-9672",
    TotalAmount: "$5,54,220",
    PaidAmount: "$3,50,000",
    PaymentMode: "Cheque",
    Balance: "$4,220",
    DueDate: "18 May 2023",
    Status: "Paid",
  },
  {
    InvoiceID: "#4992",
    Category: "Stationary",
    CreatedOn: "16 Nov 2022",
    Image: "avatar-09.jpg",
    InvoiceTo: "Randall",
    Number: "+1 989-438-3131",
    TotalAmount: "$5,54,220",
    PaidAmount: "$6,50,000",
    PaymentMode: "Cash",
    Balance: "$4,220",
    DueDate: "25 Feb 2023",
    Status: "Paid",
  },
];
export default {
  data() {
    return {
      title: "Customer Details Active",
      columns,
      data,
    };
  },
};
</script>
