// kanakku-v1.9.9/vuejs-files/template/src/views/pages/membership/subscribers.vue
<template>
  <!-- Main Wrapper -->
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>
    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <supportheader :title="title" />

        <!-- Table -->
        <div class="row">
          <div class="col-sm-12">
            <div class="card-table">
              <div class="card-body">
                <div class="table-responsive">
                  <a-table
                    class="stripped table-hover"
                    :columns="columns"
                    :data-source="data"
                    @change="onChange"
                  >
                    <template #bodyCell="{ column, record }">
                      <template v-if="column.key === 'id'">
                        <h2 class="table-avatar">
                          <router-link to="profile" class="avatar avatar-sm me-2"
                            ><img
                              class="avatar-img rounded-circle"
                              :src="require(`@/assets/img/profiles/${record.img}`)"
                              alt="User Image"
                          /></router-link>
                          <router-link to="profile"
                            >{{ record.ProviderName }}
                            <span>{{ record.mail }}</span></router-link
                          >
                        </h2>
                      </template>
                    </template>
                  </a-table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /Table -->
      </div>
    </div>
    <!-- /Page Wrapper -->
  </div>
  <!-- /Main Wrapper -->
</template>
<script>
const columns = [
  {
    title: "#",
    dataIndex: "NUM",
    sorter: {
      compare: (a, b) => {
        a = a.NUM.toLowerCase();
        b = b.NUM.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Provider Name",
    dataIndex: "ProviderName",
    key: "id",
    sorter: {
      compare: (a, b) => {
        a = a.ProviderName.toLowerCase();
        b = b.ProviderName.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Subscription",
    dataIndex: "Subscription",
    sorter: (a, b) => a.Subscription.localeCompare(b.Subscription),
  },
  {
    title: "Amount",
    dataIndex: "Amount",
    sorter: (a, b) => a.Amount.localeCompare(b.Amount),
  },
  {
    title: "Subscription Durations",
    dataIndex: "SubscriptionDurations",
    sorter: {
      compare: (a, b) => {
        a = a.SubscriptionDurations.toLowerCase();
        b = b.SubscriptionDurations.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Start Date",
    dataIndex: "StartDate",
    sorter: {
      compare: (a, b) => {
        a = a.StartDate.toLowerCase();
        b = b.StartDate.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "End Date",
    dataIndex: "EndDate",
    sorter: {
      compare: (a, b) => {
        a = a.EndDate.toLowerCase();
        b = b.EndDate.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
];
const data = [
  {
    NUM: "1",
    img: "avatar-02.jpg",
    ProviderName: "John Smith",
    mail: "john@example.com",
    Subscription: "Enterprise",
    Amount: "$650",
    SubscriptionDurations: "One Year",
    StartDate: "19 Dec 2022, 06:12 PM",
    EndDate: "19 Dec 2023, 06:12 PM",
  },
  {
    NUM: "2",
    img: "avatar-03.jpg",
    ProviderName: "Johnny",
    mail: "johnny@example.com",
    Subscription: "Standard",
    Amount: "$350",
    SubscriptionDurations: "6 Month",
    StartDate: "15 Dec 2022, 04:35 PM",
    EndDate: "15 April 2023, 04:35 PM",
  },
  {
    NUM: "3",
    img: "avatar-04.jpg",
    ProviderName: "Robert",
    mail: "robert@example.com",
    Subscription: "Basic",
    Amount: "$850",
    SubscriptionDurations: "1 Month",
    StartDate: "04 Dec 2022, 04:35 PM",
    EndDate: "05 April 2023, 04:35 PM",
  },
  {
    NUM: "4",
    img: "avatar-05.jpg",
    ProviderName: "Sharonda",
    mail: "sharon@example.com",
    Subscription: "Enterprise",
    Amount: "$950",
    SubscriptionDurations: "One Year",
    StartDate: "12 Dec 2022, 04:35 PM",
    EndDate: "13 April 2023, 04:35 PM",
  },
  {
    NUM: "5",
    img: "avatar-07.jpg",
    ProviderName: "Randall",
    mail: "randall@example.com",
    Subscription: "Standard",
    Amount: "$350",
    SubscriptionDurations: "1 Month",
    StartDate: "28 Nov 2022, 03:25 PM",
    EndDate: "28 Nov 2023, 03:25 PM",
  },
  {
    NUM: "6",
    img: "avatar-06.jpg",
    ProviderName: "Pricilla",
    mail: "pricilla@example.com",
    Subscription: "Basic",
    Amount: "$150",
    SubscriptionDurations: "3 Month",
    StartDate: "15 Nov 2022, 03:25 PM",
    EndDate: "18 Nov 2023, 03:25 PM",
  },
];
export default {
  data() {
    return {
      title: "Subscribers",
      data,
      columns,
    };
  },
};
</script>

// kanakku-v1.9.9/reactjs-files/template/src/membership/subscribers.jsx
import React, { useState } from "react";
import { Link } from "react-router-dom";
import Header from "../layouts/Header";
import Sidebar from "../layouts/Sidebar";
import { Pagination, Table } from "antd";
import Data from "../assets/jsons/subscription";
import FeatherIcon from "feather-icons-react";
import {
  onShowSizeChange,
  itemRender,
} from "../_components/paginationfunction";
import AddVendor from "../vendors/addVendor";

const Subscribers = () => {
  const [menu, setMenu] = useState(false);
  const [show, setShow] = useState(false);

  const toggleMobileMenu = () => {
    setMenu(!menu);
  };

  const datasource = Data?.Data;
  console.log(datasource);

  const columns = [
    {
      title: "#",
      dataIndex: "Id",
      sorter: (a, b) => a.id.length - b.id.length,
    },
    {
      title: "Provider Name",
      dataIndex: "Name",
      render: (text, record) => (
        <>
          <h2 className="table-avatar">
            <Link to="/profile" className="avatar avatar-sm me-2">
              <img
                className="avatar-img rounded-circle"
                src={record.img}
                alt="User Image"
              />
            </Link>
            <Link to="/profile">
              {record.Name} <span>{record.email}</span>
            </Link>
          </h2>
        </>
      ),
      sorter: (a, b) => a.Name.length - b.Name.length,
    },
    {
        title: "Subscription",
        dataIndex: "Subscription",
        sorter: (a, b) => a.Subscription.length - b.Subscription.length,
    },
    {
      title: "Amount",
      dataIndex: "Amount",
      sorter: (a, b) => a.Amount.length - b.Amount.length,
    },
    {
      title: "Subscription Duration",
      dataIndex: "Durations",
      sorter: (a, b) => a.Durations.length - b.Durations.length,
    },
    {
      title: "Start Date",
      dataIndex: "StartDate",
      sorter: (a, b) => a.StartDate.length - b.StartDate.length,
    },
    {
      title: "End Date",
      dataIndex: "EndDate",
      sorter: (a, b) => a.EndDate.length - b.EndDate.length,
    },
  ];

  return (
    <>
      <div className={`main-wrapper ${menu ? "slide-nav" : ""}`}>
        <Header onMenuClick={(value) => toggleMobileMenu()} />
        <Sidebar />

        <div className="page-wrapper">
          <div className="content container-fluid">
            {/* Page Header */}
            <div className="page-header">
              <div className="content-page-header">
                <h5>Subscribers</h5>
                <div className="list-btn">
                  <ul className="filter-list">
                    <li>
                      <Link className="btn btn-filters w-auto popup-toggle"
                        onClick={() => setShow(!show)}
                      >
                        <span className="me-2">
                          {/* <i className="fe fe-filter" /> */}
                          <FeatherIcon icon="filter"/>
                        </span>
                        Filter{" "}
                      </Link>
                    </li>
                    <li>
                      <Link className="btn-filters" to="#">
                        <span>
                          {/* <i className="fe fe-grid" /> */}
                          <FeatherIcon icon="grid"/>
                        </span>{" "}
                      </Link>
                    </li>
                    <li>
                      <Link
                        className="active btn-filters"
                        to="#"
                      >
                        <span>
                          {/* <i className="fe fe-list" /> */}
                          <FeatherIcon icon="list"/>
                        </span>{" "}
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            {/* /Page Header */}
            {/* Table */}
            <div className="row">
              <div className="col-sm-12">
                <div className="card-table">
                  <div className="card-body subscribers">
                    <div className="table-responsive table-hover">
                    <Table
                        pagination={{
                          total: datasource.length,
                          showTotal: (total, range) =>
                            `Showing ${range[0]} to ${range[1]} of ${total} entries`,
                          showSizeChanger: true,
                          onShowSizeChange: onShowSizeChange,
                          itemRender: itemRender,
                        }}
                        columns={columns}
                        dataSource={datasource}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* /Table */}
          </div>
        </div>

        <AddVendor 
          setShow={setShow}
          show={show}
        />

      </div>
    </>
  );
};

export default Subscribers;
