// kanakku-v1.9.9/vuejs-files/template-rtl/src/views/pages/customers/customer-details.vue
<template>
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>

    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <componentheader :title="title" />

        <div class="card customer-details-group">
          <div class="card-body">
            <div class="row align-items-center">
              <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                <div class="customer-details">
                  <div class="d-flex align-items-center">
                    <span class="customer-widget-img d-inline-flex">
                      <img
                        class="rounded-circle"
                        src="@/assets/img/profiles/avatar-05.jpg"
                        alt=""
                      />
                    </span>
                    <div class="customer-details-cont">
                      <h6>John Smith</h6>
                      <p>Cl-12345</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                <div class="customer-details">
                  <div class="d-flex align-items-center">
                    <span class="customer-widget-icon d-inline-flex">
                      <i class="feather feather-mail"></i>
                    </span>
                    <div class="customer-details-cont">
                      <h6>Email Address</h6>
                      <p>john@example.com</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                <div class="customer-details">
                  <div class="d-flex align-items-center">
                    <span class="customer-widget-icon d-inline-flex">
                      <i class="feather feather-phone"></i>
                    </span>
                    <div class="customer-details-cont">
                      <h6>Phone Number</h6>
                      <p>585-785-4840</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                <div class="customer-details">
                  <div class="d-flex align-items-center">
                    <span class="customer-widget-icon d-inline-flex">
                      <i class="feather feather-airplay"></i>
                    </span>
                    <div class="customer-details-cont">
                      <h6>Company Name</h6>
                      <p>Kanakku Corporation</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                <div class="customer-details">
                  <div class="d-flex align-items-center">
                    <span class="customer-widget-icon d-inline-flex">
                      <i class="feather feather-globe"></i>
                    </span>
                    <div class="customer-details-cont">
                      <h6>Website</h6>
                      <p class="customer-mail">www.example.com</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                <div class="customer-details">
                  <div class="d-flex align-items-center">
                    <span class="customer-widget-icon d-inline-flex">
                      <i class="feather feather-briefcase"></i>
                    </span>
                    <div class="customer-details-cont">
                      <h6>Company Address</h6>
                      <p>4712 Cherry Ridge Drive Rochester, NY 14620.</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Search Filter -->
        <div id="filter_inputs" class="card filter-card">
          <div class="card-body pb-0">
            <div class="row">
              <div class="col-sm-6 col-md-3">
                <div class="form-group">
                  <label>Name</label>
                  <input type="text" class="form-control" />
                </div>
              </div>
              <div class="col-sm-6 col-md-3">
                <div class="form-group">
                  <label>Email</label>
                  <input type="text" class="form-control" />
                </div>
              </div>
              <div class="col-sm-6 col-md-3">
                <div class="form-group">
                  <label>Phone</label>
                  <input type="text" class="form-control" />
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /Search Filter -->

        <!-- Inovices card -->
        <div class="row">
          <div class="col-xl-2 col-lg-4 col-sm-6 col-12 d-flex">
            <div class="card inovices-card w-100">
              <div class="card-body">
                <div class="dash-widget-header">
                  <span class="inovices-widget-icon bg-info-light">
                    <img src="@/assets/img/icons/receipt-item.svg" alt="" />
                  </span>
                  <div class="dash-count">
                    <div class="dash-title">Total Invoice</div>
                    <div class="dash-counts">
                      <p>$298</p>
                    </div>
                  </div>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                  <p class="inovices-all">
                    No of Invoice <span class="rounded-circle bg-light-gray">02</span>
                  </p>
                  <p class="inovice-trending text-success-light">
                    02
                    <span class="ms-2"><i class="feather feather-trending-up"></i></span>
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xl-2 col-lg-4 col-sm-6 col-12 d-flex">
            <div class="card inovices-card w-100">
              <div class="card-body">
                <div class="dash-widget-header">
                  <span class="inovices-widget-icon bg-primary-light">
                    <img src="@/assets/img/icons/transaction-minus.svg" alt="" />
                  </span>
                  <div class="dash-count">
                    <div class="dash-title">Total Outstanding</div>
                    <div class="dash-counts">
                      <p>$325,215</p>
                    </div>
                  </div>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                  <p class="inovices-all">
                    No of Invoice <span class="rounded-circle bg-light-gray">03</span>
                  </p>
                  <p class="inovice-trending text-success-light">
                    04
                    <span class="ms-2"><i class="feather feather-trending-up"></i></span>
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xl-2 col-lg-4 col-sm-6 col-12 d-flex">
            <div class="card inovices-card w-100">
              <div class="card-body">
                <div class="dash-widget-header">
                  <span class="inovices-widget-icon bg-warning-light">
                    <img src="@/assets/img/icons/archive-book.svg" alt="" />
                  </span>
                  <div class="dash-count">
                    <div class="dash-title">Total Overdue</div>
                    <div class="dash-counts">
                      <p>$7825</p>
                    </div>
                  </div>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                  <p class="inovices-all">
                    No of Invoice <span class="rounded-circle bg-light-gray">01</span>
                  </p>
                  <p class="inovice-trending text-danger-light">
                    03
                    <span class="ms-2"
                      ><i class="feather feather-trending-down"></i
                    ></span>
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xl-2 col-lg-4 col-sm-6 col-12 d-flex">
            <div class="card inovices-card w-100">
              <div class="card-body">
                <div class="dash-widget-header">
                  <span class="inovices-widget-icon bg-primary-light">
                    <img src="@/assets/img/icons/clipboard-close.svg" alt="" />
                  </span>
                  <div class="dash-count">
                    <div class="dash-title">Cancelled</div>
                    <div class="dash-counts">
                      <p>100</p>
                    </div>
                  </div>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                  <p class="inovices-all">
                    No of Invoice <span class="rounded-circle bg-light-gray">04</span>
                  </p>
                  <p class="inovice-trending text-danger-light">
                    05
                    <span class="ms-2"
                      ><i class="feather feather-trending-down"></i
                    ></span>
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xl-2 col-lg-4 col-sm-6 col-12 d-flex">
            <div class="card inovices-card w-100">
              <div class="card-body">
                <div class="dash-widget-header">
                  <span class="inovices-widget-icon bg-green-light">
                    <img src="@/assets/img/icons/message-edit.svg" alt="" />
                  </span>
                  <div class="dash-count">
                    <div class="dash-title">Draft</div>
                    <div class="dash-counts">
                      <p>$125,586</p>
                    </div>
                  </div>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                  <p class="inovices-all">
                    No of Invoice <span class="rounded-circle bg-light-gray">06</span>
                  </p>
                  <p class="inovice-trending text-danger-light">
                    02
                    <span class="ms-2"
                      ><i class="feather feather-trending-down"></i
                    ></span>
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xl-2 col-lg-4 col-sm-6 col-12 d-flex">
            <div class="card inovices-card w-100">
              <div class="card-body">
                <div class="dash-widget-header">
                  <span class="inovices-widget-icon bg-danger-light">
                    <img src="@/assets/img/icons/3d-rotate.svg" alt="" />
                  </span>
                  <div class="dash-count">
                    <div class="dash-title">Recurring</div>
                    <div class="dash-counts">
                      <p>$86,892</p>
                    </div>
                  </div>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                  <p class="inovices-all">
                    No of Invoice <span class="rounded-circle bg-light-gray">03</span>
                  </p>
                  <p class="inovice-trending text-success-light">
                    02
                    <span class="ms-2"><i class="feather feather-trending-up"></i></span>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /Inovices card -->

        <!-- Table -->
        <div class="row">
          <div class="col-sm-12">
            <div class="card-table">
              <div class="card-body">
                <div class="table-responsive">
                  <a-table
                    class="stripped table-hover"
                    :columns="columns"
                    :data-source="data"
                    @change="onChange"
                  >
                    <template #bodyCell="{ column, record }">
                      <template v-if="column.key === 'InvoiceID'">
                        <label class="custom_check">
                          <input type="checkbox" name="invoice" />
                          <span class="checkmark"></span>
                        </label>
                        <router-link to="/invoice-details" class="invoice-link">{{
                          record.InvoiceID
                        }}</router-link>
                      </template>
                      <template v-else-if="column.key === 'Status'">
                        <div>
                          <span :class="record.Class">{{ record.Status }}</span>
                        </div>
                      </template>
                      <template v-else-if="column.key === 'Action'">
                        <div class="dropdown dropdown-action">
                          <a
                            href="javascript:;"
                            class="btn-action-icon"
                            data-bs-toggle="dropdown"
                            aria-expanded="false"
                            ><i class="fas fa-ellipsis-v"></i
                          ></a>
                          <div class="dropdown-menu dropdown-menu-end">
                            <ul>
                              <li>
                                <a
                                  class="dropdown-item"
                                  href="javascript:void(0);"
                                  data-bs-toggle="modal"
                                  data-bs-target="#delete_modal"
                                  ><i class="far fa-trash-alt me-2"></i>Delete</a
                                >
                              </li>
                              <li>
                                <router-link
                                  class="dropdown-item"
                                  to="/customer-details-paid"
                                  ><i class="far fa-bell me-2"></i>Active</router-link
                                >
                              </li>
                              <li>
                                <router-link
                                  class="dropdown-item"
                                  to="/customer-details-cancel"
                                  ><i class="far fa-bell-slash me-2"></i>In
                                  Active</router-link
                                >
                              </li>
                            </ul>
                          </div>
                        </div>
                      </template>
                    </template>
                  </a-table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /Table -->
        <locationmodal :title1="title1" />
      </div>
    </div>
    <!-- /Page Wrapper -->
  </div>
</template>

<script>
const columns = [
  {
    title: "Invoice ID",
    dataIndex: "InvoiceID",
    key: "InvoiceID",
    sorter: {
      compare: (a, b) => {
        a = a.InvoiceID.toLowerCase();
        b = b.InvoiceID.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Category",
    dataIndex: "Category",
    sorter: {
      compare: (a, b) => {
        a = a.Category.toLowerCase();
        b = b.Category.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Created On",
    dataIndex: "CreatedOn",
    sorter: {
      compare: (a, b) => {
        a = a.CreatedOn.toLowerCase();
        b = b.CreatedOn.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Total Amount",
    dataIndex: "TotalAmount",
    sorter: {
      compare: (a, b) => {
        a = a.TotalAmount.toLowerCase();
        b = b.TotalAmount.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Paid Amount",
    dataIndex: "PaidAmount",
    sorter: {
      compare: (a, b) => {
        a = a.PaidAmount.toLowerCase();
        b = b.PaidAmount.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Payment Mode",
    dataIndex: "PaymentMode",
    sorter: {
      compare: (a, b) => {
        a = a.PaymentMode.toLowerCase();
        b = b.PaymentMode.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Balance",
    dataIndex: "Balance",
    sorter: {
      compare: (a, b) => {
        a = a.Balance.toLowerCase();
        b = b.Balance.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Due Date",
    dataIndex: "DueDate",
    sorter: {
      compare: (a, b) => {
        a = a.DueDate.toLowerCase();
        b = b.DueDate.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Status",
    dataIndex: "Status",
    key: "Status",
    sorter: {
      compare: (a, b) => {
        a = a.Status.toLowerCase();
        b = b.Status.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Action",
    key: "Action",
    sorter: true,
  },
];

const data = [
  {
    InvoiceID: "#4987",
    Category: "Food",
    CreatedOn: "23 Mar 2023",
    TotalAmount: "$1,54,220",
    PaidAmount: "$1,50,000",
    PaymentMode: "Cash",
    Balance: "$2,54,00",
    DueDate: "25 Mar 2023",
    Class: "badge bg-success-light",
    Status: "Paid",
  },
  {
    InvoiceID: "#4988",
    Category: "Advertising",
    CreatedOn: "16 Mar 2022",
    TotalAmount: "$3,54,220",
    PaidAmount: "$2,50,000",
    PaymentMode: "Cheque",
    Balance: "$4,220",
    DueDate: "16 Jan 2023",
    Class: "badge bg-success-light",
    Status: "Paid",
  },
  {
    InvoiceID: "#4989",
    Category: "Marketing",
    CreatedOn: "25 Feb 2023",
    TotalAmount: "$1,54,220",
    PaidAmount: "$1,50,000",
    PaymentMode: "Cash",
    Balance: "$4,220",
    DueDate: "16 Jan 2023",
    Class: "badge bg-success-light",
    Status: "Paid",
  },
  {
    InvoiceID: "#4990",
    Category: "Repairs",
    CreatedOn: "25 Mar 2022",
    TotalAmount: "$1,54,220",
    PaidAmount: "$1,50,000",
    PaymentMode: "Cash",
    Balance: "$4,220",
    DueDate: "12 May 2023",
    Class: "badge bg-success-light",
    Status: "Paid",
  },
  {
    InvoiceID: "#4991",
    Category: "Software",
    CreatedOn: "12 May 2022",
    TotalAmount: "$5,54,220",
    PaidAmount: "$3,50,000",
    PaymentMode: "Cheque",
    Balance: "$4,220",
    DueDate: "18 May 2023",
    Class: "badge bg-success-light",
    Status: "Paid",
  },
  {
    InvoiceID: "#4992",
    Category: "Stationary",
    CreatedOn: "16 Nov 2022",
    TotalAmount: "$5,54,220",
    PaidAmount: "$6,50,000",
    PaymentMode: "Cash",
    Balance: "$4,220",
    DueDate: "25 Feb 2023",
    Class: "badge bg-success-light",
    Status: "Paid",
  },
];
export default {
  data() {
    return {
      title: "Customer Details",
      title1: "Delete Customer Details",
      columns,
      data,
    };
  },
};
</script>

// kanakku-v1.9.9/angular-files/template/src/app/feature-module/customerdetailspage/customer-details/customer-details.component.ts
import { Component,OnInit } from '@angular/core';
import { Sort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { DataService, routes } from 'src/app/core/core.index';
import { apiResultFormat, pageSelection, recurringinvoice } from 'src/app/core/models/models';

@Component({
  selector: 'app-customer-details',
  templateUrl: './customer-details.component.html',
  styleUrls: ['./customer-details.component.scss']
})
export class CustomerDetailsComponent implements OnInit {
  public recurringinvoice: Array<recurringinvoice> = [];
  public routes = routes
  public Toggledata  = false;
  dataSource!: MatTableDataSource<recurringinvoice>;
  public searchDataValue = '';
  // pagination variables
  public lastIndex = 0;
  public pageSize = 10;
  public totalData = 0;
  public skip = 0;
  public limit: number = this.pageSize;
  public pageIndex = 0;
  public serialNumberArray: Array<number> = [];
  public currentPage = 1;
  public pageNumberArray: Array<number> = [];
  public pageSelection: Array<pageSelection> = [];
  public totalPages = 0;
  //** / pagination variables
  

  constructor(private data: DataService) {}

  ngOnInit(): void {
    this.getTableData();
  }
  private getTableData(): void {
    this.recurringinvoice = [];
    this.serialNumberArray = [];

    this.data.recurringinvoice().subscribe((data: apiResultFormat) => {
      this.totalData = data.totalData;
      data.data.map((res: recurringinvoice, index: number) => {
        const serialNumber = index + 1;
        if (index >= this.skip && serialNumber <= this.limit) {
          res.recurringinvoice = serialNumber;
          this.recurringinvoice.push(res);
          this.serialNumberArray.push(serialNumber);
        }
      });
      this.dataSource = new MatTableDataSource<recurringinvoice>(this.recurringinvoice);
      this.calculateTotalPages(this.totalData, this.pageSize);
    });
  }
 
  
  
  public sortData(sort: Sort) {
    const data = this.recurringinvoice.slice();

    if (!sort.active || sort.direction === '') {
      this.recurringinvoice = data;
    } else {
      this.recurringinvoice = data.sort((a, b) => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const aValue = (a as any)[sort.active];
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const bValue = (b as any)[sort.active];
        return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
      });
    }
  }
  public getMoreData(event: string): void {
    if (event == 'next') {
      this.currentPage++;
      this.pageIndex = this.currentPage - 1;
      this.limit += this.pageSize;
      this.skip = this.pageSize * this.pageIndex;
      this.getTableData();
    } else if (event == 'previous') {
      this.currentPage--;
      this.pageIndex = this.currentPage - 1;
      this.limit -= this.pageSize;
      this.skip = this.pageSize * this.pageIndex;
      this.getTableData();
    }
  }
  public moveToPage(pageNumber: number): void {
    this.currentPage = pageNumber;
    this.skip = this.pageSelection[pageNumber - 1].skip;
    this.limit = this.pageSelection[pageNumber - 1].limit;
    if (pageNumber > this.currentPage) {
      this.pageIndex = pageNumber - 1;
    } else if (pageNumber < this.currentPage) {
      this.pageIndex = pageNumber + 1;
    }
    this.getTableData();
  }
  public PageSize(): void {
    this.pageSelection = [];
    this.limit = this.pageSize;
    this.skip = 0;
    this.currentPage = 1;
    this.getTableData();
  }
  private calculateTotalPages(totalData: number, pageSize: number): void {
    this.pageNumberArray = [];
    this.totalPages = totalData / pageSize;
    if (this.totalPages % 1 != 0) {
      this.totalPages = Math.trunc(this.totalPages + 1);
    }
    for (let i = 1; i <= this.totalPages; i++) {
      const limit = pageSize * i;
      const skip = limit - pageSize;
      this.pageNumberArray.push(i);
      this.pageSelection.push({ skip: skip, limit: limit });
    }
  }
  open() {
    this.Toggledata = !this.Toggledata;
   
  }
  

}

<!-- Page Header -->
<div class="page-header">
    <div class="content-page-header">
        <h5>Customer Details</h5>
    </div>
</div>
<!-- /Page Header -->
<div class="card customer-details-group">
    <div class="card-body">
        <div class="row align-items-center">					
            <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                <div class="customer-details">
                    <div class="d-flex align-items-center">
                        <span class="customer-widget-img d-inline-flex">
                            <img class="rounded-circle" src="assets/img/profiles/avatar-14.jpg"alt="image">
                        </span>
                        <div class="customer-details-cont">
                            <h6>John Smith</h6>
                            <p>Cl-12345</p>
                        </div>
                    </div>
                </div> 
            </div>
            <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                <div class="customer-details">
                    <div class="d-flex align-items-center">
                        <span class="customer-widget-icon ">
                            <i class="feather icon-mail"></i>
                        </span>
                        <div class="customer-details-cont">
                            <h6>Email Address</h6>
                            <p>john@example.com</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                <div class="customer-details">
                    <div class="d-flex align-items-center">
                        <span class="customer-widget-icon ">
                            <i class="feather icon-phone"></i>
                        </span>
                        <div class="customer-details-cont">
                            <h6>Phone Number</h6>
                            <p>585-785-4840</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                <div class="customer-details">
                    <div class="d-flex align-items-center">
                        <span class="customer-widget-icon ">
                            <i class="feather icon-airplay"></i>
                        </span>
                        <div class="customer-details-cont">
                            <h6>Company Name</h6>
                            <p>Kanakku Corporation</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                <div class="customer-details">
                    <div class="d-flex align-items-center">
                        <span class="customer-widget-icon ">
                            <i class="feather icon-globe"></i>
                        </span>
                        <div class="customer-details-cont">
                            <h6>Website</h6>
                            <p class="customer-mail">www.example.com</p>
                        </div>
                    </div>
                </div>
            </div>	
            <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                <div class="customer-details">
                    <div class="d-flex align-items-center">
                        <span class="customer-widget-icon ">
                            <i class="feather icon-briefcase"></i>
                        </span>
                        <div class="customer-details-cont">
                            <h6>Company Address</h6>
                            <p>4712 Cherry Ridge Drive Rochester, NY 14620.</p>
                        </div>
                    </div>
                </div>
            </div>	
        </div>
    </div>
</div>
    
<!-- Search Filter -->
<div id="filter_inputs" class="card filter-card">
    <div class="card-body pb-0">
        <div class="row">
            <div class="col-sm-6 col-md-3">
                <div class="form-group">
                    <label htmlFor="label">Name</label>
                    <input id="label" type="text" class="form-control">
                </div>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="form-group">
                    <label htmlFor="label">Email</label>
                    <input id="label" type="text" class="form-control">
                </div>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="form-group">
                    <label htmlFor="label">Phone</label>
                    <input id="label" type="text" class="form-control">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Search Filter -->

<!-- Inovices card -->
<div class="row">
    <div class="col-xl-2 col-lg-4 col-sm-6 col-12 d-flex">
        <div class="card inovices-card w-100">
            <div class="card-body">
                <div class="dash-widget-header">
                    <span class="inovices-widget-icon bg-info-light">
                        <img src="assets/img/icons/receipt-item.svg"alt="image">
                    </span>
                    <div class="dash-count">
                        <div class="dash-title">Total Invoice</div>
                        <div class="dash-counts">
                            <p>$298</p>
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                    <p class="inovices-all">No of Invoice <span class="rounded-circle bg-light-gray">02</span></p>
                    <p class="inovice-trending text-success-light">02 <span class="ms-2"><i class="feather icon-trending-up"></i></span></p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-2 col-lg-4 col-sm-6 col-12 d-flex">
        <div class="card inovices-card w-100">
            <div class="card-body">
                <div class="dash-widget-header">
                    <span class="inovices-widget-icon bg-primary-light">
                        <img src="assets/img/icons/transaction-minus.svg"alt="image">
                    </span>
                    <div class="dash-count">
                        <div class="dash-title">Outstanding</div>
                        <div class="dash-counts">
                            <p>$325,215</p>
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                    <p class="inovices-all">No of Invoice <span class="rounded-circle bg-light-gray">03</span></p>
                    <p class="inovice-trending text-success-light">04 <span class="ms-2"><i class="feather icon-trending-up"></i></span></p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-2 col-lg-4 col-sm-6 col-12 d-flex">
        <div class="card inovices-card w-100">
            <div class="card-body">
                <div class="dash-widget-header">
                    <span class="inovices-widget-icon bg-warning-light">
                        <img src="assets/img/icons/archive-book.svg"alt="image">
                    </span>
                    <div class="dash-count">
                        <div class="dash-title">Total Overdue</div>
                        <div class="dash-counts">
                            <p>$7825</p>
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                    <p class="inovices-all">No of Invoice <span class="rounded-circle bg-light-gray">01</span></p>
                    <p class="inovice-trending text-danger-light">03 <span class="ms-2"><i class="feather icon-trending-down"></i></span></p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-2 col-lg-4 col-sm-6 col-12 d-flex">
        <div class="card inovices-card w-100">
            <div class="card-body">
                <div class="dash-widget-header">
                    <span class="inovices-widget-icon bg-primary-light">
                        <img src="assets/img/icons/clipboard-close.svg"alt="image">
                    </span>
                    <div class="dash-count">
                        <div class="dash-title">Cancelled</div>
                        <div class="dash-counts">
                            <p>100</p>
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                    <p class="inovices-all">No of Invoice <span class="rounded-circle bg-light-gray">04</span></p>
                    <p class="inovice-trending text-danger-light">05 <span class="ms-2"><i class="feather icon-trending-down"></i></span></p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-2 col-lg-4 col-sm-6 col-12 d-flex">
        <div class="card inovices-card w-100">
            <div class="card-body">
                <div class="dash-widget-header">
                    <span class="inovices-widget-icon bg-green-light">
                        <img src="assets/img/icons/message-edit.svg"alt="image">
                    </span>
                    <div class="dash-count">
                        <div class="dash-title">Draft</div>
                        <div class="dash-counts">
                            <p>$125,586</p>
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                    <p class="inovices-all">No of Invoice <span class="rounded-circle bg-light-gray">06</span></p>
                    <p class="inovice-trending text-danger-light">02 <span class="ms-2"><i class="feather icon-trending-down"></i></span></p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-2 col-lg-4 col-sm-6 col-12 d-flex">
        <div class="card inovices-card w-100">
            <div class="card-body">
                <div class="dash-widget-header">
                    <span class="inovices-widget-icon bg-danger-light">
                        <img src="assets/img/icons/3d-rotate.svg"alt="image">
                    </span>
                    <div class="dash-count">
                        <div class="dash-title">Recurring</div>
                        <div class="dash-counts">
                            <p>$86,892</p>
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-between align-items-center">
                    <p class="inovices-all">No of Invoice <span class="rounded-circle bg-light-gray">03</span></p>
                    <p class="inovice-trending text-success-light">02 <span class="ms-2"><i class="feather icon-trending-up"></i></span></p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Inovices card -->

<!-- Table -->
<div class="row">
    <div class="col-sm-12">
        <div class="card-table"> 
            <div class="card-body">
                <div class="table-responsive">
                    <div class="table-scroll">
                        <table 
                        matSort
                        (matSortChange)="sortData($event)"
                        class="table table-stripped table-hover datatable">
                            <thead class="thead-light">
                                <tr>
                                    <th mat-sort-header="invoiceId">
                                        <label class="custom_check invoice-id">
                                            <input type="checkbox" name="invoice">
                                            <span class="checkmark"></span> Invoice ID
                                        </label>
                                    </th>
                                    <th mat-sort-header="category">Category</th>
                                    <th mat-sort-header="createdOn">Created On</th>
                                    <th mat-sort-header="tOtalAmount">Total Amount</th>												   
                                    <th mat-sort-header="paidAmount">Paid Amount</th>
                                    <th mat-sort-header="paymentMode">Payment Mode</th>
                                    <th mat-sort-header="balanace">Balance</th>
                                    <th mat-sort-header="dueDate">Due Date</th>
                                    <th mat-sort-header="status">Status</th>
                                    <th mat-sort-header="action" class="text-end">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr *ngFor="let data of recurringinvoice; let i = index">
                                    <td>
                                        <label class="custom_check ">
                                            <input type="checkbox" name="invoice">
                                            <span class="checkmark"></span> 
                                        </label>
                                        <a [routerLink]="routes.viewInvoice" class="invoice-link">{{data.invoiceId}}</a>
                                    </td>
                                    <td>{{data.category}}</td>
                                    <td>{{data.createdOn}}</td>
                                    <td>{{data.totalAmount}}</td>
                                    <td>{{data.paidAmount}}</td>													
                                    <td>{{data.paymentmode}}</td>
                                    <td>{{data.balance}}</td>
                                    <td>{{data.dueDate}}</td>
                                   
                                        <td><span class="badge" [ngClass]="{'bg-success-light': data.status1 === 'Paid','bg-warning-light text-warning': data.status1 === 'Overdue',
                                        ' bg-danger-light text-danger': data.status1 ==='Cancelled',
                                        ' bg-primary-light': data.status1 ==='Partially Paid',
                                        'bg-light-gray text-secondary':data.status1 ==='Unpaid',
                                        'bg-light-gray text-primary' :data.status1 ==='Draft'}">
                                        {{data.status1}}</span></td>
    
                                    <td>
                                        <div class="dropdown dropdown-action">
                                            <a href="#" class=" btn-action-icon " data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-ellipsis-v"></i></a>
                                            <div class="dropdown-menu dropdown-menu-end customer-dropdown">
                                                <ul>
                                                    <li>
                                                        <a class="dropdown-item" [routerLink]="routes.editCustomer"><i class="feather icon-edit me-2"></i>Edit</a>
                                                    </li>
                                                    <li>
                                                        <a class="dropdown-item" href="javascript:void(0);" data-bs-toggle="modal" data-bs-target="#delete_modal"><i class="far fa-trash-alt me-2"></i>Delete</a>
                                                    </li>
                                                    <li>
                                                        <a class="dropdown-item" [routerLink]="routes.customerdetails"><i class="feather icon-eye me-2"></i>View</a>
                                                    </li>
                                                    <li>
                                                        <a class="dropdown-item" [routerLink]="routes.customerdetails"><i class="feather icon-send me-2"></i>Send</a>
                                                    </li>
                                                    <li>
                                                        <a class="dropdown-item"  [routerLink]="routes.customerdetails"><i class="feather icon-download me-2"></i>Download</a>
                                                    </li>
                                                    <li>
                                                        <a class="dropdown-item"  [routerLink]="routes. addcreditnotes"><i class="feather icon-file-text me-2"></i>Convert to Sales Return</a>
                                                    </li>
                                                    <li>
                                                        <a class="dropdown-item" [routerLink]="routes.customerdetails"><i class="feather icon-copy me-2"></i>Clone as Invoice</a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                                                   
                            </tbody>
                        </table>
                    </div>
                    <div class="table_header">
                        <div class="row">
                          <div class="col-sm-12 col-md-6">
                            <div class="dataTables_length">
                              <label>
                                Show
                                <select
                                  [(ngModel)]="pageSize"
                                  (ngModelChange)="PageSize()"
                                  class="form-control form-control-sm"
                                >
                                  <option value="10">10</option>
                                  <option value="25">25</option>
                                  <option value="50">50</option>
                                  <option value="100">100</option>
                                </select>
                                Entries
                              </label>
                            </div>
                          </div>
                        </div>
                        <div class="col-sm-12 col-md-3">
                          <div class="pagination_section">
                            <ul class="pagination">
                              <li
                                class="page-item "
                                [ngClass]="{
                                  disabled: currentPage ===1
                                }"
                              >
                                <a
                                  (click)="getMoreData('previous')"
                                  class="page-link"
                                  href="javascript:void(0);"
                                  tabindex="-1"
                                  ><i class="fa fa-angle-double-left me-2"></i>Previous</a
                                >
                              </li>
            
                              <ng-container
                                *ngFor="let item of pageNumberArray; let i = index"
                              >
                                <li
                                  class="page-item"
                                  [class.active]="item === currentPage"
                                  [ngClass]="
                                    (pageNumberArray[currentPage - 2] > item &&
                                      item !== 1 &&
                                      pageNumberArray.length > 6) ||
                                    (pageNumberArray[currentPage] < item &&
                                      item !== 1 &&
                                      pageNumberArray.length > 6 &&
                                      pageNumberArray.length !== item)
                                      ? 'hide-sub-menu'
                                      : 'show-sub-menu'
                                  "
                                >
                                  <a
                                    (click)="moveToPage(item)"
                                    class="page-link"
                                    href="javascript:void(0);"
                                  >
                                    {{ item }}
                                    <span *ngIf="item === currentPage" class="visually-hidden"
                                      >(current)</span
                                    >
                                  </a>
                                </li>
                                <li
                                  class="page-item"
                                  *ngIf="
                                    i === 0 && pageNumberArray.length > 6 && currentPage > 2
                                  "
                                  [hidden]="currentPage === 1"
                                 
                                >
                                  <a class="page-link"  (click)="moveToPage(currentPage - 2)" href="javascript:void(0);"> ... </a>
                                </li>
                                <li
                                  *ngIf="
                                    i === pageNumberArray.length - 2 &&
                                    pageNumberArray.length > 6
                                  "
                                  [hidden]="
                                    currentPage >=
                                      pageNumberArray[pageNumberArray.length - 2] ||
                                    totalData <
                                      serialNumberArray[serialNumberArray.length - 1]
                                  "
                                  class="page-item"
                                
                                >
                                  <a class="page-link"   (click)="moveToPage(currentPage + 2)" href="javascript:void(0);"> ... </a>
                                </li>
                              </ng-container>
            
                              <li
                                class="page-item"
                                [ngClass]="{
                                  disabled:
                                    currentPage ===
                                      pageNumberArray[pageNumberArray.length - 1] ||
                                      recurringinvoice.length === 0
                                }"
                              >
                                <a
                                  (click)="getMoreData('next')"
                                  class="page-link"
                                  href="javascript:void(0);"
                                  >Next<i class="fa fa-angle-double-right ms-2"></i>
                                </a>
                              </li>
                            </ul>
                          </div>
                        </div>
                    </div>
                   
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Table -->

<!-- Delete Items Modal -->
<div class="modal custom-modal fade" id="delete_modal" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-md">
        <div class="modal-content">
            <div class="modal-body">
                <div class="form-header">
                    <h3>Delete Customer Details</h3>
                    <p>Are you sure want to delete?</p>
                </div>
                <div class="modal-btn delete-action">
                    <div class="row">
                        <div class="col-6">
                            <a href="#" data-bs-dismiss="modal" class="btn btn-primary paid-continue-btn">Delete</a>
                        </div>
                        <div class="col-6">
                            <a href="#" data-bs-dismiss="modal" class="btn btn-primary paid-cancel-btn">Cancel</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Delete Items Modal -->
