// kanakku-v1.9.9/angular-files/template-rtl/src/app/feature-module/invoices/add-invoice/add-invoice.component.ts
import { Component, OnInit } from '@angular/core';

import { DataService, routes  } from 'src/app/core/core.index';
import { MatTableDataSource } from '@angular/material/table';
import { apiResultFormat, editcreditnotes, pageSelection } from 'src/app/core/models/models';
import { Sort } from '@angular/material/sort';



@Component({
  selector: 'app-add-invoice',
  templateUrl: './add-invoice.component.html',
  styleUrls: ['./add-invoice.component.scss'],
})
export class AddInvoiceComponent implements OnInit {
  public selectedValue !: string | number ;
  public editcreditnotes: Array<editcreditnotes> = [];
  country = 'India';
  status ='choose';
  product='sales';
  percentage='percentage1';
  tax="tax";
  selectbank='bank'

 
  
  public routes = routes
  public Toggledata  = false;
  dataSource!: MatTableDataSource<editcreditnotes>;
  public searchDataValue = '';
  // pagination variables
  public lastIndex = 0;
  public pageSize = 10;
  public totalData = 0;
  public skip = 0;
  public limit: number = this.pageSize;
  public pageIndex = 0;
  public serialNumberArray: Array<number> = [];
  public currentPage = 1;
  public pageNumberArray: Array<number> = [];
  public pageSelection: Array<pageSelection> = [];
  public totalPages = 0;
  //** / pagination variables
  
 
  constructor(private data: DataService) {}

  ngOnInit(): void {
    this.getTableData();
  }
  private getTableData(): void {
    this.editcreditnotes = [];
    this.serialNumberArray = [];

    this.data.getEditcreditnotes().subscribe((data: apiResultFormat) => {
      this.totalData = data.totalData;
      data.data.map((res: editcreditnotes, index: number) => {
        const serialNumber = index + 1;
        if (index >= this.skip && serialNumber <= this.limit) {
          res.editcreditnotes = serialNumber;
          this.editcreditnotes.push(res);
          this.serialNumberArray.push(serialNumber);
        }
      });
      this.dataSource = new MatTableDataSource<editcreditnotes>(this.editcreditnotes);
      this.calculateTotalPages(this.totalData, this.pageSize);
    });
  }
 
  
  
  public sortData(sort: Sort) {
    const data = this.editcreditnotes.slice();

    if (!sort.active || sort.direction === '') {
      this.editcreditnotes = data;
    } else {
      this.editcreditnotes= data.sort((a, b) => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const aValue = (a as any)[sort.active];
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const bValue = (b as any)[sort.active];
        return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
      });
    }
  }
  public getMoreData(event: string): void {
    if (event == 'next') {
      this.currentPage++;
      this.pageIndex = this.currentPage - 1;
      this.limit += this.pageSize;
      this.skip = this.pageSize * this.pageIndex;
      this.getTableData();
    } else if (event == 'previous') {
      this.currentPage--;
      this.pageIndex = this.currentPage - 1;
      this.limit -= this.pageSize;
      this.skip = this.pageSize * this.pageIndex;
      this.getTableData();
    }
  }
  public moveToPage(pageNumber: number): void {
    this.currentPage = pageNumber;
    this.skip = this.pageSelection[pageNumber - 1].skip;
    this.limit = this.pageSelection[pageNumber - 1].limit;
    if (pageNumber > this.currentPage) {
      this.pageIndex = pageNumber - 1;
    } else if (pageNumber < this.currentPage) {
      this.pageIndex = pageNumber + 1;
    }
    this.getTableData();
  }
  public PageSize(): void {
    this.pageSelection = [];
    this.limit = this.pageSize;
    this.skip = 0;
    this.currentPage = 1;
    this.getTableData();
  }
  private calculateTotalPages(totalData: number, pageSize: number): void {
    this.pageNumberArray = [];
    this.totalPages = totalData / pageSize;
    if (this.totalPages % 1 != 0) {
      this.totalPages = Math.trunc(this.totalPages + 1);
    }
    for (let i = 1; i <= this.totalPages; i++) {
      const limit = pageSize * i;
      const skip = limit - pageSize;
      this.pageNumberArray.push(i);
      this.pageSelection.push({ skip: skip, limit: limit });
    }
  }
  open() {
    this.Toggledata = !this.Toggledata;
   
  }
  files: File[] = [];
  onSelect(event: { addedFiles: File[] }) {
    this.files.push(...event.addedFiles);
  }
  onRemove(event:File) {
   this.files.splice(this.files.indexOf(event), 1);
  }
  myDateValue!: Date;
  public minDate!: Date;
  public maxDate!: Date;

 
 

}

<!-- Page Wrapper -->
<div class="card mb-0">
  <div class="card-body">
    <div class="page-header">
      <div class="content-page-header">
        <h5>Add Invoice</h5>
      </div>	
    </div>					
    <div class="row">
      <div class="col-md-12">
        <div class="form-group-item border-0 mb-0">
          <div class="row align-item-center">
            <div class="col-lg-4 col-md-6 col-sm-12">
              <div class="input-block mb-3">
                <label>Invoice Number</label>
                <input type="text" class="form-control" placeholder="Enter Invoice Number">
              </div>
            </div>										
            <div class="col-lg-4 col-md-6 col-sm-12">											
              <div class="input-block mb-3">
                <label>Customer Name</label>
                <ul class="form-group-plus css-equal-heights">
                  <li>
                    <mat-select
                    [(ngModel)]="country"
                    [ngModelOptions]="{ standalone: true }"
                    class="select mat-cust-select form-control"
                  >
                    <mat-option value="India">Choose Customer</mat-option>
                    <mat-option value="customer1">Customer 1</mat-option>
                    <mat-option value="customer2">Customer 2</mat-option>
                    <mat-option value="customer3">Customer 3</mat-option>
                  </mat-select>
                  </li>
                  <li>    
                    <a class="btn btn-primary form-plus-btn" [routerLink]="routes.addCustomer">
                      <i class="feather icon-plus-circle"></i>
                    </a>
                  </li>
                </ul>												
              </div>									
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12">
              <div class="input-block mb-3">
                <label>Invoice Date</label>
                <div class="cal-icon cal-icon-info">
                  <input type="text" class="datetimepicker form-control" placeholder="Select Date"
                  [maxDate]="maxDate"
                  #dp="bsDatepicker"
                  bsDatepicker [(bsValue)]="myDateValue">
                </div>
              </div>											
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12">
              <div class="input-block mb-3">
                <label>Due Date</label>
                <div class="cal-icon cal-icon-info">
                  <input type="text" class="datetimepicker form-control" placeholder="Select Date"
                  [minDate]="minDate"
                      [maxDate]="maxDate"
                      #dp="bsDatepicker"
                      bsDatepicker [(bsValue)]="myDateValue">
                </div>
              </div>											
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12">
              <div class="input-block mb-3">
                <label>Status</label>
                <mat-select
                [(ngModel)]="status"
                [ngModelOptions]="{ standalone: true }"
                class="select mat-cust-select form-control"
              >
                <mat-option value="choose">Choose a Status</mat-option>
                <mat-option value="Unpaid">Unpaid</mat-option>
                <mat-option value="Partially paid">Partially paid</mat-option>
                <mat-option value="Paid">Paid</mat-option>
                <mat-option value="Overdue">Overdue</mat-option>
                <mat-option value="Cancelled">Cancelled</mat-option>
                <mat-option value="Refunded">Refunded</mat-option>
                <mat-option value="Draft">Draft</mat-option>

                </mat-select>
              </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12">
              <div class="input-block mb-3">
                <label>Reference Number</label>
                <input type="text" class="form-control" placeholder="Enter Reference Number">
              </div>
            </div>
            <div class="col-lg-4">
              <div class="d-flex justify-content-between flex-wrap">
                <div class="input-block mb-3 recurring-tab">
                  <label >Recurring</label>
                  <ul class="nav nav-pills d-flex" id="pills-tab" role="tablist">
                    <li class="nav-item" role="presentation">
                      <button class="nav-link active yes" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Yes</button>
                    </li>
                    <li class="nav-item" role="presentation">
                      <button class="nav-link no" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">No</button>
                    </li>
                  </ul>	
                </div>	
                <div class="tab-content pt-0" id="pills-tabContent">
                  <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
                    <div class="input-block mb-3">
                      <label>Recurring cycle</label>
                      <input type="text" class="form-control" placeholder="Enter Month">	
                    </div>
                  </div>
                  <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab"></div>
                </div>
              </div>
            </div>
            <div class="col-lg-8">											
              <div class="input-block mb-3">
                <label htmlFor="label">Products</label>
                <ul class="form-group-plus css-equal-heights">
                  <li>
                    <mat-select
                    [(ngModel)]="product"
                    [ngModelOptions]="{ standalone: true }"
                    class="select mat-cust-select form-control"
                  >
                    <mat-option value="sales">Select Product</mat-option>
                    <mat-option value="Product 1">Product 1</mat-option>
                    <mat-option value="Product 2">Product 2</mat-option>
                    <mat-option value="Product 3">Product 3</mat-option>
                  </mat-select>
                  </li>
                  <li>    
                    <a class="btn btn-primary form-plus-btn" [routerLink]="routes.addproducts">
                      <i class="feather icon-plus-circle"></i>
                    </a>
                  </li>
                </ul>												
              </div>									
            </div>
          </div>
        </div>
        <div class="form-group-item">
          <div class="card-table">
            <div class="card-body">
              <div class="table-responsive no-pagination">
                <table  matSort
                (matSortChange)="sortData($event)"
                class="table table-center table-hover datatable">
                  <thead class="thead-light">
                    <tr>
                      <th mat-sort-header="product">Product / Service</th>
                      <th mat-sort-header="quantity">Quantity</th>
                      <th mat-sort-header="unit"> Unit</th>
                      <th mat-sort-header="rate">Rate</th>
                      <th mat-sort-header="discount">Discount</th>
                      <th mat-sort-header="tax">Tax</th>
                      <th mat-sort-header="amount"> Amount</th>
                      <th mat-sort-header="action">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr *ngFor="let data of editcreditnotes; let i = index">
                      <td>{{ data.product }}</td>
                      <td><input type="number" class="form-control" value="0"></td>
                      <td>{{ data.unit }}</td>
                      <td><input type="number" class="form-control" value="120"></td>
                      <td>{{ data.discount }}</td>
                      <td>{{ data.tax }}</td>
                      <td>{{ data.amount }}</td>
                      <td class="d-flex align-items-center">
                        <a href="#" class="btn-action-icon me-2" data-bs-toggle="modal" data-bs-target="#add_discount"><span><i class="feather icon-edit"></i></span></a>
                        <a href="#" class="btn-action-icon" data-bs-toggle="modal" data-bs-target="#delete_discount"><span><i class="feather icon-trash-2"></i></span></a>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <div class="row">
              <div class="col-lg-7">
                <div class="input-block mb-3">
                  <label>Discount Type</label>
                  <mat-select
                  [(ngModel)]="percentage"
                  [ngModelOptions]="{ standalone: true }"
                  class="select mat-cust-select form-control"
                >
                  <mat-option value="percentage1">Percentage(%)</mat-option>
                  <mat-option value="percentage2">Fixed</mat-option>
                
              </mat-select>
                </div>
              </div>
              <div class="col-lg-5">
                <div class="input-block mb-3">
                  <label>Discount(%)</label>
                  <input type="text" class="form-control" placeholder="10">
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="input-block mb-3">
              <label>Tax</label>
            <mat-select
              [(ngModel)]="tax"
              [ngModelOptions]="{ standalone: true }"
              class="select mat-cust-select form-control"
            >
              <mat-option value="tax">No Tax</mat-option>
              <mat-option value="customer1">IVA - (21%)</mat-option>
              <mat-option value="customer2">IRPF - (-15%)</mat-option>
              <mat-option value="customer2">PDV - (20%)</mat-option>
            </mat-select>
            </div>
          </div>
          <div class="col-md-4"></div>
        </div>
        <div class="form-group-item border-0 p-0">
          <div class="row">
            <div class="col-xl-6 col-lg-12">
              <div class="form-group-bank">
                <div class="row align-items-center">
                  <div class="col-md-8">
                    <div class="input-block mb-3">
                      <label>Select Bank</label>
                      <mat-select
              [(ngModel)]="selectbank"
              [ngModelOptions]="{ standalone: true }"
              class="select mat-cust-select form-control"
            >
              <mat-option value="bank">Select Bank</mat-option>
              <mat-option value="bank1">SBI</mat-option>
              <mat-option value="bank2">IOB</mat-option>
              <mat-option value="bank3">Canara</mat-option>
            </mat-select>
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-groups">
                      <a class="btn btn-primary" href="#" data-bs-toggle="modal" data-bs-target="#bank_details">Add Bank</a>
                    </div>
                  </div>
                </div>
                
                <div class="input-block mb-3 notes-form-group-info">
                  <label>Notes</label>
                  <textarea class="form-control" placeholder="Enter Notes"></textarea>
                </div>
                <div class="input-block mb-3 notes-form-group-info mb-0">
                  <label>Terms and Conditions</label>
                  <textarea class="form-control" placeholder="Enter Terms and Conditions"></textarea>
                </div>
              </div>
            </div>
            <div class="col-xl-6 col-lg-12">
              <div class="form-group-bank">
                <div class="invoice-total-box">
                  <div class="invoice-total-inner">
                    <p>Taxable Amount <span>$120.00</span></p>
                    <p>Discount <span>$13.20</span></p>
                    <p>Vat <span>$0.00</span></p>
                    <div class="status-toggle justify-content-between">
                      <div class="d-flex align-center">
                        <p>Round Off </p>
                        <input id="rating_1" class="check" type="checkbox" checked="">
                        <label for="rating_1" class="checktoggle checkbox-bg">checkbox</label>
                      </div>
                      <span>$0.00</span>
                    </div>																
                  </div>
                  <div class="invoice-total-footer">
                    <h4>Total Amount <span>$107.80</span></h4>
                  </div>
                </div>
                <div class="input-block mb-3">
                  <label>Signature Name</label>
                  <input type="text" class="form-control" placeholder="Enter Signature Name">
                </div>
                <div class="input-block mb-0">
                  <label>Signature Image</label>
                  <div class="input-block mb-3 service-upload service-upload-info mb-0">
                    <span><i class="fe fe-upload-cloud me-1"></i>Upload Signature</span>
                    <input type="file" multiple="" id="image_sign">
                    <div id="frames"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>	
        </div>							
        <form action="invoices.html" class="add-customer-btns text-start">
          <button type="reset" class="btn btn-primary cancel me-2">Cancel</button>
          <button type="reset" class="btn btn-primary cancel me-2">Save</button>
          <button type="submit" class="btn btn-primary">Save & Send</button>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- /Page Wrapper -->

<!-- Add Tax & Discount Modal -->
<div class="modal custom-modal fade" id="add_discount" role="dialog">
  <div class="modal-dialog modal-dialog-centered modal-md">
    <div class="modal-content">
      <div class="modal-header border-0 pb-0">
        <div class="form-header modal-header-title text-start mb-0 align-center">
          <h4 class="mb-0">Add Tax & Discount</h4>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="input-block mb-3">
              <label>Rate</label>
              <input type="number" class="form-control" placeholder="120">
            </div>
          </div>
          <div class="col-lg-12 col-md-12">
            <div class="input-block mb-3">
              <label>Discount Amount</label>
              <input type="number" class="form-control" placeholder="0">
            </div>
          </div>
          <div class="col-lg-12 col-md-12">
            <div class="input-block mb-0">
              <label>Tax</label>
              <mat-select
              [(ngModel)]="tax"
              [ngModelOptions]="{ standalone: true }"
              class="select mat-cust-select form-control"
            >
              <mat-option value="tax">No Tax</mat-option>
              <mat-option value="customer1">IVA - (21%)</mat-option>
              <mat-option value="customer2">IRPF - (-15%)</mat-option>
              <mat-option value="customer2">PDV - (20%)</mat-option>
            </mat-select>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer add-tax-btns">
        <button type="reset" data-bs-dismiss="modal" class="btn btn-back cancel-btn me-2">Cancel</button>
        <button type="submit" data-bs-dismiss="modal" class="btn btn-primary paid-continue-btn">Save</button>
      </div>
    </div>
  </div>
</div>
<!-- /Add Tax & Discount Modal -->

<!-- Delete Items Modal -->
<div class="modal custom-modal fade" id="delete_discount" role="dialog">
  <div class="modal-dialog modal-dialog-centered modal-md">
    <div class="modal-content">
      <div class="modal-header border-0 justify-content-center pb-0">
        <div class="form-header modal-header-title text-center mb-0">
          <h4 class="mb-2">Delete Product / Services</h4>
          <p>Are you sure want to delete?</p>
        </div>
      </div>
      <div class="modal-body">
        <div class="modal-btn delete-action">
          <div class="row">
            <div class="col-6">
              <a href="#" data-bs-dismiss="modal" class="btn btn-primary paid-continue-btn">Delete</a>
            </div>
            <div class="col-6">
              <a href="#" data-bs-dismiss="modal" class="btn btn-primary paid-cancel-btn">Cancel</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /Delete Items Modal -->

<!-- Add Bank Details Modal -->
<div class="modal custom-modal fade" id="bank_details" role="dialog">
  <div class="modal-dialog modal-dialog-centered modal-md">
    <div class="modal-content">
      <div class="modal-header border-0 pb-0">
        <div class="form-header modal-header-title text-start mb-0">
          <h4 class="mb-0">Add Bank Details</h4>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="input-block mb-3">
              <label>Bank Name <span class="text-danger">*</span></label>
              <input type="text" class="form-control" placeholder="Enter Bank Name">
            </div>
          </div>
          <div class="col-lg-12 col-md-12">
            <div class="input-block mb-3">
              <label>Account Number <span class="text-danger">*</span></label>
              <input type="number" class="form-control" placeholder="Enter Account Number">
            </div>
          </div>
          <div class="col-lg-12 col-md-12">
            <div class="input-block mb-3">
              <label>Account Holder Name <span class="text-danger">*</span></label>
              <input type="text" class="form-control" placeholder="Enter Account Holder Name">
            </div>
          </div>
          <div class="col-lg-12 col-md-12">
            <div class="input-block mb-3">
              <label>Branch Name <span class="text-danger">*</span></label>
              <input type="text" class="form-control" placeholder="Enter Branch Name">
            </div>
          </div>
          <div class="col-lg-12 col-md-12">
            <div class="input-block mb-0">
              <label>IFSC Code <span class="text-danger">*</span></label>
              <input type="number" class="form-control" placeholder="Enter IFSC COde">
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <a href="#" data-bs-dismiss="modal" class="btn btn-back cancel-btn me-2">Cancel</a>
        <a href="#" data-bs-dismiss="modal" class="btn btn-primary paid-continue-btn">Save</a>
      </div>
    </div>
  </div>
</div>
<!-- /Add Bank Details Modal -->

// kanakku-v1.9.9/reactjs-files/template-rtl/src/invoices/AddInvoice.jsx
import React, { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import DatePicker from "react-datepicker";
import Header from "../layouts/Header";
import Sidebar from "../layouts/Sidebar";
import { Logo, signature, circle1, circle2 } from "../_components/imagepath";
import FeatherIcon from "feather-icons-react";
import Select2 from "react-select2-wrapper";

const AddInvoice = () => {
  const [menu, setMenu] = useState(false);
  const [startDate, setStartDate] = useState(new Date());

  const toggleMobileMenu = () => {
    setMenu(!menu);
  };

  const [product, setProduct] = useState([
    { id: 1, text: "Choose Customer" },
    { id: 2, text: "Customer 1" },
    { id: 3, text: "Customer 2" },
    { id: 4, text: "Customer 3" },
  ]);

  const [productOption, setProductOption] = useState([
    { id: 1, text: "Select Product" },
    { id: 2, text: "Product 1" },
    { id: 3, text: "Product 2" },
    { id: 4, text: "Product 3" },
  ]);

  const [currency, setCurrency] = useState([
    { id: 1, text: "Select Currency" },
    { id: 2, text: "US dollar" },
    { id: 3, text: "Euro" },
    { id: 4, text: "Pound sterling" },
    { id: 5, text: "Swiss franc" },
  ]);

  const [percentage, setPercentage] = useState([
    { id: 1, text: "Percentage(%)" },
    { id: 2, text: "0%" },
    { id: 3, text: "5%" },
    { id: 4, text: "10%" },
    { id: 5, text: "15%" },
  ]);

  const [tax, setTax] = useState([
    { id: 1, text: "N/A" },
    { id: 2, text: "5%" },
    { id: 3, text: "10%" },
    { id: 4, text: "15%" },
  ]);

  useEffect(() => {
    let elements = Array.from(
      document.getElementsByClassName("react-datepicker-wrapper")
    );
    elements.map((element) => element.classList.add("w-100"));
  }, []);

  return (
    <>
      <div className={`main-wrapper ${menu ? "slide-nav" : ""}`}>
        <Header onMenuClick={(value) => toggleMobileMenu()} />
        <Sidebar />
        {/* <!-- Page Wrapper --> */}
        <div className="page-wrapper">
          <div className="content container-fluid">
            <div className="page-header">
              <div className="content-page-header">
                <h5>Add Invoice</h5>
              </div>
            </div>
            <div className="row">
              <div className="col-md-12">
                <div className="card">
                  <div className="card-body">
                    <div className="form-group-item border-0 mb-0">
                      <div className="row align-item-center">
                        <div className="col-lg-4 col-md-6 col-sm-12">
                          <div className="form-group">
                            <label>Invoice Number</label>
                            <input
                              type="text"
                              className="form-control"
                              placeholder="Enter First Name"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6 col-sm-12">
                          <div className="form-group">
                            <label>Customer Name</label>
                            <ul className="form-group-plus css-equal-heights">
                              <li>
                                <Select2
                                  // className="w-100"
                                  data={product}
                                  options={{
                                    placeholder: "Choose Customer",
                                  }}
                                />
                              </li>
                              <li>
                                <Link
                                  className="btn btn-primary form-plus-btn"
                                  to="/add-customer"
                                >
                                  {/* <i className="fe fe-plus-circle" /> */}
                                  <FeatherIcon icon="plus-circle" />
                                </Link>
                              </li>
                            </ul>
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6 col-sm-12">
                          <div className="form-group">
                            <label>Invoice Date</label>
                            <div className="cal-icon cal-icon-info">
                              <DatePicker
                                className="datetimepicker form-control"
                                selected={startDate}
                                onChange={(date) => setStartDate(date)}
                              ></DatePicker>
                              {/* <FeatherIcon icon="calendar"/> */}
                            </div>
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6 col-sm-12">
                          <div className="form-group">
                            <label>Due Date</label>
                            <div className="cal-icon cal-icon-info">
                              <DatePicker
                                className="datetimepicker form-control"
                                selected={startDate}
                                onChange={(date) => setStartDate(date)}
                              ></DatePicker>
                            </div>
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6 col-sm-12">
                          <div className="form-group">
                            <label>Reference No</label>
                            <input
                              type="text"
                              className="form-control"
                              placeholder="Enter Phone Number"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6 col-sm-12">
                          <div className="form-group d-flex align-items-end h-100">
                            <label className="custom_check me-3">
                              <input type="checkbox" name="invoice" />
                              <span className="checkmark" /> Enable tax
                            </label>
                            <label className="custom_check">
                              <input type="checkbox" name="re_invoice" />
                              <span className="checkmark" /> Recurring Invoice
                            </label>
                          </div>
                        </div>
                        <div className="col-lg-12">
                          <div className="form-group">
                            <label>Products</label>
                            <ul className="form-group-plus css-equal-heights">
                              <li>
                                {/* <select className="select">
                                  <option>Select Product</option>
                                  <option>Product 1</option>
                                  <option>Product 2</option>
                                  <option>Product 3</option>
                                </select> */}
                                <Select2
                                  // className="w-100"
                                  data={productOption}
                                  options={{
                                    placeholder: "Select Product",
                                  }}
                                />
                              </li>
                              <li>
                                <Link
                                  className="btn btn-primary form-plus-btn"
                                  to="/add-product"
                                >
                                  {/* <i className="fe fe-plus-circle" /> */}
                                  <FeatherIcon icon="plus-circle" />
                                </Link>
                              </li>
                            </ul>
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6 col-sm-12">
                          <div className="form-group">
                            <label>Currency</label>
                            <Select2
                              // className="w-100"
                              data={currency}
                              options={{
                                placeholder: "Select Currency",
                              }}
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6 col-sm-12">
                          <div className="form-group">
                            <label>Website</label>
                            <input
                              type="text"
                              className="form-control"
                              placeholder="Enter Website Address"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6 col-sm-12">
                          <div className="form-group">
                            <label>Notes</label>
                            <input
                              type="text"
                              className="form-control"
                              placeholder="Enter Your Notes"
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="form-group-item">
                      <div className="card-table">
                        <div className="card-body add-invoice">
                          <div className="table-responsive">
                            <table className="table table-center table-hover datatable">
                              <thead className="thead-light">
                                <tr>
                                  <th>Product / Service</th>
                                  <th>Quantity</th>
                                  <th>Unit</th>
                                  <th>Rate</th>
                                  <th>Discount</th>
                                  <th>Tax</th>
                                  <th>Amount</th>
                                  <th>Action</th>
                                </tr>
                              </thead>
                              <tbody>
                                <tr>
                                  <td>Lorem ipsum dolor sit amet</td>
                                  <td>0</td>
                                  <td>Pcs</td>
                                  <td>$120.00</td>
                                  <td>0</td>
                                  <td>0</td>
                                  <td>$120.00</td>
                                  <td className="d-flex align-items-center">
                                    <Link
                                      to="#"
                                      className="btn-action-icon ms-2"
                                      data-bs-toggle="modal"
                                      data-bs-target="#add_discount"
                                    >
                                      <span>
                                        {/* <i className="fe fe-edit" /> */}
                                        <FeatherIcon icon="edit" />
                                      </span>
                                    </Link>
                                    <Link
                                      to="#"
                                      className="btn-action-icon"
                                      data-bs-toggle="modal"
                                      data-bs-target="#delete_discount"
                                    >
                                      <span>
                                        {/* <i className="fe fe-trash-2" /> */}
                                        <FeatherIcon icon="trash-2" />
                                      </span>
                                    </Link>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="form-group-item border-0 p-0">
                      <div className="row">
                        <div className="col-xl-6 col-lg-12">
                          <div className="form-group-bank">
                            <div className="form-group">
                              <label>Select Bank</label>
                              <div className="bank-details">
                                <Link
                                  className="text-danger-light"
                                  to="#"
                                  data-bs-toggle="modal"
                                  data-bs-target="#bank_details"
                                >
                                  <i className="fas fa-bank ms-2" />
                                  Add Bank Details
                                </Link>
                              </div>
                            </div>
                            <div className="form-group notes-form-group-info">
                              <label>Notes</label>
                              <textarea
                                className="form-control"
                                placeholder="Enter Notes"
                                defaultValue={""}
                              />
                            </div>
                            <div className="form-group notes-form-group-info mb-0">
                              <label>Terms and Conditions</label>
                              <textarea
                                className="form-control"
                                placeholder="Enter Terms and Conditions"
                                defaultValue={""}
                              />
                            </div>
                          </div>
                        </div>
                        <div className="col-xl-6 col-lg-12">
                          <div className="form-group-bank">
                            <div className="row">
                              <div className="col-lg-4 col-md-12">
                                <div className="form-group">
                                  <label>Discount Type</label>
                                  <Select2
                                    // className="w-100"
                                    data={percentage}
                                    options={{
                                      placeholder: "Percentage(%)",
                                    }}
                                  />
                                </div>
                              </div>
                              <div className="col-lg-4 col-md-12">
                                <div className="form-group">
                                  <label>Discount (%)</label>
                                  <input
                                    type="text"
                                    className="form-control"
                                    placeholder={10}
                                  />
                                </div>
                              </div>
                              <div className="col-lg-4 col-md-12">
                                <div className="form-group">
                                  <label>Total discount</label>
                                  <input
                                    type="text"
                                    className="bg-white-smoke form-control"
                                    placeholder="13.2"
                                  />
                                </div>
                              </div>
                            </div>
                            <div className="invoice-total-box">
                              <div className="invoice-total-inner">
                                <p>
                                  Taxable Amount <span>$120.00</span>
                                </p>
                                <p>
                                  Discount <span>$13.20</span>
                                </p>
                                <p>
                                  Vat <span>$0.00</span>
                                </p>
                                <div className="status-toggle justify-content-between">
                                  <div className="d-flex align-center">
                                    <p>Round Off </p>
                                    <input
                                      id="rating_1"
                                      className="check"
                                      type="checkbox"
                                      defaultChecked="true"
                                    />
                                    <label
                                      htmlFor="rating_1"
                                      className="checktoggle checkbox-bg"
                                    >
                                      checkbox
                                    </label>
                                  </div>
                                  <span>$0.00</span>
                                </div>
                              </div>
                              <div className="invoice-total-footer">
                                <h4>
                                  Total Amount <span>$107.80</span>
                                </h4>
                              </div>
                            </div>
                            <div className="form-group">
                              <label>Signature Name</label>
                              <input
                                type="text"
                                className="form-control"
                                placeholder="Enter Signature Name"
                              />
                            </div>
                            <div className="form-group mb-0">
                              <label>Signature Image</label>
                              <div className="form-group service-upload service-upload-info mb-0">
                                <span>
                                  {/* <i className="fe fe-upload-cloud me-1" /> */}
                                  <FeatherIcon
                                    icon="upload-cloud"
                                    className="ms-1"
                                  />
                                  Upload Signature
                                </span>
                                <input
                                  type="file"
                                  multiple=""
                                  id="image_sign"
                                />
                                <div id="frames" />
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="add-customer-btns text-end">
                      <button
                        type="reset"
                        className="btn btn-primary cancel ms-2"
                      >
                        Cancel
                      </button>
                      <button type="submit" className="btn btn-primary">
                        Save Changes
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Add Tax & Discount Modal */}
        <div
          className="modal custom-modal fade"
          id="add_discount"
          role="dialog"
        >
          <div className="modal-dialog modal-dialog-centered modal-md">
            <div className="modal-content">
              <div className="modal-header border-0 pb-0">
                <div className="form-header modal-header-title text-start mb-0 align-center">
                  <h4 className="mb-0">Add Tax &amp; Discount</h4>
                </div>
                <button
                  type="button"
                  className="close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <span className="align-center" aria-hidden="true">
                    ×
                  </span>
                </button>
              </div>
              <div className="modal-body">
                <div className="row">
                  <div className="col-lg-12 col-md-12">
                    <div className="form-group">
                      <label>Rate</label>
                      <input
                        type="number"
                        className="form-control"
                        placeholder={120}
                      />
                    </div>
                  </div>
                  <div className="col-lg-12 col-md-12">
                    <div className="form-group">
                      <label>Discount Amount</label>
                      <input
                        type="number"
                        className="form-control"
                        placeholder={0}
                      />
                    </div>
                  </div>
                  <div className="col-lg-12 col-md-12">
                    <div className="form-group mb-0">
                      <label>Tax</label>
                      <Select2
                        // className="w-100"
                        data={tax}
                        options={{
                          placeholder: "Choose Customer",
                        }}
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div className="modal-footer add-tax-btns">
                <button
                  type="reset"
                  data-bs-dismiss="modal"
                  className="btn btn-primary paid-cancel-btn ms-2"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  data-bs-dismiss="modal"
                  className="btn btn-primary paid-continue-btn"
                >
                  Save
                </button>
              </div>
            </div>
          </div>
        </div>
        {/* /Add Tax & Discount Modal */}

        {/* Delete Items Modal */}
        <div
          className="modal custom-modal fade"
          id="delete_discount"
          role="dialog"
        >
          <div className="modal-dialog modal-dialog-centered modal-md">
            <div className="modal-content">
              <div className="modal-header border-0 justify-content-center pb-0">
                <div className="form-header modal-header-title text-center mb-0">
                  <h4 className="mb-2">Delete Product / Services</h4>
                  <p>Are you sure want to delete?</p>
                </div>
              </div>
              <div className="modal-body">
                <div className="modal-btn delete-action">
                  <div className="row">
                    <div className="col-6">
                      <Link
                        to="#"
                        data-bs-dismiss="modal"
                        className="btn btn-primary paid-continue-btn"
                      >
                        Delete
                      </Link>
                    </div>
                    <div className="col-6">
                      <Link
                        to="#"
                        data-bs-dismiss="modal"
                        className="btn btn-primary paid-cancel-btn"
                      >
                        Cancel
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* /Delete Items Modal */}

        {/* Add Bank Details Modal */}
        <div
          className="modal custom-modal fade"
          id="bank_details"
          role="dialog"
        >
          <div className="modal-dialog modal-dialog-centered modal-md">
            <div className="modal-content">
              <div className="modal-header border-0 pb-0">
                <div className="form-header modal-header-title text-start mb-0">
                  <h4 className="mb-0">Add Bank Details</h4>
                </div>
                <button
                  type="button"
                  className="close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <span className="align-center" aria-hidden="true">
                    ×
                  </span>
                </button>
              </div>
              <div className="modal-body">
                <div className="row">
                  <div className="col-lg-12 col-md-12">
                    <div className="form-group">
                      <label>
                        Bank Name <span className="text-danger">*</span>
                      </label>
                      <input
                        type="text"
                        className="form-control"
                        placeholder="Enter Bank Name"
                      />
                    </div>
                  </div>
                  <div className="col-lg-12 col-md-12">
                    <div className="form-group">
                      <label>
                        Account Number <span className="text-danger">*</span>
                      </label>
                      <input
                        type="number"
                        className="form-control"
                        placeholder="Enter Account Number"
                      />
                    </div>
                  </div>
                  <div className="col-lg-12 col-md-12">
                    <div className="form-group">
                      <label>
                        Branch Name <span className="text-danger">*</span>
                      </label>
                      <input
                        type="text"
                        className="form-control"
                        placeholder="Enter Branch Name"
                      />
                    </div>
                  </div>
                  <div className="col-lg-12 col-md-12">
                    <div className="form-group mb-0">
                      <label>
                        IFSC Code <span className="text-danger">*</span>
                      </label>
                      <input
                        type="number"
                        className="form-control"
                        placeholder="Enter IFSC COde"
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div className="modal-footer">
                <Link
                  to="#"
                  data-bs-dismiss="modal"
                  className="btn btn-primary paid-cancel-btn ms-2"
                >
                  Back
                </Link>
                <Link
                  to="#"
                  data-bs-dismiss="modal"
                  className="btn btn-primary paid-continue-btn"
                >
                  Save
                </Link>
              </div>
            </div>
          </div>
        </div>
        {/* /Add Bank Details Modal */}
      </div>
    </>
  );
};
export default AddInvoice;
