// kanakku-v1.9.9/angular-files/template-rtl/src/app/feature-module/ticket-pages/tickets-list-draft/tickets-list-draft.component.ts
import { Component } from '@angular/core';
import { routes } from 'src/app/core/core.index';

@Component({
  selector: 'app-tickets-list-draft',
  templateUrl: './tickets-list-draft.component.html',
  styleUrls: ['./tickets-list-draft.component.scss']
})
export class TicketsListDraftComponent {
  public routes = routes;
  country = 'India';
}

    
<!-- Page Header -->
<div class="page-header">
    <div class="content-page-header">
        <h5>Tickets</h5>
        <div class="list-btn">
            <ul class="filter-list">
                <li>
                    <div class="short-filter">
                        <img class="me-2" src="assets/img/icons/sort.svg" alt="Sort by select">
                        <div class="sort-by">
                            <select class="sort">
                            <option>Sort by: Date</option>
                            <option>Sort by: Date 1</option>
                            <option>Sort by: Date 2</option>
                            </select>
                        </div>
                    </div>
                </li>
                <li>
                    <a class="btn btn-filters w-auto popup-toggle"><span class="me-2"><i class="feather icon-filter"></i></span>Filter </a>
                </li>
                <li>
                    <a class="btn-filters" href="javascript:void(0);"><span><i class="feather icon-settings"></i></span> </a>
                </li>
                <li>
                    <a class="btn-filters" href="javascript:void(0);"><span><i class="feather icon-grid"></i></span> </a>
                </li>
                <li>
                    <a class="active btn-filters" href="javascript:void(0);"><span><i class="feather icon-list"></i></span> </a>
                </li>
                <li>
                    <a class="btn btn-primary" href="javascript:void(0);" data-bs-toggle="modal" data-bs-target="#add_ticket"><i class="fa fa-plus-circle me-2" aria-hidden="true"></i>New Tickets</a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- /Page Header -->
    
<!-- Search Filter -->
<div id="filter_inputs" class="card filter-card">
    <div class="card-body pb-0">
        <div class="row">
            <div class="col-sm-6 col-md-3">
                <div class="form-group">
                    <label htmlFor="label">Name</label>
                    <input id="label" type="text" class="form-control">
                </div>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="form-group">
                    <label htmlFor="label">Email</label>
                    <input id="label" type="text" class="form-control">
                </div>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="form-group">
                    <label htmlFor="label">Phone</label>
                    <input id="label" type="text" class="form-control">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Search Filter -->

<!-- Inovices card -->
<div class="row">
    <div class="col-xl-2 col-lg-4 col-sm-6 col-12">
        <div class="card inovices-card">
            <div class="card-body">
                <div class="dash-widget-header mb-0">
                    <span class="inovices-widget-icon rounded-circle bg-info-light">
                        <img src="assets/img/icons/receipt-item.svg"alt="image">
                    </span>
                    <div class="dash-count">
                        <div class="dash-title">Total Tickets</div>
                        <div class="dash-counts">
                            <p class="mb-0">$298</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-2 col-lg-4 col-sm-6 col-12">
        <div class="card inovices-card">
            <div class="card-body">
                <div class="dash-widget-header mb-0">
                    <span class="inovices-widget-icon rounded-circle bg-primary-light">
                        <img src="assets/img/icons/transaction-minus.svg"alt="image">
                    </span>
                    <div class="dash-count">
                        <div class="dash-title">Completed</div>
                        <div class="dash-counts">
                            <p class="mb-0">$325,215</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-2 col-lg-4 col-sm-6 col-12">
        <div class="card inovices-card">
            <div class="card-body">
                <div class="dash-widget-header mb-0">
                    <span class="inovices-widget-icon rounded-circle bg-warning-light">
                        <img src="assets/img/icons/archive-book.svg"alt="image">
                    </span>
                    <div class="dash-count">
                        <div class="dash-title">In Progress</div>
                        <div class="dash-counts">
                            <p class="mb-0">$7825</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-2 col-lg-4 col-sm-6 col-12">
        <div class="card inovices-card">
            <div class="card-body">
                <div class="dash-widget-header mb-0">
                    <span class="inovices-widget-icon rounded-circle bg-primary-light">
                        <img src="assets/img/icons/clipboard-close.svg"alt="image">
                    </span>
                    <div class="dash-count">
                        <div class="dash-title">Unassigned</div>
                        <div class="dash-counts">
                            <p class="mb-0">100</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-2 col-lg-4 col-sm-6 col-12">
        <div class="card inovices-card">
            <div class="card-body">
                <div class="dash-widget-header mb-0">
                    <span class="inovices-widget-icon rounded-circle bg-green-light">
                        <img src="assets/img/icons/message-edit.svg"alt="image">
                    </span>
                    <div class="dash-count">
                        <div class="dash-title">New</div>
                        <div class="dash-counts">
                            <p class="mb-0">$125,586</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-2 col-lg-4 col-sm-6 col-12">
        <div class="card inovices-card">
            <div class="card-body">
                <div class="dash-widget-header mb-0">
                    <span class="inovices-widget-icon rounded-circle bg-danger-light">
                        <img src="assets/img/icons/3d-rotate.svg"alt="image">
                    </span>
                    <div class="dash-count">
                        <div class="dash-title">Hold Tickets</div>
                        <div class="dash-counts">
                            <p class="mb-0">$86,892</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /Inovices card -->

<!-- All Invoice -->
<div class="card invoices-tabs-card">
    <div class="invoices-main-tabs">
        <div class="row align-items-center">
            <div class="col-lg-12">
                <div class="invoices-tabs">
                    <ul>
                        <li><a [routerLink]="routes.ticketskanban">All</a></li>
                        <li><a [routerLink]="routes.ticketslistpending">Pending</a></li>	
                        <li><a [routerLink]="routes.ticketslistoverdue">Overdue</a></li>		
                        <li><a [routerLink]="routes.ticketslistdraft" class="active">Draft</a></li>	
                        <li><a [routerLink]="routes.ticketslistrecurring">Recurring</a></li>
                        <li><a [routerLink]="routes.ticketslistcancelled">Cancelled</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /All Invoice -->

<!-- Ticket list -->
<div class="comments">
    <!-- card -->
    <div class="card">
        <div class="card-body card-support">
            <div class="comments-details d-flex align-items-center justify-content-between">
                <div class="d-flex align-items-center describe-btn mt-0">
                    <h6 class="fw-bolder text-gray-dark">Support for theme</h6><span class="badge badge-pill bg-success-light ms-3">Draft</span>
                </div>
                <a href="javascript:void(0);" class="reply-comment d-flex text-gray-light"><span><i class="fe fe-clock text-gray-light fw-normal me-2"></i></span><span class="text-gray-light fw-normal">Just Now</span></a>
            </div>
            <div class="card-describe">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incididunt labore dolore magna aliqua. Ut enim minim veniam, nostrud exercitation ullamco laboris nisi ut aliquip ex commodo consequat. Duis aute non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
            <div class="describe-btn">
                <span class="badge bg-warning-light text-warning-light me-2">Medium</span>
                <span class="badge badge-gray-outline me-2">#4987</span>
                <span><i class="fe fe-message-square text-gray-light fw-normal me-2"></i>3</span>
            </div>
        </div>
    </div>
    <!-- /card -->

    <!-- card -->
    <div class="card">
        <div class="card-body card-support">
            <div class="comments-details d-flex align-items-center justify-content-between">
                <div class="d-flex align-items-center describe-btn mt-0">
                    <h6 class="fw-bolder text-gray-dark">Verify your email</h6><span class="badge badge-pill bg-success-light ms-3">Draft</span>
                </div>
                <a href="javascript:void(0);" class="reply-comment d-flex text-gray-light"><span><i class="fe fe-clock text-gray-light fw-normal me-2"></i></span><span class="text-gray-light fw-normal">Just Now</span></a>
            </div>
            <div class="card-describe">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incididunt labore dolore magna aliqua. Ut enim minim veniam, nostrud exercitation ullamco laboris nisi ut aliquip ex commodo consequat. Duis aute non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
            <div class="describe-btn">
                <span class="badge bg-danger-light text-danger-light me-2">High</span>
                <span class="badge badge-gray-outline me-2">#4987</span>
                <span><i class="fe fe-message-square text-gray-light fw-normal me-2"></i>3</span>
            </div>
        </div>
    </div>
    <!-- /card -->

    <!-- card -->
    <div class="card">
        <div class="card-body card-support">
            <div class="comments-details d-flex align-items-center justify-content-between">
                <div class="d-flex align-items-center describe-btn mt-0">
                    <h6 class="fw-bolder text-gray-dark">Calling for help</h6><span class="badge badge-pill bg-success-light ms-3">Draft</span>
                </div>
                <a href="javascript:void(0);" class="reply-comment d-flex text-gray-light"><span><i class="fe fe-clock text-gray-light fw-normal me-2"></i></span><span class="text-gray-light fw-normal">Just Now</span></a>
            </div>
            <div class="card-describe">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incididunt labore dolore magna aliqua. Ut enim minim veniam, nostrud exercitation ullamco laboris nisi ut aliquip ex commodo consequat. Duis aute non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
            <div class="describe-btn">
                <span class="badge bg-primary-light me-2">Low</span>
                <span class="badge badge-gray-outline me-2">#4987</span>
                <span><i class="fe fe-message-square text-gray-light fw-normal me-2"></i>3</span>
            </div>
        </div>
    </div>
    <!-- /card -->

    <!-- card -->
    <div class="card">
        <div class="card-body card-support">
            <div class="comments-details d-flex align-items-center justify-content-between">
                <div class="d-flex align-items-center describe-btn mt-0">
                    <h6 class="fw-bolder text-gray-dark">Management</h6><span class="badge badge-pill bg-success-light ms-3">Draft</span>
                </div>
                <a href="javascript:void(0);" class="reply-comment d-flex text-gray-light"><span><i class="fe fe-clock text-gray-light fw-normal me-2"></i></span><span class="text-gray-light fw-normal">Just Now</span></a>
            </div>
            <div class="card-describe">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incididunt labore dolore magna aliqua. Ut enim minim veniam, nostrud exercitation ullamco laboris nisi ut aliquip ex commodo consequat. Duis aute non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
            <div class="describe-btn">
                <span class="badge bg-warning-light text-warning-light me-2">Low</span>
                <span class="badge badge-gray-outline me-2">#4987</span>
                <span><i class="fe fe-message-square text-gray-light fw-normal me-2"></i>3</span>
            </div>
        </div>
    </div>
    <!-- /card -->

</div>
<!-- /Ticket list -->

// kanakku-v1.9.9/vuejs-files/template/src/views/pages/support/ticket/tickets-list-draft.vue
<template>
  <!-- Main Wrapper -->
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>

    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <ticketheader :title="title" />
        <filter />
        <card />
        <tab />
        <!-- Ticket list -->
        <div class="comments">
          <!-- card -->
          <div class="card">
            <div class="card-body card-support">
              <div
                class="comments-details d-flex align-items-center justify-content-between"
              >
                <div class="d-flex align-items-center describe-btn mt-0">
                  <h6 class="fw-bolder text-gray-dark">Support for theme</h6>
                  <span class="badge badge-pill bg-success-light ms-3">Draft</span>
                </div>
                <a href="javascript:;" class="reply-comment d-flex text-gray-light"
                  ><span
                    ><i
                      class="feather feather-clock text-gray-light fw-normal me-2"
                    ></i></span
                  ><span class="text-gray-light fw-normal">Just Now</span></a
                >
              </div>
              <div class="card-describe">
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod
                  tempor incididunt labore dolore magna aliqua. Ut enim minim veniam,
                  nostrud exercitation ullamco laboris nisi ut aliquip ex commodo
                  consequat. Duis aute non proident, sunt in culpa qui officia deserunt
                  mollit anim id est laborum.
                </p>
              </div>
              <div class="describe-btn">
                <span class="badge bg-warning-light text-warning-light me-2">Medium</span>
                <span class="badge badge-gray-outline me-2">#4987</span>
                <span
                  ><i
                    class="feather feather-message-square text-gray-light fw-normal me-2"
                  ></i
                  >3</span
                >
              </div>
            </div>
          </div>
          <!-- /card -->

          <!-- card -->
          <div class="card">
            <div class="card-body card-support">
              <div
                class="comments-details d-flex align-items-center justify-content-between"
              >
                <div class="d-flex align-items-center describe-btn mt-0">
                  <h6 class="fw-bolder text-gray-dark">Verify your email</h6>
                  <span class="badge badge-pill bg-success-light ms-3">Draft</span>
                </div>
                <a href="javascript:;" class="reply-comment d-flex text-gray-light"
                  ><span
                    ><i
                      class="feather feather-clock text-gray-light fw-normal me-2"
                    ></i></span
                  ><span class="text-gray-light fw-normal">Just Now</span></a
                >
              </div>
              <div class="card-describe">
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod
                  tempor incididunt labore dolore magna aliqua. Ut enim minim veniam,
                  nostrud exercitation ullamco laboris nisi ut aliquip ex commodo
                  consequat. Duis aute non proident, sunt in culpa qui officia deserunt
                  mollit anim id est laborum.
                </p>
              </div>
              <div class="describe-btn">
                <span class="badge bg-danger-light text-danger-light me-2">High</span>
                <span class="badge badge-gray-outline me-2">#4987</span>
                <span
                  ><i
                    class="feather feather-message-square text-gray-light fw-normal me-2"
                  ></i
                  >3</span
                >
              </div>
            </div>
          </div>
          <!-- /card -->

          <!-- card -->
          <div class="card">
            <div class="card-body card-support">
              <div
                class="comments-details d-flex align-items-center justify-content-between"
              >
                <div class="d-flex align-items-center describe-btn mt-0">
                  <h6 class="fw-bolder text-gray-dark">Calling for help</h6>
                  <span class="badge badge-pill bg-success-light ms-3">Draft</span>
                </div>
                <a href="javascript:;" class="reply-comment d-flex text-gray-light"
                  ><span
                    ><i
                      class="feather feather-clock text-gray-light fw-normal me-2"
                    ></i></span
                  ><span class="text-gray-light fw-normal">Just Now</span></a
                >
              </div>
              <div class="card-describe">
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod
                  tempor incididunt labore dolore magna aliqua. Ut enim minim veniam,
                  nostrud exercitation ullamco laboris nisi ut aliquip ex commodo
                  consequat. Duis aute non proident, sunt in culpa qui officia deserunt
                  mollit anim id est laborum.
                </p>
              </div>
              <div class="describe-btn">
                <span class="badge bg-primary-light me-2">Low</span>
                <span class="badge badge-gray-outline me-2">#4987</span>
                <span
                  ><i
                    class="feather feather-message-square text-gray-light fw-normal me-2"
                  ></i
                  >3</span
                >
              </div>
            </div>
          </div>
          <!-- /card -->

          <!-- card -->
          <div class="card">
            <div class="card-body card-support">
              <div
                class="comments-details d-flex align-items-center justify-content-between"
              >
                <div class="d-flex align-items-center describe-btn mt-0">
                  <h6 class="fw-bolder text-gray-dark">Management</h6>
                  <span class="badge badge-pill bg-success-light ms-3">Draft</span>
                </div>
                <a href="javascript:;" class="reply-comment d-flex text-gray-light"
                  ><span
                    ><i
                      class="feather feather-clock text-gray-light fw-normal me-2"
                    ></i></span
                  ><span class="text-gray-light fw-normal">Just Now</span></a
                >
              </div>
              <div class="card-describe">
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod
                  tempor incididunt labore dolore magna aliqua. Ut enim minim veniam,
                  nostrud exercitation ullamco laboris nisi ut aliquip ex commodo
                  consequat. Duis aute non proident, sunt in culpa qui officia deserunt
                  mollit anim id est laborum.
                </p>
              </div>
              <div class="describe-btn">
                <span class="badge bg-warning-light text-warning-light me-2">Low</span>
                <span class="badge badge-gray-outline me-2">#4987</span>
                <span
                  ><i
                    class="feather feather-message-square text-gray-light fw-normal me-2"
                  ></i
                  >3</span
                >
              </div>
            </div>
          </div>
          <!-- /card -->
        </div>
        <!-- /Ticket list -->
      </div>
    </div>
    <!-- /Page Wrapper -->
    <ticketmodal></ticketmodal>
  </div>
  <!-- /Main Wrapper -->
</template>
<script>
export default {
  setup() {
    return {
      title: "Tickets",
    };
  },
};
</script>
