// kanakku-v1.9.9/angular-files/template/src/app/feature-module/credit-note-pages/add-credit-notes/add-credit-notes.component.ts
import { Component, OnInit } from '@angular/core';
import { Sort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { DataService, routes } from 'src/app/core/core.index';
import { apiResultFormat, editcreditnotes, pageSelection } from 'src/app/core/models/models';

@Component({
  selector: 'app-add-credit-notes',
  templateUrl: './add-credit-notes.component.html',
  styleUrls: ['./add-credit-notes.component.scss']
})
export class AddCreditNotesComponent implements OnInit {
  
  public editcreditnotes: Array<editcreditnotes> = [];
  public routes = routes
  country = 'India';
  products='select';
  discount='discount1'
  customer='customers'
  tax='tax1'
  selectbank='bank1'
  public Toggledata  = false;
  dataSource!: MatTableDataSource<editcreditnotes>;
  public searchDataValue = '';
  // pagination variables
  public lastIndex = 0;
  public pageSize = 10;
  public totalData = 0;
  public skip = 0;
  public limit: number = this.pageSize;
  public pageIndex = 0;
  public serialNumberArray: Array<number> = [];
  public currentPage = 1;
  public pageNumberArray: Array<number> = [];
  public pageSelection: Array<pageSelection> = [];
  public totalPages = 0;
  //** / pagination variables
  

  constructor(private data: DataService) {}

  ngOnInit(): void {
    this.getTableData();
  }
  private getTableData(): void {
    this.editcreditnotes = [];
    this.serialNumberArray = [];

    this.data.getEditcreditnotes().subscribe((data: apiResultFormat) => {
      this.totalData = data.totalData;
      data.data.map((res:editcreditnotes, index: number) => {
        const serialNumber = index + 1;
        if (index >= this.skip && serialNumber <= this.limit) {
          res.editcreditnotes= serialNumber;
          this.editcreditnotes.push(res);
          this.serialNumberArray.push(serialNumber);
        }
      });
      this.dataSource = new MatTableDataSource<editcreditnotes>(this.editcreditnotes);
      this.calculateTotalPages(this.totalData, this.pageSize);
    });
  }
 
  
  
  public sortData(sort: Sort) {
    const data = this.editcreditnotes.slice();

    if (!sort.active || sort.direction === '') {
      this.editcreditnotes = data;
    } else {
      this.editcreditnotes= data.sort((a, b) => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const aValue = (a as any)[sort.active];
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const bValue = (b as any)[sort.active];
        return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
      });
    }
  }
  public getMoreData(event: string): void {
    if (event == 'next') {
      this.currentPage++;
      this.pageIndex = this.currentPage - 1;
      this.limit += this.pageSize;
      this.skip = this.pageSize * this.pageIndex;
      this.getTableData();
    } else if (event == 'previous') {
      this.currentPage--;
      this.pageIndex = this.currentPage - 1;
      this.limit -= this.pageSize;
      this.skip = this.pageSize * this.pageIndex;
      this.getTableData();
    }
  }
  public moveToPage(pageNumber: number): void {
    this.currentPage = pageNumber;
    this.skip = this.pageSelection[pageNumber - 1].skip;
    this.limit = this.pageSelection[pageNumber - 1].limit;
    if (pageNumber > this.currentPage) {
      this.pageIndex = pageNumber - 1;
    } else if (pageNumber < this.currentPage) {
      this.pageIndex = pageNumber + 1;
    }
    this.getTableData();
  }
  public PageSize(): void {
    this.pageSelection = [];
    this.limit = this.pageSize;
    this.skip = 0;
    this.currentPage = 1;
    this.getTableData();
  }
  private calculateTotalPages(totalData: number, pageSize: number): void {
    this.pageNumberArray = [];
    this.totalPages = totalData / pageSize;
    if (this.totalPages % 1 != 0) {
      this.totalPages = Math.trunc(this.totalPages + 1);
    }
    for (let i = 1; i <= this.totalPages; i++) {
      const limit = pageSize * i;
      const skip = limit - pageSize;
      this.pageNumberArray.push(i);
      this.pageSelection.push({ skip: skip, limit: limit });
    }
  }
  open() {
    this.Toggledata = !this.Toggledata;
   
  }
  files: File[] = [];
  onSelect(event: { addedFiles: File[] }) {
    this.files.push(...event.addedFiles);
  }
  onRemove(event:File) {
   this.files.splice(this.files.indexOf(event), 1);
   
  }
  myDateValue!: Date;
   public minDate!: Date;
   public maxDate!: Date;
  

}

<div class="card mb-0">
  <div class="card-body">
    <div class="page-header">
      <div class="content-page-header">
        <h5>Add Credit Note</h5>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="cards">
          
          <div class="form-group-item border-0 mb-0">
            <div class="row align-item-center">
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                    <label htmlFor="label">Credit Notes Id</label>
                  <input id="label"
                    type="text"
                    class="form-control"
                    placeholder="Enter Credit Note ID Name"
                  />
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                    <label htmlFor="label">Select Customer</label>
                  <ul class="form-group-plus css-equal-heights">
                    <li>
                      <mat-select
                        [(ngModel)]="customer"
                        [ngModelOptions]="{ standalone: true }"
                        class="select mat-cust-select form-control"
                      >
                        <mat-option value="customers">Choose Customer</mat-option>
                        <mat-option value="customer1">Customer 1</mat-option>
                        <mat-option value="customer2">Customer 2</mat-option>
                        <mat-option value="customer3">Customer 3</mat-option>
                      </mat-select>
                    </li>
                    <li>
                      <a
                        class="btn btn-primary form-plus-btn"
                        [routerLink]="routes.addCustomer"
                      >
                        <i class="feather icon-plus-circle"></i>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                    <label htmlFor="label">Credit Note Date</label>
                  <input 
                  
                    type="email"
                    class="form-control datetimepicker"
                    placeholder="Select Date"
                    [maxDate]="maxDate"
                    #dp="bsDatepicker"
                    bsDatepicker [(bsValue)]="myDateValue">
                 
                 
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                    <label htmlFor="label">Due Date</label>
                  <input 
                   
                   
                    type="email"
                    class="form-control datetimepicker"
                    placeholder="Select Date" 
                    [minDate]="minDate"
                      [maxDate]="maxDate"
                      #dp="bsDatepicker"
                      bsDatepicker [(bsValue)]="myDateValue"
                    
                  />
                 
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                    <label htmlFor="label">Reference No</label>
                  <input id="label"
                    type="text"
                    class="form-control"
                    placeholder="Enter Phone Number"
                  />
                </div>
              </div>
              
              <div class="col-lg-12">
                <div class="input-block mb-3">
                    <label htmlFor="label">Products</label>
                  <ul class="form-group-plus css-equal-heights">
                    <li>
                      <mat-select
                        [(ngModel)]="products"
                        [ngModelOptions]="{ standalone: true }"
                        class="select mat-cust-select form-control"
                      >
                        <mat-option value="select">Select Product</mat-option>
                        <mat-option value="Product 1">Product 1</mat-option>
                        <mat-option value="Product 2">Product 2</mat-option>
                        <mat-option value="customer3">Product 3</mat-option>
                      </mat-select>
                    </li>
                    <li>
                      <a
                        class="btn btn-primary form-plus-btn"
                        [routerLink]="routes.addproducts"
                      >
                        <i class="feather icon-plus-circle"></i>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="form-group-item">
            <div class="card-table">
              <div class="card-body">
                <div class="table-responsive">
                  <table
                    matSort
                    (matSortChange)="sortData($event)"
                    class="table table-center table-hover datatable"
                  >
                    <thead class="thead-light">
                      <tr>
                        <th mat-sort-header="product">Product / Service</th>
                        <th mat-sort-header="quantity">Quantity</th>
                        <th mat-sort-header="unit">Unit</th>
                        <th mat-sort-header="rate">Rate</th>
                        <th mat-sort-header="discount">Discount</th>
                        <th mat-sort-header="tax">Tax</th>
                        <th mat-sort-header="amount">Amount</th>
                        <th mat-sort-header="action">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr *ngFor="let data of editcreditnotes; let i = index">
                        <td>{{ data.product }}</td>
                        <td><input type="number" class="form-control" placeholder="120"></td>
                        <td>{{ data.unit }}</td>
                        <td><input type="number" class="form-control" placeholder="120"></td>
                        <td>{{ data.discount }}</td>
                        <td>{{ data.tax }}</td>
                        <td>{{ data.amount }}</td>
                        <td class="d-flex align-items-center">
                          <a
                            href="#"
                            class="btn-action-icon me-2"
                            data-bs-toggle="modal"
                            data-bs-target="#add_discount"
                            ><span><i class="feather icon-edit"></i></span
                          ></a>
                          <a
                            href="#"
                            class="btn-action-icon"
                            data-bs-toggle="modal"
                            data-bs-target="#delete_discount"
                            ><span><i class="feather icon-trash-2"></i></span
                          ></a>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                  
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4">
              <div class="row">
                <div class="col-lg-7">
                  <div class="input-block mb-3">
                    <label>Discount Type</label>
                    <mat-select
                        [(ngModel)]="discount"
                        [ngModelOptions]="{ standalone: true }"
                        class="select mat-cust-select form-control"
                      >
                        <mat-option value="discount1">Percentage(%)</mat-option>
                        <mat-option value="discount2">Fixed</mat-option>
                    
                      </mat-select>
                  </div>
                </div>
                <div class="col-lg-5">
                  <div class="input-block mb-3">
                    <label>Discount(%)</label>
                    <input
                      type="text"
                      class="form-control"
                      placeholder="10"
                    />
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="input-block mb-3">
                <label>Tax</label>
                <mat-select
                [(ngModel)]="tax"
                [ngModelOptions]="{ standalone: true }"
                class="select mat-cust-select form-control"
              >
                <mat-option value="tax1">No Tax</mat-option>
                <mat-option value="tax2">IVA - (21%)</mat-option>
                <mat-option value="tax3">IVA - (21%)</mat-option>
                <mat-option value="tax4">IVA - (21%)</mat-option>
                
            
              </mat-select>
              </div>
            </div>
          </div>
          <div class="form-group-item border-0 p-0">
            <div class="row">
              <div class="col-xl-6 col-lg-12">
                <div class="form-group-bank">
                  <div class="row align-items-center">
                    <div class="col-md-8">
                      <div class="input-block mb-3">
                        <label >Select Bank</label>
                        <mat-select
                        [(ngModel)]="selectbank"
                        [ngModelOptions]="{ standalone: true }"
                        class="select mat-cust-select form-control"
                      >
                        <mat-option value="bank1">Select Bank</mat-option>
                        <mat-option value="Ban">SBI</mat-option>
                        <mat-option value="Ban">IOB</mat-option>
                        <mat-option value="Ban">Canara</mat-option>
                        
                    
                      </mat-select>
                      </div>
                    </div>
                    <div class="col-md-4">
                      <div class="form-groups">
                        <a
                          class="btn btn-primary"
                          href="#"
                          data-bs-toggle="modal"
                          data-bs-target="#bank_details"
                          >Add Bank</a
                        >
                      </div>
                    </div>
                  </div>
    
                  <div class="input-block mb-3 notes-form-group-info">
                    <label>Notes</label>
                    <textarea
                      class="form-control"
                      placeholder="Enter Notes"
                    ></textarea>
                  </div>
                  <div class="input-block mb-3 notes-form-group-info mb-0">
                    <label>Terms and Conditions</label>
                    <textarea
                      class="form-control"
                      placeholder="Enter Terms and Conditions"
                    ></textarea>
                  </div>
                </div>
              </div>
              <div class="col-xl-6 col-lg-12">
                <div class="form-group-bank">
                  <div class="invoice-total-box">
                    <div class="invoice-total-inner">
                      <p>Taxable Amount <span>$120.00</span></p>
                      <p>Discount <span>$13.20</span></p>
                      <p>Vat <span>$0.00</span></p>
                      <div
                        class="status-toggle justify-content-between"
                      >
                        <div class="d-flex align-center">
                          <p>Round Off</p>
                          <input
                            id="rating_1"
                            class="check"
                            type="checkbox"
                            checked=""
                          />
                          <label
                            for="rating_1"
                            class="checktoggle checkbox-bg"
                            >checkbox</label
                          >
                        </div>
                        <span>$0.00</span>
                      </div>
                    </div>
                    <div class="invoice-total-footer">
                      <h4>Total Amount <span>$107.80</span></h4>
                    </div>
                  </div>
                  <div class="input-block mb-3">
                    <label>Signature Name</label>
                    <input
                      type="text"
                      class="form-control"
                      placeholder="Enter Signature Name"
                    />
                  </div>
                  <div class="col-md-12">
                    <div class="input-block mb-3 mb-0 pb-0">
                      <label>Signature Image</label>
                      <ngx-dropzone
                        (change)="onSelect($event)"
                        class="service-upload add-credit"
                      >
                        <ngx-dropzone-label class="drop-browse align-center">
                          <span><i class="feather icon-upload-cloud me-2"></i>Upload Signature</span>
                        </ngx-dropzone-label>
                        <ngx-dropzone-image-preview
                          ngProjectAs="ngx-dropzone-preview"
                          *ngFor="let f of files"
                          [file]="f"
                          [removable]="true"
                          (removed)="onRemove(f)"
                        >
                        </ngx-dropzone-image-preview>
                      </ngx-dropzone>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="add-customer-btns text-end">
            <a  [routerLink]="routes.editcreditnotes" class="btn customer-btn-cancel"
              >Cancel</a
            >
            <a  [routerLink]="routes.editcreditnotes" class="btn customer-btn-save"
              >Save</a
            >
          </div>
          
        </div>
      </div>
      <!-- Add Tax & Discount Modal -->
  <div class="modal custom-modal fade" id="add_discount" role="dialog">
  <div class="modal-dialog modal-dialog-centered modal-md">
    <div class="modal-content">
      <div class="modal-header border-0 pb-0">
        <div class="form-header modal-header-title text-start mb-0 align-center">
          <h4 class="mb-0">Add Tax & Discount</h4>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="input-block mb-3">
              <label>Rate</label>
              <input type="number" class="form-control" placeholder="120">
            </div>
          </div>
          <div class="col-lg-12 col-md-12">
            <div class="input-block mb-3">
              <label>Discount Amount</label>
              <input type="number" class="form-control" placeholder="0">
            </div>
          </div>
          <div class="col-lg-12 col-md-12">
            <div class="input-block mb-0">
              <label>Tax</label>
              <mat-select
              [(ngModel)]="tax"
              [ngModelOptions]="{ standalone: true }"
              class="select mat-cust-select form-control"
            >
              <mat-option value="tax">No Tax</mat-option>
              <mat-option value="customer1">IVA - (21%)</mat-option>
              <mat-option value="customer2">IRPF - (-15%)</mat-option>
              <mat-option value="customer2">PDV - (20%)</mat-option>
            </mat-select>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer add-tax-btns">
        <button type="reset" data-bs-dismiss="modal" class="btn btn-back cancel-btn me-2">Cancel</button>
        <button type="submit" data-bs-dismiss="modal" class="btn btn-primary paid-continue-btn">Save</button>
      </div>
    </div>
  </div>
</div>
<!-- /Add Tax & Discount Modal -->
    
      <!-- Delete Items Modal -->
      <div class="modal custom-modal fade" id="delete_discount" role="dialog">
        <div class="modal-dialog modal-dialog-centered modal-md">
          <div class="modal-content">
            <div class="modal-header border-0 justify-content-center pb-0">
              <div class="form-header modal-header-title text-center mb-0">
                <h4 class="mb-2">Delete Product / Services</h4>
                <p>Are you sure want to delete?</p>
              </div>
            </div>
            <div class="modal-body">
              <div class="modal-btn delete-action">
                <div class="row">
                  <div class="col-6">
                    <a
                      href="#"
                      data-bs-dismiss="modal"
                      class="btn btn-primary paid-continue-btn"
                      >Delete</a
                    >
                  </div>
                  <div class="col-6">
                    <a
                      href="#"
                      data-bs-dismiss="modal"
                      class="btn btn-primary paid-cancel-btn"
                      >Cancel</a
                    >
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /Delete Items Modal -->
    
     <!-- Add Bank Details Modal -->
			<div class="modal custom-modal fade" id="bank_details" role="dialog">
				<div class="modal-dialog modal-dialog-centered modal-md">
					<div class="modal-content">
						<div class="modal-header border-0 pb-0">
							<div class="form-header modal-header-title text-start mb-0">
								<h4 class="mb-0">Add Bank Details</h4>
							</div>
							<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
								
							</button>
						</div>
						<div class="modal-body">
							<div class="row">
								<div class="col-lg-12 col-md-12">
									<div class="input-block mb-3">
										<label>Bank Name <span class="text-danger">*</span></label>
										<input type="text" class="form-control" placeholder="Enter Bank Name">
									</div>
								</div>
								<div class="col-lg-12 col-md-12">
									<div class="input-block mb-3">
										<label>Account Number <span class="text-danger">*</span></label>
										<input type="number" class="form-control" placeholder="Enter Account Number">
									</div>
								</div>
								<div class="col-lg-12 col-md-12">
									<div class="input-block mb-3">
										<label>Branch Name <span class="text-danger">*</span></label>
										<input type="text" class="form-control" placeholder="Enter Branch Name">
									</div>
								</div>
								<div class="col-lg-12 col-md-12">
									<div class="input-block mb-0">
										<label>IFSC Code <span class="text-danger">*</span></label>
										<input type="number" class="form-control" placeholder="Enter IFSC COde">
									</div>
								</div>
							</div>
						</div>
						<div class="modal-footer">
							<a href="#" data-bs-dismiss="modal" class="btn btn-back cancel-btn me-2">Back</a>
							<a href="#" data-bs-dismiss="modal" class="btn btn-primary paid-continue-btn">Save</a>
						</div>
					</div>
				</div>
			</div>
			<!-- /Add Bank Details Modal -->
    </div>
  </div>

</div>

// kanakku-v1.9.9/vuejs-files/template-rtl/src/views/pages/sales/creditnotes/add-credit-notes.vue
<template>
  <!-- Main Wrapper -->
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>
    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <componentheader :title="title" />
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-body">
                <div class="form-group-item border-0 mb-0">
                  <div class="row align-item-center">
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="form-group">
                        <label>Credit Notes Id</label>
                        <input
                          type="text"
                          class="form-control"
                          placeholder="Enter First Name"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="form-group">
                        <label>Select Customer</label>
                        <ul class="form-group-plus css-equal-heights">
                          <li>
                            <vue-select
                              :options="Customer"
                              placeholder="Choose Customer"
                            />
                          </li>
                          <li>
                            <router-link
                              class="btn btn-primary form-plus-btn"
                              to="add-customer"
                            >
                              <i class="feather feather-plus-circle"></i>
                            </router-link>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="form-group">
                        <label>Credit Note Date</label>
                        <div class="cal-icon">
                          <datepicker
                            v-model="startdate"
                            class="picker"
                            :editable="true"
                            :clearable="false"
                          />
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="form-group">
                        <label>Due Date</label>
                        <div class="cal-icon">
                          <datepicker
                            v-model="startdate"
                            class="picker"
                            :editable="true"
                            :clearable="false"
                          />
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="form-group">
                        <label>Reference No</label>
                        <input
                          type="text"
                          class="form-control"
                          placeholder="Enter Reference Number"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="form-group">
                        <label>Document Title</label>
                        <div class="mt-2">
                          <label class="custom_check me-3 mb-0">
                            <input type="checkbox" name="invoice" />
                            <span class="checkmark"></span> Invoice
                          </label>
                          <label class="custom_check mb-0">
                            <input type="checkbox" name="re_invoice" />
                            <span class="checkmark"></span> Bill of Supply
                          </label>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-12">
                      <div class="form-group">
                        <label>Products</label>
                        <ul class="form-group-plus css-equal-heights">
                          <li>
                            <vue-select :options="Product" placeholder="Select Product" />
                          </li>
                          <li>
                            <router-link
                              class="btn btn-primary form-plus-btn"
                              to="add-products"
                            >
                              <i class="feather feather-plus-circle"></i>
                            </router-link>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="form-group">
                        <label>Currency</label>
                        <vue-select :options="Currency" placeholder="Select Currency" />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="form-group">
                        <label>Website</label>
                        <input
                          type="text"
                          class="form-control"
                          placeholder="Enter Website Address"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="form-group">
                        <label>Notes</label>
                        <input
                          type="text"
                          class="form-control"
                          placeholder="Enter Your Notes"
                        />
                      </div>
                    </div>
                  </div>
                </div>
                <div class="form-group-item">
                  <div class="card-table">
                    <div class="card-body">
                      <div class="table-responsive">
                        <a-table
                          class="stripped table-hover"
                          :columns="columns"
                          :data-source="data"
                          @change="onChange"
                        >
                          <template #bodyCell="{ column, record }">
                            <template v-if="column.key === 'action'">
                              <a
                                href="javascript:;"
                                class="btn-action-icon me-2"
                                data-bs-toggle="modal"
                                data-bs-target="#add_discount"
                                ><span><i class="feather feather-edit"></i></span
                              ></a>
                              <a
                                href="javascript:;"
                                class="btn-action-icon"
                                data-bs-toggle="modal"
                                data-bs-target="#delete_discount"
                                ><span><i class="feather feather-trash-2"></i></span
                              ></a>
                            </template>
                          </template>
                        </a-table>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="form-group-item border-0 p-0">
                  <div class="row">
                    <div class="col-xl-6 col-lg-12">
                      <div class="form-group-bank">
                        <div class="form-group">
                          <label>Select Bank</label>
                          <div class="bank-details">
                            <a
                              class="text-danger-light"
                              href="javascript:;"
                              data-bs-toggle="modal"
                              data-bs-target="#bank_details"
                              ><i class="fas fa-bank me-2"></i>Add Bank Details</a
                            >
                          </div>
                        </div>
                        <div class="form-group notes-form-group-info">
                          <label>Notes</label>
                          <textarea
                            class="form-control"
                            placeholder="Enter Notes"
                          ></textarea>
                        </div>
                        <div class="form-group notes-form-group-info mb-0">
                          <label>Terms and Conditions</label>
                          <textarea
                            class="form-control"
                            placeholder="Enter Terms and Conditions"
                          ></textarea>
                        </div>
                      </div>
                    </div>
                    <div class="col-xl-6 col-lg-12">
                      <div class="form-group-bank">
                        <div class="row">
                          <div class="col-lg-4 col-md-12">
                            <div class="form-group">
                              <label>Discount Type</label>
                              <vue-select
                                :options="Percentage"
                                placeholder="Percentage(%)"
                              />
                            </div>
                          </div>
                          <div class="col-lg-4 col-md-12">
                            <div class="form-group">
                              <label>Discount (%)</label>
                              <input type="text" class="form-control" placeholder="10" />
                            </div>
                          </div>
                          <div class="col-lg-4 col-md-12">
                            <div class="form-group">
                              <label>Total discount</label>
                              <input
                                type="text"
                                class="bg-white-smoke form-control"
                                placeholder="13.2"
                              />
                            </div>
                          </div>
                        </div>
                        <div class="invoice-total-box">
                          <div class="invoice-total-inner">
                            <p>Taxable Amount <span>$120.00</span></p>
                            <p>Discount <span>$13.20</span></p>
                            <p>Vat <span>$0.00</span></p>
                            <div class="status-toggle justify-content-between">
                              <div class="d-flex align-center">
                                <p>Round Off</p>
                                <input
                                  id="rating_1"
                                  class="check"
                                  type="checkbox"
                                  checked=""
                                />
                                <label for="rating_1" class="checktoggle checkbox-bg"
                                  >checkbox</label
                                >
                              </div>
                              <span>$0.00</span>
                            </div>
                          </div>
                          <div class="invoice-total-footer">
                            <h4>Total Amount <span>$107.80</span></h4>
                          </div>
                        </div>
                        <div class="form-group">
                          <label>Signature Name</label>
                          <input
                            type="text"
                            class="form-control"
                            placeholder="Enter Signature Name"
                          />
                        </div>
                        <div class="form-group mb-0">
                          <label>Signature Image</label>
                          <div class="form-group service-upload service-upload-info mb-0">
                            <span
                              ><i class="feather feather-upload-cloud me-1"></i>Upload
                              Signature</span
                            >
                            <input type="file" multiple="" id="image_sign" />
                            <div id="frames"></div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="add-customer-btns text-end">
                  <b-button type="reset" variant="primary cancel me-2">Cancel</b-button>
                  <b-button type="submit" variant="primary">Save Changes</b-button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /Page Wrapper -->
    <pagemodal :banktitle="banktitle" />
  </div>
  <!-- /Main Wrapper -->
</template>
<script>
const columns = [
  {
    title: "Product / Service",
    dataIndex: "Product",
    sorter: {
      compare: (a, b) => {
        a = a.Product.toLowerCase();
        b = b.Product.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Quantity",
    dataIndex: "Quantity",
    sorter: (a, b) => a.Quantity.localeCompare(b.Quantity),
  },
  {
    title: "Unit",
    dataIndex: "Unit",
    sorter: (a, b) => a.Unit.localeCompare(b.Unit),
  },
  {
    title: "Rate",
    dataIndex: "Rate",
    sorter: {
      compare: (a, b) => {
        a = a.Rate.toLowerCase();
        b = b.Rate.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Discount",
    dataIndex: "Discount",
    sorter: {
      compare: (a, b) => {
        a = a.Discount.toLowerCase();
        b = b.Discount.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Tax",
    dataIndex: "Tax",
    sorter: {
      compare: (a, b) => {
        a = a.Tax.toLowerCase();
        b = b.Tax.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Amount",
    dataIndex: "Amount",
    sorter: {
      compare: (a, b) => {
        a = a.Amount.toLowerCase();
        b = b.Amount.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Action",
    key: "action",
    sorter: true,
  },
];
const data = [
  {
    Product: "Lorem ipsum dolor sit amet",
    Quantity: "0",
    Unit: "Pcs",
    Rate: "$120.00",
    Discount: "0",
    Tax: "0",
    Amount: "$120.00",
    Action: "",
  },
];
import { ref } from "vue";
const currentDate = ref(new Date());
export default {
  data() {
    return {
      startdate: currentDate,
      banktitle: "Add Bank Details",
      title: "Add Credit Note",
      Customer: ["Choose Customer", "Customer 1", "Customer 2", "Customer 3"],
      GST: ["Without GST", "With GST"],
      Product: ["Select Product", "Product 1", "Product 2", "Product 3"],
      Percentage: ["Percentage(%)", "0%", "5%", "10%", "15%"],
      Currency: ["Select Currency", "US dollar", "Euro", "Pound sterling", "Swiss franc"],
      data,
      columns,
    };
  },
  mounted() {
    document.addEventListener("DOMContentLoaded", function () {
      const imageSign = document.querySelector("#image_sign");
      imageSign.addEventListener("change", function () {
        const frames = document.querySelector("#frames");
        frames.innerHTML = "";
        for (let i = 0; i < this.files.length; i++) {
          const img = document.createElement("img");
          img.src = window.URL.createObjectURL(this.files[i]);
          img.width = "100";
          img.height = "100";
          frames.appendChild(img);
        }
      });
    });
  },
};
</script>
