// kanakku-v1.9.9/angular-files/template-rtl/src/app/feature-module/products-service/edit-products/edit-products.component.ts
import { Component } from '@angular/core';
import { AngularEditorConfig } from '@kolkov/angular-editor';
import { routes } from 'src/app/core/core.index';

@Component({
  selector: 'app-edit-products',
  templateUrl: './edit-products.component.html',
  styleUrls: ['./edit-products.component.scss']
})
export class EditProductsComponent {
  public routes = routes;
  files: File[] = [];
  Units='select units'
  Discount='select discount'
  Tax='select tax'

  config: AngularEditorConfig = {
    editable: true,
    spellcheck: true,
    sanitize: false,
    height: '15rem',
    minHeight: '5rem',
    placeholder: 'Enter text here...',
    translate: 'no',
    defaultParagraphSeparator: 'p',
    defaultFontName: 'Arial',
    toolbarHiddenButtons: [['bold']],
    customClasses: [
      {
        name: 'quote',
        class: 'quote',
      },
      {
        name: 'redText',
        class: 'redText',
      },
      {
        name: 'titleText',
        class: 'titleText',
        tag: 'h1',
      },
    ],
  };
  onSelect(event: { addedFiles: File[] }) {
    this.files.push(...event.addedFiles);
  }
  onRemove(event:File) {
   this.files.splice(this.files.indexOf(event), 1);
  }



}

<div class="card mb-0">
  <div class="card-body">
    <div class="content-page-header">
      <h5>Edit Products / Services</h5>
  </div>					
  <div class="row">
      <div class="col-md-12">
          <div class="card-body">
              <div class="form-group-item">
                  <h5 class="form-title">Basic Details</h5>
                  <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="form-group">
                        <label>Item Type<span class="text-danger">  *</span></label>
                        <div class="align-center">
                          <div class="form-control me-3">
                            <label class="custom_radio me-3 mb-0">
                              <input
                                type="radio"
                                class="form-control"
                                name="payment"
                                checked
                              />
                              <span class="checkmark"></span> Product
                            </label>
                          </div>
                          <div class="form-control">
                            <label class="custom_radio mb-0">
                              <input type="radio" name="payment" />
                              <span class="checkmark"></span> Service
                            </label>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="input-block mb-3">
                        <label>Product Name <span class="text-danger">  *</span></label>
                        <input
                          type="text"
                          class="form-control"
                          value="Lorem ipsum"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="input-block  add-products">
                        <label>Product Code (SKU)<span class="text-danger">  *</span></label>
                        <input
                          type="text"
                          class="form-control"
                          value="123"
                        />
                        <button type="submit" class="btn btn-primary">
                          Generate Code
                        </button>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="input-block mb-3">
                        <label>Category  <span class="text-danger">  *</span></label>
                        <input
                          type="text"
                          class="form-control"
                          value="Advertising"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="input-block mb-3">
                        <label>Selling Price  <span class="text-danger">  *</span></label>
                        <input
                          type="text"
                          class="form-control"
                          value="230"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="input-block mb-3">
                        <label>Purchase Price  <span class="text-danger">  *</span></label>
                        <input
                          type="text"
                          class="form-control"
                          value="230"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="input-block mb-3">
                        <label>Quantity <span class="text-danger">  *</span></label>
                        <input
                          type="number"
                          class="form-control"
                          value="5"
                          name="name"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="input-block mb-3">
                        <label>Units</label>
                        <mat-select [(ngModel)]="Units" [ngModelOptions]="{standalone: true}"class="select mat-cust-select form-control">
                          <mat-option value="select units">Select Units</mat-option>
                          <mat-option value="pieces">Pieces</mat-option>
                          <mat-option value="box">Box</mat-option>
                          <mat-option value="box">Kilograms</mat-option>
                          
                        </mat-select>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="input-block mb-3">
                        <label>Discount Type</label>
                        <mat-select [(ngModel)]="Discount" [ngModelOptions]="{standalone: true}"class="select mat-cust-select form-control">
                          <mat-option value="select discount">Select Discount Type</mat-option>
                          <mat-option value="percentage1">Percentage</mat-option>
                          <mat-option value="fixed">Fixed</mat-option>
                          
                        </mat-select>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="input-block  add-products">
                        <label>Generate Barcode</label>
                        <input
                          type="text"
                          class="form-control"
                          value=""
                        />
                        <button type="submit" class="btn btn-primary">
                          Generate Code
                        </button>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="input-block mb-3">
                        <label>Alert Quantity </label>
                        <input
                          type="number"
                          class="form-control"
                          value="5"
                          name="name"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12">
                      <div class="input-block mb-3">
                        <label>Tax</label>
                          <mat-select [(ngModel)]="Tax" [ngModelOptions]="{standalone: true}"class="select mat-cust-select form-control">
                          <mat-option value="select tax">Select Tax</mat-option>
                          <mat-option value="tax1">IVA - (21%)</mat-option>
                          <mat-option value="tax2">IRPF - (-15%)</mat-option>
                          <mat-option value="tax3">PDV - (20%)</mat-option>
      
                          
                        </mat-select>
                      </div>
                    </div>
                  </div>
                </div>
              <div class="form-group-item">																		
                  <div class="row">
                      <div class="col-xl-6 col-lg-6 col-md-6 col-12"> 
                          <div class="input-block mb-3" id="summernote_container">
                              <label htmlFor="label" class="form-control-label">Product Descriptions</label>
                              <angular-editor ngDefaultControl [config]="config">
                              </angular-editor>
                          </div>
                      </div>
                      <div class="col-lg-6 col-sm-12">
                        <div class="input-block mb-0 pb-0">
                          <label>Image</label>
                          <ngx-dropzone (change)="onSelect($event)" class="service-upload">
                            <ngx-dropzone-label class="drop-browse align-center">
                              <span
                                ><img src="assets/img/icons/drop-icon.svg" alt="upload"
                              /></span>
                              <div class="d-flex">
                                Drop your files here or<span class="text-primary ms-1"
                                >browse</span
                              >
                              </div>
                               
                              <span class="text-muted">Maximum size: 50MB</span>
                            </ngx-dropzone-label>
                            <ngx-dropzone-image-preview
                              ngProjectAs="ngx-dropzone-preview"
                              *ngFor="let f of files"
                              [file]="f"
                              [removable]="true"
                              (removed)="onRemove(f)"
                            >
                            </ngx-dropzone-image-preview>
                          </ngx-dropzone>
                        </div>
                      </div>
                  </div>
              </div>
                                      
              <div class="text-end">
                  <button type="reset" class="btn btn-primary cancel me-2">Cancel</button>
                  <button [routerLink]="routes.productlist" type="submit" class="btn btn-primary">Add Item</button>
              </div>
          </div>
      </div>
  </div>
  
</div>

// kanakku-v1.9.9/vuejs-files/template/src/views/pages/products&services/edit-products.vue
<template>
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>

    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <componentheader :title="title" />

        <div class="row">
          <div class="col-md-12">
            <div class="card-body">
              <div class="form-group-item">
                <h5 class="form-title">Basic Details</h5>
                <div class="row">
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Item Type</label>
                      <input
                        type="text"
                        class="form-control"
                        value="Product"
                        placeholder="Enter Item Name"
                      />
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Name</label>
                      <input
                        type="text"
                        class="form-control"
                        value="Lorem ipsum dolor sit"
                        placeholder="Enter Item Name"
                      />
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Item Category</label>
                      <input
                        type="text"
                        class="form-control"
                        value="Duis aute irure"
                        placeholder="Enter Category Name"
                      />
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Price</label>
                      <input
                        type="number"
                        class="form-control"
                        value="253.00"
                        placeholder="Enter Item Price"
                        name="name"
                      />
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Units</label>
                      <input
                        type="text"
                        class="form-control"
                        value="Inches"
                        placeholder="Enter Units"
                        name="name"
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div class="form-group-item">
                <div class="form-group">
                  <h5 class="form-title">Additional Details</h5>
                </div>
                <div class="row">
                  <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                    <div class="form-group">
                      <label>Generate Barcode</label>
                      <input
                        type="text"
                        class="form-control"
                        value="P125389"
                        placeholder="Enter Barcode Number"
                      />
                    </div>
                  </div>
                  <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                    <div class="form-group">
                      <label>Purchase Price Without Tax</label>
                      <input
                        type="text"
                        class="form-control"
                        value="$00.00"
                        placeholder="Enter Address 1"
                      />
                    </div>
                  </div>
                  <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                    <div class="form-group">
                      <label>Purchase Price With Tax</label>
                      <input
                        type="text"
                        class="form-control"
                        value="$253.00"
                        placeholder="Enter Tax Amount"
                      />
                    </div>
                  </div>
                  <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                    <div class="form-group">
                      <label>Quantity</label>
                      <input
                        type="text"
                        class="form-control"
                        value="2"
                        placeholder="eg 10"
                      />
                    </div>
                  </div>
                  <div class="col-xl-6 col-lg-6 col-md-6 col-12">
                    <div class="form-group" id="summernote_container">
                      <label class="form-control-label">Details</label>
                      <SummernoteEditor
                        v-model="myValue"
                        @update:modelValue="summernoteChange($event)"
                        @summernoteImageLinkInsert="summernoteImageLinkInsert"
                      />
                    </div>
                  </div>
                  <div class="col-xl-6 col-lg-6 col-md-6 col-12">
                    <div class="form-group">
                      <label>Image</label>
                      <div class="form-group service-upload mb-0">
                        <span
                          ><img src="@/assets/img/icons/drop-icon.svg" alt="upload"
                        /></span>
                        <h6 class="drop-browse align-center">
                          Drop your files here or<span class="text-primary ms-1"
                            >browse</span
                          >
                        </h6>
                        <p class="text-muted">Maximum size: 50MB</p>
                        <input type="file" multiple="" id="image_sign" />
                        <div id="frames"></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="form-group-item border-0 pb-0">
                <div class="form-group">
                  <h5 class="form-title">Discount Details</h5>
                </div>
                <div class="row">
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Discount (%)</label>
                      <ul class="form-group-plus css-equal-heights">
                        <li>
                          <vue-select :options="Percentage" placeholder="5%" />
                        </li>
                        <li>
                          <span class="btn btn-gray form-plus-btn">%</span>
                        </li>
                      </ul>
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Discount Amount</label>
                      <input
                        type="text"
                        class="form-control"
                        value="$10.00"
                        placeholder="Enter Discount Amount"
                      />
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Minimum Stock Qty</label>
                      <input
                        type="text"
                        class="form-control"
                        value="2"
                        placeholder="eg 10"
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div class="text-end">
                <button type="reset" class="btn btn-primary cancel me-2">Cancel</button>
                <b-button type="submit" variant="primary">Add Item</b-button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /Page Wrapper -->
  </div>
</template>

<script>
import SummernoteEditor from "vue3-summernote-editor";
export default {
  components: {
    SummernoteEditor,
  },
  data() {
    return {
      Percentage: ["5%", "10%", "15%"],
      myValue: "",
      title: "Edit Products / Services",
    };
  },
  methods: {
    summernoteChange(newValue) {
      console.log("summernoteChange", newValue);
    },
    summernoteImageLinkInsert(...args) {
      console.log("summernoteImageLinkInsert()", args);
    },
  },
};
</script>
