// kanakku-v1.9.9/vuejs-files/template-rtl/src/views/pages/settings/preferences.vue
<template>
  <!-- Main Wrapper -->
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>

    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <componentheader :title="title" />

        <div class="row">
          <div class="col-xl-3 col-md-4">
            <settingsidebar />
          </div>

          <div class="col-xl-9 col-md-8">
            <div class="card">
              <div class="card-header">
                <h5 class="card-title">Preferences</h5>
              </div>
              <div class="card-body">
                <!-- Form -->
                <b-form>
                  <div class="row form-group">
                    <label for="currencyLabel" class="col-sm-3 col-form-label input-label"
                      >Currency</label
                    >
                    <div class="col-sm-9">
                      <vue-select :options="USD" placeholder="USD - US Dollar" />
                    </div>
                  </div>
                  <div class="row form-group">
                    <label for="languageLabel" class="col-sm-3 col-form-label input-label"
                      >Language</label
                    >
                    <div class="col-sm-9">
                      <vue-select :options="English" placeholder="English" />
                    </div>
                  </div>
                  <div class="row form-group">
                    <label for="timezoneLabel" class="col-sm-3 col-form-label input-label"
                      >Time Zone</label
                    >
                    <div class="col-sm-9">
                      <vue-select :options="English" placeholder="English" />
                    </div>
                  </div>
                  <div class="row form-group">
                    <label for="dateformat" class="col-sm-3 col-form-label input-label"
                      >Date Format</label
                    >
                    <div class="col-sm-9">
                      <vue-select :options="date" placeholder="2020 Nov 09" />
                    </div>
                  </div>
                  <div class="row form-group">
                    <label for="financialyear" class="col-sm-3 col-form-label input-label"
                      >Financial Year</label
                    >
                    <div class="col-sm-9">
                      <vue-select :options="month" placeholder="january-december" />
                    </div>
                  </div>

                  <!-- Toggle Switch -->
                  <label class="row form-group toggle-switch" for="preferencesSwitch1">
                    <span class="col-8 col-sm-9 toggle-switch-content ml-0">
                      <span class="d-block text-dark">Discount Per Item</span>
                      <span class="d-block text-muted"
                        >Enable this if you want to add Discount to individual invoice
                        items. By default, Discount is added directly to the
                        invoice.</span
                      >
                    </span>
                    <span class="col-4 col-sm-3">
                      <input
                        type="checkbox"
                        class="toggle-switch-input"
                        id="preferencesSwitch1"
                      />
                      <span class="toggle-switch-label ms-auto">
                        <span class="toggle-switch-indicator"></span>
                      </span>
                    </span>
                  </label>
                  <!-- /Toggle Switch -->

                  <div class="text-end">
                    <b-button variant="primary">Save Changes</b-button>
                  </div>
                </b-form>
                <!-- /Form -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /Page Wrapper -->
  </div>
  <!-- /Main Wrapper -->
</template>
<script>
export default {
  setup() {
    return {
      title: "Settings",
      USD: [
        "USD - US Dollar",
        "GBP - British Pound",
        "EUR - Euro",
        "INR - Indian Rupee",
        "AUD - Australian Dollar",
      ],
      English: ["English", "French", "German", "Italian", "Spanish"],
      date: [
        "2020 Nov 09",
        "09 Nov 2020",
        "09/11/2020",
        "09.11.2020",
        "09-11-2020",
        "11/09/2020",
        "2020/11/09",
        "2020-11-09",
      ],
      month: [
        "january-december",
        "february-january",
        "march-february",
        "april-march",
        "may-april",
        "june-may",
        "july-june",
        "august-july",
        "september-august",
        "october-september",
        "november-october",
        "december-november",
      ],
    };
  },
};
</script>

// kanakku-v1.9.9/angular-files/template/src/app/feature-module/setting/preferences/preferences.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-preferences',
  templateUrl: './preferences.component.html',
  styleUrls: ['./preferences.component.scss'],
})
export class PreferencesComponent  {
 
  discount = false
  currency ="selectcurrency"
  language = "selectedlanguage"
  time = "timezone"
  date ="dateformat"
  date1 = "date2"
  finalyear = "finalyear"
  

}

<div class="card">
  <div class="card-body">
    <div class="content-page-header">
      <h5>Preference Settings</h5>
    </div>
    <div class="row">
      <div class="col-lg-6 col-12">
        <div class="input-block mb-3">
          <label>Currency</label>
          <mat-select
            [(ngModel)]="currency"
            [ngModelOptions]="{ standalone: true }"
            class="select mat-cust-select form-control"
          >
            <mat-option value="selectcurrency">Select Currency</mat-option>
            <mat-option value="Usd">USD - US Dollar</mat-option>
            <mat-option value="gbp">GBP - British Pound</mat-option>
            <mat-option value="eur">EUR - Euro</mat-option>
            <mat-option value="inr">INR - Indian Rupee</mat-option>
            <mat-option value="aud">AUD - Australian Dollar</mat-option>
          </mat-select>
        </div>
      </div>
      <div class="col-lg-6 col-12">
        <div class="input-block mb-3">
          <label>language</label>
          <mat-select
            [(ngModel)]="language"
            [ngModelOptions]="{ standalone: true }"
            class="select mat-cust-select form-control"
          >
            <mat-option value="selectedlanguage">Select Language</mat-option>
            <mat-option value="english">English</mat-option>
            <mat-option value="french">French</mat-option>
            <mat-option value="german">German</mat-option>
            <mat-option value="italian">Italian</mat-option>
            <mat-option value="spanish">Spanish</mat-option>
          </mat-select>
        </div>
      </div>
      <div class="col-xl-6 col-lg-6 col-md-6 col-12">
        <div class="input-block mb-3">
          <label>Time Zone</label>
          <mat-select
            [(ngModel)]="time"
            [ngModelOptions]="{ standalone: true }"
            class="select mat-cust-select form-control"
          >
            <mat-option value="timezone">Select Time Zone</mat-option>
            <mat-option value="zone1">(UTC+09:00) Tokyo</mat-option>
            <mat-option value="zone2">(UTC+11:00) INR</mat-option>
          </mat-select>
        </div>
      </div>
      <div class="col-xl-6 col-lg-6 col-md-6 col-12">
        <div class="input-block mb-3">
          <label>Date Format</label>
          <mat-select
            [(ngModel)]="date"
            [ngModelOptions]="{ standalone: true }"
            class="select mat-cust-select form-control"
          >
            <mat-option value="dateformat">Select Date Format</mat-option>
            <mat-option value="dateformat1">2020 Nov 09</mat-option>
            <mat-option value="dateformat2">09 Nov 2020</mat-option>
            <mat-option value="dateformat3">09/11/2020</mat-option>
          </mat-select>
        </div>
      </div>
      <div class="col-xl-6 col-lg-6 col-md-6 col-12">
        <div class="form-group">
          <label>Time Format</label>
          <mat-select
            [(ngModel)]="date1"
            [ngModelOptions]="{ standalone: true }"
            class="select mat-cust-select form-control"
          >
            <mat-option value="date2">Select Time Format</mat-option>
            <mat-option value="date3">10:00 AM - 11:00 AM</mat-option>
            <mat-option value="date3">12:00 PM - 02:00 PM</mat-option>
          </mat-select>
        </div>
      </div>
      <div class="col-xl-6 col-lg-6 col-md-6 col-12">
        <div class="input-block mb-3">
          <label>Financial Year </label>
          <mat-select
            [(ngModel)]="finalyear"
            [ngModelOptions]="{ standalone: true }"
            class="select mat-cust-select form-control"
          >
            <mat-option value="finalyear">Select Financial Year </mat-option>
            <mat-option value="january">january-december</mat-option>
            <mat-option value="februbary">february-january</mat-option>
            <mat-option value="march">march-february</mat-option>
          </mat-select>
        </div>
      </div>
      <div class="col-lg-12">
        <div class="btn-path text-end">
          <a
            href="javascript:void(0);"
            class="btn btn-cancel bg-primary-light me-3"
            >Cancel</a
          >
          <a href="javascript:void(0);" class="btn btn-primary">Save Changes</a>
        </div>
      </div>
    </div>
  </div>
</div>
