// kanakku-v1.9.9/vuejs-files/template-rtl/src/views/pages/pages/error/error404.vue
<template>
    <!-- Main Wrapper -->
    <div class="main-wrapper error-page">
        
        <div class="error-box">
            <h1>404</h1>
            <h3 class="h2 mb-3"><i class="fas fa-exclamation-circle"></i> Oops! Page not found!</h3>
            <p class="h4 font-weight-normal">The page you requested was not found.</p>
            <router-link to="/" class="btn btn-primary">Back to Home</router-link>
        </div>
    
    </div>
    <!-- /Main Wrapper -->
</template>

// kanakku-v1.9.9/angular-files/template/src/app/shared/error/error404/error404.component.ts
import { Component,} from '@angular/core';
import { routes } from 'src/app/core/core.index';

@Component({
  selector: 'app-error404',
  templateUrl: './error404.component.html',
  styleUrls: ['./error404.component.scss'],
})
export class Error404Component  {
  public routes = routes;

  
}

<!-- Main Wrapper -->
<div class="main-wrapper error-page">
  <div class="error-box">
    <h1>404</h1>
    <h3 class="h2 mb-3">
      <i class="fas fa-exclamation-circle"></i> Oops! Page not found!
    </h3>
    <p class="h4 font-weight-normal">The page you requested was not found.</p>
    <a [routerLink]="routes.dashboard" class="btn btn-primary">Back to Home</a>
  </div>
</div>
<!-- /Main Wrapper -->
