// kanakku-v1.9.9/vuejs-files/template/src/views/pages/pages/blankpage.vue
<template>
  <!-- Main Wrapper -->
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>

    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <componentheader :title="title" />

        <div class="row">
          <div class="col-sm-12">Contents here</div>
        </div>
      </div>
    </div>
    <!-- /Page Wrapper -->
  </div>
  <!-- /Main Wrapper -->
</template>
<script>
export default {
  setup() {
    return {
      title: "Blank Page",
    };
  },
};
</script>

// kanakku-v1.9.9/reactjs-files/template-rtl/src/blankpage/Index.jsx
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import Header from '../layouts/Header'
import Sidebar from '../layouts/Sidebar'

const BlankPage = () => {

	const [menu, setMenu] = useState(false)

	const toggleMobileMenu = () => {
		setMenu(!menu)
	}
	return (
		<div className={`main-wrapper ${menu ? 'slide-nav' : ''}`}>

			<Header onMenuClick={(value) => toggleMobileMenu()} />
			<Sidebar />


			<div class="page-wrapper">
				<div class="content container-fluid">

					<div class="page-header">
						<div class="content-page-header">
							<h5>Blank Page</h5>
						</div>
					</div>

					<div class="row">
						<div class="col-sm-12">
							Contents here
						</div>
					</div>

				</div>
			</div>
		</div>



	);

}
export default BlankPage;
