// kanakku-v1.9.9/reactjs-files/template-rtl/src/vendors/index.jsx
import React, { useState } from "react";
import Header from "../layouts/Header";
import Sidebar from "../layouts/Sidebar";
import "../_components/antd.css";
import { Table } from "antd";
import {
  onShowSizeChange,
  itemRender,
} from "../_components/paginationfunction";
import Data from "../assets/jsons/vendors";
import { Link } from "react-router-dom";
import FeatherIcon from "feather-icons-react";
import AddVendor from "./addVendor";

const Vendors = () => {

  const [menu, setMenu] = useState(false);
  const [show, setShow] = useState(false);

  const toggleMobileMenu = () => {
    setMenu(!menu);
  };

  const datasource = Data?.Data;

  const columns = [
    {
      title: "#",
      dataIndex: "id",
      sorter: (a, b) => a.id.length - b.id.length,
    },
    {
      title: "Name",
      dataIndex: "Name",
      render: (text, record) => (
        <>
          <h2 className="table-avatar">
            <Link to="/profile" className="avatar avatar-md ms-2">
              <img
                className="avatar-img rounded-circle"
                src={record.img}
                alt="User Image"
              />
            </Link>
            <Link to="/profile">
              {record.Name} <span>{record.email}</span>
            </Link>
          </h2>
        </>
      ),
      sorter: (a, b) => a.Name.length - b.Name.length,
    },
    {
      title: "Phone",
      dataIndex: "Phone",
      sorter: (a, b) => a.Phone.length - b.Phone.length,
    },
    {
      title: "Created",
      dataIndex: "Created",
      sorter: (a, b) => a.Created.length - b.Created.length,
    },
    {
      title: "Balance",
      dataIndex: "Balance",
      sorter: (a, b) => a.Balance.length - b.Balance.length,
    },
    {
      title: "Action",
      dataIndex: "Action",
      render: (text, record) => (
        <>
          <div className="d-flex align-items-center">
            <Link to="/add-ledger" className="btn btn-greys ms-2">
              <i className="fa fa-eye ms-1" /> Ledger
            </Link>
            <div className="dropdown dropdown-action">
              <Link
                to="#"
                className=" btn-action-icon "
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                <i className="fas fa-ellipsis-v" />
              </Link>
              <div className="dropdown-menu dropdown-menu-end">
                <ul>
                  <li>
                    <Link
                      className="dropdown-item"
                      to="#"
                      data-bs-toggle="modal"
                      data-bs-target="#edit_vendor"
                    >
                      <i className="far fa-edit ms-2" />
                      Edit
                    </Link>
                  </li>
                  <li>
                    <Link
                      className="dropdown-item"
                      to="#"
                      data-bs-toggle="modal"
                      data-bs-target="#delete_modal"
                    >
                      <i className="far fa-trash-alt ms-2" />
                      Delete
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </>
      ),
      sorter: (a, b) => a.Action.length - b.Action.length,
    },
  ];

  return (
    <>
      <div className={`main-wrapper ${menu ? "slide-nav" : ""}`}>
        <Header onMenuClick={(value) => toggleMobileMenu()} />
        <Sidebar />

        <div className="page-wrapper">
          <div className="content container-fluid">
            {/* Page Header */}
            <div className="page-header">
              <div className="content-page-header ">
                <h5>Vendors</h5>
                <div className="list-btn">
                  <ul className="filter-list">
                    <li>
                      <Link className="btn btn-filters w-auto popup-toggle"
                      onClick={() => setShow(!show)}
                      >
                        <span className="ms-2">
                          <FeatherIcon icon="filter" />
                        </span>
                        Filter{" "}
                      </Link>
                    </li>
                    <li>
                      <Link className="btn-filters" to="#">
                        <span>
                          <FeatherIcon icon="grid" />
                        </span>{" "}
                      </Link>
                    </li>
                    <li>
                      <Link className="active btn-filters ms-2" to="#">
                        <span>
                          <FeatherIcon icon="list" />
                        </span>
                      </Link>
                    </li>
                    <li className="">
                      <div className="dropdown dropdown-action">
                        <Link
                          to="#"
                          className="btn-filters ms-2"
                          data-bs-toggle="dropdown"
                          aria-expanded="false"
                        >
                          <span>
                            <FeatherIcon icon="download" />
                          </span>
                        </Link>
                        <div className="dropdown-menu dropdown-menu-end">
                          <ul className="d-block">
                            <li>
                              <Link
                                className="d-flex align-items-center download-item"
                                to="#"
                                download=""
                              >
                                <i className="far fa-file-pdf ms-2" />
                                PDF
                              </Link>
                            </li>
                            <li>
                              <Link
                                className="d-flex align-items-center download-item"
                                to="#"
                                download=""
                              >
                                <i className="far fa-file-text ms-2" />
                                CVS
                              </Link>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </li>
                    <li>
                      <Link className="btn-filters" to="#">
                        <span>
                          <FeatherIcon icon="printer" />
                        </span>{" "}
                      </Link>
                    </li>
                    <li>
                      <Link className="btn btn-import" to="#">
                        <span>
                          <FeatherIcon icon="check-square" className="ms-2" />{" "}
                          Import
                        </span>
                      </Link>
                    </li>
                    <li>
                      <Link
                        className="btn btn-primary"
                        to="#"
                        data-bs-toggle="modal"
                        data-bs-target="#add_vendor"
                      >
                        <i
                          className="fa fa-plus-circle ms-2"
                          aria-hidden="true"
                        />
                        Add Vendors
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            {/* /Page Header */}
            {/* Search Filter */}
            <div id="filter_inputs" className="card filter-card">
              <div className="card-body pb-0">
                <div className="row">
                  <div className="col-sm-6 col-md-3">
                    <div className="form-group">
                      <label>Name</label>
                      <input type="text" className="form-control" />
                    </div>
                  </div>
                  <div className="col-sm-6 col-md-3">
                    <div className="form-group">
                      <label>Email</label>
                      <input type="text" className="form-control" />
                    </div>
                  </div>
                  <div className="col-sm-6 col-md-3">
                    <div className="form-group">
                      <label>Phone</label>
                      <input type="text" className="form-control" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* /Search Filter */}
            <div className="row">
              <div className="col-sm-12">
                <div className=" card-table">
                  <div className="card-body vendors">
                    <div className="table-responsive table-hover table-striped">
                      <Table
                        pagination={{
                          total: datasource.length,
                          showTotal: (total, range) =>
                            `Showing ${range[0]} to ${range[1]} of ${total} entries`,
                          showSizeChanger: true,
                          onShowSizeChange: onShowSizeChange,
                          itemRender: itemRender,
                        }}
                        columns={columns}
                        dataSource={datasource}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <AddVendor 
          setShow={setShow}
          show={show}
        />

        <div className="modal custom-modal fade" id="add_vendor" role="dialog">
          <div className="modal-dialog modal-dialog-centered modal-md">
            <div className="modal-content">
              <div className="modal-header border-0 pb-0">
                <div className="form-header modal-header-title text-start mb-0">
                  <h4 className="mb-0">Add Vendor</h4>
                </div>
                <button
                  type="button"
                  className="close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <span className="align-center" aria-hidden="true">
                    ×
                  </span>
                </button>
              </div>
              <div className="modal-body">
                <div className="row">
                  <div className="col-lg-12 col-sm-12">
                    <div className="form-group">
                      <label>Name</label>
                      <input
                        type="text"
                        className="form-control"
                        placeholder="Enter Name"
                      />
                    </div>
                  </div>
                  <div className="col-lg-12 col-sm-12">
                    <div className="form-group">
                      <label>Email</label>
                      <input
                        type="text"
                        className="form-control"
                        placeholder="Enter Email Address"
                      />
                    </div>
                  </div>
                  <div className="col-lg-12 col-sm-12">
                    <div className="form-group">
                      <label>Phone Number</label>
                      <input
                        type="number"
                        className="form-control"
                        placeholder="Enter Phone Number"
                      />
                    </div>
                  </div>
                  <div className="col-lg-12 col-sm-12">
                    <div className="form-group mb-0">
                      <label>Balance</label>
                      <input
                        type="number"
                        className="form-control"
                        placeholder="Enter Balance Amount"
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div className="modal-footer">
                <Link
                  to="#"
                  data-bs-dismiss="modal"
                  className="btn btn-primary paid-cancel-btn ms-2"
                >
                  Cancel
                </Link>
                <Link
                  to="#"
                  data-bs-dismiss="modal"
                  className="btn btn-primary paid-continue-btn"
                >
                  Add Vendor
                </Link>
              </div>
            </div>
          </div>
        </div>

        <div className="modal custom-modal fade" id="edit_vendor" role="dialog">
          <div className="modal-dialog modal-dialog-centered modal-md">
            <div className="modal-content">
              <div className="modal-header border-0 pb-0">
                <div className="form-header modal-header-title text-start mb-0">
                  <h4 className="mb-0">Edit Vendor</h4>
                </div>
                <button
                  type="button"
                  className="close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <span className="align-center" aria-hidden="true">
                    ×
                  </span>
                </button>
              </div>
              <div className="modal-body">
                <div className="row">
                  <div className="col-lg-12 col-md-12">
                    <div className="form-group">
                      <label>Name</label>
                      <input
                        type="text"
                        className="form-control"
                        defaultValue="John Smith"
                        placeholder="Enter Name"
                      />
                    </div>
                  </div>
                  <div className="col-lg-12 col-md-12">
                    <div className="form-group">
                      <label>Email</label>
                      <input
                        type="text"
                        className="form-control"
                        defaultValue="john@example.com"
                        placeholder="Select Date"
                      />
                    </div>
                  </div>
                  <div className="col-lg-12 col-md-12">
                    <div className="form-group">
                      <label>Phone Number</label>
                      <input
                        type="text"
                        className="form-control"
                        defaultValue="+1 989-438-3131"
                        placeholder="Enter Reference Number"
                      />
                    </div>
                  </div>
                  <div className="col-lg-12 col-md-12">
                    <div className="form-group mb-0">
                      <label>Balance</label>
                      <input
                        type="text"
                        className="form-control"
                        defaultValue="$4200"
                        placeholder="Enter Reference Number"
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div className="modal-footer">
                <Link
                  to="#"
                  data-bs-dismiss="modal"
                  className="btn btn-primary paid-cancel-btn ms-2"
                >
                  Cancel
                </Link>
                <Link
                  to="#"
                  data-bs-dismiss="modal"
                  className="btn btn-primary paid-continue-btn"
                >
                  Update
                </Link>
              </div>
            </div>
          </div>
        </div>

        <div
          className="modal custom-modal fade"
          id="delete_modal"
          role="dialog"
        >
          <div className="modal-dialog modal-dialog-centered modal-md">
            <div className="modal-content">
              <div className="modal-body">
                <div className="form-header">
                  <h3>Delete Vendor</h3>
                  <p>Are you sure want to delete?</p>
                </div>
                <div className="modal-btn delete-action">
                  <div className="row">
                    <div className="col-6">
                      <button
                        type="reset"
                        data-bs-dismiss="modal"
                        className="w-100 btn btn-primary paid-continue-btn"
                      >
                        Delete
                      </button>
                    </div>
                    <div className="col-6">
                      <button
                        type="submit"
                        data-bs-dismiss="modal"
                        className="w-100 btn btn-primary paid-cancel-btn"
                      >
                        Cancel
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </>
  );
};

export default Vendors;

// kanakku-v1.9.9/angular-files/template-rtl/src/app/feature-module/vendors/vendors.component.ts
import { Component, OnInit } from '@angular/core';
import { Sort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { DataService, routes } from 'src/app/core/core.index';
import { apiResultFormat, pageSelection, vendor } from 'src/app/core/models/models';
@Component({
  selector: 'app-vendors',
  templateUrl: './vendors.component.html',
  styleUrls: ['./vendors.component.scss']
})
export class VendorsComponent implements OnInit {
 
  public routes = routes ;
  public datas: Array<vendor> = [];
  public Toggledata  = false;
  dataSource!: MatTableDataSource<vendor>;
  public searchDataValue = '';
  isCollapsed = false;
  // pagination variables
  public lastIndex = 0;
  public pageSize = 10;
  public totalData = 0;
  public skip = 0;
  public limit: number = this.pageSize;
  public pageIndex = 0;
  public serialNumberArray: Array<number> = [];
  public currentPage = 1;
  public pageNumberArray: Array<number> = [];
  public pageSelection: Array<pageSelection> = [];
  public totalPages = 0;
  //** / pagination variables



  constructor(private data: DataService) {}

  ngOnInit(): void {
    this.getTableData();
  }
  private getTableData(): void {
    this.datas = [];
    this.serialNumberArray = [];

    this.data.getVendors().subscribe((data: apiResultFormat) => {
      this.totalData = data.totalData;
      data.data.map((res: vendor , index: number) => {
        const serialNumber = index + 1;
        if (index >= this.skip && serialNumber <= this.limit) {
          res.sNo = serialNumber;
          this.datas.push(res);
          this.serialNumberArray.push(serialNumber);
        }
      });
      this.dataSource = new MatTableDataSource<vendor>(this.datas);
      this.calculateTotalPages(this.totalData, this.pageSize);
    });
  }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  public searchData(value: any): void {
    this.dataSource.filter = value.trim().toLowerCase();
    this.datas = this.dataSource.filteredData;
  }
  
  
  public sortData(sort: Sort) {
    const data = this.datas.slice();

    if (!sort.active || sort.direction === '') {
      this.datas = data;
    } else {
      this.datas = data.sort((a, b) => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const aValue = (a as any)[sort.active];
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const bValue = (b as any)[sort.active];
        return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
      });
    }
  }
  public getMoreData(event: string): void {
    if (event == 'next') {
      this.currentPage++;
      this.pageIndex = this.currentPage - 1;
      this.limit += this.pageSize;
      this.skip = this.pageSize * this.pageIndex;
      this.getTableData();
    } else if (event == 'previous') {
      this.currentPage--;
      this.pageIndex = this.currentPage - 1;
      this.limit -= this.pageSize;
      this.skip = this.pageSize * this.pageIndex;
      this.getTableData();
    }
  }
  public moveToPage(pageNumber: number): void {
    this.currentPage = pageNumber;
    this.skip = this.pageSelection[pageNumber - 1].skip;
    this.limit = this.pageSelection[pageNumber - 1].limit;
    if (pageNumber > this.currentPage) {
      this.pageIndex = pageNumber - 1;
    } else if (pageNumber < this.currentPage) {
      this.pageIndex = pageNumber + 1;
    }
    this.getTableData();
  }
  public PageSize(): void {
    this.pageSelection = [];
    this.limit = this.pageSize;
    this.skip = 0;
    this.currentPage = 1;
    this.getTableData();
  }
  private calculateTotalPages(totalData: number, pageSize: number): void {
    this.pageNumberArray = [];
    this.totalPages = totalData / pageSize;
    if (this.totalPages % 1 != 0) {
      this.totalPages = Math.trunc(this.totalPages + 1);
    }
    for (let i = 1; i <= this.totalPages; i++) {
      const limit = pageSize * i;
      const skip = limit - pageSize;
      this.pageNumberArray.push(i);
      this.pageSelection.push({ skip: skip, limit: limit });
    }
  }
  open() {
    this.Toggledata = !this.Toggledata;
   
  }
  users = [
    { name: 'Barbara Moore', checked: false },
    { name: 'Hendry Evan', checked: false },
    { name: 'Richard Miles', checked: false }
  ];
  
  toggleCollapse() {
    this.isCollapsed = !this.isCollapsed;
  }
}

<!-- Page Header -->
<div class="page-header">
  <div class="content-page-header">
    <h5>Vendors</h5>
    <div class="list-btn">
      <ul class="filter-list">
        <li>
          <a
            (click)="open()"
            matTooltip="Filter"
            href="javascript:void(0);"
            class="btn btn-filters w-auto popup-toggle"
          >
            <span class="me-2"
              ><img src="assets/img/icons/filter-icon.svg" alt="filter" /></span
            >Filter
          </a>
        </li>
        <li>
          <a class="btn-filters" matTooltip="Grid-View" href="javascript:void(0);"
            ><span><i class="feather icon-grid"></i></span>
          </a>
        </li>
        <li>
          <a class="active btn-filters" matTooltip="List-View" href="javascript:void(0);"
            ><span><i class="feather icon-list"></i></span>
          </a>
        </li>
        <li class="">
          <div class="dropdown dropdown-action">
            <a
              href="#"
              class="btn-filters"
              data-bs-toggle="dropdown"
              aria-expanded="false"
              matTooltip="download"
              ><span><i class="feather icon-download"></i></span
            ></a>
            <div class="dropdown-menu dropdown-menu-end">
              <ul class="d-block">
                <li>
                  <a
                    class="d-flex align-items-center download-item"
                    href="javascript:void(0);"
                    download
                    ><i class="far fa-file-pdf me-2"></i>PDF</a
                  >
                </li>
                <li>
                  <a
                    class="d-flex align-items-center download-item"
                    href="javascript:void(0);"
                    download
                    ><i class="far fa-file-text me-2"></i>CVS</a
                  >
                </li>
              </ul>
            </div>
          </div>
        </li>
        <li>
          <a class="btn-filters"  matTooltip="print" href="javascript:void(0);"
            ><span><i class="feather icon-printer"></i></span>
          </a>
        </li>
        <li>
          <a class="btn btn-import" href="javascript:void(0);"
            ><span
              ><i class="feather icon-check-square me-2"></i> Import</span
            ></a
          >
        </li>
        <li>
          <a
            class="btn btn-primary"
            href="javascript:void(0);"
            data-bs-toggle="modal"
            data-bs-target="#add_vendor"
            ><i class="fa fa-plus-circle me-2" aria-hidden="true"></i>Add
            Vendors</a
          >
        </li>
      </ul>
    </div>
  </div>
</div>
<!-- /Page Header -->

<!-- Search Filter -->
<div id="filter_inputs" class="card filter-card">
  <div class="card-body pb-0">
    <div class="row">
      <div class="col-sm-6 col-md-3">
        <div class="form-group">
          <label htmlFor="label">Name</label>
          <input id="label" type="text" class="form-control" />
        </div>
      </div>
      <div class="col-sm-6 col-md-3">
        <div class="form-group">
          <label htmlFor="label">Email</label>
          <input id="label" type="text" class="form-control" />
        </div>
      </div>
      <div class="col-sm-6 col-md-3">
        <div class="form-group">
          <label htmlFor="label">Phone</label>
          <input id="label" type="text" class="form-control" />
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /Search Filter -->

<div class="row">
  <div class="col-sm-12">
    <div class="card-table">
      <div class="card-body">
        <div class="table-responsive">
          <table
            matSort
            (matSortChange)="sortData($event)"
            class="table table-center table-hover datatable"
          >
            <thead class="thead-light">
              <tr>
                <th mat-sort-header="sNo">#</th>
                <th mat-sort-header="name">Name</th>
                <th mat-sort-header="phone">Phone</th>
                <th mat-sort-header="created">Created</th>
                <th mat-sort-header="balance">Balance</th>
                <th mat-sort-header="action">Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let data of datas; let i = index">
                <td>{{ data.sNo }}</td>
                <td>
                  <h2 class="table-avatar">
                    <a
                      [routerLink]="routes.profile"
                      class="avatar avatar-sm me-2"
                      ><img
                        class="avatar-img rounded-circle"
                        [src]="data.img"
                        alt="User Image"
                    /></a>
                    <a [routerLink]="routes.profile"
                      >{{ data.name }} <span>{{ data.email }}</span></a
                    >
                  </h2>
                </td>
                <td>{{ data.phone }}</td>
                <td>{{ data.created }}</td>
                <td>{{ data.balance }}</td>
                <td class="d-flex align-items-center">
                  <a [routerLink]="routes.ledger" class="btn btn-greys me-2"
                    ><i class="fa fa-eye me-1"></i> Ledger</a
                  >
                  <div class="dropdown dropdown-action">
                    <a
                      href="#"
                      class="btn-action-icon"
                      data-bs-toggle="dropdown"
                      aria-expanded="false"
                      ><i class="fas fa-ellipsis-v"></i
                    ></a>
                    <div class="dropdown-menu dropdown-menu-end">
                      <ul>
                        <li>
                          <a
                            class="dropdown-item"
                            href="javascript:void(0);"
                            data-bs-toggle="modal"
                            data-bs-target="#edit_vendor"
                            ><i class="far fa-edit me-2"></i>Edit</a
                          >
                        </li>
                        <li>
                          <a
                            class="dropdown-item"
                            href="javascript:void(0);"
                            data-bs-toggle="modal"
                            data-bs-target="#delete_modal"
                            ><i class="far fa-trash-alt me-2"></i>Delete</a
                          >
                        </li>
                      </ul>
                    </div>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
          <div class="table_header">
            <div class="row">
              <div class="col-sm-12 col-md-6">
                <div class="dataTables_length">
                  <label>
                    Show
                    <select
                      [(ngModel)]="pageSize"
                      (ngModelChange)="PageSize()"
                      class="form-control form-control-sm"
                    >
                      <option value="10">10</option>
                      <option value="25">25</option>
                      <option value="50">50</option>
                      <option value="100">100</option>
                    </select>
                    Entries
                  </label>
                </div>
              </div>
            </div>
            <div class="col-sm-12 col-md-3">
              <div class="pagination_section">
                <ul class="pagination">
                  <li
                    class="page-item"
                    [ngClass]="{
                      disabled: currentPage === 1
                    }"
                  >
                    <a
                      (click)="getMoreData('previous')"
                      class="page-link"
                      href="javascript:void(0);"
                      tabindex="-1"
                      ><i class="fa fa-angle-double-right me-2"></i>Previous</a
                    >
                  </li>

                  <ng-container
                    *ngFor="let item of pageNumberArray; let i = index"
                  >
                    <li
                      class="page-item"
                      [class.active]="item === currentPage"
                      [ngClass]="
                        (pageNumberArray[currentPage - 2] > item &&
                          item !== 1 &&
                          pageNumberArray.length > 6) ||
                        (pageNumberArray[currentPage] < item &&
                          item !== 1 &&
                          pageNumberArray.length > 6 &&
                          pageNumberArray.length !== item)
                          ? 'hide-sub-menu'
                          : 'show-sub-menu'
                      "
                    >
                      <a
                        (click)="moveToPage(item)"
                        class="page-link"
                        href="javascript:void(0);"
                      >
                        {{ item }}
                        <span *ngIf="item === currentPage" class="sr-only"
                          >(current)</span
                        >
                      </a>
                    </li>
                    <li
                      class="page-item"
                      *ngIf="
                        i === 0 && pageNumberArray.length > 6 && currentPage > 2
                      "
                      [hidden]="currentPage === 1"
                    >
                      <a
                        (click)="moveToPage(currentPage - 2)"
                        tabindex="0"
                        class="page-link"
                        href="javascript:void(0);"
                      >
                        ...
                      </a>
                    </li>
                    <li
                      *ngIf="
                        i === pageNumberArray.length - 2 &&
                        pageNumberArray.length > 6
                      "
                      [hidden]="
                        currentPage >=
                          pageNumberArray[pageNumberArray.length - 2] ||
                        totalData <
                          serialNumberArray[serialNumberArray.length - 1]
                      "
                      class="page-item"
                    >
                      <a
                        (click)="moveToPage(currentPage + 2)"
                        tabindex="0"
                        class="page-link"
                        href="javascript:void(0);"
                      >
                        ...
                      </a>
                    </li>
                  </ng-container>

                  <li
                    class="page-item"
                    [ngClass]="{
                      disabled:
                        currentPage ===
                          pageNumberArray[pageNumberArray.length - 1] ||
                        datas.length === 0
                    }"
                  >
                    <a
                      (click)="getMoreData('next')"
                      class="page-link"
                      href="javascript:void(0);"
                      >Next<i class="fa fa-angle-double-left ms-2"></i>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Add Asset -->
<div [ngClass]="{ 'open-filter': Toggledata === true }" class="toggle-sidebar">
  <div class="sidebar-layout-filter">
    <div class="sidebar-header">
      <h5>Filter</h5>
      <a (click)="open()" href="javascript:void(0);" class="sidebar-closes"
        ><i class="fa-regular fa-circle-xmark"></i
      ></a>
    </div>
    <div class="sidebar-body">
      <form action="#" autocomplete="off">
        <!-- Customer -->
        <div class="accordion" id="accordionMain1">
          <div class="card-header-new" id="headingOne">
            <h6 class="filter-title">
              <a
                href="javascript:void(0);"
                class="w-100"
                data-bs-toggle="collapse"
                data-bs-target="#collapseOne"
                aria-expanded="true"
                aria-controls="collapseOne"
              >
                Vendors
                <span class="float-end"
                  ><i class="fa-solid fa-chevron-down"></i
                ></span>
              </a>
            </h6>
          </div>

          <div
            id="collapseOne"
            class="collapse show"
            aria-labelledby="headingOne"
            data-bs-parent="#accordionExample1"
          >
            <div class="card-body-chat">
              <div class="row">
                <div class="col-md-12">
                  <div id="checkBoxes1">
                    <div class="form-custom">
                      <input
                        type="text"
                        class="form-control"
                        id="member_search1"
                        placeholder="Search here"
                      />
                      <span
                        ><img src="assets/img/icons/search.svg" alt="img"
                      /></span>
                    </div>
                    <div class="selectBox-cont">
                      <label htmlFor="label" class="custom_check w-100">
                        <input id="label" type="checkbox" name="username" />
                        <span class="checkmark"></span> Brian Johnson
                      </label>
                      <label htmlFor="label" class="custom_check w-100">
                        <input id="label" type="checkbox" name="username" />
                        <span class="checkmark"></span> Russell Copeland
                      </label>
                      <label htmlFor="label" class="custom_check w-100">
                        <input id="label" type="checkbox" name="username" />
                        <span class="checkmark"></span> Greg Lynch
                      </label>
                      <label htmlFor="label" class="custom_check w-100">
                        <input id="label" type="checkbox" name="username" />
                        <span class="checkmark"></span> John Blair
                      </label>
                      <!-- View All -->
                      <div class="view-content">
                        <div
                          class="viewall-One"
                          *ngFor="let user of users"
                          [ngClass]="{
                            closed: !isCollapsed,
                            open: isCollapsed
                          }"
                        >
                          <label htmlFor="label" class="custom_check w-100">
                            <input
                              id="label"
                              type="checkbox"
                              name="username"
                              [(ngModel)]="user.checked"
                            />
                            <span class="checkmark"></span> {{ user.name }}
                          </label>
                        </div>
                        <div class="view-all">
                          <a
                            href="javascript:void(0);"
                            class="viewall-button-One"
                            (click)="toggleCollapse()"
                            ><span class="me-2">{{
                              isCollapsed ? "Close" : "View all"
                            }}</span
                            ><span
                              ><i class="fa fa-circle-chevron-down"></i></span
                          ></a>
                        </div>
                      </div>
                      <!-- /View All -->
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /Customer -->

        <div class="filter-buttons">
          <button
            type="submit"
            class="d-inline-flex align-items-center justify-content-center btn w-100 btn-primary"
          >
            Apply
          </button>
          <button
            type="submit"
            class="d-inline-flex align-items-center justify-content-center btn w-100 btn-secondary"
          >
            Reset
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
<!--/Add Asset -->

<!-- Add Vendor Modal -->
<div class="modal custom-modal fade" id="add_vendor" role="dialog">
  <div class="modal-dialog modal-dialog-centered modal-md">
    <div class="modal-content">
      <div class="modal-header border-0 pb-0">
        <div class="form-header modal-header-title text-start mb-0">
          <h4 class="mb-0">Add Vendor</h4>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-lg-12 col-sm-12">
            <div class="input-block mb-3">
              <label>Name</label>
              <input type="text" class="form-control" placeholder="Enter Name">
            </div>
          </div>
          <div class="col-lg-12 col-sm-12">
            <div class="input-block mb-3">
              <label>Email</label>
              <input type="text" class="form-control" placeholder="Enter Email Address">
            </div>
          </div>
          <div class="col-lg-12 col-sm-12">
            <div class="input-block mb-3">
              <label>Phone Number</label>
              <input type="number" class="form-control" placeholder="Enter Phone Number">
            </div>
          </div>
          <div class="col-lg-12 col-sm-12">
            <div class="input-block mb-0">
              <label>Closing Balance</label>
              <input type="number" class="form-control" placeholder="Enter Closing Balance Amount">
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <a href="#" data-bs-dismiss="modal" class="btn btn-back cancel-btn me-2">Cancel</a>
        <a href="#" data-bs-dismiss="modal" class="btn btn-primary paid-continue-btn">Add Vendor</a>
      </div>
    </div>
  </div>
</div>
<!-- /Add Vendor Modal -->

<!-- Edit Vendor Modal -->
<div class="modal custom-modal fade" id="edit_vendor" role="dialog">
  <div class="modal-dialog modal-dialog-centered modal-md">
    <div class="modal-content">
      <div class="modal-header border-0 pb-0">
        <div class="form-header modal-header-title text-start mb-0">
          <h4 class="mb-0">Edit Vendor</h4>
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="input-block mb-3">
              <label>Name</label>
              <input type="text" class="form-control" value="John Smith" placeholder="Enter Name">
            </div>
          </div>
          <div class="col-lg-12 col-md-12">
            <div class="input-block mb-3">
              <label>Email</label>
              <input type="text" class="form-control" value="john@example.com" placeholder="Select Date">
            </div>
          </div>
          <div class="col-lg-12 col-md-12">
            <div class="input-block mb-3">
              <label>Phone Number</label>
              <input type="text" class="form-control" value="+1 989-438-3131" placeholder="Enter Reference Number">
            </div>
          </div>
          <div class="col-lg-12 col-md-12">
            <div class="input-block mb-0">
              <label>Balance</label>
              <input type="text" class="form-control" value="$4200" placeholder="Enter Reference Number">
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <a href="#" data-bs-dismiss="modal" class="btn btn-back cancel-btn me-2">Cancel</a>
        <a href="#" data-bs-dismiss="modal" class="btn btn-primary paid-continue-btn">Update</a>
      </div>
    </div>
  </div>
</div>
<!-- /Edit Vendor Modal -->

<!-- Delete Items Modal -->
<div class="modal custom-modal fade" id="delete_modal" role="dialog">
  <div class="modal-dialog modal-dialog-centered modal-md">
    <div class="modal-content">
      <div class="modal-body">
        <div class="form-header">
          <h3>Delete Vendor</h3>
          <p>Are you sure want to delete?</p>
        </div>
        <div class="modal-btn delete-action">
          <div class="row">
            <div class="col-6">
              <button type="reset" data-bs-dismiss="modal" class="w-100 btn btn-primary paid-continue-btn">Delete</button>
            </div>
            <div class="col-6">
              <button type="submit" data-bs-dismiss="modal" class="w-100 btn btn-primary paid-cancel-btn">Cancel</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /Delete Items Modal -->
