// kanakku-v1.9.9/vuejs-files/template/src/views/pages/purchases/purchases.vue
<template>
  <!-- Main Wrapper -->
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>
    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <blogheader :title="title" :path="path" :text="text" />

        <!-- Search Filter -->
        <div id="filter_inputs" class="card filter-card">
          <div class="card-body pb-0">
            <div class="row">
              <div class="col-sm-6 col-md-3">
                <div class="form-group">
                  <label>Name</label>
                  <input type="text" class="form-control" />
                </div>
              </div>
              <div class="col-sm-6 col-md-3">
                <div class="form-group">
                  <label>Email</label>
                  <input type="text" class="form-control" />
                </div>
              </div>
              <div class="col-sm-6 col-md-3">
                <div class="form-group">
                  <label>Phone</label>
                  <input type="text" class="form-control" />
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /Search Filter -->

        <!-- Table -->
        <div class="row">
          <div class="col-sm-12">
            <div class="card-table">
              <div class="card-body">
                <div class="table-responsive">
                  <a-table
                    class="stripped table-hover"
                    :columns="columns"
                    :data-source="data"
                    @change="onChange"
                  >
                    <template #bodyCell="{ column, record }">
                      <template v-if="column.key === 'id'">
                        <h2 class="table-avatar">
                          <router-link to="profile" class="avatar avatar-sm me-2"
                            ><img
                              class="avatar-img rounded-circle"
                              :src="require(`@/assets/img/profiles/${record.img}`)"
                              alt="User Image"
                          /></router-link>
                          <router-link to="profile"
                            >{{ record.Vendor }}<span>{{ record.num }}</span></router-link
                          >
                        </h2>
                      </template>
                      <template v-else-if="column.key === 'Status'">
                        <span
                          class="badge bg-success-light text-success-light"
                          v-if="record.Status === 'Paid'"
                          >{{ record.Status }}</span
                        >
                        <span
                          class="badge bg-warning-light text-warning-light"
                          v-else-if="record.Status === 'Pending'"
                          >{{ record.Status }}</span
                        >
                        <span
                          class="badge bg-danger-light"
                          v-else-if="record.Status === 'Cancelled'"
                          >{{ record.Status }}</span
                        >
                      </template>
                      <template v-else-if="column.key === 'Action'">
                        <div class="d-flex align-items-center">
                          <div class="dropdown dropdown-action">
                            <a
                              href="javascript:;"
                              class="btn-action-icon"
                              data-bs-toggle="dropdown"
                              aria-expanded="false"
                              ><i class="fas fa-ellipsis-v"></i
                            ></a>
                            <div class="dropdown-menu dropdown-menu-right">
                              <ul>
                                <li>
                                  <router-link class="dropdown-item" to="edit-purchases"
                                    ><i class="far fa-eye me-2"></i>Edit</router-link
                                  >
                                </li>
                                <li>
                                  <a
                                    class="dropdown-item"
                                    href="javascript:void(0);"
                                    data-bs-toggle="modal"
                                    data-bs-target="#delete_modal"
                                    ><i class="far fa-trash-alt me-2"></i>Delete</a
                                  >
                                </li>
                                <li>
                                  <router-link
                                    class="dropdown-item"
                                    to="purchases-details"
                                    ><i class="far fa-eye me-2"></i>View</router-link
                                  >
                                </li>
                              </ul>
                            </div>
                          </div>
                        </div>
                      </template>
                    </template>
                  </a-table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /Table -->
      </div>
    </div>
    <!-- /Page Wrapper -->
    <locationmodal :title1="title1" />
  </div>
  <!-- /Main Wrapper -->
</template>
<script>
const columns = [
  {
    title: "#",
    dataIndex: "NUM",
    sorter: {
      compare: (a, b) => {
        a = a.NUM.toLowerCase();
        b = b.NUM.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Purchase ID",
    dataIndex: "PurchaseID",
    sorter: (a, b) => a.PurchaseID.localeCompare(b.PurchaseID),
  },
  {
    title: "Vendor",
    dataIndex: "Vendor",
    key: "id",
    sorter: (a, b) => a.Vendor.localeCompare(b.Vendor),
  },
  {
    title: "Amount",
    dataIndex: "Amount",
    sorter: {
      compare: (a, b) => {
        a = a.Amount.toLowerCase();
        b = b.Amount.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Payment Mode",
    dataIndex: "PaymentMode",
    sorter: {
      compare: (a, b) => {
        a = a.PaymentMode.toLowerCase();
        b = b.PaymentMode.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Date",
    dataIndex: "Date",
    sorter: {
      compare: (a, b) => {
        a = a.Date.toLowerCase();
        b = b.Date.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Status",
    dataIndex: "Status",
    key: "Status",
    sorter: {
      compare: (a, b) => {
        a = a.Status.toLowerCase();
        b = b.Status.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },

  {
    title: "Action",
    key: "Action",
    sorter: true,
  },
];
const data = [
  {
    NUM: "1",
    img: "avatar-02.jpg",
    num: "+1 843-443-3282",
    PurchaseID: "#25689825",
    Vendor: "John Smith",
    Amount: "$1,54,220",
    PaymentMode: "Cash",
    Date: "19 Dec 2022, 06:12 PM",
    Status: "Paid",
  },
  {
    NUM: "2",
    img: "avatar-03.jpg",
    num: "+1 917-409-0861",
    PurchaseID: "#25689826",
    Vendor: "Johnny",
    Amount: "$2,54,220",
    PaymentMode: "Cheque",
    Date: "19 Dec 2022, 06:12 PM",
    Status: "Pending",
  },
  {
    NUM: "3",
    img: "avatar-04.jpg",
    num: "+1 956-623-2880",
    PurchaseID: "#25689827",
    Vendor: "Robert",
    Amount: "$1,84,220",
    PaymentMode: "Cash",
    Date: "19 Dec 2022, 06:12 PM",
    Status: "Cancelled",
  },
  {
    NUM: "4",
    img: "avatar-05.jpg",
    num: "+1 707-439-1732",
    PurchaseID: "#25689828",
    Vendor: "Sharonda",
    Amount: "$6,54,220",
    PaymentMode: "Cheque",
    Date: "19 Dec 2022, 06:12 PM",
    Status: "Pending",
  },
  {
    NUM: "5",
    img: "avatar-07.jpg",
    num: "+1 559-741-9672",
    PurchaseID: "#25689829",
    Vendor: "Randall",
    Amount: "$3,54,220",
    PaymentMode: "Cash",
    Date: "19 Dec 2022, 06:12 PM",
    Status: "Paid",
  },
  {
    NUM: "6",
    img: "avatar-06.jpg",
    num: "+1 989-438-3131",
    PurchaseID: "#25689830",
    Vendor: "Pricilla",
    Amount: "$1,54,220",
    PaymentMode: "Cheque",
    Date: "19 Dec 2022, 06:12 PM",
    Status: "Paid",
  },
];
export default {
  data() {
    return {
      title: "Purchases",
      path: "add-purchases",
      text: "Add Purchases",
      title1: "Delete Purchases",
      data,
      columns,
    };
  },
};
</script>

// kanakku-v1.9.9/angular-files/template-rtl/src/app/feature-module/purchasepage/purchases/purchases.component.ts
import { Component, OnInit } from '@angular/core';
import { Sort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { DataService, routes } from 'src/app/core/core.index';
import { apiResultFormat, pageSelection, purchase } from 'src/app/core/models/models';

@Component({
  selector: 'app-purchases',
  templateUrl: './purchases.component.html',
  styleUrls: ['./purchases.component.scss']
})
export class PurchasesComponent implements OnInit {
  public routes = routes;
  isCollapsed = false;
  public purchase: Array<purchase> = [];
 
  public Toggledata  = false;
  dataSource!: MatTableDataSource<purchase>;
  public searchDataValue = '';
  // pagination variables
  public lastIndex = 0;
  public pageSize = 10;
  public totalData = 0;
  public skip = 0;
  public limit: number = this.pageSize;
  public pageIndex = 0;
  public serialNumberArray: Array<number> = [];
  public currentPage = 1;
  public pageNumberArray: Array<number> = [];
  public pageSelection: Array<pageSelection> = [];
  public totalPages = 0;
  //** / pagination variables
  

  constructor(private data: DataService) {}

  ngOnInit(): void {
    this.getTableData();
  }
  private getTableData(): void {
    this.purchase = [];
    this.serialNumberArray = [];

    this.data.getpurchase().subscribe((data: apiResultFormat) => {
      this.totalData = data.totalData;
      data.data.map((res: purchase, index: number) => {
        const serialNumber = index + 1;
        if (index >= this.skip && serialNumber <= this.limit) {
          res.sNo = serialNumber;
          this.purchase.push(res);
          this.serialNumberArray.push(serialNumber);
        }
      });
      this.dataSource = new MatTableDataSource<purchase>(this.purchase);
      this.calculateTotalPages(this.totalData, this.pageSize);
    });
  }
  public sortData(sort: Sort) {
    const data = this.purchase.slice();
    if (!sort.active || sort.direction === '') {
      this.purchase = data;
    } else {
      this.purchase = data.sort((a, b) => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const aValue = (a as any)[sort.active];
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const bValue = (b as any)[sort.active];
        return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
      });
    }
  }
  public getMoreData(event: string): void {
    if (event == 'next') {
      this.currentPage++;
      this.pageIndex = this.currentPage - 1;
      this.limit += this.pageSize;
      this.skip = this.pageSize * this.pageIndex;
      this.getTableData();
    } else if (event == 'previous') {
      this.currentPage--;
      this.pageIndex = this.currentPage - 1;
      this.limit -= this.pageSize;
      this.skip = this.pageSize * this.pageIndex;
      this.getTableData();
    }
  }
  public moveToPage(pageNumber: number): void {
    this.currentPage = pageNumber;
    this.skip = this.pageSelection[pageNumber - 1].skip;
    this.limit = this.pageSelection[pageNumber - 1].limit;
    if (pageNumber > this.currentPage) {
      this.pageIndex = pageNumber - 1;
    } else if (pageNumber < this.currentPage) {
      this.pageIndex = pageNumber + 1;
    }
    this.getTableData();
  }
  public PageSize(): void {
    this.pageSelection = [];
    this.limit = this.pageSize;
    this.skip = 0;
    this.currentPage = 1;
    this.getTableData();
  }
  private calculateTotalPages(totalData: number, pageSize: number): void {
    this.pageNumberArray = [];
    this.totalPages = totalData / pageSize;
    if (this.totalPages % 1 != 0) {
      this.totalPages = Math.trunc(this.totalPages + 1);
    }
    for (let i = 1; i <= this.totalPages; i++) {
      const limit = pageSize * i;
      const skip = limit - pageSize;
      this.pageNumberArray.push(i);
      this.pageSelection.push({ skip: skip, limit: limit });
    }
  }
  open() {
    this.Toggledata = !this.Toggledata;
   
  }
  users = [
    { name: 'Barbara Moore', checked: false },
    { name: 'Hendry Evan', checked: false },
    { name: 'Richard Miles', checked: false }
  ];
  
  toggleCollapse() {
    this.isCollapsed = !this.isCollapsed;
  }
  

}

<!-- Page Header -->
<div class="page-header">
    <div class="content-page-header">
      <h5>Purchases</h5>
      <div class="list-btn">
        <ul class="filter-list">
          <li>
            <a  (click)="open()" matTooltip="Filter"href="javascript:void(0);" class="btn btn-filters w-auto popup-toggle"><span class="me-2"><img src="assets/img/icons/filter-icon.svg" alt="filter"></span>Filter </a>
        </li>
        <li>
            <a class="btn-filters" matTooltip="Setting"href="javascript:void(0);"><span><i class="feather icon-settings"></i></span> </a>
        </li>
        <li>
            <a class="btn-filters"  matTooltip="Grid-View" href="javascript:void(0);"><span><i class="feather icon-grid"></i></span> </a>
        </li>
        <li>
            <a class="active btn-filters"  matTooltip="List-View" href="javascript:void(0);"><span><i class="feather icon-list"></i></span> </a>
        </li>
          <li>
            <a class="btn btn-primary" [routerLink]="routes.addpurchases"
              ><i class="fa fa-plus-circle me-2" aria-hidden="true"></i>Add
              Purchases</a
            >
          </li>
        </ul>
      </div>
    </div>
  </div>
  <!-- /Page Header -->
  
  <!-- Search Filter -->
  <div id="filter_inputs" class="card filter-card">
    <div class="card-body pb-0">
      <div class="row">
        <div class="col-sm-6 col-md-3">
          <div class="form-group">
            <label htmlFor="label">Name</label>
            <input id="label" type="text" class="form-control" />
          </div>
        </div>
        <div class="col-sm-6 col-md-3">
          <div class="form-group">
            <label htmlFor="label">Email</label>
            <input type="text" class="form-control" />
          </div>
        </div>
        <div class="col-sm-6 col-md-3">
          <div class="form-group">
            <label htmlFor="label">Phone</label>
            <input id="label" type="text" class="form-control" />
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /Search Filter -->
  
  <!-- Table -->
  <div class="row">
    <div class="col-sm-12">
      <div class="card-table">
        <div class="card-body">
          <div class="table-responsive">
            <div class="table-scroll">
            <table
              matSort
              (matSortChange)="sortData($event)"
              class="table table-stripped table-hover datatable"
            >
              <thead class="thead-light">
                <tr>
                  <th mat-sort-header="sNo">#</th>
                  <th mat-sort-header="id">Purchase ID</th>
                  <th mat-sort-header="person">Vendor</th>
                  <th mat-sort-header="totalamount">Amount</th>
                  <th mat-sort-header="paymentmode">Payment Mode</th>
                  <th mat-sort-header="date">Date</th>
                  <th mat-sort-header="status">Status</th>
                  <th mat-sort-header="action">Action</th>
                </tr>
              </thead>
              <tbody>
                <tr *ngFor="let data of purchase; let i = index">
                  <td>{{ data.sNo }}</td>
                 
                  <td><a [routerLink]="routes.purchasesdetails" class="invoice-link">{{ data.purchaseId }}</a>	</td>
                  <td>
                    <h2 class="table-avatar">
                      <a
                        [routerLink]="routes.profile"
                        class="avatar avatar-sm me-2"
                        ><img
                          class="avatar-img rounded-circle"
                          [src]="data.img"
                          alt="User Image"
                      /></a>
                      <a [routerLink]="routes.profile"
                        >{{ data.person }} <span>{{ data.phone }}</span></a
                      >
                    </h2>
                  </td>
                  <td>{{ data.totalAmount }}</td>
                  <td>{{ data.paymentmode }}</td>
                  <td>{{ data.date }}</td>
                  <td>
                    <span
                      [ngClass]="{
                        'bg-success-light text-success-light':
                          data.status === 'Paid',
                        'bg-warning-light text-warning-light':
                          data.status === 'Pending',
                        'bg-danger-light': data.status === 'Cancelled'
                      }"
                      class="badge badge-pill"
                      >{{ data.status }}</span
                    >
                  </td>
                  <td class="d-flex align-items-center">
                    <div class="dropdown dropdown-action">
                      <a
                        href="#"
                        class="btn-action-icon"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                        ><i class="fas fa-ellipsis-v"></i
                      ></a>
                     
                    
                      <div class="dropdown-menu dropdown-menu-right credit-note-dropdown">
                          <ul>
                              <li>
                                  <a class="dropdown-item"  [routerLink]="routes.editpurchases"><i class="far fa-edit me-2"></i>Edit</a>
                              </li>
                              <li>
                                  <a class="dropdown-item" href="javascript:void(0);" data-bs-toggle="modal" data-bs-target="#delete_modal"><i class="far fa-trash-alt me-2"></i>Delete</a>
                              </li>
                              <li>
                                  <a class="dropdown-item"  [routerLink]="routes.purchasesdetails"><i class="far fa-eye me-2"></i>View</a>
                              </li>
                              <li>
                                  <a class="dropdown-item"[routerLink]="routes.purchase"><i class="feather icon-download me-2"></i>Download</a>
                              </li>
                              <li>
                                  <a class="dropdown-item" [routerLink]="routes.purchase"><i class="feather icon-send me-2"></i>Send</a>
                              </li>
                              <li>
                                  <a class="dropdown-item" [routerLink]="routes.addpurchasereturn"><i class="fe feather icon-file-text me-2"></i>Convert to Purchase Return</a>
                              </li>										
                          </ul>
                      </div>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
            <div class="table_header">
              <div class="row">
                <div class="col-sm-12 col-md-6">
                  <div class="dataTables_length">
                    <label>
                      Show
                      <select
                        [(ngModel)]="pageSize"
                        (ngModelChange)="PageSize()"
                        class="form-control form-control-sm"
                      >
                        <option value="10">10</option>
                        <option value="25">25</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                      </select>
                      Entries
                    </label>
                  </div>
                </div>
              </div>
              <div class="col-sm-12 col-md-3">
                <div class="pagination_section">
                  <ul class="pagination">
                    <li
                      class="page-item"
                      [ngClass]="{
                        disabled: currentPage === 1
                      }"
                    >
                      <a
                        (click)="getMoreData('previous')"
                        class="page-link"
                        href="javascript:void(0);"
                        tabindex="-1"
                        ><i class="fa fa-angle-double-right me-2"></i>Previous</a
                      >
                    </li>
  
                    <ng-container
                      *ngFor="let item of pageNumberArray; let i = index"
                    >
                      <li
                        class="page-item"
                        [class.active]="item === currentPage"
                        [ngClass]="
                          (pageNumberArray[currentPage - 2] > item &&
                            item !== 1 &&
                            pageNumberArray.length > 6) ||
                          (pageNumberArray[currentPage] < item &&
                            item !== 1 &&
                            pageNumberArray.length > 6 &&
                            pageNumberArray.length !== item)
                            ? 'hide-sub-menu'
                            : 'show-sub-menu'
                        "
                      >
                        <a
                          (click)="moveToPage(item)"
                          class="page-link"
                          href="javascript:void(0);"
                        >
                          {{ item }}
                          <span *ngIf="item === currentPage" class="sr-only"
                            >(current)</span
                          >
                        </a>
                      </li>
                      <li
                        class="page-item"
                        *ngIf="
                          i === 0 && pageNumberArray.length > 6 && currentPage > 2
                        "
                        [hidden]="currentPage === 1"
                      >
                        <a
                          (click)="moveToPage(currentPage - 2)"
                          tabindex="0"
                          class="page-link"
                          href="javascript:void(0);"
                        >
                          ...
                        </a>
                      </li>
                      <li
                        *ngIf="
                          i === pageNumberArray.length - 2 &&
                          pageNumberArray.length > 6
                        "
                        [hidden]="
                          currentPage >=
                            pageNumberArray[pageNumberArray.length - 2] ||
                          totalData <
                            serialNumberArray[serialNumberArray.length - 1]
                        "
                        class="page-item"
                      >
                        <a
                          (click)="moveToPage(currentPage + 2)"
                          class="page-link"
                          href="javascript:void(0);"
                        >
                          ...
                        </a>
                      </li>
                    </ng-container>
  
                    <li
                      class="page-item"
                      [ngClass]="{
                        disabled:
                          currentPage ===
                            pageNumberArray[pageNumberArray.length - 1] ||
                          purchase.length === 0
                      }"
                    >
                      <a
                        (click)="getMoreData('next')"
                        class="page-link"
                        href="javascript:void(0);"
                        >Next<i class="fa fa-angle-double-left ms-2"></i>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /Table -->
  
 
  <!-- Add Asset -->
  <div  [ngClass]="{ 'open-filter': Toggledata === true }" class="toggle-sidebar">
    <div class="sidebar-layout-filter">
      <div class="sidebar-header">
        <h5>Filter</h5>
        <a href="javascript:void(0);"  (click)="open()"class="sidebar-closes"><i class="fa-regular fa-circle-xmark"></i></a>
      </div>
      <div class="sidebar-body">						
        <form action="#" autocomplete="off">
          <!-- Customer -->
          <div class="accordion" id="accordionMain1">
            <div class="card-header-new" id="headingOne">
              <h6 class="filter-title">
              <a href="javascript:void(0);" class="w-100" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Vendor
                <span class="float-end"><i class="fa-solid fa-chevron-down"></i></span>
              </a> 
              </h6>
            </div>
          
            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne"  data-bs-parent="#accordionExample1">
              <div class="card-body-chat">
                <div class="row">
                  <div class="col-md-12">
                    <div id="checkBoxes1">
                      <div class="form-custom">														
                        <input type="text" class="form-control" id="member_search1" placeholder="Search Vendor">
                        <span><img src="assets/img/icons/search.svg" alt="img"></span>
                      </div>
                      <div class="selectBox-cont">
                        <label class="custom_check w-100">
                          <input type="checkbox" name="username">
                          <span class="checkmark"></span>  Brian Johnson
                        </label>
                        <label class="custom_check w-100">
                          <input type="checkbox" name="username">
                          <span class="checkmark"></span>  Russell Copeland
                        </label>
                        <label class="custom_check w-100">
                          <input type="checkbox" name="username">
                          <span class="checkmark"></span>  Greg Lynch
                        </label>
                        <label class="custom_check w-100">
                          <input type="checkbox" name="username">
                          <span class="checkmark"></span> John Blair
                        </label>
                       <!-- View All -->
                      <div class="view-content">
                        <div
                          class="viewall-One"
                          *ngFor="let user of users"
                          [ngClass]="{
                            closed: !isCollapsed,
                            open: isCollapsed
                          }"
                        >
                          <label class="custom_check w-100">
                            <input
                              type="checkbox"
                              name="username"
                              [(ngModel)]="user.checked"
                            />
                            <span class="checkmark"></span> {{ user.name }}
                          </label>
                        </div>
                        <div class="view-all">
                          <a
                            href="javascript:void(0);"
                            class="viewall-button-One"
                            (click)="toggleCollapse()"
                            ><span class="me-2">{{
                              isCollapsed ? "Close" : "View All"
                            }}</span
                            ><span
                              ><i class="fa fa-circle-chevron-down"></i></span
                          ></a>
                        </div>
                      </div>
                      <!-- /View All -->
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- /Customer -->

          <!-- By Status -->
          <div class="accordion" id="accordionMain3">
            <div class="card-header-new" id="headingThree">
              <h6 class="filter-title">
              <a href="javascript:void(0);" class="w-100 collapsed"  data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                Purchase Id	
                <span class="float-end"><i class="fa-solid fa-chevron-down"></i></span>
              </a> 
              </h6>
            </div>
          
            <div id="collapseThree" class="collapse" aria-labelledby="headingThree"  data-bs-parent="#accordionExample3">
              <div class="card-body-chat">
                <div id="checkBoxes2">											
                  <div class="selectBox-cont">
                    <label class="custom_check w-100">
                      <input type="checkbox" name="bystatus">
                      <span class="checkmark"></span> 4905681
                    </label>
                    <label class="custom_check w-100">
                      <input type="checkbox" name="bystatus">
                      <span class="checkmark"></span>  4905682
                    </label>
                    <label class="custom_check w-100">
                      <input type="checkbox" name="bystatus">
                      <span class="checkmark"></span>  4905683
                    </label>
                    <label class="custom_check w-100">
                      <input type="checkbox" name="bystatus">
                      <span class="checkmark"></span> 4905684
                    </label>
                    <label class="custom_check w-100">
                      <input type="checkbox" name="bystatus">
                      <span class="checkmark"></span> 4905685
                    </label>
                    <label class="custom_check w-100">
                      <input type="checkbox" name="bystatus">
                      <span class="checkmark"></span> 4905686
                    </label>
                  </div>
                </div>	
              </div>
            </div>
          </div>
          <!-- /By Status -->

          <!-- Category -->
          <div class="accordion accordion-last" id="accordionMain4">
            <div class="card-header-new" id="headingFour">
              <h6 class="filter-title">
              <a href="javascript:void(0);" class="w-100 collapsed"  data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="true" aria-controls="collapseFour">
                Payment Method
                <span class="float-end"><i class="fa-solid fa-chevron-down"></i></span>
              </a> 
              </h6>
            </div>
          
            <div id="collapseFour" class="collapse" aria-labelledby="headingFour"  data-bs-parent="#accordionExample4">
              <div class="card-body-chat">
                <div id="checkBoxes3">
                  <div class="selectBox-cont">
                    <label class="custom_check w-100">
                      <input type="checkbox" name="category">
                      <span class="checkmark"></span> Cash
                    </label>
                    <label class="custom_check w-100">
                      <input type="checkbox" name="category">
                      <span class="checkmark"></span>  Cheque
                    </label>
                  </div>
                </div>	
              </div>
            </div>
          </div>
          <!-- /Category -->

          <div class="filter-buttons">
            <button type="submit" class="d-inline-flex align-items-center justify-content-center btn w-100 btn-primary">
              Apply
            </button>
            <button type="submit" class="d-inline-flex align-items-center justify-content-center btn w-100 btn-secondary">
              Reset
            </button>
          </div>
        </form>
        
      </div>
    </div>
  </div>	
  <!--/Add Asset -->	
  
  <!-- Delete Items Modal -->
  <div class="modal custom-modal fade" id="delete_modal" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-md">
      <div class="modal-content">
        <div class="modal-body">
          <div class="form-header">
            <h3>Delete Purchases</h3>
            <p>Are you sure want to delete?</p>
          </div>
          <div class="modal-btn delete-action">
            <div class="row">
              <div class="col-6">
                <button
                  type="reset"
                  data-bs-dismiss="modal"
                  class="w-100 btn btn-primary paid-continue-btn"
                >
                  Delete
                </button>
              </div>
              <div class="col-6">
                <button
                  type="submit"
                  data-bs-dismiss="modal"
                  class="w-100 btn btn-primary paid-cancel-btn"
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /Delete Items Modal -->
