// kanakku-v1.9.9/vuejs-files/template/src/views/pages/uiinterface/baseui/alerts.vue
<template>
  <!-- Main Wrapper -->
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>

    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <componentheader :title="title" />
        <!-- Alerts -->
        <div class="card bg-white">
          <div class="card-body">
            <b-alert show dismissible variant="primary">
              <strong>Holy guacamole!</strong> You should check in on some of those fields
              below.
            </b-alert>
            <b-alert show dismissible variant="secondary">
              <strong>Holy guacamole!</strong> You should check in on some of those fields
              below.
            </b-alert>
            <b-alert show dismissible variant="success">
              <strong>Holy guacamole!</strong> You should check in on some of those fields
              below.
            </b-alert>
            <b-alert show dismissible variant="danger">
              <strong>Holy guacamole!</strong> You should check in on some of those fields
              below.
            </b-alert>
            <b-alert show dismissible variant="warning">
              <strong>Holy guacamole!</strong> You should check in on some of those fields
              below.
            </b-alert>
            <b-alert show dismissible variant="info">
              <strong>Holy guacamole!</strong> You should check in on some of those fields
              below.
            </b-alert>
            <b-alert show dismissible variant="light">
              <strong>Holy guacamole!</strong> You should check in on some of those fields
              below.
            </b-alert>
            <b-alert show dismissible variant="dark">
              <strong>Holy guacamole!</strong> You should check in on some of those fields
              below.
            </b-alert>
          </div>
        </div>
        <!-- /Alerts -->
      </div>
    </div>
    <!-- /Page Wrapper -->
  </div>
  <!-- /Main Wrapper -->
</template>
<script>
export default {
  data() {
    return {
      title: "Alert",
    };
  },
};
</script>

// kanakku-v1.9.9/angular-files/template/src/app/feature-module/ui-interface/base-ui/alerts/alerts.component.ts
import { Component } from '@angular/core';
import { routes } from 'src/app/core/core.index';

@Component({
  selector: 'app-alerts',
  templateUrl: './alerts.component.html',
  styleUrls: ['./alerts.component.scss'],
})
export class AlertsComponent {
  public routes = routes;

}

<!-- Page Header -->
<div class="page-header">
  <div class="content-page-header">
    <h5>Alert</h5>
  </div>	
</div>
<!-- /Page Header -->	
<!-- Alerts -->
<div class="card bg-white">
  <div class="card-body">
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
      <strong>Holy guacamole!</strong> You should check in on some of those
      fields below.
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    <div class="alert alert-secondary alert-dismissible fade show" role="alert">
      <strong>Holy guacamole!</strong> You should check in on some of those
      fields below.
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <strong>Holy guacamole!</strong> You should check in on some of those
      fields below.
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong>Holy guacamole!</strong> You should check in on some of those
      fields below.
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>Holy guacamole!</strong> You should check in on some of those
      fields below.
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      <strong>Holy guacamole!</strong> You should check in on some of those
      fields below.
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    <div class="alert alert-light alert-dismissible fade show" role="alert">
      <strong>Holy guacamole!</strong> You should check in on some of those
      fields below.
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    <div class="alert alert-dark alert-dismissible fade show mb-0" role="alert">
      <strong>Holy guacamole!</strong> You should check in on some of those
      fields below.
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
  </div>
</div>
<!-- /Alerts -->
