// kanakku-v1.9.9/angular-files/template/src/app/feature-module/authentication/forgot-password/forgot-password.component.ts
import { Component} from '@angular/core';
import { FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService, routes } from 'src/app/core/core.index';

@Component({
  selector: 'app-forgot-password',
  templateUrl: './forgot-password.component.html',
  styleUrls: ['./forgot-password.component.scss'],
})
export class ForgotPasswordComponent  {
  public routes = routes;
  public isValidConfirmPassword = false;
  public CustomControler: undefined;
  

  form = new FormGroup({
    email: new FormControl('', [Validators.required, Validators.email]),
    password: new FormControl('', [Validators.required]),
    confirmPassword: new FormControl('', [Validators.required]),
  });

  get f() {
    return this.form.controls;
  }

  constructor(private router: Router, private auth: AuthService) {}

  submit() {
    if (this.form.value.password != this.form.value.confirmPassword) {
      this.isValidConfirmPassword = true;
    } else {
      this.isValidConfirmPassword = false;
      this.auth.login();
    }
  }
 
}

<!-- Main Wrapper -->
<div class="main-wrapper login-body">
  <div class="login-wrapper">
    <div class="container">
      <img
        class="img-fluid logo-dark mb-2"
        src="assets/img/logo.png"
        alt="Logo"
      />

      <div class="loginbox">
        <div class="login-right">
          <div class="login-right-wrap">
            <h1>Forgot Password?</h1>
            <p class="account-subtitle">
              Enter your email to get a password reset link
            </p>

            <!-- Form -->
            <form [formGroup]="form" (ngSubmit)="submit()">
              <div class="input-block mb-3">
                <label htmlFor="label" class="form-control-label">Email Address</label>
                <input id="label"  class="form-control" type="text" />
              </div>
              <div class="input-block mb-3 mb-0">
                <button
                  class="btn btn-lg btn-block btn-primary w-100"
                  type="button"
                >
                  Reset Password
                </button>
              </div>
            </form>
            <!-- /Form -->

            <div class="text-center dont-have">
              Remember your password? <a [routerLink]="routes.login">Login</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /Main Wrapper -->

// kanakku-v1.9.9/vuejs-files/template/src/views/pages/auth/forgotpassword.vue
<template>
  <!-- Main Wrapper -->
  <div class="main-wrapper login-body">
    <div class="login-wrapper">
      <div class="container">
        <img class="img-fluid logo-dark mb-2" src="@/assets/img/logo2.png" alt="Logo" />

        <div class="loginbox">
          <div class="login-right">
            <div class="login-right-wrap">
              <h1>Forgot Password?</h1>
              <p class="account-subtitle">
                Enter your email to get a password reset link
              </p>

              <!-- Form -->
              <b-form>
                <div class="form-group">
                  <label class="form-control-label">Email Address</label>
                  <input class="form-control" type="text" />
                </div>
                <div class="form-group mb-0">
                  <button
                    class="btn btn-lg btn-block btn-primary w-100"
                    type="button"
                    @click="$router.push('/')"
                  >
                    Reset Password
                  </button>
                </div>
              </b-form>
              <!-- /Form -->

              <div class="text-center dont-have">
                Remember your password? <router-link to="/">Login</router-link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /Main Wrapper -->
</template>
