// kanakku-v1.9.9/vuejs-files/template/src/views/pages/applications/inbox.vue
<template>
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>

    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <!-- Page Header -->
        <div class="page-header">
          <div class="content-page-header">
            <h5>Inbox</h5>
          </div>
        </div>
        <!-- /Page Header -->

        <div class="row">
          <div class="col-lg-3 col-md-4">
            <div class="card">
              <div class="card-body">
                <div class="compose-btn">
                  <a href="javascript:void(0);" class="btn btn-primary btn-block w-100">
                    Compose
                  </a>
                </div>
                <ul class="inbox-menu">
                  <li class="active">
                    <a href="javascript:;"
                      ><i class="fas fa-download"></i> Inbox
                      <span class="mail-count">(5)</span></a
                    >
                  </li>
                  <li>
                    <a href="javascript:;"><i class="far fa-star"></i> Important</a>
                  </li>
                  <li>
                    <a href="javascript:;"
                      ><i class="far fa-paper-plane"></i> Sent Mail</a
                    >
                  </li>
                  <li>
                    <a href="javascript:;"
                      ><i class="far fa-file-alt"></i> Drafts
                      <span class="mail-count">(13)</span></a
                    >
                  </li>
                  <li>
                    <a href="javascript:;" class="pb-0 mb-0"
                      ><i class="far fa-trash-alt"></i> Trash</a
                    >
                  </li>
                </ul>
              </div>
            </div>
          </div>

          <div class="col-lg-9 col-md-8">
            <div class="card bg-white">
              <div class="card-body">
                <div class="email-header">
                  <div class="row">
                    <div class="col top-action-left">
                      <div class="float-left">
                        <div class="btn-group dropdown-action">
                          <button
                            type="button"
                            class="btn btn-white-outline dropdown-toggle me-1"
                            data-bs-toggle="dropdown"
                          >
                            Select <i class="fas fa-angle-down"></i>
                          </button>
                          <div class="dropdown-menu">
                            <a class="dropdown-item" href="javascript:;">All</a>
                            <a class="dropdown-item" href="javascript:;">None</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="javascript:;">Read</a>
                            <a class="dropdown-item" href="javascript:;">Unread</a>
                          </div>
                        </div>
                        <div class="btn-group dropdown-action">
                          <button
                            type="button"
                            class="btn btn-white-outline dropdown-toggle me-1"
                            data-bs-toggle="dropdown"
                          >
                            Actions <i class="fas fa-angle-down"></i>
                          </button>
                          <div class="dropdown-menu">
                            <a class="dropdown-item" href="javascript:;">Reply</a>
                            <a class="dropdown-item" href="javascript:;">Forward</a>
                            <a class="dropdown-item" href="javascript:;">Archive</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="javascript:;">Mark As Read</a>
                            <a class="dropdown-item" href="javascript:;"
                              >Mark As Unread</a
                            >
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="javascript:;">Delete</a>
                          </div>
                        </div>
                        <div class="btn-group dropdown-action">
                          <button
                            type="button"
                            class="btn btn-white-outline dropdown-toggle me-1"
                            data-bs-toggle="dropdown"
                          >
                            <i class="fas fa-folder me-1"></i>
                            <i class="fas fa-angle-down"></i>
                          </button>
                          <div role="menu" class="dropdown-menu">
                            <a class="dropdown-item" href="javascript:;">Social</a>
                            <a class="dropdown-item" href="javascript:;">Forums</a>
                            <a class="dropdown-item" href="javascript:;">Updates</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="javascript:;">Spam</a>
                            <a class="dropdown-item" href="javascript:;">Trash</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="javascript:;">New</a>
                          </div>
                        </div>
                        <div class="btn-group dropdown-action">
                          <button
                            type="button"
                            data-bs-toggle="dropdown"
                            class="btn btn-white-outline dropdown-toggle me-1"
                          >
                            <i class="fas fa-tags"></i> <i class="fas fa-angle-down"></i>
                          </button>
                          <div role="menu" class="dropdown-menu">
                            <a class="dropdown-item" href="javascript:;">Work</a>
                            <a class="dropdown-item" href="javascript:;">Family</a>
                            <a class="dropdown-item" href="javascript:;">Social</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="javascript:;">Primary</a>
                            <a class="dropdown-item" href="javascript:;">Promotions</a>
                            <a class="dropdown-item" href="javascript:;">Forums</a>
                          </div>
                        </div>
                        <div class="btn-group dropdown-action mail-search">
                          <input
                            type="text"
                            placeholder="Search Messages"
                            class="form-control search-message"
                          />
                        </div>
                      </div>
                    </div>
                    <div class="col-auto top-action-right">
                      <div class="text-end">
                        <button
                          type="button"
                          title="Refresh"
                          data-toggle="tooltip"
                          class="btn btn-white-outline d-none d-md-inline-block me-1"
                        >
                          <i class="fas fa-sync-alt"></i>
                        </button>
                        <div class="btn-group">
                          <a class="btn btn-white-outline"
                            ><i class="fas fa-angle-left"></i
                          ></a>
                          <a class="btn btn-white-outline"
                            ><i class="fas fa-angle-right"></i
                          ></a>
                        </div>
                      </div>
                      <div class="text-end">
                        <span class="text-muted d-none d-md-inline-block"
                          >Showing 10 of 112
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="email-content">
                  <div class="table-responsive">
                    <table class="table table-inbox table-hover">
                      <thead>
                        <tr>
                          <th colspan="6" class="py-3">
                            <input type="checkbox" class="checkbox-all" />
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr class="unread clickable-row">
                          <td>
                            <input type="checkbox" class="checkmail" />
                          </td>
                          <td>
                            <span class="mail-important"
                              ><i class="fas fa-star starred"></i
                            ></span>
                          </td>
                          <td class="name">John Doe</td>
                          <td class="subject">
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                          </td>
                          <td><i class="fas fa-paperclip"></i></td>
                          <td class="mail-date">13:14</td>
                        </tr>
                        <tr class="unread clickable-row">
                          <td>
                            <input type="checkbox" class="checkmail" />
                          </td>
                          <td>
                            <span class="mail-important"
                              ><i class="far fa-star"></i
                            ></span>
                          </td>
                          <td class="name">Envato Account</td>
                          <td class="subject">
                            Important account security update from Envato
                          </td>
                          <td></td>
                          <td class="mail-date">8:42</td>
                        </tr>
                        <tr class="clickable-row">
                          <td>
                            <input type="checkbox" class="checkmail" />
                          </td>
                          <td>
                            <span class="mail-important"
                              ><i class="far fa-star"></i
                            ></span>
                          </td>
                          <td class="name">Twitter</td>
                          <td class="subject">HRMS Bootstrap Admin Template</td>
                          <td></td>
                          <td class="mail-date">30 Nov</td>
                        </tr>
                        <tr class="unread clickable-row">
                          <td>
                            <input type="checkbox" class="checkmail" />
                          </td>
                          <td>
                            <span class="mail-important"
                              ><i class="far fa-star"></i
                            ></span>
                          </td>
                          <td class="name">Richard Parker</td>
                          <td class="subject">
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                          </td>
                          <td></td>
                          <td class="mail-date">18 Sep</td>
                        </tr>
                        <tr class="clickable-row">
                          <td>
                            <input type="checkbox" class="checkmail" />
                          </td>
                          <td>
                            <span class="mail-important"
                              ><i class="far fa-star"></i
                            ></span>
                          </td>
                          <td class="name">John Smith</td>
                          <td class="subject">
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                          </td>
                          <td></td>
                          <td class="mail-date">21 Aug</td>
                        </tr>
                        <tr class="clickable-row">
                          <td>
                            <input type="checkbox" class="checkmail" />
                          </td>
                          <td>
                            <span class="mail-important"
                              ><i class="far fa-star"></i
                            ></span>
                          </td>
                          <td class="name">me, Robert Smith (3)</td>
                          <td class="subject">
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                          </td>
                          <td></td>
                          <td class="mail-date">1 Aug</td>
                        </tr>
                        <tr class="unread clickable-row">
                          <td>
                            <input type="checkbox" class="checkmail" />
                          </td>
                          <td>
                            <span class="mail-important"
                              ><i class="far fa-star"></i
                            ></span>
                          </td>
                          <td class="name">Codecanyon</td>
                          <td class="subject">Welcome To Codecanyon</td>
                          <td></td>
                          <td class="mail-date">Jul 13</td>
                        </tr>
                        <tr class="clickable-row">
                          <td>
                            <input type="checkbox" class="checkmail" />
                          </td>
                          <td>
                            <span class="mail-important"
                              ><i class="far fa-star"></i
                            ></span>
                          </td>
                          <td class="name">Richard Miles</td>
                          <td class="subject">
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                          </td>
                          <td><i class="fas fa-paperclip"></i></td>
                          <td class="mail-date">May 14</td>
                        </tr>
                        <tr class="unread clickable-row">
                          <td>
                            <input type="checkbox" class="checkmail" />
                          </td>
                          <td>
                            <span class="mail-important"
                              ><i class="far fa-star"></i
                            ></span>
                          </td>
                          <td class="name">John Smith</td>
                          <td class="subject">
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                          </td>
                          <td></td>
                          <td class="mail-date">11/11/16</td>
                        </tr>
                        <tr class="clickable-row">
                          <td>
                            <input type="checkbox" class="checkmail" />
                          </td>
                          <td>
                            <span class="mail-important"
                              ><i class="far fa-star starred"></i
                            ></span>
                          </td>
                          <td class="name">Mike Litorus</td>
                          <td class="subject">
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                          </td>
                          <td></td>
                          <td class="mail-date">10/31/16</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /Main Wrapper -->
  </div>
</template>

// kanakku-v1.9.9/reactjs-files/template-rtl/src/application/Inbox.jsx
import React, { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import Header from "../layouts/Header";
import Sidebar from "../layouts/Sidebar";

const Inbox = (props) => {
  const [menu, setMenu] = useState(false);

  const toggleMobileMenu = () => {
    setMenu(!menu);
  };

  return (
    <>
      <div className={`main-wrapper ${menu ? "slide-nav" : ""}`}>
        <Header onMenuClick={(value) => toggleMobileMenu()} />
        <Sidebar />
        {/* Page Wrapper */}
		<div className="page-wrapper">
  <div className="content container-fluid">
    {/* Page Header */}
    <div className="page-header">
      <div className="content-page-header">
        <h5>Inbox</h5>
      </div>
    </div>
    {/* /Page Header */}
    <div className="row">
      <div className="col-lg-3 col-md-4">
        <div className="card">
          <div className="card-body">
            <div className="compose-btn">
              <Link 
                to="javascript:void(0);"
                className="btn btn-primary btn-block w-100"
              >
                Compose
              </Link>
            </div>
            <ul className="inbox-menu">
              <li className="active">
                <Link  to="#">
                  <i className="fas fa-download" /> Inbox{" "}
                  <span className="mail-count">(5)</span>
                </Link>
              </li>
              <li>
                <Link  to="#">
                  <i className="far fa-star" /> Important
                </Link>
              </li>
              <li>
                <Link  to="#">
                  <i className="far fa-paper-plane" /> Sent Mail
                </Link>
              </li>
              <li>
                <Link  to="#">
                  <i className="far fa-file-alt" /> Drafts{" "}
                  <span className="mail-count">(13)</span>
                </Link>
              </li>
              <li>
                <Link  to="#" className="pb-0 mb-0">
                  <i className="far fa-trash-alt" /> Trash
                </Link>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div className="col-lg-9 col-md-8">
        <div className="card bg-white">
          <div className="card-body">
            <div className="email-header">
              <div className="row">
                <div className="col top-action-left">
                  <div className="float-left">
                    <div className="btn-group dropdown-action">
                      <button
                        type="button"
                        className="btn btn-white-outline dropdown-toggle me-1"
                        data-bs-toggle="dropdown"
                      >
                        Select <i className="fas fa-angle-down" />
                      </button>
                      <div className="dropdown-menu">
                        <Link  className="dropdown-item" to="#">
                          All
                        </Link>
                        <Link  className="dropdown-item" to="#">
                          None
                        </Link>
                        <div className="dropdown-divider" />
                        <Link  className="dropdown-item" to="#">
                          Read
                        </Link>
                        <Link  className="dropdown-item" to="#">
                          Unread
                        </Link>
                      </div>
                    </div>
                    <div className="btn-group dropdown-action">
                      <button
                        type="button"
                        className="btn btn-white-outline dropdown-toggle me-1"
                        data-bs-toggle="dropdown"
                      >
                        Actions <i className="fas fa-angle-down" />
                      </button>
                      <div className="dropdown-menu">
                        <Link  className="dropdown-item" to="#">
                          Reply
                        </Link>
                        <Link  className="dropdown-item" to="#">
                          Forward
                        </Link>
                        <Link  className="dropdown-item" to="#">
                          Archive
                        </Link>
                        <div className="dropdown-divider" />
                        <Link  className="dropdown-item" to="#">
                          Mark As Read
                        </Link>
                        <Link  className="dropdown-item" to="#">
                          Mark As Unread
                        </Link>
                        <div className="dropdown-divider" />
                        <Link  className="dropdown-item" to="#">
                          Delete
                        </Link>
                      </div>
                    </div>
                    <div className="btn-group dropdown-action">
                      <button
                        type="button"
                        className="btn btn-white-outline dropdown-toggle me-1"
                        data-bs-toggle="dropdown"
                      >
                        <i className="fas fa-folder" />{" "}
                        <i className="fas fa-angle-down" />
                      </button>
                      <div role="menu" className="dropdown-menu">
                        <Link  className="dropdown-item" to="#">
                          Social
                        </Link>
                        <Link  className="dropdown-item" to="#">
                          Forums
                        </Link>
                        <Link  className="dropdown-item" to="#">
                          Updates
                        </Link>
                        <div className="dropdown-divider" />
                        <Link  className="dropdown-item" to="#">
                          Spam
                        </Link>
                        <Link  className="dropdown-item" to="#">
                          Trash
                        </Link>
                        <div className="dropdown-divider" />
                        <Link  className="dropdown-item" to="#">
                          New
                        </Link>
                      </div>
                    </div>
                    <div className="btn-group dropdown-action">
                      <button
                        type="button"
                        data-bs-toggle="dropdown"
                        className="btn btn-white-outline dropdown-toggle"
                      >
                        <i className="fas fa-tags" />{" "}
                        <i className="fas fa-angle-down" />
                      </button>
                      <div role="menu" className="dropdown-menu">
                        <Link  className="dropdown-item" to="#">
                          Work
                        </Link>
                        <Link  className="dropdown-item" to="#">
                          Family
                        </Link>
                        <Link  className="dropdown-item" to="#">
                          Social
                        </Link>
                        <div className="dropdown-divider" />
                        <Link  className="dropdown-item" to="#">
                          Primary
                        </Link>
                        <Link  className="dropdown-item" to="#">
                          Promotions
                        </Link>
                        <Link  className="dropdown-item" to="#">
                          Forums
                        </Link>
                      </div>
                    </div>
                    <div className="btn-group dropdown-action mail-search">
                      <input
                        type="text"
                        placeholder="Search Messages"
                        className="form-control search-message"
                      />
                    </div>
                  </div>
                </div>
                <div className="col-auto top-action-right">
                  <div className="text-end">
                    <button
                      type="button"
                      title="Refresh"
                      data-toggle="tooltip"
                      className="btn btn-white-outline d-none d-md-inline-block me-1"
                    >
                      <i className="fas fa-sync-alt" />
                    </button>
                    <div className="btn-group">
                      <Link  className="btn btn-white-outline">
                        <i className="fas fa-angle-left" />
                      </Link>
                      <Link  className="btn btn-white-outline">
                        <i className="fas fa-angle-right" />
                      </Link>
                    </div>
                  </div>
                  <div className="text-end">
                    <span className="text-muted d-none d-md-inline-block">
                      Showing 10 of 112{" "}
                    </span>
                  </div>
                </div>
              </div>
            </div>
            <div className="email-content">
              <div className="table-responsive">
                <table className="table table-inbox table-hover">
                  <thead>
                    <tr>
                      <th colSpan={6} className="py-3">
                        <input type="checkbox" className="checkbox-all" />
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="unread clickable-row">
                      <td>
                        <input type="checkbox" className="checkmail" />
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="fas fa-star starred" />
                        </span>
                      </td>
                      <td className="name">John Doe</td>
                      <td className="subject">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                      </td>
                      <td>
                        <i className="fas fa-paperclip" />
                      </td>
                      <td className="mail-date">13:14</td>
                    </tr>
                    <tr className="unread clickable-row">
                      <td>
                        <input type="checkbox" className="checkmail" />
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="far fa-star" />
                        </span>
                      </td>
                      <td className="name">Envato Account</td>
                      <td className="subject">
                        Important account security update from Envato
                      </td>
                      <td />
                      <td className="mail-date">8:42</td>
                    </tr>
                    <tr className="clickable-row">
                      <td>
                        <input type="checkbox" className="checkmail" />
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="far fa-star" />
                        </span>
                      </td>
                      <td className="name">Twitter</td>
                      <td className="subject">HRMS Bootstrap Admin Template</td>
                      <td />
                      <td className="mail-date">30 Nov</td>
                    </tr>
                    <tr className="unread clickable-row">
                      <td>
                        <input type="checkbox" className="checkmail" />
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="far fa-star" />
                        </span>
                      </td>
                      <td className="name">Richard Parker</td>
                      <td className="subject">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                      </td>
                      <td />
                      <td className="mail-date">18 Sep</td>
                    </tr>
                    <tr className="clickable-row">
                      <td>
                        <input type="checkbox" className="checkmail" />
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="far fa-star" />
                        </span>
                      </td>
                      <td className="name">John Smith</td>
                      <td className="subject">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                      </td>
                      <td />
                      <td className="mail-date">21 Aug</td>
                    </tr>
                    <tr className="clickable-row">
                      <td>
                        <input type="checkbox" className="checkmail" />
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="far fa-star" />
                        </span>
                      </td>
                      <td className="name">me, Robert Smith (3)</td>
                      <td className="subject">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                      </td>
                      <td />
                      <td className="mail-date">1 Aug</td>
                    </tr>
                    <tr className="unread clickable-row">
                      <td>
                        <input type="checkbox" className="checkmail" />
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="far fa-star" />
                        </span>
                      </td>
                      <td className="name">Codecanyon</td>
                      <td className="subject">Welcome To Codecanyon</td>
                      <td />
                      <td className="mail-date">Jul 13</td>
                    </tr>
                    <tr className="clickable-row">
                      <td>
                        <input type="checkbox" className="checkmail" />
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="far fa-star" />
                        </span>
                      </td>
                      <td className="name">Richard Miles</td>
                      <td className="subject">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                      </td>
                      <td>
                        <i className="fas fa-paperclip" />
                      </td>
                      <td className="mail-date">May 14</td>
                    </tr>
                    <tr className="unread clickable-row">
                      <td>
                        <input type="checkbox" className="checkmail" />
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="far fa-star" />
                        </span>
                      </td>
                      <td className="name">John Smith</td>
                      <td className="subject">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                      </td>
                      <td />
                      <td className="mail-date">11/11/16</td>
                    </tr>
                    <tr className="clickable-row">
                      <td>
                        <input type="checkbox" className="checkmail" />
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="far fa-star starred" />
                        </span>
                      </td>
                      <td className="name">Mike Litorus</td>
                      <td className="subject">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                      </td>
                      <td />
                      <td className="mail-date">10/31/16</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

      </div>
    </>
  );
};
export default Inbox;
