// kanakku-v1.9.9/vuejs-files/template/src/views/pages/pages/error/error500.vue
<template>
    <!-- Main Wrapper -->
    <div class="main-wrapper error-page">
        
        <div class="error-box">
            <h1>500</h1>
            <h3 class="h2 mb-3"><i class="fas fa-exclamation-circle"></i> Oops! Something went wrong</h3>
            <p class="h4 font-weight-normal">The page you requested was not found.</p>
            <router-link to="/" class="btn btn-primary">Back to Home</router-link>
        </div>
    
    </div>
    <!-- /Main Wrapper -->
</template>

// kanakku-v1.9.9/angular-files/template-rtl/src/app/shared/error/error500/error500.component.ts
import { Component,} from '@angular/core';
import { routes } from 'src/app/core/core.index';

@Component({
  selector: 'app-error500',
  templateUrl: './error500.component.html',
  styleUrls: ['./error500.component.scss']
})
export class Error500Component {
  public routes = routes
 
}

<!-- Main Wrapper -->
<div class="main-wrapper error-page">
  <div class="error-box">
    <h1>500</h1>
    <h3 class="h2 mb-3">
      <i class="fas fa-exclamation-circle"></i> Oops! Something went wrong
    </h3>
    <p class="h4 font-weight-normal">The page you requested was not found.</p>
    <a [routerLink]="routes.dashboard" class="btn btn-primary">Back to Home</a>
  </div>
</div>
<!-- /Main Wrapper -->
