// kanakku-v1.9.9/reactjs-files/template-rtl/src/blog/addBlog.jsx
import React, { useState } from "react";
import { Link } from "react-router-dom";
import Header from "../layouts/Header";
import Sidebar from "../layouts/Sidebar";
import FeatherIcon from "feather-icons-react";
import Select2 from "react-select2-wrapper";
import TextEditor from "../products/editor";
import { DropIcon } from "../_components/imagepath";

const AddBlog = () => {
  const [menu, setMenu] = useState(false);

  const toggleMobileMenu = () => {
    setMenu(!menu);
  };

  const [category, setcategory] = useState([
    { id: 1, text: "Select Category" },
    { id: 2, text: "Category 1" },
    { id: 3, text: "Category 2" },
    { id: 4, text: "Category 3" },
  ]);

  return (
    <>
      <div className={`main-wrapper ${menu ? "slide-nav" : ""}`}>
        <Header onMenuClick={(value) => toggleMobileMenu()} />
        <Sidebar />

        <div className="page-wrapper">
          <div className="content container-fluid">
            <div className="content-page-header">
              <h5>Add Blog</h5>
            </div>
            <div className="row">
              <div className="col-md-12">
                <div className="card-body">
                  <div className="form-group-item border-0 pb-0">
                    <div className="row">
                      <div className="col-lg-4 col-md-6 col-sm-12">
                        <div className="form-group">
                          <label>
                            Title <span className="text-danger">*</span>
                          </label>
                          <input
                            type="text"
                            className="form-control"
                            placeholder="Enter Title"
                          />
                        </div>
                      </div>
                      <div className="col-lg-4 col-md-6 col-sm-12">
                        <div className="form-group">
                          <label>Category</label>
                          <Select2
                            className="w-100"
                            data={category}
                            options={{
                            placeholder: "Select Category",
                            }}
                            />
                        </div>
                      </div>
                      <div className="col-lg-4 col-md-6 col-sm-12">
                        <div className="form-group">
                          <label>Parent Category</label>
                          <input
                            type="text"
                            className="form-control"
                            placeholder="Enter Parent Category"
                          />
                        </div>
                      </div>
                      <div className="col-lg-6 col-md-12">
                        <div className="form-group" id="summernote_container">
                          <label className="form-control-label">
                            Description
                          </label>
                          {/* <textarea
                            className="summernote form-control"
                            placeholder="Type your message"
                            defaultValue={""}
                          /> */}
                          <TextEditor/>
                        </div>
                      </div>
                      <div className="col-lg-6 col-md-12">
                        <div className="form-group">
                          <label>Image</label>
                          <div className="form-group service-upload mb-0">
                            <span>
                              <img
                                src={DropIcon}
                                alt="upload"
                              />
                            </span>
                            <h6 className="drop-browse align-center">
                              Drop your files here or
                              <span className="text-primary ms-1">browse</span>
                            </h6>
                            <p className="text-muted">Maximum size: 50MB</p>
                            <input type="file" multiple="" id="image_sign" />
                            <div id="frames" />
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="text-end mt-4">
                    <button
                      type="reset"
                      className="btn btn-primary cancel ms-2"
                    >
                      Cancel
                    </button>
                    <button type="submit" className="btn btn-primary">
                      Add Post
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default AddBlog;

// kanakku-v1.9.9/vuejs-files/template/src/views/pages/content/blog/addblog.vue
<template>
  <!-- Main Wrapper -->
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>
    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <div class="content-page-header">
          <h5>Add Blog</h5>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="card-body">
              <div class="form-group-item border-0 pb-0">
                <div class="row">
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Title <span class="text-danger">*</span></label>
                      <input type="text" class="form-control" placeholder="Enter Title" />
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Category</label>
                      <vue-select :options="Category" placeholder="Select Category" />
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Parent Category</label>
                      <input
                        type="text"
                        class="form-control"
                        placeholder="Enter Parent Category"
                      />
                    </div>
                  </div>
                  <div class="col-lg-6 col-md-12">
                    <div class="form-group" id="summernote_container">
                      <label class="form-control-label">Description</label>
                      <SummernoteEditor
                        v-model="myValue"
                        @update:modelValue="summernoteChange($event)"
                        @summernoteImageLinkInsert="summernoteImageLinkInsert"
                      />
                    </div>
                  </div>
                  <div class="col-lg-6 col-md-12">
                    <div class="form-group">
                      <label>Image</label>
                      <div class="form-group service-upload mb-0">
                        <span
                          ><img src="@/assets/img/icons/drop-icon.svg" alt="upload"
                        /></span>
                        <h6 class="drop-browse align-center">
                          Drop your files here or<span class="text-primary ms-1"
                            >browse</span
                          >
                        </h6>
                        <p class="text-muted">Maximum size: 50MB</p>
                        <input type="file" multiple="" id="image_sign" />
                        <div id="frames"></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="text-end mt-4">
                <button type="reset" class="btn btn-primary cancel me-2">Cancel</button>
                <b-button type="submit" variant="primary">Add Post</b-button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /Page Wrapper -->
  </div>
  <!-- /Main Wrapper -->
</template>
<script>
import SummernoteEditor from "vue3-summernote-editor";
export default {
  components: {
    SummernoteEditor,
  },
  data() {
    return {
      myValue: "Description",
      Category: [" Select Category", "Category 1", "Category 2", "Category 3"],
    };
  },
  mounted() {
    document.addEventListener("DOMContentLoaded", function () {
      document.querySelector("#image_sign").addEventListener("change", function () {
        document.querySelector("#frames").innerHTML = "";
        for (var i = 0; i < this.files.length; i++) {
          var img = document.createElement("img");
          img.src = window.URL.createObjectURL(this.files[i]);
          img.width = 100;
          img.height = 100;
          document.querySelector("#frames").appendChild(img);
        }
      });
    });
  },
  methods: {
    summernoteChange(newValue) {
      console.log("summernoteChange", newValue);
    },
    summernoteImageLinkInsert(...args) {
      console.log("summernoteImageLinkInsert()", args);
    },
  },
};
</script>
