// kanakku-v1.9.9/angular-files/template/src/app/feature-module/products-service/add-products/add-products.component.ts
import { Component } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import { AngularEditorConfig } from '@kolkov/angular-editor';
import { Editor, Toolbar, Validators } from 'ngx-editor';
import { routes } from 'src/app/core/core.index';
import jsonDoc from './doc'

@Component({
  selector: 'app-add-products',
  templateUrl: './add-products.component.html',
  styleUrls: ['./add-products.component.scss']
})
export class AddProductsComponent {
  editordoc = jsonDoc;
  files: File[] = [];
  public routes = routes;
  nation = 'units';
  Discount='select Discount'
  Tax='tax'
 
  config: AngularEditorConfig = {
    editable: true,
    spellcheck: true,
    sanitize: false,
    height: '15rem',
    minHeight: '5rem',
    placeholder: 'Enter text here...',
    translate: 'no',
    defaultParagraphSeparator: 'p',
    defaultFontName: 'Arial',
    toolbarHiddenButtons: [['bold']],
    customClasses: [
      {
        name: 'quote',
        class: 'quote',
      },
      {
        name: 'redText',
        class: 'redText',
      },
      {
        name: 'titleText',
        class: 'titleText',
        tag: 'h1',
      },
    ],
  };
  onSelect(event: { addedFiles: File[] }) {
    this.files.push(...event.addedFiles);
  }
  onRemove(event:File) {
   this.files.splice(this.files.indexOf(event), 1);
  }
  editor: Editor | any;
  toolbar: Toolbar = [
    ['bold', 'italic'],
    ['underline', 'strike'],
    ['code', 'blockquote'],
    
    [{ heading: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'] }],
    ['link', 'image'],
    ['text_color', 'background_color'],
    ['align_left', 'align_center', 'align_right', 'align_justify'],
  ];
  form = new FormGroup({
    editorContent: new FormControl(
      { value: jsonDoc, disabled: false },
      Validators.required()
    ),
  });
  ngOnDestroy(): void {
    this.editor.destroy();
  }
 

  ngOnInit(): void {
    this.editor = new Editor();
  }


}

  <div class="card mb-0">
    <div class="card-body">
      <div class="page-header">
        <div class="content-page-header">
          <h5>Add Products / Services</h5>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group-item">
            <h5 class="form-title">Basic Details</h5>
            <div class="row">
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                  <label>Item Type<span class="text-danger">  *</span></label>
                  <div class="align-center">
                    <div class="form-control me-3">
                      <label class="custom_radio me-3 mb-0">
                        <input
                          type="radio"
                          class="form-control"
                          name="payment"
                          checked
                        >
                        <span class="checkmark"></span> Product
                      </label>
                    </div>
                    <div class="form-control">
                      <label class="custom_radio mb-0">
                        <input type="radio" name="payment" >
                        <span class="checkmark"></span> Service
                      </label>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                  <label>Product Name <span class="text-danger">  *</span></label>
                  <input
                    type="text"
                    class="form-control"
                    placeholder="Enter Product Name"
                  >
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3 add-products">
                  <label>Product Code (SKU)<span class="text-danger">  *</span></label>
                  <input
                    type="text"
                    class="form-control"
                    placeholder="Enter Product Code"
                  >
                  <button type="submit" class="btn btn-primary">
                    Generate Code
                  </button>
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                  <label>Category  <span class="text-danger">  *</span></label>
                  <input
                    type="text"
                    class="form-control"
                    placeholder="Enter Category Name"
                  >
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                  <label>Selling Price  <span class="text-danger">  *</span></label>
                  <input
                    type="text"
                    class="form-control"
                    placeholder="Enter Selling Price"
                  >
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                  <label>Purchase Price  <span class="text-danger">  *</span></label>
                  <input
                    type="text"
                    class="form-control"
                    placeholder="Enter Purchase Prices"
                  >
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                  <label>Quantity <span class="text-danger">  *</span></label>
                  <input
                    type="number"
                    class="form-control"
                    placeholder="Enter Quantity"
                    name="name"
                  >
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                  <label>Units</label>
                  <mat-select [(ngModel)]="nation" [ngModelOptions]="{standalone: true}"class="select mat-cust-select form-control">
                    <mat-option value="units">Select Units</mat-option>
                    <mat-option value="customer1">Pieces</mat-option>
                    <mat-option value="customer2">Box</mat-option>
                    <mat-option value="customer3">Kilograms</mat-option>
                  </mat-select>
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                  <label>Discount Type</label>
                  <mat-select [(ngModel)]="Discount" [ngModelOptions]="{standalone: true}"class="select mat-cust-select form-control">
                    <mat-option value="select Discount">Select Discount Type</mat-option>
                    <mat-option value="discount1">Percentage</mat-option>
                    <mat-option value="discount2">Fixed</mat-option>
                  </mat-select>
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3 add-products">
                  <label>Generate Barcode</label>
                  <input
                    type="text"
                    class="form-control"
                    placeholder="Enter Barcode Code"
                  >
                  <button type="submit" class="btn btn-primary">
                    Generate Code
                  </button>
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                  <label>Alert Quantity </label>
                  <input
                    type="number"
                    class="form-control"
                    placeholder="Enter Alert Quantity"
                    name="name"
                  >
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                  <label>Tax</label>
                  <mat-select [(ngModel)]="Tax" [ngModelOptions]="{standalone: true}"class="select mat-cust-select form-control">
                    <mat-option value="tax">Select Tax</mat-option>
                    <mat-option value="customer1">IVA - (21%)</mat-option>
                    <mat-option value="customer2">IRPF - (-15%)</mat-option>
                    <mat-option value="customer3">PDV - (20%)</mat-option>
                  </mat-select>
                </div>
              </div>
            </div>
          </div>
          <div class="form-group-item">
            <div class="row">
              <div class="col-xl-6 col-lg-6 col-md-6 col-12 description-box">
                <div class="input-block mb-3" id="summernote_container">
                  <label class="form-control-label">Product Descriptions</label>
                  <form [formGroup]="form">
                    <div class="editor">
                      <ngx-editor-menu [editor]="editor" [toolbar]="toolbar">
                      </ngx-editor-menu>
                      <ngx-editor [editor]="editor" formControlName="editorContent">
                      </ngx-editor>
                  </div>
                  </form>
                </div>
              </div>
              <div class="col-xl-6 col-lg-6 col-md-6 col-12">
                <div class="input-block mb-3">
                  <label>Product Image</label>
                  <div class="input-block mb-3 service-upload mb-0">
                    <span
                      ><img
                        src="assets/img/icons/drop-icon.svg"
                        alt="upload"
                      ></span>
                    <h6 class="drop-browse align-center">
                      Drop your files here or<span
                        class="text-primary ms-1"
                        >browse</span
                      >
                    </h6>
                    <p class="text-muted">Maximum size: 50MB</p>
                    <input type="file" multiple="" id="image_sign" >
                    <div id="frames"></div>
                    <ngx-dropzone-image-preview
                    ngProjectAs="ngx-dropzone-preview"
                    *ngFor="let f of files"
                    [file]="f"
                    [removable]="true"
                    (removed)="onRemove(f)"
                  >
                  </ngx-dropzone-image-preview>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <form action="product-list.html" class="text-end">
            <button type="reset" class="btn btn-primary cancel me-2">
              Cancel
            </button>
            <button type="submit" class="btn btn-primary">
              Add Item
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>

// kanakku-v1.9.9/vuejs-files/template-rtl/src/views/pages/reports/add-products.vue
<template>
  <!-- Main Wrapper -->
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>
    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <componentheader :title="title" />

        <div class="row">
          <div class="col-md-12">
            <div class="card-body">
              <div class="form-group-item">
                <h5 class="form-title">Basic Details</h5>
                <div class="row">
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Item Type</label>
                      <div class="align-center">
                        <div class="form-control me-3">
                          <label class="custom_radio me-3 mb-0">
                            <input
                              type="radio"
                              class="form-control"
                              name="payment"
                              checked
                            />
                            <span class="checkmark"></span> Product
                          </label>
                        </div>
                        <div class="form-control">
                          <label class="custom_radio mb-0">
                            <input type="radio" name="payment" />
                            <span class="checkmark"></span> Service
                          </label>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Name</label>
                      <b-form-input
                        type="text"
                        class="form-control"
                        placeholder="Enter Item Name"
                      />
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Item Category</label>
                      <vue-select
                        :options="Category"
                        placeholder="Select Item Category"
                      />
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Price</label>
                      <input
                        type="number"
                        class="form-control"
                        placeholder="Enter Item Price"
                        name="name"
                      />
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Units</label>
                      <vue-select :options="Units" placeholder="Select Units" />
                    </div>
                  </div>
                </div>
              </div>
              <div class="form-group-item">
                <div class="form-group">
                  <h5 class="form-title">Additional Details</h5>
                </div>
                <div class="row">
                  <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                    <div class="form-group">
                      <label>Generate Barcode</label>
                      <b-form-input
                        type="text"
                        class="form-control"
                        placeholder="Enter Barcode Number"
                      />
                    </div>
                  </div>
                  <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                    <div class="form-group">
                      <label>Purchase Price Without Tax</label>
                      <input type="text" class="form-control" placeholder="Enter Amout" />
                    </div>
                  </div>
                  <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                    <div class="form-group">
                      <label>Purchase Price With Tax</label>
                      <b-form-input
                        type="text"
                        class="form-control"
                        placeholder="Enter Tax Amount"
                      />
                    </div>
                  </div>
                  <div class="col-xl-3 col-lg-4 col-md-6 col-12">
                    <div class="form-group">
                      <label>Quantity</label>
                      <b-form-input type="text" class="form-control" placeholder="eg 10" />
                    </div>
                  </div>
                  <div class="col-xl-6 col-lg-6 col-md-6 col-12">
                    <div class="form-group summernote_Editor" id="summernote_container">
                      <label class="form-control-label">Details</label>
                      <SummernoteEditor
                        v-model="myValue"
                        @update:modelValue="summernoteChange($event)"
                        @summernoteImageLinkInsert="summernoteImageLinkInsert"
                      />
                    </div>
                  </div>
                  <div class="col-xl-6 col-lg-6 col-md-6 col-12">
                    <div class="form-group">
                      <label>Image</label>
                      <div class="form-group service-upload mb-0">
                        <span
                          ><img src="@/assets/img/icons/drop-icon.svg" alt="upload"
                        /></span>
                        <h6 class="drop-browse align-center">
                          Drop your files here or<span class="text-primary ms-1"
                            >browse</span
                          >
                        </h6>
                        <p class="text-muted">Maximum size: 50MB</p>
                        <input type="file" multiple="" id="image_sign" />
                        <div id="frames"></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="form-group-item border-0 pb-0">
                <div class="form-group">
                  <h5 class="form-title">Discount Details</h5>
                </div>
                <div class="row">
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Discount (%)</label>
                      <ul class="form-group-plus css-equal-heights">
                        <li>
                          <vue-select
                            :options="Amount"
                            placeholder="Enter Discount Amount"
                          />
                        </li>
                        <li>
                          <span class="btn btn-gray form-plus-btn">%</span>
                        </li>
                      </ul>
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Discount Amount</label>
                      <b-form-input
                        type="text"
                        class="form-control"
                        placeholder="Enter Discount Amount"
                      />
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="form-group">
                      <label>Minimum Stock Qty</label>
                      <b-form-input type="text" class="form-control" placeholder="eg 10" />
                    </div>
                  </div>
                </div>
              </div>
              <div class="text-end">
                <button type="reset" class="btn btn-primary cancel me-2">Cancel</button>
                <b-button type="submit" variant="primary">Add Item</b-button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /Page Wrapper -->
  </div>
  <!-- /Main Wrapper -->
</template>
<script>
import SummernoteEditor from "vue3-summernote-editor";
export default {
  components: {
    SummernoteEditor,
  },
  data() {
    return {
      myValue: "Discription",
      title: "Add Products / Services",
      Category: ["Select Item Category", "Category 1", "Category 2", "Category 3"],
      Units: ["Select Units", "Pieces", "Box", "Kilograms"],
      Amount: ["Enter Discount Amount", "5%", "10%", "15%"],
    };
  },
  methods: {
    summernoteChange(newValue) {
      console.log("summernoteChange", newValue);
    },
    summernoteImageLinkInsert(...args) {
      console.log("summernoteImageLinkInsert()", args);
    },
  },
  mounted() {
    document.addEventListener("DOMContentLoaded", function () {
      const imageSign = document.querySelector("#image_sign");
      imageSign.addEventListener("change", function () {
        const frames = document.querySelector("#frames");
        frames.innerHTML = "";
        for (let i = 0; i < this.files.length; i++) {
          const img = document.createElement("img");
          img.src = window.URL.createObjectURL(this.files[i]);
          img.width = "100";
          img.height = "100";
          frames.appendChild(img);
        }
      });
    });
  },
};
</script>
