// kanakku-v1.9.9/reactjs-files/template-rtl/src/paymentSummary/index.jsx
import React, { useState } from "react";
import { Link } from "react-router-dom";
import Header from "../layouts/Header";
import Sidebar from "../layouts/Sidebar";
import "../_components/antd.css";
import { Pagination, Table } from "antd";
import Data from "../assets/jsons/paymentSummary";
import FeatherIcon from "feather-icons-react";
import {
  onShowSizeChange,
  itemRender,
} from "../_components/paginationfunction";
import AddVendor from "../vendors/addVendor";

const PaymentSummary = () => {
  const [menu, setMenu] = useState(false);
  const [show, setShow] = useState(false);
  
  const toggleMobileMenu = () => {
    setMenu(!menu);
  };

  const datasource = Data?.Data;
  console.log(datasource);

  const columns = [
    {
      title: "#",
      dataIndex: "Id",
      sorter: (a, b) => a.Id.length - b.Id.length,
    },
    {
      title: "Transaction ID",
      dataIndex: "Transaction",
      sorter: (a, b) => a.Transaction.length - b.Transaction.length,
    },
    {
      title: "Invoice Number",
      dataIndex: "Invoice",
      sorter: (a, b) => a.Invoice.length - b.Invoice.length,
    },
    {
      title: "Customer",
      dataIndex: "Name",
      render: (text, record) => (
        <>
          <h2 className="table-avatar">
            <Link to="/profile" className="avatar avatar-sm ms-2">
              <img
                className="avatar-img rounded-circle"
                src={record.Img}
                alt="User Image"
              />
            </Link>
            <Link to="/profile">
              {record.Name} <span>{record.Phone}</span>
            </Link>
          </h2>
        </>
      ),
      sorter: (a, b) => a.Invoice.length - b.Invoice.length,
    },
    {
      title: "Amount",
      dataIndex: "Amount",
      sorter: (a, b) => a.Amount.length - b.Amount.length,
    },
    {
      title: "Date",
      dataIndex: "date",
      sorter: (a, b) => a.date.length - b.date.length,
    },
    {
      title: "Payment Method",
      dataIndex: "Payment",
      sorter: (a, b) => a.Payment.length - b.Payment.length,
    }
  ];

  return (
    <>
      <div className={`main-wrapper ${menu ? "slide-nav" : ""}`}>
        <Header onMenuClick={(value) => toggleMobileMenu()} />
        <Sidebar />

        <div className="page-wrapper">
          <div className="content container-fluid">
            {/* Page Header */}
            <div className="page-header">
              <div className="content-page-header">
                <h5>Payment Summary</h5>
                <div className="list-btn">
                  <ul className="filter-list">
                    <li>
                      <Link className="btn btn-filters w-auto popup-toggle"
                      onClick={() => setShow(!show)}
                      >
                        <span className="ms-2">
                          {/* <i className="fe fe-filter" /> */}
                          <FeatherIcon icon="filter"/>
                        </span>
                        Filter{" "}
                      </Link>
                    </li>
                    <li>
                      <Link className="btn-filters" to="#">
                        <span>
                          {/* <i className="fe fe-settings" /> */}
                          <FeatherIcon icon="settings"/>
                        </span>{" "}
                      </Link>
                    </li>
                    <li>
                      <Link className="btn-filters" to="#">
                        <span>
                          {/* <i className="fe fe-grid" /> */}
                          <FeatherIcon icon="grid"/>
                        </span>{" "}
                      </Link>
                    </li>
                    <li>
                      <Link
                        className="active btn-filters"
                        to="#"
                      >
                        <span>
                          {/* <i className="fe fe-list" /> */}
                          <FeatherIcon icon="list"/>
                        </span>{" "}
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            {/* /Page Header */}
            {/* Search Filter */}
            <div id="filter_inputs" className="card filter-card">
              <div className="card-body pb-0">
                <div className="row">
                  <div className="col-sm-6 col-md-3">
                    <div className="form-group">
                      <label>Name</label>
                      <input type="text" className="form-control" />
                    </div>
                  </div>
                  <div className="col-sm-6 col-md-3">
                    <div className="form-group">
                      <label>Email</label>
                      <input type="text" className="form-control" />
                    </div>
                  </div>
                  <div className="col-sm-6 col-md-3">
                    <div className="form-group">
                      <label>Phone</label>
                      <input type="text" className="form-control" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* /Search Filter */}
            {/* Table */}
            <div className="row">
              <div className="col-sm-12">
                <div className="card-table">
                  <div className="card-body paymentSummary">
                    <div className="table-responsive table-hover">
                      <Table
                        pagination={{
                          total: datasource.length,
                          showTotal: (total, range) =>
                            `Showing ${range[0]} to ${range[1]} of ${total} entries`,
                          showSizeChanger: true,
                          onShowSizeChange: onShowSizeChange,
                          itemRender: itemRender,
                        }}
                        columns={columns}
                        dataSource={datasource}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* /Table */}
          </div>
        </div>

        <AddVendor 
          setShow={setShow}
          show={show}
        />
        
      </div>
    </>
  );
};

export default PaymentSummary;

// kanakku-v1.9.9/vuejs-files/template-rtl/src/views/pages/reports/payment-summary.vue
<template>
  <!-- Main Wrapper -->
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>

    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <supportheader :title="title" />
        <filter />
        <!-- Table -->
        <div class="row">
          <div class="col-sm-12">
            <div class="card-table">
              <div class="card-body">
                <div class="table-responsive">
                  <a-table
                    class="stripped table-hover"
                    :columns="columns"
                    :data-source="data"
                    @change="onChange"
                  >
                    <template #bodyCell="{ column, record }">
                      <template v-if="column.key === 'Customer'">
                        <h2 class="table-avatar">
                          <router-link to="profile" class="avatar avatar-sm me-2"
                            ><img
                              class="avatar-img rounded-circle"
                              :src="require(`@/assets/img/profiles/${record.img}`)"
                              alt="User Image"
                          /></router-link>
                          <router-link to="profile"
                            >{{ record.Customer
                            }}<span>{{ record.number }}</span></router-link
                          >
                        </h2>
                      </template>
                      <template v-else-if="column.key === 'id'">
                        <router-link to="invoice-details" class="invoice-link">{{
                          record.InvoiceNumber
                        }}</router-link>
                      </template>
                    </template>
                  </a-table>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /Table -->
      </div>
    </div>
    <!-- /Page Wrapper -->
    <locationmodal :title1="title1" />
  </div>
  <!-- /Main Wrapper -->
</template>
<script>
const columns = [
  {
    title: "#",
    dataIndex: "NUM",
    sorter: (a, b) => a.NUM.localeCompare(b.NUM),
  },
  {
    title: "Transaction ID",
    dataIndex: "TransactionID",

    sorter: {
      compare: (a, b) => {
        a = a.TransactionID.toLowerCase();
        b = b.TransactionID.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Invoice Number",
    dataIndex: "InvoiceNumber",
    key: "id",
    sorter: (a, b) => a.InvoiceNumber.localeCompare(b.InvoiceNumber),
  },
  {
    title: "Customer",
    dataIndex: "Customer",
    key: "Customer",
    sorter: {
      compare: (a, b) => {
        a = a.Customer.toLowerCase();
        b = b.Customer.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Amount",
    dataIndex: "Amount",
    sorter: {
      compare: (a, b) => {
        a = a.Amount.toLowerCase();
        b = b.Amount.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Date",
    dataIndex: "Date",
    sorter: {
      compare: (a, b) => {
        a = a.Date.toLowerCase();
        b = b.Date.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Payment Method",
    dataIndex: "PaymentMethod",
    sorter: {
      compare: (a, b) => {
        a = a.PaymentMethod.toLowerCase();
        b = b.PaymentMethod.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
];
const data = [
  {
    NUM: "1",
    img: "avatar-02.jpg",
    TransactionID: "137370531",
    InvoiceNumber: "#4987",
    Customer: "John Smith",
    number: "+1 843-443-3282",
    Amount: "$1,54,220",
    Date: "19 Dec 2022, 06:12 PM",
    PaymentMethod: "Cash",
  },
  {
    NUM: "2",
    img: "avatar-03.jpg",
    TransactionID: "137370532",
    InvoiceNumber: "#4988",
    Customer: "Johnny",
    number: "+1 917-409-0861",
    Amount: "$2,54,220",
    Date: "19 Dec 2022, 06:12 PM",
    PaymentMethod: "Cheque",
  },
  {
    NUM: "3",
    img: "avatar-04.jpg",
    TransactionID: "137370533",
    InvoiceNumber: "#4989",
    Customer: "Robert",
    number: "+1 956-623-2880",
    Amount: "$3,54,220",
    Date: "19 Dec 2022, 06:12 PM",
    PaymentMethod: "Cash",
  },
  {
    NUM: "4",
    img: "avatar-05.jpg",
    TransactionID: "137370534",
    InvoiceNumber: "#4990",
    Customer: "Sharonda",
    number: "+1 707-439-1732",
    Amount: "$4,54,220",
    Date: "19 Dec 2022, 06:12 PM",
    PaymentMethod: "Cheque",
  },
  {
    NUM: "5",
    img: "avatar-07.jpg",
    TransactionID: "137370535",
    InvoiceNumber: "#4991",
    Customer: "Randall",
    number: "+1 559-741-9672",
    Amount: "$5,54,220",
    Date: "19 Dec 2022, 06:12 PM",
    PaymentMethod: "Cheque",
  },
  {
    NUM: "6",
    img: "avatar-06.jpg",
    TransactionID: "137370536",
    InvoiceNumber: "#4992",
    Customer: "Pricilla",
    number: "+1 989-438-3131",
    Amount: "$4,54,220",
    Date: "19 Dec 2022, 06:12 PM",
    PaymentMethod: "Cheque",
  },
  {
    NUM: "7",
    img: "avatar-02.jpg",
    TransactionID: "137370532",
    InvoiceNumber: "#4988",
    Customer: "John Smith",
    number: "+1 843-443-3282",
    Amount: "$1,54,220",
    Date: "19 Dec 2022, 06:12 PM",
    PaymentMethod: "Cash",
  },
  {
    NUM: "8",
    img: "avatar-03.jpg",
    TransactionID: "137370533",
    InvoiceNumber: "#4989",
    Customer: "Johnny",
    number: "+1 917-409-0861",
    Amount: "$2,54,220",
    Date: "19 Dec 2022, 06:12 PM",
    PaymentMethod: "Cheque",
  },
  {
    NUM: "9",
    img: "avatar-04.jpg",
    TransactionID: "1373705334",
    InvoiceNumber: "#4990",
    Customer: "Robert",
    number: "+1 956-623-2880",
    Amount: "$3,54,220",
    Date: "19 Dec 2022, 06:12 PM",
    PaymentMethod: "Cash",
  },
];
export default {
  setup() {
    return {
      title: "Payment Summary",
      title1: "Payment Summary",
      data,
      columns,
    };
  },
};
</script>
