// kanakku-v1.9.9/vuejs-files/template/src/views/pages/settings/notifications.vue
<template>
  <!-- Main Wrapper -->
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>

    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <componentheader :title="title" />
        <div class="row">
          <div class="col-xl-3 col-md-4">
            <settingsidebar />
          </div>
          <div class="col-xl-9 col-md-8">
            <div class="card">
              <div class="card-header">
                <h5 class="card-title">Notifications</h5>
                <p>
                  Which email notifications would you like to receive when something
                  changes?
                </p>
              </div>
              <div class="card-body">
                <!-- Form -->
                <b-form>
                  <div class="row form-group">
                    <label
                      for="notificationmail"
                      class="col-sm-3 col-form-label input-label"
                      >Send Notifications to</label
                    >
                    <div class="col-sm-9">
                      <b-form-input
                        type="email"
                        class="form-control"
                        id="notificationmail"
                      />
                    </div>
                  </div>

                  <!-- Toggle Switch -->
                  <label class="row form-group toggle-switch" for="notification_switch1">
                    <span class="col-8 col-sm-9 toggle-switch-content ms-0">
                      <span class="d-block text-dark">Invoice viewed</span>
                      <span class="d-block text-muted"
                        >When your customer views the invoice sent via dashboard.</span
                      >
                    </span>
                    <span class="col-4 col-sm-3">
                      <input
                        type="checkbox"
                        class="toggle-switch-input"
                        id="notification_switch1"
                      />
                      <span class="toggle-switch-label ms-auto">
                        <span class="toggle-switch-indicator"></span>
                      </span>
                    </span>
                  </label>
                  <!-- /Toggle Switch -->

                  <!-- Toggle Switch -->
                  <label class="row form-group toggle-switch" for="notification_switch2">
                    <span class="col-8 col-sm-9 toggle-switch-content ms-0">
                      <span class="d-block text-dark">Estimate viewed</span>
                      <span class="d-block text-muted"
                        >When your customer views the estimate sent via dashboard.</span
                      >
                    </span>
                    <span class="col-4 col-sm-3">
                      <input
                        type="checkbox"
                        class="toggle-switch-input"
                        id="notification_switch2"
                      />
                      <span class="toggle-switch-label ms-auto">
                        <span class="toggle-switch-indicator"></span>
                      </span>
                    </span>
                  </label>
                  <!-- /Toggle Switch -->

                  <div class="text-end">
                    <b-button variant="primary">Save Changes</b-button>
                  </div>
                </b-form>
                <!-- /Form -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /Page Wrapper -->
  </div>
  <!-- /Main Wrapper -->
</template>
<script>
export default {
  setup() {
    return {
      title: "Settings",
    };
  },
};
</script>

// kanakku-v1.9.9/reactjs-files/template-rtl/src/settings/Notifications.jsx
import React, {useEffect,useState} from 'react';
import { Link } from 'react-router-dom';
import SettingSidebar from '../layouts/SettingsSidebar'
import Header from '../layouts/Header'
import Sidebar from '../layouts/Sidebar'

const Notifications = () => {
   
	const [menu, setMenu] = useState(false)

	const toggleMobileMenu = () => {
		setMenu(!menu)
	  }

    useEffect(() => {
		let elements = Array.from(document.getElementsByClassName('select2-container'));
        elements.map(element => element.classList.add("width-100"))
	},[]);
   

    return (
            
        <div className={`main-wrapper ${menu ? 'slide-nav': ''}`}> 
          
            <Header onMenuClick={(value) => toggleMobileMenu()} />
            <Sidebar />   
            <div className="page-wrapper">
                <div className="content container-fluid">
                <div class="page-header">
						<div class="content-page-header">						
							<h5>Settings</h5>
						</div>
					</div>
                    
                        <div className="row">
                            <div className="col-xl-3 col-md-4">
                                <SettingSidebar />    
                            </div>
                            
                            <div className="col-xl-9 col-md-8">
                                <div className="card">
                                    <div className="card-header">
                                        <h5 className="card-title">Notifications</h5>
                                        <p>Which email notifications would you like to receive when something changes?</p>
                                    </div>
                                    <div className="card-body">
                                    
                                        <form>
                                            <div className="row form-group">
                                                <label className="col-sm-3 col-form-label input-label">Send Notifications to</label>
                                                <div className="col-sm-9">
                                                    <input type="email" className="form-control" id="notificationmail" />
                                                </div>
                                            </div>
    
    
                                            <label className="row form-group toggle-switch">
                                                <span className="col-8 col-sm-9 toggle-switch-content ml-0">
                                                    <span className="d-block text-dark">Invoice viewed</span>
                                                    <span className="d-block text-muted">When your customer views the invoice sent via dashboard.</span>
                                                </span>
                                                <span className="col-4 col-sm-3">
                                                    <input type="checkbox" className="toggle-switch-input" id="notification_switch1" />
                                                    <span className="toggle-switch-label ms-auto">
                                                        <span className="toggle-switch-indicator"></span>
                                                    </span>
                                                </span>
                                            </label>
    
                                            <label className="row form-group toggle-switch">
                                                <span className="col-8 col-sm-9 toggle-switch-content ml-0">
                                                    <span className="d-block text-dark">Estimate viewed</span>
                                                    <span className="d-block text-muted">When your customer views the estimate sent via dashboard.</span>
                                                </span>
                                                <span className="col-4 col-sm-3">
                                                    <input type="checkbox" className="toggle-switch-input" id="notification_switch2" />
                                                    <span className="toggle-switch-label ms-auto">
                                                        <span className="toggle-switch-indicator"></span>
                                                    </span>
                                                </span>
                                            </label>
                                            
                                            <div className="text-end">
                                                <button type="submit" className="btn btn-primary">Save Changes</button>
                                            </div>
                                        </form>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
             </div>   
         
        );
    
}
export default Notifications;
