// kanakku-v1.9.9/angular-files/template/src/app/feature-module/quotationspage/edit-quotations/edit-quotations.component.ts
import { Component, OnInit } from '@angular/core';
import { Sort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { DataService, routes } from 'src/app/core/core.index';
import { apiResultFormat, editcreditnotes, pageSelection } from 'src/app/core/models/models';

@Component({
  selector: 'app-edit-quotations',
  templateUrl: './edit-quotations.component.html',
  styleUrls: ['./edit-quotations.component.scss']
})
export class EditQuotationsComponent implements OnInit  {
  myDateValue!: Date;
  country = 'India';
  public minDate!: Date;
  public maxDate!: Date;
  Gst = 'Gst1';
  product = 'product1';
  na='n';
  bank='selectbank';
  discount ='percentage';
  tax = "tax1"
  public editcreditnotes: Array<editcreditnotes> = [];
  files: File[] = [];
  public routes = routes
  public Toggledata  = false;
  dataSource!: MatTableDataSource<editcreditnotes>;
  public searchDataValue = '';
  // pagination variables
  public lastIndex = 0;
  public pageSize = 10;
  public totalData = 0;
  public skip = 0;
  public limit: number = this.pageSize;
  public pageIndex = 0;
  public serialNumberArray: Array<number> = [];
  public currentPage = 1;
  public pageNumberArray: Array<number> = [];
  public pageSelection: Array<pageSelection> = [];
  public totalPages = 0;
  //** / pagination variables
  

  constructor(private data: DataService) {}

  ngOnInit(): void {
    this.getTableData();
  }
  private getTableData(): void {
    this.editcreditnotes = [];
    this.serialNumberArray = [];

    this.data.getEditcreditnotes().subscribe((data: apiResultFormat) => {
      this.totalData = data.totalData;
      data.data.map((res: editcreditnotes, index: number) => {
        const serialNumber = index + 1;
        if (index >= this.skip && serialNumber <= this.limit) {
          res.product = serialNumber;
          this.editcreditnotes.push(res);
          this.serialNumberArray.push(serialNumber);
        }
      });
      this.dataSource = new MatTableDataSource<editcreditnotes>(this.editcreditnotes);
      this.calculateTotalPages(this.totalData, this.pageSize);
    });
  }
 
  
  
  public sortData(sort: Sort) {
    const data = this.editcreditnotes.slice();

    if (!sort.active || sort.direction === '') {
      this.editcreditnotes = data;
    } else {
      this.editcreditnotes= data.sort((a, b) => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const aValue = (a as any)[sort.active];
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const bValue = (b as any)[sort.active];
        return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
      });
    }
  }
  public getMoreData(event: string): void {
    if (event == 'next') {
      this.currentPage++;
      this.pageIndex = this.currentPage - 1;
      this.limit += this.pageSize;
      this.skip = this.pageSize * this.pageIndex;
      this.getTableData();
    } else if (event == 'previous') {
      this.currentPage--;
      this.pageIndex = this.currentPage - 1;
      this.limit -= this.pageSize;
      this.skip = this.pageSize * this.pageIndex;
      this.getTableData();
    }
  }
  public moveToPage(pageNumber: number): void {
    this.currentPage = pageNumber;
    this.skip = this.pageSelection[pageNumber - 1].skip;
    this.limit = this.pageSelection[pageNumber - 1].limit;
    if (pageNumber > this.currentPage) {
      this.pageIndex = pageNumber - 1;
    } else if (pageNumber < this.currentPage) {
      this.pageIndex = pageNumber + 1;
    }
    this.getTableData();
  }
  public PageSize(): void {
    this.pageSelection = [];
    this.limit = this.pageSize;
    this.skip = 0;
    this.currentPage = 1;
    this.getTableData();
  }
  private calculateTotalPages(totalData: number, pageSize: number): void {
    this.pageNumberArray = [];
    this.totalPages = totalData / pageSize;
    if (this.totalPages % 1 != 0) {
      this.totalPages = Math.trunc(this.totalPages + 1);
    }
    for (let i = 1; i <= this.totalPages; i++) {
      const limit = pageSize * i;
      const skip = limit - pageSize;
      this.pageNumberArray.push(i);
      this.pageSelection.push({ skip: skip, limit: limit });
    }
  }
  open() {
    this.Toggledata = !this.Toggledata;
   
  }
  onSelect(event: { addedFiles: File[] }) {
    this.files.push(...event.addedFiles);
  }
  onRemove(event:File) {
   this.files.splice(this.files.indexOf(event), 1);
  }

}

<div class="card mb-0">
  <div class="card-body">
    <div class="page-header">
      <div class="content-page-header">
        <h5>Edit Quotations</h5>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="quotation-card">
          
          <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-12">
              <div class="input-block mb-3">
                <div class="mb-2">
                  <label>Document Title</label>
                </div>
                <label class="custom_check me-3 mb-0">
                  <input type="checkbox" name="invoice" />
                  <span class="checkmark"></span> Quotation
                </label>
                <label class="custom_check mb-0">
                  <input type="checkbox" name="re_invoice" />
                  <span class="checkmark"></span> Estimate
                </label>
              </div>
            </div>
          </div>
          <div class="form-group-item border-0 mb-0">
            <div class="row align-item-center">
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                  <label htmlFor="label">Quotation Id</label>
                  <input
                    id="label"
                    type="text"
                    class="form-control"
                    placeholder="Enter Quotation ID"
                  />
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                  <label htmlFor="label">Select Customer</label>
                  <ul class="form-group-plus css-equal-heights">
                    <li>
                      <mat-select
                        [(ngModel)]="country"
                        [ngModelOptions]="{ standalone: true }"
                        class="select mat-cust-select form-control"
                      >
                        <mat-option value="India">Choose Customer</mat-option>
                        <mat-option value="customer1">Customer 1</mat-option>
                        <mat-option value="customer2">Customer 2</mat-option>
                        <mat-option value="customer3">Customer 3</mat-option>
                      </mat-select>
                    </li>
                    <li>
                      <a
                        class="btn btn-primary form-plus-btn"
                        [routerLink]="routes.addCustomer"
                        ><i class="fas fa-plus-circle"></i
                      ></a>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                  <label htmlFor="label">Quotation Date</label>
                  <input
                    id="label"
                    type="text"
                    class="datetimepicker form-control"
                    placeholder="Select Date"
                    [minDate]="minDate"
                    [maxDate]="maxDate"
                    #dp="bsDatepicker"
                    bsDatepicker [(bsValue)]="myDateValue">
                  
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                  <label htmlFor="label">Due Date</label>
                  <input
                    id="label"
                    type="text"
                    class="datetimepicker form-control"
                    placeholder="Select Date"
                    [minDate]="minDate"
                    [maxDate]="maxDate"
                    #dp="bsDatepicker"
                    bsDatepicker [(bsValue)]="myDateValue">
                  
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                  <label htmlFor="label">Reference No</label>
                  <input
                    id="label"
                    type="text"
                    class="form-control"
                    placeholder="Enter Phone Number"
                  />
                </div>
              </div>
              <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="input-block mb-3">
                  <label htmlFor="label">Create Quotation with/without GST</label>
                  <mat-select
                    [(ngModel)]="Gst"
                    [ngModelOptions]="{ standalone: true }"
                    class="select mat-cust-select form-control"
                  >
                    <mat-option value="Gst1">Without GST</mat-option>
                    <mat-option value="Gst2">With GST</mat-option>
                  </mat-select>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-12">
                <div class="input-block mb-3">
                  <label htmlFor="label">Products</label>
                  <ul class="form-group-plus css-equal-heights">
                    <li>
                      <mat-select
                        [(ngModel)]="product"
                        [ngModelOptions]="{ standalone: true }"
                        class="select mat-cust-select form-control"
                      >
                        <mat-option value="product1">Select Product</mat-option>
                        <mat-option value="product2">Product 1</mat-option>
                        <mat-option value="product3">Product 2</mat-option>
                        <mat-option value="product4">Product 3</mat-option>
                      </mat-select>
                    </li>
                    <li>
                      <a
                        class="btn btn-primary form-plus-btn"
                        [routerLink]="routes.addproducts"
                        ><i class="fas fa-plus-circle"></i
                      ></a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="form-group-item">
            <div class="card-table">
              <div class="card-body">
                <div class="table-responsive">
                  <table
                    matSort
                    (matSortChange)="sortData($event)"
                    class="table table-center table-hover datatable"
                  >
                    <thead class="thead-light">
                      <tr>
                        <th mat-sort-header="product">Product / Service</th>
                        <th mat-sort-header="quantity">Quantity</th>
                        <th mat-sort-header="unit">Unit</th>
                        <th mat-sort-header="rate">Rate</th>
                        <th mat-sort-header="discount">Discount</th>
                        <th mat-sort-header="tax">Tax</th>
                        <th mat-sort-header="amount">Amount</th>
                        <th mat-sort-header="action">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr *ngFor="let data of editcreditnotes; let i = index">
                        <td>{{ data.product }}</td>
                        <td>
                          <input
                            type="number"
                            class="form-control"
                            placeholder="0"
                          />
                        </td>
                        <td>{{ data.unit }}</td>
                        <td>
                          <input
                            type="number"
                            class="form-control"
                            placeholder="1200"
                          />
                        </td>
                        <td>{{ data.discount }}</td>
                        <td>{{ data.tax }}</td>
                        <td>{{ data.amount }}</td>
                        <td class="d-flex align-items-center">
                          <a
                            href="#"
                            class="btn-action-icon me-2"
                            data-bs-toggle="modal"
                            data-bs-target="#add_discount"
                            ><span><i class="feather icon-edit"></i></span
                          ></a>
                          <a
                            href="#"
                            class="btn-action-icon"
                            data-bs-toggle="modal"
                            data-bs-target="#delete_discount"
                            ><span><i class="feather icon-trash-2"></i></span
                          ></a>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4">
              <div class="row">
                <div class="col-lg-7">
                  <div class="input-block mb-3">
                    <label>Discount Type</label>
                    <mat-select
                      [(ngModel)]="discount"
                      [ngModelOptions]="{ standalone: true }"
                      class="select mat-cust-select form-control"
                    >
                      <mat-option value="percentage">Percentage(%)</mat-option>
                      <mat-option value="fixed">Fixed</mat-option>
                    </mat-select>
                  </div>
                </div>
                <div class="col-lg-5">
                  <div class="input-block mb-3">
                    <label>Discount(%)</label>
                    <input type="text" class="form-control" placeholder="10" />
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="input-block mb-3">
                <label>Tax</label>
                <mat-select
                  [(ngModel)]="tax"
                  [ngModelOptions]="{ standalone: true }"
                  class="select mat-cust-select form-control"
                >
                  <mat-option value="tax">No Tax</mat-option>
                  <mat-option value="tax1">IVA - (21%)</mat-option>
                  <mat-option value="tax2">IRPF - (-15%)</mat-option>
                  <mat-option value="tax3">PDV - (20%)</mat-option>
                </mat-select>
              </div>
            </div>
            <div class="col-md-4"></div>
          </div>
          <div class="form-group-item border-0 p-0">
            <div class="row">
              <div class="col-xl-6 col-lg-12">
                <div class="form-group-bank">
                  <div class="row align-items-center">
                    <div class="col-md-8">
                      <div class="input-block mb-3">
                        <label>Select Bank</label>
                        <mat-select
                          [(ngModel)]="bank"
                          [ngModelOptions]="{ standalone: true }"
                          class="select mat-cust-select form-control"
                        >
                          <mat-option value="selectbank">Select Bank</mat-option>
                          <mat-option value="sbi">SBI</mat-option>
                          <mat-option value="iob">IOB</mat-option>
                          <mat-option value="canara">Canara</mat-option>
                        </mat-select>
                      </div>
                    </div>
                    <div class="col-md-4">
                      <div class="input-block mb-3">
                        <a
                          class="btn btn-primary"
                          href="javascript:void(0);"
                          data-bs-toggle="modal"
                          data-bs-target="#bank_details"
                          >Add Bank</a
                        >
                      </div>
                    </div>
                  </div>
    
                  <div class="input-block mb-3 notes-form-group-info">
                    <label>Notes</label>
                    <textarea
                      class="form-control"
                      placeholder="Enter Notes"
                    ></textarea>
                  </div>
                  <div class="input-block mb-3 notes-form-group-info mb-0">
                    <label>Terms and Conditions</label>
                    <textarea
                      class="form-control"
                      placeholder="Enter Terms and Conditions"
                    ></textarea>
                  </div>
                </div>
              </div>
              <div class="col-xl-6 col-lg-12">
                <div class="form-group-bank">
                  <div class="invoice-total-box">
                    <div class="invoice-total-inner">
                      <p>Taxable Amount <span>$120.00</span></p>
                      <p>Discount <span>$13.20</span></p>
                      <p>Vat <span>$0.00</span></p>
                      <div class="status-toggle justify-content-between">
                        <div class="d-flex align-center">
                          <p>Round Off</p>
                          <input
                            id="rating_1"
                            class="check"
                            type="checkbox"
                            checked=""
                          />
                          <label for="rating_1" class="checktoggle checkbox-bg"
                            >checkbox</label
                          >
                        </div>
                        <span>$0.00</span>
                      </div>
                    </div>
                    <div class="invoice-total-footer">
                      <h4>Total Amount <span>$107.80</span></h4>
                    </div>
                  </div>
                  <div class="input-block mb-3">
                    <label>Signature Name</label>
                    <input
                      type="text"
                      class="form-control"
                      placeholder="Enter Signature Name"
                    />
                  </div>
                  <div class="col-md-12 ">
                    <div class="input-block mb-3 mb-0 pb-0">
                      <label>Signature Image</label>
                      <ngx-dropzone (change)="onSelect($event)" class="service-upload add-credit">
                        <ngx-dropzone-label class="drop-browse align-center">                           <span><i ></i>Upload Signature</span>
                        </ngx-dropzone-label>
                        <ngx-dropzone-image-preview
                          ngProjectAs="ngx-dropzone-preview"
                          *ngFor="let f of files"
                          [file]="f"
                          [removable]="true"
                          (removed)="onRemove(f)"
                        >
                        </ngx-dropzone-image-preview>
                      </ngx-dropzone>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="text-end">
            <button type="reset" class="btn btn-primary cancel me-2">
              Cancel
            </button>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
          
        </div>
      </div>
    </div>
  </div>
</div>


<!-- Add Tax & Discount Modal -->
<div class="modal custom-modal fade" id="add_discount" role="dialog">
  <div class="modal-dialog modal-dialog-centered modal-md">
    <div class="modal-content">
      <div class="modal-header border-0 pb-0">
        <div class="form-header modal-header-title text-start mb-0">
          <h4 class="mb-0">Add Tax & Discount</h4>
        </div>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        >
          <span class="align-center" aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="input-block mb-3">
              <label htmlFor="label">Rate</label>
              <input
                id="label"
                type="number"
                class="form-control"
                placeholder="120"
              />
            </div>
          </div>
          <div class="col-lg-12 col-md-12">
            <div class="input-block mb-3">
              <label htmlFor="label">Discount Amount</label>
              <input
                id="label"
                type="number"
                class="form-control"
                placeholder="0"
              />
            </div>
          </div>
          <div class="col-lg-12 col-md-12">
            <div class="form-group mb-0">
              <label htmlFor="label">Tax</label>
              <select class="form-select">
                <option>N/A</option>
                <option>5%</option>
                <option>10%</option>
                <option>15%</option>
              </select>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <a
          href="#"
          data-bs-dismiss="modal"
          class="btn btn-back cancel-btn me-2"
          >Back</a
        >
        <a
          href="#"
          data-bs-dismiss="modal"
          class="btn btn-primary paid-continue-btn"
          >Save</a
        >
      </div>
    </div>
  </div>
</div>
<!-- /Add Tax & Discount Modal -->

<!-- Delete Items Modal -->
<div class="modal custom-modal fade" id="delete_discount" role="dialog">
  <div class="modal-dialog modal-dialog-centered modal-md">
    <div class="modal-content">
      <div class="modal-body">
        <div class="form-header">
          <h3>Delete Products</h3>
          <p>Are you sure want to delete?</p>
        </div>
        <div class="modal-btn delete-action">
          <div class="row">
            <div class="col-6">
              <a
                href="#"
                data-bs-dismiss="modal"
                class="btn btn-primary paid-continue-btn"
                >Delete</a
              >
            </div>
            <div class="col-6">
              <a
                href="#"
                data-bs-dismiss="modal"
                class="btn btn-primary paid-cancel-btn"
                >Cancel</a
              >
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /Delete Items Modal -->

<!-- Add Bank Details Modal -->
<div class="modal custom-modal fade" id="bank_details" role="dialog">
  <div class="modal-dialog modal-dialog-centered modal-md">
    <div class="modal-content">
      <div class="modal-header border-0 pb-0">
        <div class="form-header modal-header-title text-start mb-0">
          <h4 class="mb-0">Add Bank Details</h4>
        </div>
        <button
          type="button"
          class="close"
          data-bs-dismiss="modal"
          aria-label="Close"
        >
          <span class="align-center" aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-lg-12 col-md-12">
            <div class="form-group">
              <label>Bank Name <span class="text-danger">*</span></label>
              <input
                type="text"
                class="form-control"
                placeholder="Enter Bank Name"
              />
            </div>
          </div>
          <div class="col-lg-12 col-md-12">
            <div class="form-group">
              <label>Account Number <span class="text-danger">*</span></label>
              <input
                type="number"
                class="form-control"
                placeholder="Enter Account Number"
              />
            </div>
          </div>
          <div class="col-lg-12 col-md-12">
            <div class="form-group">
              <label>Branch Name <span class="text-danger">*</span></label>
              <input
                type="text"
                class="form-control"
                placeholder="Enter Branch Name"
              />
            </div>
          </div>
          <div class="col-lg-12 col-md-12">
            <div class="form-group mb-0">
              <label>IFSC Code <span class="text-danger">*</span></label>
              <input
                type="number"
                class="form-control"
                placeholder="Enter IFSC COde"
              />
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="reset" class="btn btn-back cancel-btn me-2">Cancel</button>
        <button type="submit" class="btn btn-primary">Save</button>
      </div>
    </div>
  </div>
</div>
<!-- /Add Bank Details Modal -->

// kanakku-v1.9.9/reactjs-files/template-rtl/src/quatations/editQuotations.jsx
import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import Header from "../layouts/Header";
import Sidebar from "../layouts/Sidebar";
import Data from "../assets/jsons/editInvoice";
import "../_components/antd.css";
import { Table } from "antd";
import FeatherIcon from "feather-icons-react";
import {
  onShowSizeChange,
  itemRender,
} from "../_components/paginationfunction";
import Select2 from "react-select2-wrapper";

const EditQuotations = () => {
  const [menu, setMenu] = useState(false);

  const toggleMobileMenu = () => {
    setMenu(!menu);
  };

  const datasource = Data?.Data;
  console.log(datasource);

  const [tax, setTax] = useState([
    { id: 1, text: "N/A" },
    { id: 2, text: "5%" },
    { id: 3, text: "10%" },
    { id: 4, text: "15%" },
  ]);

  const columns = [
    {
      title: "Product/Service",
      dataIndex: "Product",
      sorter: (a, b) => a.Product.length - b.Product.length,
    },
    {
      title: "Quantity",
      dataIndex: "Quantity",
      sorter: (a, b) => a.Quantity.length - b.Quantity.length,
    },
    {
      title: "Unit",
      dataIndex: "Unit",
      sorter: (a, b) => a.Unit.length - b.Unit.length,
    },
    {
      title: "Rate",
      dataIndex: "Rate",
      sorter: (a, b) => a.Rate.length - b.Rate.length,
    },
    {
      title: "Discount",
      dataIndex: "Discount",
      sorter: (a, b) => a.Discount.length - b.Discount.length,
    },
    {
      title: "Tax",
      dataIndex: "Tax",
      sorter: (a, b) => a.Tax.length - b.Tax.length,
    },
    {
      title: "Amount",
      dataIndex: "Amount",
      sorter: (a, b) => a.Amount.length - b.Amount.length,
    },
    {
      title: "Action",
      dataIndex: "Action",
      render: (text, record) => (
        <>
          <div className="d-flex align-items-center">
            <Link
              to="#"
              className="btn-action-icon ms-2"
              data-bs-toggle="modal"
              data-bs-target="#add_discount"
            >
              <span>
                <i className="fe fe-edit">
                  <FeatherIcon icon="edit" />
                </i>
              </span>
            </Link>
            <Link
              to="#"
              className="btn-action-icon"
              data-bs-toggle="modal"
              data-bs-target="#delete_discount"
            >
              <span>
                <i className="fe fe-trash-2">
                  <FeatherIcon icon="trash-2" />
                </i>
              </span>
            </Link>
          </div>
        </>
      ),
      sorter: (a, b) => a.Action.length - b.Action.length,
    },
  ];

  return (
    <>
      <div className={`main-wrapper ${menu ? "slide-nav" : ""}`}>
        <Header onMenuClick={(value) => toggleMobileMenu()} />
        <Sidebar />
        <div className="page-wrapper">
          <div className="content container-fluid">
            <div className="page-header">
              <div className="content-page-header">
                <h5>Edit Quotations</h5>
              </div>
            </div>
            <div className="row">
              <div className="col-md-12">
                <div className="card">
                  <div className="card-body">
                    <div className="form-group-item border-0 mb-0">
                      <div className="row align-item-center">
                        <div className="col-lg-4 col-md-6 col-sm-12">
                          <div className="form-group">
                            <label>Quotations Number</label>
                            <input
                              type="text"
                              className="form-control"
                              defaultValue={10001}
                              placeholder="Enter Quotations Number"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6 col-sm-12">
                          <div className="form-group">
                            <label>Customer Name</label>
                            <input
                              type="text"
                              className="form-control"
                              defaultValue="John Smith"
                              placeholder="Enter Customer Name"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6 col-sm-12">
                          <div className="form-group">
                            <label>Quotations Date</label>
                            <input
                              type="text"
                              className="form-control"
                              defaultValue="19 Dec 2022"
                              placeholder="Quotations Date"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6 col-sm-12">
                          <div className="form-group">
                            <label>Due Date</label>
                            <input
                              type="text"
                              className="form-control"
                              defaultValue="20 Dec 2022"
                              placeholder="Invoice Date"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6 col-sm-12">
                          <div className="form-group">
                            <label>Reference No</label>
                            <input
                              type="text"
                              className="form-control"
                              defaultValue={12345}
                              placeholder="Reference No"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6 col-sm-12">
                          <div className="form-group">
                            <label>Enable Option</label>
                            <input
                              type="text"
                              className="form-control"
                              defaultValue="Recurring Invoice"
                              placeholder="Invoice Option"
                            />
                          </div>
                        </div>
                        <div className="col-lg-12">
                          <div className="form-group">
                            <label>Products</label>
                            <input
                              type="text"
                              className="form-control"
                              defaultValue="Lorem ipsum dolor sit amet"
                              placeholder="Products"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6 col-sm-12">
                          <div className="form-group">
                            <label>Currency</label>
                            <input
                              type="text"
                              className="form-control"
                              defaultValue="US dollar"
                              placeholder="Currency"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6 col-sm-12">
                          <div className="form-group">
                            <label>Website</label>
                            <input
                              type="text"
                              className="form-control"
                              defaultValue="www.example.com"
                              placeholder="Enter Website Address"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6 col-sm-12">
                          <div className="form-group">
                            <label>Notes</label>
                            <input
                              type="text"
                              className="form-control"
                              defaultValue="Lorem ipsum dolor sit amet"
                              placeholder="Enter Your Notes"
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="form-group-item">
                      <div className="card-table">
                        <div className="card-body editInvoice">
                          <div className="table-responsive table-hover">
                          <Table
                              pagination={{
                                total: datasource.length,
                                showTotal: (total, range) =>
                                  `Showing ${range[0]} to ${range[1]} of ${total} entries`,
                                showSizeChanger: true,
                                onShowSizeChange: onShowSizeChange,
                                itemRender: itemRender,
                              }}
                              columns={columns}
                              dataSource={datasource}
                              rowKey={(record) => record.id}
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="form-group-item border-0 p-0">
                      <div className="row">
                        <div className="col-xl-6 col-lg-12">
                          <div className="form-group-bank">
                            <div className="form-group">
                              <label>Select Bank</label>
                              <div className="bank-details">
                                <Link
                                  className="text-danger-light"
                                  to="#"
                                  data-bs-toggle="modal"
                                  data-bs-target="#bank_details"
                                >
                                  <i className="fas fa-bank ms-2" />
                                  Edit Bank Details
                                </Link>
                              </div>
                            </div>
                            <div className="form-group notes-form-group-info">
                              <label>Notes</label>
                              <textarea
                                className="form-control"
                                placeholder="Enter Notes"
                                defaultValue={""}
                              />
                            </div>
                            <div className="form-group notes-form-group-info mb-0">
                              <label>Terms and Conditions</label>
                              <textarea
                                className="form-control"
                                placeholder="Enter Terms and Conditions"
                                defaultValue={""}
                              />
                            </div>
                          </div>
                        </div>
                        <div className="col-xl-6 col-lg-12">
                          <div className="form-group-bank">
                            <div className="row">
                              <div className="col-lg-4 col-md-12">
                                <div className="form-group">
                                  <label>Discount Type</label>
                                  <input
                                    type="text"
                                    className="form-control"
                                    defaultValue="5%"
                                    placeholder={10}
                                  />
                                </div>
                              </div>
                              <div className="col-lg-4 col-md-12">
                                <div className="form-group">
                                  <label>Discount (%)</label>
                                  <input
                                    type="text"
                                    className="form-control"
                                    defaultValue="10%"
                                    placeholder={10}
                                  />
                                </div>
                              </div>
                              <div className="col-lg-4 col-md-12">
                                <div className="form-group">
                                  <label>Total discount</label>
                                  <input
                                    type="text"
                                    className="bg-white-smoke form-control"
                                    defaultValue="15%"
                                    placeholder="13.2"
                                  />
                                </div>
                              </div>
                            </div>
                            <div className="invoice-total-box">
                              <div className="invoice-total-inner">
                                <p>
                                  Taxable Amount <span>$120.00</span>
                                </p>
                                <p>
                                  Discount <span>$13.00</span>
                                </p>
                                <p>
                                  Vat <span>$10.00</span>
                                </p>
                              </div>
                              <div className="invoice-total-footer">
                                <h4>
                                  Total Amount <span>$143.00</span>
                                </h4>
                              </div>
                            </div>
                            <div className="form-group">
                              <label>Signature Name</label>
                              <input
                                type="text"
                                className="form-control"
                                placeholder="Enter Signature Name"
                              />
                            </div>
                            <div className="form-group mb-0">
                              <label>Signature Image</label>
                              <input
                                type="text"
                                className="form-control"
                                defaultValue="John Smith"
                                placeholder={10}
                              />
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="add-customer-btns text-end">
                      <Link to="#" className="btn customer-btn-cancel">
                        Cancel
                      </Link>
                      <Link to="#" className="btn customer-btn-save me-2">
                        Update
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="modal custom-modal fade" id="add_discount" role="dialog">
        <div className="modal-dialog modal-dialog-centered modal-md">
          <div className="modal-content">
            <div className="modal-header border-0 pb-0">
              <div className="form-header modal-header-title text-start mb-0">
                <h4 className="mb-0">Add Tax &amp; Discount</h4>
              </div>
              <button
                type="button"
                className="close"
                data-bs-dismiss="modal"
                aria-label="Close"
              >
                <span className="align-center" aria-hidden="true">
                  ×
                </span>
              </button>
            </div>
            <div className="modal-body">
              <div className="row">
                <div className="col-lg-12 col-md-12">
                  <div className="form-group">
                    <label>Rate</label>
                    <input
                      type="number"
                      className="form-control"
                      placeholder={120}
                    />
                  </div>
                </div>
                <div className="col-lg-12 col-md-12">
                  <div className="form-group">
                    <label>Discount Amount</label>
                    <input
                      type="number"
                      className="form-control"
                      placeholder={0}
                    />
                  </div>
                </div>
                <div className="col-lg-12 col-md-12">
                  <div className="form-group mb-0">
                    <label>Tax</label>
                    <Select2
                      data={tax}
                      options={{
                        placeholder: "N/A",
                      }}
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className="modal-footer">
              <Link
                to="#"
                data-bs-dismiss="modal"
                className="btn btn-primary paid-cancel-btn ms-2"
              >
                Back
              </Link>
              <Link
                to="#"
                data-bs-dismiss="modal"
                className="btn btn-primary paid-continue-btn"
              >
                Save
              </Link>
            </div>
          </div>
        </div>
      </div>

      <div className="modal custom-modal fade" id="delete_discount" role="dialog">
        <div className="modal-dialog modal-dialog-centered modal-md">
          <div className="modal-content">
            <div className="modal-header border-0 justify-content-center pb-0">
              <div className="form-header modal-header-title text-center mb-0">
                <h4 className="mb-2">Delete Product / Services</h4>
                <p>Are you sure want to delete?</p>
              </div>
            </div>
            <div className="modal-body">
              <div className="modal-btn delete-action">
                <div className="row">
                  <div className="col-6">
                    <Link
                      to="#"
                      data-bs-dismiss="modal"
                      className="btn btn-primary paid-continue-btn"
                    >
                      Delete
                    </Link>
                  </div>
                  <div className="col-6">
                    <Link
                      to="#"
                      data-bs-dismiss="modal"
                      className="btn btn-primary paid-cancel-btn"
                    >
                      Cancel
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="modal custom-modal fade" id="bank_details" role="dialog">
        <div className="modal-dialog modal-dialog-centered modal-md">
          <div className="modal-content">
            <div className="modal-header border-0 pb-0">
              <div className="form-header modal-header-title text-start mb-0">
                <h4 className="mb-0">Add Bank Details</h4>
              </div>
              <button
                type="button"
                className="close"
                data-bs-dismiss="modal"
                aria-label="Close"
              >
                <span className="align-center" aria-hidden="true">
                  ×
                </span>
              </button>
            </div>
            <div className="modal-body">
              <div className="row">
                <div className="col-lg-12 col-md-12">
                  <div className="form-group">
                    <label>
                      Bank Name <span className="text-danger">*</span>
                    </label>
                    <input
                      type="text"
                      className="form-control"
                      placeholder="Enter Bank Name"
                    />
                  </div>
                </div>
                <div className="col-lg-12 col-md-12">
                  <div className="form-group">
                    <label>
                      Account Number <span className="text-danger">*</span>
                    </label>
                    <input
                      type="number"
                      className="form-control"
                      placeholder="Enter Account Number"
                    />
                  </div>
                </div>
                <div className="col-lg-12 col-md-12">
                  <div className="form-group">
                    <label>
                      Branch Name <span className="text-danger">*</span>
                    </label>
                    <input
                      type="text"
                      className="form-control"
                      placeholder="Enter Branch Name"
                    />
                  </div>
                </div>
                <div className="col-lg-12 col-md-12">
                  <div className="form-group mb-0">
                    <label>
                      IFSC Code <span className="text-danger">*</span>
                    </label>
                    <input
                      type="number"
                      className="form-control"
                      placeholder="Enter IFSC COde"
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className="modal-footer">
              <Link
                to="#"
                data-bs-dismiss="modal"
                className="btn btn-primary paid-cancel-btn ms-2"
              >
                Back
              </Link>
              <Link
                to="#"
                data-bs-dismiss="modal"
                className="btn btn-primary paid-continue-btn"
              >
                Save
              </Link>
            </div>
          </div>
        </div>
      </div>

      </div>
    </>
  );
};

export default EditQuotations;
