// kanakku-v1.9.9/reactjs-files/template-rtl/src/application/Calendar.jsx
import React, {useState, useEffect} from 'react';
import { Link } from 'react-router-dom';
import Modalbox from '../_components/modalbox/Modalbox'
import FullCalendar from '@fullcalendar/react'
import dayGridPlugin from '@fullcalendar/daygrid'
import timeGridPlugin from '@fullcalendar/timegrid'
import interactionPlugin from '@fullcalendar/interaction'
import Header from '../layouts/Header'
import Sidebar from '../layouts/Sidebar'

const Calendar = (props) => {
    const [menu, setMenu] = useState(false)

	const toggleMobileMenu = () => {
		setMenu(!menu)
	  }
    const [startDate, setDate] = useState(new Date()),
            [showCategory, setshowCategory] = useState(false),
            [showmodel, setshowmodel] = useState(false),
            [showEvents, setshowEvents] = useState(false),
            [show, setshow] = useState(false),
            [iseditdelete, setiseditdelete] = useState(false),
            [addneweventobj, setaddneweventobj] = useState(null),
            [isnewevent, setisnewevent] = useState(false),
            [event_title, setevent_title] = useState(""),
            [category_color, setcategory_color] = useState(""),
            [calenderevent, setcalenderevent] = useState(""),
            [weekendsVisible, setweekendsVisible] = useState(true),
            [currentEvents, setscurrentEvents] = useState([]),
           
              
            defaultEvents = [{
                title: 'Event Name 4',
                start: Date.now() + 148000000,
                className: 'bg-purple'
              },
              {
                  title: 'Test Event 1',
                  start: Date.now(),
                  end: Date.now(),
                  className: 'bg-success'
              },
              {
                  title: 'Test Event 2',
                  start: Date.now() + 168000000,
                  className: 'bg-info'
              },
              {
                  title: 'Test Event 3',
                  start: Date.now() + 338000000,
                  className: 'bg-primary'
              }]
    ;
    useEffect(() => {
        let elements = Array.from(document.getElementsByClassName('react-datepicker-wrapper'));
        elements.map(element => element.classList.add("width-100"))
	},[]);
        
    const handleChange = (date) => {
        setDate(date)
    }
    const addEvent = () => {
        setshowEvents(true)
    }
    const categoryHandler = () => {
        setshowCategory(true)
    } 
      
      const handleClose=()=>{
          setisnewevent(false)
          setiseditdelete(false)
          setshow(false)
          setshowCategory(false)
          setshowEvents(false)          
          setshowmodel(false)
    }

    const handleEventClick = (clickInfo) => {  
        setiseditdelete(false)
        setevent_title(clickInfo.event.title)
        setcalenderevent(clickInfo.event) 
    }
    
    const handleDateSelect = (selectInfo) => {
        setisnewevent(true)
        setaddneweventobj(selectInfo)
    }
    const addnewevent=()=>{
        let calendarApi = addneweventobj.view.calendar

        calendarApi.unselect() // clear date selection

        if (event_title) {
            calendarApi.addEvent({
            id: 10,
            title : event_title,
            className: category_color,
            start: addneweventobj.startStr,
            end: addneweventobj.endStr,
            allDay: addneweventobj.allDay
            })
        }   
        setisnewevent(false)
    }
      
    const onupdateModalClose=()=> {
        setiseditdelete(false)
        setevent_title('')
    }
    const oncreateeventModalClose=()=> {
        setevent_title("")
        setisnewevent(false)
    }
    const removeevent=()=>{
        calenderevent.remove()
        setiseditdelete(false)
    }
    const clickupdateevent=()=>{
        const newArray = defaultEvents
        for(let i=0;i<newArray.length;i++){
            if(newArray[i].id === parseInt(calenderevent.id)){
            newArray[i].title = event_title
            }
        }
        defaultEvents = newArray
        setiseditdelete(false)
    }
    
    const handleClick=()=>{
        setshow(true)
    }
    console.log ("showmodel",showmodel);

 
        return (
        
     
			<>
            <div className={`main-wrapper ${menu ? 'slide-nav': ''}`}> 
          
          <Header onMenuClick={(value) => toggleMobileMenu()} />
          <Sidebar />
			  {/* Page Wrapper */ }
            <div className="page-wrapper">
                <div className="content container-fluid">
				
					{/* Page Header */ }
					<div className="page-header">
						<div className="content-page-header">
							
							<h5 className="page-title">Calendar</h5>
                            <div className="list-btn">
								<ul className="filter-list">
									<li>
                                    <Link to="#" onClick = {() => setshowmodel ("showEvents")} className="btn btn-primary">Create Event</Link>
									</li>
								</ul>
							</div>
							
							{/* <div className="col-auto text-end float-end ms-auto">
                                <Link to="#" onClick = {() => setshowmodel ("showEvents")} className="btn btn-primary">Create Event</Link>
							</div> */}
						</div>
					</div>
					{/*  /Page Header */ }
					
					<div className="row">
						<div className="col-lg-3 col-md-4">
                        <div className='card'>
                        <div className='card-body'>
							<h5 className="card-title">Drag & Drop Event</h5>
							<div id="calendar-events" className="mb-3">
								<div className="calendar-events" ><i className="fas fa-circle text-info"></i> My Event One</div>
								<div className="calendar-events" ><i className="fas fa-circle text-success"></i> My Event Two</div>
								<div className="calendar-events" ><i className="fas fa-circle text-danger"></i> My Event Three</div>
								<div className="calendar-events"><i className="fas fa-circle text-warning"></i> My Event Four</div>
							</div>
							<div className="checkbox  mb-3">
								<input id="drop-remove" type="checkbox" />
								<label className="me-1">Remove after drop</label>
							</div>
                            <Link to="#0" onClick = {() => setshowmodel("showCategory")} className="btn mb-3 btn-primary btn-block w-100 w-100">
								<i className="fas fa-plus"></i> Add Category
							</Link>  
                        </div>
                        </div>                         							
						</div>
						<div className="col-lg-9 col-md-8">
							<div className="card bg-white calendarIndex">
								<div className="card-body">
                                <FullCalendar
                                    plugins={[dayGridPlugin, timeGridPlugin, interactionPlugin]}
                                    headerToolbar={{
                                        left: 'prev,next today',
                                        center: 'title',
                                        right: 'dayGridMonth,timeGridWeek,timeGridDay',
                                    }}
                                    
                                    initialView='dayGridMonth'
                                    editable={true}
                                    selectable={true}
                                    selectMirror={true}
                                    dayMaxEvents={true}
                                    weekends={weekendsVisible}
                                    initialEvents={defaultEvents} // alternatively, use the `events` setting to fetch from a feed
                                    select={handleDateSelect}
                                    eventClick={clickInfo=>handleEventClick(clickInfo)}                                  
                                />
								</div>
							</div>
						</div>
					</div>
				
				{/*  Add Event modal */ }
				<div id="add_event" className="modal custom-modal fade" role="dialog">
					<div className="modal-dialog modal-dialog-centered" role="document">
						<div className="modal-content">
							<div className="modal-header">
								<h5 className="modal-title">Add Event</h5>
								<button  type="button" className="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
							<div className="modal-body">
								<form>
									<div className="form-group">
										<label>Event Name <span className="text-danger">*</span></label>
										<input className="form-control" type="text" />
									</div>
									<div className="form-group">
										<label>Event Date <span className="text-danger">*</span></label>
										<div className="cal-icon">
											<input className="form-control" type="text" />
										</div>
									</div>
									<div className="submit-section">
										<button className="btn btn-primary submit-btn">Submit</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
				{/*  /Add Event modal */ }
				
                {/*  Create Event modal */ }
                <div className="modal custom-modal fade none-border" id="my_event">
                    <div className="modal-dialog modal-dialog-centered">
                        <div className="modal-content">                   
                            <div className="modal-header">
                                <h4 className="modal-title">Add Event</h4>
                                <button type="button" className="btn-close" data-bs-dismiss="modal" aria-hidden="true">&times;</button>
                            </div>
                            <div className="modal-body"></div>
                            <div className="modal-footer justify-content-center">
                                <button  type="button" className="btn btn-success save-event submit-btn">Create event</button>
                                <button  type="button" className="btn btn-danger delete-event submit-btn" data-bs-dismiss="modal">Delete</button>
                            </div>
                        </div>
                    </div>
                </div>
				{/*  /Create Event modal */ }
               <Modalbox show={showmodel} handleClose={handleClose} />
				
				</div>			
			</div>
            </div>
            </>
 
		
        );
    
}
export default  Calendar;

// kanakku-v1.9.9/vuejs-files/template-rtl/src/views/pages/applications/calendar.vue
<template>
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>

    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <!-- Page Header -->
        <div class="page-header">
          <div class="content-page-header">
            <h5>Calendar</h5>
            <div class="list-btn">
              <ul class="filter-list">
                <li>
                  <a
                    href="javascript:;"
                    class="btn btn-primary"
                    data-bs-toggle="modal"
                    data-bs-target="#add_event"
                    >Create Event</a
                  >
                </li>
              </ul>
            </div>
          </div>
        </div>
        <!-- /Page Header -->

        <div class="row">
          <div class="col-lg-3 col-md-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title mb-2">Drag & Drop Event</h5>
                <div id="calendar-events" class="mb-3">
                  <div class="calendar-events" data-class="bg-info">
                    <i class="fas fa-circle text-info"></i> My Event One
                  </div>
                  <div class="calendar-events" data-class="bg-success">
                    <i class="fas fa-circle text-success"></i> My Event Two
                  </div>
                  <div class="calendar-events" data-class="bg-danger">
                    <i class="fas fa-circle text-danger"></i> My Event Three
                  </div>
                  <div class="calendar-events" data-class="bg-warning">
                    <i class="fas fa-circle text-warning"></i> My Event Four
                  </div>
                </div>
                <div class="checkbox mb-3">
                  <input id="drop-remove" type="checkbox" class="me-1" />
                  <label for="drop-remove"> Remove after drop </label>
                </div>
                <a
                  href="javascript:;"
                  data-bs-toggle="modal"
                  data-bs-target="#add_new_event"
                  class="btn mb-0 btn-primary btn-block w-100"
                >
                  <i class="fas fa-plus me-1"></i> Add Category
                </a>
              </div>
            </div>
          </div>
          <div class="col-lg-9 col-md-8">
            <div class="card bg-white">
              <div class="card-body">
                <div id="calendar"></div>
                <FullCalendar
                  :options="calendarOptions"
                  :events="events"
                  id="calendar-book"
                ></FullCalendar>
              </div>
            </div>
          </div>
        </div>

        <!-- Add Event Modal -->
        <div id="add_event" class="modal custom-modal fade" role="dialog">
          <div class="modal-dialog modal-dialog-centered modal-md" role="document">
            <div class="modal-content">
              <div class="modal-header border-0 pb-0">
                <div class="form-header modal-header-title text-start mb-0">
                  <h4 class="mb-0">Add Event</h4>
                </div>
                <button
                  type="button"
                  class="close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <span class="align-center" aria-hidden="true">×</span>
                </button>
              </div>
              <div class="modal-body">
                <b-form>
                  <div class="form-group">
                    <label>Event Name <span class="text-danger">*</span></label>
                    <b-form-input class="form-control" type="text" />
                  </div>
                  <div class="form-group">
                    <label>Event Date <span class="text-danger">*</span></label>
                    <div class="cal-icon">
                      <datepicker
                        v-model="startdate"
                        class="picker"
                        :editable="true"
                        :clearable="false"
                      />
                    </div>
                  </div>
                  <div class="submit-section">
                    <button class="btn btn-primary submit-btn">Submit</button>
                  </div>
                </b-form>
              </div>
            </div>
          </div>
        </div>
        <!-- /Add Event Modal -->

        <!-- Add Event Modal -->
        <div class="modal custom-modal fade none-border" id="my_event">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title">Add Event</h4>
                <button
                  type="button"
                  class="close"
                  data-dismiss="modal"
                  aria-hidden="true"
                >
                  &times;
                </button>
              </div>
              <div class="modal-body"></div>
              <div class="modal-footer justify-content-center">
                <button type="button" class="btn btn-success save-event submit-btn">
                  Create event
                </button>
                <button
                  type="button"
                  class="btn btn-danger delete-event submit-btn"
                  data-dismiss="modal"
                >
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>
        <!-- /Add Event Modal -->

        <!-- Add Category Modal -->
        <div class="modal custom-modal fade" id="add_new_event">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header border-0 pb-0">
                <div class="form-header modal-header-title text-start mb-0">
                  <h4 class="mb-0">Add Category</h4>
                </div>
                <button
                  type="button"
                  class="close"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >
                  <span class="align-center" aria-hidden="true">×</span>
                </button>
              </div>

              <div class="modal-body">
                <b-form>
                  <div class="form-group">
                    <label>Category Name</label>
                    <input
                      class="form-control form-white"
                      placeholder="Enter name"
                      type="text"
                    />
                  </div>
                  <div class="form-group mb-0">
                    <label>Choose Category Color</label>
                    <select
                      class="form-control form-white select2"
                      data-placeholder="Choose a color..."
                      name="category-color"
                    >
                      <option value="success">Success</option>
                      <option value="danger">Danger</option>
                      <option value="info">Info</option>
                      <option value="primary">Primary</option>
                      <option value="warning">Warning</option>
                      <option value="inverse">Inverse</option>
                    </select>
                  </div>
                  <div class="submit-section">
                    <button
                      type="button"
                      class="btn btn-primary save-category submit-btn"
                      data-dismiss="modal"
                    >
                      Save
                    </button>
                  </div>
                </b-form>
              </div>
            </div>
          </div>
        </div>
        <!-- /Add Category Modal -->
      </div>
    </div>
    <!-- /Main Wrapper -->
  </div>
</template>

<script>
import FullCalendar from "@fullcalendar/vue3";
import dayGridPlugin from "@fullcalendar/daygrid";
import timeGridPlugin from "@fullcalendar/timegrid";
import interactionPlugin from "@fullcalendar/interaction";
import { ref } from "vue";
const currentDate = ref(new Date());
export default {
  components: {
    FullCalendar,
  },
  data() {
    return {
      startdate: currentDate,
      calendarOptions: {
        plugins: [
          dayGridPlugin,
          timeGridPlugin,
          interactionPlugin, // needed for dateClick
        ],
        headerToolbar: {
          left: "prev next today",
          center: "title",
          right: "dayGridMonth,timeGridWeek,timeGridDay",
        },
        events: [
          {
            title: "9:42a Test Event 1",
            start: "2023-04-26",
          },
          {
            title: "7:35a Test Event 3",
            start: "2023-04-30",
          },
          {
            title: "Event Name 4 2:49a",
            start: "2023-04-28",
          },
          {
            title: "Test Event 2 8:22a",
            start: "2023-04-28",
          },
        ],
        initialView: "dayGridMonth",
        editable: true,
        selectable: true,
        selectMirror: true,
        dayMaxEvents: true,
        weekends: true,
      },
    };
  },
};
</script>
