// kanakku-v1.9.9/angular-files/template-rtl/src/app/feature-module/setting/settings/settings.component.ts
import { Component } from '@angular/core';
import { ToasterService } from 'src/app/core/core.index'; 

@Component({
  selector: 'app-settings',
  templateUrl: './settings.component.html',
  styleUrls: ['./settings.component.scss'],
})
export class SettingsComponent {
  myDateValue!: Date;
  gender = "selectgender"
  public minDate!: Date;
  public maxDate!: Date;
  constructor(private toast: ToasterService) {}

  
  public submitForm(): void {
    this.toast.typeSuccess('Profile details edited successfully', 'Kanakku');
  }
}

<div class="card">
  <div class="card-body w-100">
    <div class="content-page-header">
      <h5>Account Settings</h5>
    </div>
    <div class="row">
      <div class="profile-picture">
        <div class="upload-profile me-2">
          <div class="profile-img">
            <img id="blah" class="avatar" src="assets/img/profiles/avatar-10.jpg"alt="image">
          </div>
        </div>
        <div class="img-upload">
          <label class="btn btn-primary">
            Upload new picture <input type="file">
          </label>
          <a class="btn btn-remove">Delete</a>
          <p class="mt-1">Logo Should be minimum 152 * 152 Supported File format JPG,PNG,SVG</p>
        </div>										
      </div>
      
      <div class="col-lg-12">
        <div class="form-title">
          <h5>General Information</h5>
        </div>
      </div>
      <div class="col-lg-6 col-12">
        <div class="input-block mb-3">
          <label>First Name</label>
          <input type="text" class="form-control" placeholder="Enter First Name">
        </div>
      </div>
      <div class="col-lg-6 col-12">
        <div class="input-block mb-3">
          <label>Last Name</label>
          <input type="text" class="form-control" placeholder="Enter Last Name">
        </div>
      </div>
      <div class="col-lg-6 col-12">
        <div class="input-block mb-3">
          <label>Email</label>
          <input type="text" class="form-control" placeholder="Enter Email Address">
        </div>
      </div>
      <div class="col-lg-6 col-12">
        <div class="input-block mb-3">
          <label>Mobile Number</label>
          <input type="text" class="form-control" placeholder="Enter Mobile Number">
        </div>
      </div>
      <div class="col-lg-6 col-12">
        <div class="input-block mb-3 mb-0">
          <label>Gender</label>
          <mat-select
          [(ngModel)]="gender"
          [ngModelOptions]="{ standalone: true }"
          class="select mat-cust-select form-control"
        >
            <mat-option value="selectgender">Select Gender</mat-option>
            <mat-option value="male">Male</mat-option>
            <mat-option value="female">Female</mat-option>
          </mat-select>
        </div>
      </div>
      <div class="col-lg-6 col-12">
        <div class="input-block mb-3">
          <label>Date of Birth</label>
          <div class="cal-icon cal-icon-info">
            <input type="text" class="datetimepicker form-control" placeholder="Select Date"  [minDate]="minDate"
            [maxDate]="maxDate"
            #dp="bsDatepicker"
            bsDatepicker [(bsValue)]="myDateValue">
          </div>
        </div>
      </div>
      <div class="col-lg-12">
        <div class="form-title">
          <h5>Address Information</h5>
        </div>
      </div>
      <div class="col-lg-12">
        <div class="input-block mb-3">
          <label>Address</label>
          <input type="text" class="form-control" placeholder="Enter your Address">
        </div>
      </div>
      <div class="col-lg-6 col-12">
        <div class="input-block mb-3">
          <label>Country</label>
          <input type="text" class="form-control" placeholder="Enter your Country">
        </div>
      </div>
      <div class="col-lg-6 col-12">
        <div class="input-block mb-3">
          <label>State</label>
          <input type="text" class="form-control" placeholder="Enter your State">
        </div>
      </div>
      <div class="col-lg-6 col-12">
        <div class="input-block mb-3">
          <label>City</label>
          <input type="text" class="form-control" placeholder="Enter your City">
        </div>
      </div>
      <div class="col-lg-6 col-12">
        <div class="input-block mb-3">
          <label>Postal Code</label>
          <input type="text" class="form-control" placeholder="Enter Your Postal Code">
        </div>
      </div>
      <div class="col-lg-12">
        <div class="btn-path text-end">
          <a href="javascript:void(0);" class="btn btn-cancel bg-primary-light me-3">Cancel</a>
          <a href="javascript:void(0);" class="btn btn-primary">Save Changes</a>
        </div>
      </div>
    </div>
  </div>
</div>

// kanakku-v1.9.9/vuejs-files/template/src/views/pages/settings/settings.vue
<template>
  <!-- Main Wrapper -->
  <div class="main-wrapper">
    <layout-header></layout-header>
    <layout-sidebar></layout-sidebar>

    <!-- Page Wrapper -->
    <div class="page-wrapper">
      <div class="content container-fluid">
        <componentheader :title="title" />

        <div class="row">
          <div class="col-xl-3 col-md-4">
            <settingsidebar />
          </div>

          <div class="col-xl-9 col-md-8">
            <div class="card">
              <div class="card-header">
                <h5 class="card-title">Basic information</h5>
              </div>
              <div class="card-body">
                <!-- Form -->
                <b-form>
                  <div class="row form-group">
                    <label for="name" class="col-sm-3 col-form-label input-label"
                      >Name</label
                    >
                    <div class="col-sm-9">
                      <div class="d-flex align-items-center">
                        <label
                          class="avatar avatar-xxl profile-cover-avatar m-0"
                          for="edit_img"
                        >
                          <img
                            id="avatarImg"
                            class="avatar-img"
                            src="@/assets/img/profiles/avatar-02.jpg"
                            alt="Profile Image"
                          />
                          <input type="file" id="edit_img" />
                          <span class="avatar-edit">
                            <i
                              class="feather feather-edit avatar-uploader-icon shadow-soft"
                            ></i>
                          </span>
                        </label>
                      </div>
                    </div>
                  </div>
                  <div class="row form-group">
                    <label for="name" class="col-sm-3 col-form-label input-label"
                      >Name</label
                    >
                    <div class="col-sm-9">
                      <b-form-input
                        type="text"
                        class="form-control"
                        id="name"
                        placeholder="Your Name"
                        value="Charles Hafner"
                      />
                    </div>
                  </div>
                  <div class="row form-group">
                    <label for="email" class="col-sm-3 col-form-label input-label"
                      >Email</label
                    >
                    <div class="col-sm-9">
                      <b-form-input
                        type="email"
                        class="form-control"
                        id="email"
                        placeholder="Email"
                        value="charleshafner@example.com"
                      />
                    </div>
                  </div>
                  <div class="row form-group">
                    <label for="phone" class="col-sm-3 col-form-label input-label"
                      >Phone <span class="text-muted">(Optional)</span></label
                    >
                    <div class="col-sm-9">
                      <b-form-input
                        type="text"
                        class="form-control"
                        id="phone"
                        placeholder="+x(xxx)xxx-xx-xx"
                        value="+1 (304) 499-13-66"
                      />
                    </div>
                  </div>
                  <div class="row form-group">
                    <label for="location" class="col-sm-3 col-form-label input-label"
                      >Location</label
                    >
                    <div class="col-sm-9">
                      <div class="mb-3">
                        <b-form-input
                          type="text"
                          class="form-control"
                          id="location"
                          placeholder="Country"
                          value="United States"
                        />
                      </div>
                      <div class="mb-3">
                        <b-form-input
                          type="text"
                          class="form-control"
                          placeholder="City"
                          value="Charleston"
                        />
                      </div>
                      <b-form-input
                        type="text"
                        class="form-control"
                        placeholder="State"
                        value="West Virginia"
                      />
                    </div>
                  </div>
                  <div class="row form-group">
                    <label for="addressline1" class="col-sm-3 col-form-label input-label"
                      >Address line 1</label
                    >
                    <div class="col-sm-9">
                      <b-form-input
                        type="text"
                        class="form-control"
                        id="addressline1"
                        placeholder="Your address"
                        value="2681  Columbia Mine Road"
                      />
                    </div>
                  </div>
                  <div class="row form-group">
                    <label for="addressline2" class="col-sm-3 col-form-label input-label"
                      >Address line 2 <span class="text-muted">(Optional)</span></label
                    >
                    <div class="col-sm-9">
                      <b-form-input
                        type="text"
                        class="form-control"
                        id="addressline2"
                        placeholder="Your address"
                      />
                    </div>
                  </div>
                  <div class="row form-group">
                    <label for="zipcode" class="col-sm-3 col-form-label input-label"
                      >Zip code</label
                    >
                    <div class="col-sm-9">
                      <b-form-input
                        type="text"
                        class="form-control"
                        id="zipcode"
                        placeholder="Your zip code"
                        value="25301"
                      />
                    </div>
                  </div>
                  <div class="text-end">
                    <b-button type="submit" variant="primary">Save Changes</b-button>
                  </div>
                </b-form>
                <!-- /Form -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /Page Wrapper -->
  </div>
  <!-- /Main Wrapper -->
</template>
<script>
export default {
  setup() {
    return {
      title: "Settings",
    };
  },
};
</script>
